### ISSUE TITLE
Error message: "[findPatternInTick] tick = 192. No pattern list found" when playing in Song mode without loop enabled"

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#1005]
Hydrogen version *          :  Hydrogen 1.1.0-'6d8ca1a3'

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When Hydrogen plays a simple pattern with size 8 and res 32 in song mode, but the loop mode is deactivated, an error message appears:

`(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 192. No pattern list found` 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by mauser** [comment]
@theGreatWhiteShark : It seems the -1 in findPatternInTick is the "normal" way to tell audioEngine_updateNoteQueue that the song has ending. In my opinion, the error message is misleading since its part of a code path which occurs in a regular situation. Would you agree if i remove that error message?

**Comment by theGreatWhiteShark** [comment]
Sure.

According to the blame function of Github it is as old as the repository itself. Maybe back than things did work differently. But I don't see any use of it right now either.

**Comment by oddtime** [comment]
Does it happens at other resolutions as well?

`(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 766. No pattern list found`

I have many messages like this, with different ticks (all > 192).
I am running a modified branch but I don't think it is relevant

**Comment by theGreatWhiteShark** [comment]
Hey @oddtime ,

The `tick` is like a frame or a second a basic time unit in Hydrogen. This issue should affect all resolutions which do only change the number of ticks notes can be assigned to.

**Comment by mauser** [comment]
Some additional comments: The tick number which is displayed in the message is the last tick of the song. So the actual number depends on your song and pattern length. However, that message should appear only if the loop mode is turned off and if song mode is active. Is this the case for you, @oddtime ?

**Comment by oddtime** [comment]
yes only fs loop off and song mode active.
pattern size = 192
but the messages are

```
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 1027. No pattern list found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 1029. No pattern list found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 192. No pattern list found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 193. No pattern list found

```

retry another time
```
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 797. No pattern list found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 799. No pattern list found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 192. No pattern list found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 193. No pattern list found
```


(commit bc94f858)

**Comment by mauser** [comment]
When do those error messages appear? Is this only after hydrogen reached the end of a song?

**Comment by oddtime** [comment]
The first two appear at the beginning of play, the last two at the end.

**Comment by mauser** [comment]
Can you provide h2song file where this happens at the beginning of play? I can't reproduce it here.. You can attach it to this ticket..

**Comment by oddtime** [comment]
[song.zip](https://github.com/hydrogen-music/hydrogen/files/5667701/song.zip)

**Comment by oddtime** [comment]
I don't know if that helps, but if I press Stop after the playback is finished another message appears:
`(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 486. No pattern list found`

And this happen also in Pattern mode (with Loop = Off, even if the player does loop)

**Comment by oddtime** [comment]
News: it depends if Jack Time Master is on or off

**Comment by theGreatWhiteShark** [comment]
What the Jack Time Master (if Hydrogen is not the master itself) does is to set the tempo in Hydrogen according to the one used in an external application (e.g QTractor or Ardour). So, in general it will adjust the ticksize (when changing speed) which in turn affect the number of the final tick in the Song.

@oddtime could you provide the tempo including the position of the bar it is set?

**Comment by oddtime** [comment]
I have no tempo changes,
button "enable time edit" is on

**Comment by theGreatWhiteShark** [comment]
> I have no tempo changes

Are there any other applications apart from Hydrogen present which use Jack (and may feature tempo changes)?

**Comment by oddtime** [comment]
No, only Hydrogen

**Comment by theGreatWhiteShark** [comment]
@mauser I just had a look at this. `audioEngine_updateNoteQueue` calls `findPatternInTicks` with the current tick + a lookahead, the Jack Timebase callback function calls it with current tick + a smaller lookahead, and `setTimelineBpm` just with the current tick. Having different values if Timeline or Timebase master is activated is totally expected. I approve removing this line.
