### ISSUE TITLE
Tweaking INSTALL.md

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1007]
Hydrogen version *          : 362d745

--- 

There are some things I do want to change about the `INSTALL.md` file.

- [ ] Split the essential and the optional packages to install on Linux systems
- [ ] Fix Windows requirements statement (11 years old and suggesting 198MB RAM + keyboard and mouse...) 
- [ ] Move the "create binary package" paragraph to the `DEVELOPERS` file. IMHO this goes beyond the scope of this file and only scares users.
- [ ] Add packages required to generate the documentation
- [ ] Add packages required to support C++17

About the second one: Do we support Windows right now or are the corresponding components still "fallen into despair"?

Opinions?

**Comment by mauser** [comment]
About the Windows compatibility: In my opinion, we have now reached a state where the quality of Linux, OS X and Windows builds differ only slightly. The INSTALL file was written in a time when we had to compile the windows version (including the complete QT environment) on our PCs. I remember that it sometimes took more then one day on my machine to compile QT :) So there were times when there were years between two windows releases..

**Comment by theGreatWhiteShark** [comment]
> I remember that it sometimes took more then one day on my machine to compile QT :)

Yeah, I know. I tried that too once. After more than 20 hours compilation I only got an error about insufficient memory :D

**Comment by theGreatWhiteShark** [comment]
In #972 it was mentioned the `liblash-compat-dev` package could not be found. But this does not seem to be correct https://packages.debian.org/sid/liblash-compat-dev.

> Split the essential and the optional packages to install on Linux systems

They already are (in verbose form). Breaking the apt install command into individual pieces is not necessary and can be done by the user herself (the verbose form lists both the general name and the corresponding package).

> Move the "create binary package" paragraph to the DEVELOPERS file. IMHO this goes beyond the scope of this file and only scares users.

I'll leave it in the INSTALL.md . Packagers are no developers either.

> Add packages required to support C++17

I think it's out of the scope of this file (and not a good idea) to tell the user to get a specific version `gcc`. If their OS does not supply a current one, we can still help them via the issues and discussion.
