### ISSUE TITLE
JACK port property metadata?

### ISSUE THREAD

**Issue by mxmilkiib** [hydrogen-music/hydrogen#1014]
JACK ports can have [metadata](https://jackaudio.org/metadata/) properties set, such as [pretty-name](https://jackaudio.org/metadata/pretty-name/). With support for that, JACK connection graphs could display something a bit neater than "out_L" and "out_R" for Hydrogen.

**Comment by theGreatWhiteShark** [comment]
What name would you suggest instead?

The ports provide more or less the summed audio of the left and right outputs of each instrument after effects were applied on them. You can also set a per instrument output port with them bearing the names of the particular instrument (+"_L" or "_R" for stereo instruments).

But what just caught my eye is the [group](https://jackaudio.org/api/group__Metadata.html#ga68ad11f571b1382c971f1d73851d11bb) property. Unfortunately, it is undocumented. Do you know what is its intended meaning and if programs like qjackctl or patchage do support them? Grouping the outputs intro cymbals and toms would be indeed nice (although our drumkits do not yet support this).

**Comment by mxmilkiib** [comment]
"Main Out L" and "Main Out R"(?)

port-group is for denoting stereo/multi-channel tracks, though I don't recall seeing any apps make use of it so far.

**Comment by theGreatWhiteShark** [comment]
Hey @mxmilkiib 

I added the pretty names "Main Output L" and "Main Output R" for the two main ports.

Thanks for clarifying the usage of the group key. I keep an eye on the changelog of QjackCtl whether it could be used to e.g. ease connecting the different per instrument output ports.

**Comment by mxmilkiib** [comment]
RaySession now supports a patchbay with port groups (and there is a PR for Carla), if that might work with / assist the Hydrogen paradigm; https://github.com/Houston4444/RaySession/issues/112

**Comment by theGreatWhiteShark** [comment]
Thanks for the notice! (AFAIU this is just an user thingy and does not require any action/patch from development side, right?)

**Comment by mxmilkiib** [comment]
I jumped the gun a bit there as RS uses pattern matching right now for grouping and will move to using metadata in the near-ish future. The app has become more than an NSM front-end recently, using code from Carla.

Any metadata can be altered by using `jack_property`, but once port grouping (and then order) lands in RS (and there is an accidentally closed IIRC PR for Carla) then Hydrogen could present a sightly more sophisticated patchbay for/to users.
