### ISSUE TITLE
About the updateMixer() operations, optimization

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#1017]
Working with dynamic tooltips in the mixer for PR #1013, I saw that the method `updateMixer()` in` Mixer.cpp` (which is called something like 20 times/second) calls many methods like `setVolume()` for the faders or `setPan()`...

I wonder if any of these calls are not really necessary.
For example: is it possible that the 'component' fader (which I suppose be a general volume but not for the sends) and master Fader do change independently of a manual change on the mixer? And instrument pan, Fx sends, Fx return?
If not they shouldn't be updated.

If all or almost all the operations are needed at the construction, one could use a method `initMixer()` and then a lighter `updateMixer()`

I know that this optimization could be negligible, or maybe I am wrong and there is no point in this issue.

**Comment by mauser** [comment]
> For example: is it possible that the 'component' fader (which I suppose be a general volume but not for the sends) and master Fader do change independently of a manual change on the mixer? And instrument pan, Fx sends, Fx return?

I'm not sure if i understand you correctly here, but the volume can also be changed via OSC or Midi, without a manual fader interaction.

**Comment by oddtime** [comment]
Thank you for the information!
So better to keep it unchanged for eventual different interactions/automations and the issue can be closed.
