### ISSUE TITLE
Interaction between JACK per instrument outputs and Mixer

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1027]
Audio driver + version      :  JACK

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I just realized that all the audio of the ports created by the "per instrument outputs" for the JACK driver is passing the Mixer before leaving Hydrogen.

At least for me this not what I expected and I would consider this behavior invalid. I thought the output is the raw one generated by the audio engine (after pitch shifting, randomization etc) intercepted right before it would enter the Mixer. This way the user could use an external Mixer + effects etc. Hydrogen's internal Mixer is still of use as something like a preview and the "out_L" and "out_R" ports are always associated with the Mixer. But right now changing the pan, volume or an effect does affect both the internally mixed signal as well as the sources provided via the per instrument outputs. This doesn't feel right.

**Comment by mauser** [comment]
Hi,

you can switch it from "Pre-Fader" to "Post-Fader" in the Preferences dialog. Is this not working or not working as intended?

**Comment by theGreatWhiteShark** [comment]
Perfect!

I just wasn't aware of it.

**Comment by theGreatWhiteShark** [comment]
https://github.com/hydrogen-music/documentation/pull/28
