### ISSUE TITLE
Lack of warning when closing with unsaved changes

### ISSUE THREAD

**Issue by duck57** [hydrogen-music/hydrogen#1039]
Hydrogen version *          :  0.9.7
Operating system + version  :  Raspian 
Audio driver + version      : JACK

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When exiting Hydrogen with unsaved changes, the prompt asking if you want to save or discard the changes appears inconsistently.

**Comment by theGreatWhiteShark** [comment]
Can you reproduce a situation in which Hydrogen does not ask you about the unsaved changes?

Also, please note that the prompt won't appear if close the application via `kill -SIGKILL`, `kill -SIGTERM`, and alike.

**Comment by trebmuh** [comment]
0.9.7 is quite old (november 2016), you should try with a more recent version.

**Comment by duck57** [comment]
I just built 1.0.1

I'm pretty sure this is an LXDE thing telling H2 to quit ASAP rather than a Hydrogen bug, so I'm closing the issue.
