### ISSUE TITLE
Mapping pattern between different drumkits

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1070]
If a pattern contains e.g. a snare rimshot but the drumkit does not it would most probably better to replace it by a snare hit than omitting it.

If we adopt the `#instrument primary`, `#instrument secondary`, ... notation, all notes belonging to unavailable instruments could be mapped to the lowest ones (primary > secondary > ...).

For other instruments we could hard-code a mapping table, e.g. `tom tiny` > `tom not so tiny`; `tom not so tiny` > `tom high` (please don't mind the names),  and apply it over and over until all instruments are present in the target drumkit.

**Comment by oddtime** [comment]
I am not sure about the "hard code" behaviour for any case.

example:
pattern has 1 splash, 1 china and no other cymbals,
the drumkit to map to has 2 crashes and no other cymbals
Shouldn't H2 map splash and china to different crashes? (trying to keep the instruments separate)

**Comment by theGreatWhiteShark** [comment]
Ideally, there will also be a widget for the user to modify the results of the mapping. This hopefully won't take much longer than the mapping itself. So, I think it's not so important to cover every case. But switching from a something like a 90% GM-compatible kit to a 80% one should provide plausible mappings and be just answered with an OK.

**Comment by nabero** [comment]
First contribution here, and not aware of the internals. Sorry if this comment is garbage. 

What about adding the concept of instrument group as a user defined list.
Hydrogen would come with default instruments (tom), drumkits would come with their own values of size (floor tom: 12, big tom: 42, tiny tom: 55), which can then be mapped to the target drumkit. Maybe labelled values (tiny=25) would help standardize some while keeping flexibility.

**Comment by theGreatWhiteShark** [comment]
> What about adding the concept of instrument group as a user defined list.
Hydrogen would come with default instruments (tom), drumkits would come with their own values of size (floor tom: 12, big tom: 42, tiny tom: 55), which can then be mapped to the target drumkit. Maybe labelled values (tiny=25) would help standardize some while keeping flexibility.

So, If I get your concept right each drumkit comes with an unique integer number for each instrument and the current Hydrogen session holds a user defined list that maps maps these integer numbers to the instrument of a pattern, right?

**Comment by nabero** [comment]
Yes. But an instrument would also have an additional instrument category so
that selection of alternatives can only be done in that category.

I was thinking of bundling hydrogen with a default list, editable by the
user, and from which you can assign the value from for each instrument in
the current drumkit to prevent usage of multiple names for the same group
in different drumkits.

**Comment by theGreatWhiteShark** [comment]
Okay. I see.

I think I will need a couple of weeks to finish some GUI updates and afterwards I will try to come up with a proposal to implement the whole thing. It would be nice to have your feedback to this one too.
