### ISSUE TITLE
The Mixer doesn't show up

### ISSUE THREAD

**Issue by leslei2001** [hydrogen-music/hydrogen#1072]
Hydrogen version: 1.0.1
Operating system + version : Windows 10 (64-bit)
Audio driver + version: 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I recently updated Hydrogen on my computer (updated from 0.9.7 to 1.0.1). Every time I click on the Mixer button, the window can be seen on my desktop but it's only a white space and I can't use the mixer at all. What should I do?

**Comment by theGreatWhiteShark** [comment]
The size of most windows are stored in the preferences file `hydrogen.conf`. Maybe the one of the mixer got messed up. You should look for an entry called 
```xml
  <mixer_properties>
```

**Comment by leslei2001** [comment]
I've found it, changed and saved it, but the white space keeps showing up when trying to open Mixer. Is there anything else I could try to solve this?
