### ISSUE TITLE
[improvements requests] opening a pattern

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#1078]
Hydrogen version *          : GIT master b17f662
Operating system + version  : LibraZiK-3 (Debian Buster based)
Audio driver + version      : irrelevant

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When going: `H2 menu -> Project -> Open Pattern`, I'm usually going to search those on `/usr/share/hydrogen/data/Patterns/` where I've got the ones from our [song and pattern repository](https://github.com/hydrogen-music/Song-and-pattern-repository) installed.

By default, Hydrogen goes to `~/.hydrogen/data/patterns/` which can be seen as a relevant choice. No issue here.

---

Then, I'm navigating to `/usr/share/hydrogen/data/Patterns/` and I'm selecting one pattern here. Hydrogen launches it and I press play to listen to it. Usually, I've got to test a bunch of those before finding the one I'm choosing, so I'm going again to `H2 menu -> Project -> Open Pattern`.

**_First improvement request_**: it could be great to have a keyboard shortcut here to open this window without needing to go in the menu with the mouse pointer.

---

When going again to `H2 menu -> Project -> Open Pattern`, Hydrogen is back to showing me `~/.hydrogen/data/patterns/`.

**_Second improvement request_**: it could be great if H2 could remember where I was (`/usr/share/hydrogen/data/Patterns/` above) and show me this one again, since it's more likely that a user will want/need to go back to the same location.

_(note that if we click on the **<-** button in the files browser, we're back to the relevant location, but it's not very user-friendly, hence my second improvement request above)_

---

When `H2 menu -> Project -> Open Pattern` I can only open patterns one by one.

**_Third improvement request_**:  it'd be great to be able to select several for being opened.

**Comment by theGreatWhiteShark** [comment]
I would add that we could provide two links in the left panel (favorites) pointing to the pattern folder in the user home and to the systems' one. Same for song, demo, and drumkit open dialog.

**Comment by trebmuh** [comment]
If that can programmatically be done, that would be very good to have.

**Comment by trebmuh** [comment]
A third request (_I've updated my first message_): when `H2 menu -> Project -> Open Pattern` I can only open patterns one by one. It'd be great to be able to select several for being opened.

**Comment by theGreatWhiteShark** [comment]
Closed with #1399
