### ISSUE TITLE
i18n bugs

### ISSUE THREAD

**Issue by aaronbcn** [hydrogen-music/hydrogen#1089]
Hydrogen version *          : v 1.1.0
Operating system + version  : Windows 10 Home 20H2
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Some strings of the product are not internationalized, which means that translators cannot localize through the i18n folder.

Besides, some strings will change back to English once clicked.

See details in the docx file below:
[i18n bugs.docx](https://github.com/hydrogen-music/hydrogen/files/5793171/i18n.bugs.docx)

**Comment by trebmuh** [comment]
Duplicate, please user this issue: #397
Closing here.

_(Also, easier for everyone wanting to help if you put the text & image straight into your message, rather than in a linked doc)_
