### ISSUE TITLE
Highlighting selected pattern and cursor position in SongEditor

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1098]
In the pattern editor we already highlight the line corresponding to the currently selected instrument. I would suggest we also introduce this to the song editor. It's area is even more vast (and I get lost in it quite frequently)

![current](https://user-images.githubusercontent.com/14164547/104707509-c625d100-571c-11eb-9e68-e24489ea3a3b.png)

How about 
- Using a lighter color for the line of the selected pattern
- Using a black border for the pattern the cursor is visiting (which should then also be applied to the pattern editor)

![highlight_1](https://user-images.githubusercontent.com/14164547/104707518-c8882b00-571c-11eb-8946-51e8561e5956.png)

Any thoughts?

**Comment by trebmuh** [comment]
LGTM

**Comment by theGreatWhiteShark** [comment]
Implemented in #1544
