### ISSUE TITLE
Do not preview instrument sound when "hear" button is deactivated

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1101]
In the panel of the pattern editor we have a button called "hear" which toggles the playback of all notes inserted into the current pattern. However, this button does not effect the preview of the different instrument sound played back when clicking the name of the instrument (left of the mute/solo buttons). If think this should be toggled as well in order to allow for "silent" editing while playing a song. Thoughts?

**Comment by trebmuh** [comment]
I wouldn't do that, the current behavior is perfect for me.

Use case: I'm building a pattern. For that, I'm building it with the "hear" button in the OFF position since my pattern is loop-playing and I don't want to hear the sound of the notes I'm adding at the time I'm adding it. But, I want to hear the sound of the preview instrument when I'm clicking on its name because I need to choose the sound I want to pick up (think: "_I want to make a break with a tom, but which one do I want to pick up?_", same with "_which cymbal I want to pick up?

**Comment by oddtime** [comment]
Both arguments by @theGreatWhiteShark and @trebmuh make sense.
What about another button to deactivate the instrument sound preview?

**Comment by theGreatWhiteShark** [comment]
> What about another button to deactivate the instrument sound preview?
Or an option in preferences...

I'm actually quite reluctant when it comes to introduce further buttons in Hydrogen. There are already so many button, knobs etc. that introducing a new one is unlikely to point the user to a new, exciting feature. Take for example the "stack mode" as discussed in another issue. It has been there for years without anyone of use being interested in clicking it.

But we indeed have the area to the left of the instrument field. So, currently we have AFAICS three different options of changing the instrument silently:
- in the muted area on the very left of the instruments field (which is right now quite small)
- dragging select a small area of a particular instrument
- click on a row of a particular instrument using the middle mouse button

I think this is sufficient.

**Comment by oddtime** [comment]
> in the muted area on the very left of the instruments field (which is right now quite small)

How small it is? I thought it was null

**Comment by cme** [comment]
> But we indeed have the area to the left of the instrument field. So, currently we have AFAICS three different options of changing the instrument silently:
>     * in the muted area on the very left of the instruments field (which is right now quite small)
>     * dragging select a small area of a particular instrument
>     * click on a row of a particular instrument using the middle mouse button

I'd add to that list:
  *  using the up/down arrow keys 

(this was one of my original motivators for that!)

**Comment by theGreatWhiteShark** [comment]
> using the up/down arrow keys

Uh. Nice!

**Comment by oddtime** [comment]
Ok! I agree that there is no need of further ways :)
