### ISSUE TITLE
Show other pattern notes in Stacked Mode / Virtual Patterns

### ISSUE THREAD

**Issue by cme** [hydrogen-music/hydrogen#1103]
Hydrogen version *          :
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Editing a pattern in "stacked" mode (or editing notes in the 'owner' pattern of a virtual pattern group), we can hear the notes of the other patterns active during playback. This is great for editing patterns that go together, but can lead to some trial and error to get exactly what you want.

It would be handy if the Pattern Editor would *show* the notes from the other patterns (in some different representation to make it clear they can't be interacted with) that are active.

This would also be really useful for teaching, and figuring out handing.

**Comment by theGreatWhiteShark** [comment]
I never used the `stack` mode before and it was a bit trial and error first. We should add in the manual that you have to press [Ctrl]+left mouse to add/remove patterns to/from the stack. Is there more to it I missed out?

> It would be handy if the Pattern Editor would show the notes from the other patterns (in some different representation to make it clear they can't be interacted with) that are active.

How about showing them in a light greyish color shifted some 2-3 pixels left and up? Note: the patterns could have different lengths too. Maybe continuing the grid in a light color while keeping the general background of the pattern editor could indicate this difference in length very well.

**Comment by oddtime** [comment]
> I never used the stack mode before and it was a bit trial and error first. 

I didn't know either.
How about adding "add to stack" and "remove from stack" in the pop up menu of the song editor?

**Comment by cme** [comment]
> I didn't know either.
> How about adding "add to stack" and "remove from stack" in the pop up menu of the song editor?

I was thinking something similar.

Also since stacked mode doesn't apply to Song Mode, perhaps the button should be greyed out in Song Mode.

**Comment by theGreatWhiteShark** [comment]
And a short tooltip like "play back other selected patterns while editing" would be nice too.

**Comment by cme** [comment]
#1310 applied to master
