### ISSUE TITLE
Notes with low velocity are hard to see in the note properties panel

### ISSUE THREAD

**Issue by Ratfink** [hydrogen-music/hydrogen#1106]
Hydrogen version *          : 1.0.1 or master
Operating system + version  : Fedora Workstation 33

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

In the note properties panel, notes with a low velocity have a very similar lightness to the background color.  This makes the velocity bars hard to see.  See the screenshot below.  The pattern editor gives the notes a dark outline, which could be used here as well.
![Screenshot from 2021-01-18 20-05-43](https://user-images.githubusercontent.com/320472/104975418-94389700-59c8-11eb-9ce5-8c9d91f54842.png)

**Comment by theGreatWhiteShark** [comment]
> The pattern editor gives the notes a dark outline, which could be used here as well.

A dark outline is already used by the cursor (which hides itself as soon as I try to make a screenshot). It get's shown when pressing the arrow keys while being in the note property ruler.

How about some more color instead?

**Comment by cme** [comment]
I agree this is a pain. I think there's probably enough visual distinction between the cursor and an outline that's snug against the bar. The main problem with outlining things in the note properties editor is making sure it's still comprehensible when multiple notes occupy the same position, but I have a couple of ideas that might work.

**Comment by oddtime** [comment]
what about red (vel=127) to blue (vel=0)?

**Comment by oddtime** [comment]
@cme 
> but I have a couple of ideas that might work
What were you thinking on this?

**Comment by theGreatWhiteShark** [comment]
Implemented in #1544. You can now set custom colors for note velocities 1.5, 1.0, 0.5 and 0.0. For all values in between the adjacent colors will be interpolated
