### ISSUE TITLE
connections aren't saved for instrument-outs 

### ISSUE THREAD

**Issue by rhetr** [hydrogen-music/hydrogen#111]
I always use the instrument-outs in JACK because there aren't enough built-in plugin ports for me to use (i need at least 6 for all the drums, usually more) and because I almost always sidechain with the kick using sc3. The problem is that when I use ladish (via claudia) or nsm (via nsm-proxy, this may become my preferred method actually) to save the connections, for some reason none of the connections to the instrument-outs are ever saved, so I have to manually reroute them every single time, which is not ideal.

**Comment by thijz** [comment]
hi rhetr
IIRC nms support has been added
can you retest and let us know if this issue is solved?

**Comment by thijz** [comment]
hi rhetr
any update on this item ?

grtz
Thijs

**Comment by mauser** [comment]
I'm closing this since due to lack of feedback (and NSM is now supported).
