### ISSUE TITLE
The documentation needs to be updated

### ISSUE THREAD

**Issue by notsmoothsteve** [hydrogen-music/hydrogen#1110]
Hydrogen version *          : 1.0.1
Operating system + version  : Windows 10 2004 x64
Audio driver + version      : N/A

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Just discovered Hydrogen and am having fun playing with it, but the fact that the documentation doesn't match the software keeps getting in the way.  As a former programmer, I understand how much more enjoyable it is to code than to document :-) but when features are added or changed in any significant way, the documentation does need to be updated by someone who understands the features in question.

For instance, here's the actual instrument editor (on the left) and its documentation (on the right):

![image](https://user-images.githubusercontent.com/77751064/105225690-f01c3080-5b2c-11eb-9d4b-45606c4c4b9e.png)

Auto-Stop-Note has moved, which isn't a big deal (the user will find it sooner or later), but Apply Velocity and the entire HH.Press.Grp are undocumented.  (On a related note, there's also no mouseover tooltip for anything in the HH.Press.Grp, so the user can't even use that as a hint to try to understand what it is.)

That's the one that is the most blatant example for me as a Hydrogen beginner because it's hard to look at it and correctly guess what the undocumented items are.  There are others that are easier to figure out on your own (for instance, that the 3. Main menu section's list of menus and menu items doesn't match the real one - Projects vs. Project, the entire Drumkits menu is missing from the documentation, the contents of the Instruments menu differ significantly between the program and the manual, etc.)

**Comment by trebmuh** [comment]
That is right that the documentation is lagging behind.
That said, some improvements have been done on the last week regarding this.

Feel free to help out, on [its dedicated repo](https://github.com/hydrogen-music/documentation).

@notsmoothsteve , would you mind opening issues on the documentation dedicated repo? Thank you.

(_closing here_)
