### ISSUE TITLE
Endless pop-up after updating the server list

### ISSUE THREAD

**Issue by moonshaadow** [hydrogen-music/hydrogen#1122]
Hydrogen version *          : 847d5ee7734ed9a244d25713ce12c2cf878a2725
Operating system + version  : ubuntu studio 18.04 + KX repos
Audio driver + version      :  jackd 1.9.17

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
When I add a wrong drumkits server address, it results in an endless try of install.

```

 ......(E) Download::finished Échec de l'importation de l'élément : Error transferring http://download.forzee.org/hydrogen/Forzee Stereo Drumkit.h2drumkit - server replied: Not Found
(E) Download::finished Échec de l'importation de l'élément : Error transferring http://download.forzee.org/hydrogen/Forzee Stereo Drumkit.h2drumkit - server replied: Not Found
(E) Download::finished Échec de l'importation de l'élément : Error transferring http://download.forzee.org/hydrogen/Forzee Stereo Drumkit.h2drumkit - server replied: Not Found
(E) Download::finished Échec de l'importation de l'élément : Error transferring http://download.forzee.org/hydrogen/Forzee Stereo Drumkit.h2drumkit - server replied: Not Found.........
```

Steps to reproduce : add the following adress  'http://download.forzee.org/hydrogen/ForzeeStereoDrumkit.h2drumkit' as a new server adress. (404 error adress)

**Comment by theGreatWhiteShark** [comment]
Hey @moonshaadow,

Could you try #1125?

Hydrogen did try a number of times (30) to reach the server and created a popup each time. Now, this is only done once after the last retry.

**Comment by moonshaadow** [comment]
Hi @theGreatWhiteShark 
I've successfully tried #1125 .

Is this number of times not a bit too high ?
Anyway it works.

Thank you.

**Comment by theGreatWhiteShark** [comment]
> Is this number of times not a bit too high ?

No idea. Let's call it "for historical reasons".
