### ISSUE TITLE
Hydrogen crashes when double clicking the sample waveform in an instrument

### ISSUE THREAD

**Issue by camtarn** [hydrogen-music/hydrogen#1138]
Hydrogen version *          : 1.0.1
Operating system + version  : Windows 10 Home v2004 build 19041.746
Audio driver + version      : Microsoft generic USB audio v10.0.19041.388, via PortAudio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

In the instrument rack, if I click the Layers button, I see a waveform display near the bottom of the rack.

If I double-click the waveform display, Hydrogen immediately crashes. This is always reproducible. It happens both on instruments created by dragging from the GM kit, and on instruments created with external WAV files.

Windows Error Reporting details:

```
Application Error
Faulting application name: hydrogen.exe, version: 0.0.0.0, time stamp: 0x5f593567
Faulting module name: hydrogen.exe, version: 0.0.0.0, time stamp: 0x5f593567
Exception code: 0xc0000005
Fault offset: 0x0000000000089f3a
Faulting process ID: 0x2cb4
Faulting application start time: 0x01d6f71af5cc2ed4
Faulting application path: C:\Program Files\Hydrogen\hydrogen.exe
Faulting module path: C:\Program Files\Hydrogen\hydrogen.exe
Report ID: b1c87a36-bdaf-447c-ad68-4fb725a9077d
Faulting package full name: 
Faulting package-relative application ID: 
```

Extra XML event data attached: [double click waveform crash.txt](https://github.com/hydrogen-music/hydrogen/files/5898188/double.click.waveform.crash.txt)

Maybe related to #455 ?

**Comment by trebmuh** [comment]
I can't reproduce with a build from GIT master 1bacb4a here on LibraZiK-3 (Debian buster based).
I've tried with a 1.0.1 as well, and I've got no issue too.

**Comment by cme** [comment]
@camtarn Can this be reproduced by starting with a clean 'new' song, or does it happen only when there's a song loaded that has a broken drumkit? I've provoked a crash round there while trying to reproduce the other issue. I'm going to review code in the area for robustness.

(Because that sounds more fun than debugging on a Windows VM :D )

**Comment by camtarn** [comment]
@cme - ah, you're right, it only happens with the broken drumkit. Will link up that issue once I file it.
