### ISSUE TITLE
Dialog: "The current loaded song missing his soundlibrary. Please load a existing soundlibrary first"

### ISSUE THREAD

**Issue by camtarn** [hydrogen-music/hydrogen#1139]
Hydrogen version * : 1.0.1
Operating system + version : Windows 10 Home v2004 build 19041.746
Audio driver + version : Microsoft generic USB audio v10.0.19041.388, via PortAudio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

In the instrument rack, when I right-click on any kit and select 'Properties', I get this error message:

"The current loaded song missing his soundlibrary. Please load a existing soundlibrary first"

It is not clear what this means, or how to fix it. The current song was created from scratch, every instrument in the song drumkit has sample(s) assigned, and the song's drumkit was saved into the sound library successfully in this editing session.

I discovered that right-clicking any kit and selecting 'Load' in the context menu 'fixes' this issue for _all_ kits, at the expense of overwriting the current song's drumkit.

The song is not under .hydrogen, in case that matters.

**Comment by theGreatWhiteShark** [comment]
I can not reproduce this. Could you attach the debugging log? (Starting Hydrogen via command line with the `-VDebug` option)

**Comment by cme** [comment]
> I can not reproduce this. Could you attach the debugging log? (Starting Hydrogen via command line with the `-VDebug` option)

I can reproduce. Just needs a song with a drumkit name which is not in the currently installed user or system drumkits. 

The error is basically saying "you might be missing some samples", and should probably be a warning rather than an error.

**Comment by theGreatWhiteShark** [comment]
I see.
