### ISSUE TITLE
Preferences Dialog is not resizable

### ISSUE THREAD

**Issue by ezust** [hydrogen-music/hydrogen#114]
While I was in the MIDI System tab, I was trying to make the Preferences Dialog bigger so I could see more text in the EVENT and ACTION columns of the table without an ellipsis or a scrollbar.

If those columns could be the ones to grab the extra space on resize that would be also nice.

**Comment by pvint** [comment]
Just thought I'd look at this, but I tested and it appears to be done. 

Maybe an easy issue to close? :-)

**Comment by thijz** [comment]
wow, Paul !
i you keep 'fixing' issues at this pace Hydrogen will be bug-free in a couple of weeks ;-)
thanks for pointing this out !

grtz
Thijs
