### ISSUE TITLE
Drumkit -> Save automatically uses same name as system kit / Drumkits with same name as system kits cause bugs

### ISSUE THREAD

**Issue by camtarn** [hydrogen-music/hydrogen#1141]
Hydrogen version * : 1.0.1
Operating system + version : Windows 10 Home v2004 build 19041.746
Audio driver + version : Microsoft generic USB audio v10.0.19041.388, via PortAudio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- Create a new project
- Drumkits -> New
- Clear all instruments? [OK]
- Drumkits -> Save

A new user drumkit appears in the sound library, with the same name as the previously loaded system drumkit (e.g. GMRockKit)

Try to load the previously loaded system drumkit:
- Open the sound library
- Right-click on a differently-named drumkit (e.g. TR808EmulationKit), Load
- Right-click the previously loaded system drumkit (e.g. System drumkits -> GMRockKit), Load
- The empty user drumkit is loaded instead

Try to delete the empty user drumkit:
- Right-click the user drumkit (e.g. User drumkits -> GMRockKit), Delete
- Dialog: "It is not possible to delete the currently loaded drumkit: "GmRockKit". To delete this drumkit first load another drumkit."

Since there is no way to rename user drumkits without copying them, the only way to delete the user kit or to load the shadowed system kit, is to select the *other* built-in kit (e.g. TR808EmulationKit) then delete the user kit.

**Comment by trebmuh** [comment]
I can reproduce here with a build from GIT master 1bacb4a on a LibraZiK-3 (Debian Buster based).

**Comment by theGreatWhiteShark** [comment]
Nice catch!
