### ISSUE TITLE
[Feature request] Allow to download many or all drumkits from a list at once

### ISSUE THREAD

**Issue by moonshaadow** [hydrogen-music/hydrogen#1143]
Hydrogen version *          : last from git
Operating system + version  : ubuntu studio 18.04 +KX repos
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
It could be nice to have possibility of download many things at once. Most of the time, description ( which is a nice feature ) is not enough, user has to download and test the kit to have a good preview. So to download many kits is currently a long and repeating thing to do.

Such a feature might need a way to add the kit's size in the description.

**Comment by theGreatWhiteShark** [comment]
You are right. A "download all" button would be nice.

**Comment by trebmuh** [comment]
Even better would be a tick box on each available drum kit line, then the user could make a selection.

**Comment by mauser** [comment]
Hi,

what about sth. like this?

![H2_OnlineImport](https://user-images.githubusercontent.com/202461/115088205-f5accb00-9f0f-11eb-9f75-009d28d14dfc.png)

One thing bothered me.. The already installed items have no checkbox, which breaks the alignment of the items. Not sure if this can be easily fixed, but i'm also not sure if this an issue for other people :smiley:

**Comment by trebmuh** [comment]
That looks awesome.

**Comment by moonshaadow** [comment]
Hi. This look very good!
Maybe the already installed items could have a greyed tickbox or something similar if you carry about alignement.
In any case it will do the job for sure! It's clean and understandable.

**Comment by cme** [comment]
> Maybe the already installed items could have a greyed tickbox or something similar if you carry about alignement.
> In any case it will do the job for sure! It's clean and understandable.

Agreed, a greyed-out tick-box would be my suggestion as it accurately shows the status of the installed kits and the available operation (ie. none :D ) on them.

**Comment by theGreatWhiteShark** [comment]
Implemented in #1992
