### ISSUE TITLE
hydrogen change his colour on closing a QFileDialog.

### ISSUE THREAD

**Issue by wolkstein** [hydrogen-music/hydrogen#115]
Open a QFileDialog, for example in open song. after closing this QFileDialog hydrogen change his default colour layout. now all h2 custom colours switched to system wide (kde) colour layout.

**Comment by thijz** [comment]
Hi Wolke
i cant reproduce this
can you see if this is still present in the latest 0.9.7 ?

grtz
Thijs

**Comment by thijz** [comment]
hi Wolke
any progress on this ?

**Comment by mauser** [comment]
Hi, 
I'm closing the ticket now due to missing feedback. In addition, i can't reproduce it here..
