### ISSUE TITLE
User drumkits shown in library do not sound

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#1153]
Hydrogen version : d1d07a8d4ee2d486345afe14c23d68fbfd4aba4f
Operating system + version  : lubuntu 20

Sorry for opening another issue, but I am not able to hear preview of user drumkits anymore, even if samples are in the folder and drumkits do appear in the library. I can load them but they still do not sound.

I am having this problem since some day, also now building the current master branch

Is this happening to somebody else?

**Comment by trebmuh** [comment]
I've got no issue here with a build from GIT master 1bacb4a

**Comment by oddtime** [comment]
I noticed that layers are not loaded, also there are five new files named `drumkit.xml.bak` in every drumkit directory

**Comment by oddtime** [comment]
If nobody's having this problem I may have introduced it in some branch

**Comment by theGreatWhiteShark** [comment]
Could you attach both the debugging log (when starting Hydrogen as `hydrogen -VDebug`) and one of the affected `drumkit.xml` files?

**Comment by oddtime** [comment]
Ok! I have already restored the old drumkit files and trashed the corrupted drumkit files.
I hope the log file I am attaching is correct
[files.zip](https://github.com/hydrogen-music/hydrogen/files/5920169/files.zip)

**Comment by theGreatWhiteShark** [comment]
> Ok! Unfortunately I have already restored the old drumkit files and trashed the corrupted drumkit files.
I hope the log file I am attaching is correct

Hmm. I can't see anything suspicious. But there were changed to the `Drumkit` and the `upgrade_drumkit` function. So, it's quite possible something can go wrong.

Does this problem still occurs? If so, do the unit tests work? (There is a new one checking whether the drumkit upgrade works and whether the loaded ones are valid)

**Comment by oddtime** [comment]
It seems all right, rebuilt the master and restored that old drumkit, all the tests pass. Unless you don't want I can close the issue
