### ISSUE TITLE
Punch-in/punch-out "feature"

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1166]
I just discovered another "feature" in the code:

When pressing the right mouse key at the position ruler above the song editor and moving it to the right, a red rectangle appears. Well, AFAICS this is all it does.

Judging from the naming in the code the leftmost and rightmost point of the rectangle should serve as punch-in and punch-out. In other words, they define the range recording will be enabled. But that behavior seems to never been implemented.

I'm not 100% sure what to do about this stump. But I would tend to say this is not feature creep but on of the basic controls a (MIDI) recording software should provide. Any thoughts on that? If we tend to implement it rather then removing it, I would add a drawable loop region as well. It would be odd to have punch-in and -out without the loop.

**Comment by oddtime** [comment]
> If we tend to implement it rather then removing it, I would add a drawable loop region as well. It would be odd to have punch-in and -out without the loop

Cool!

**Comment by theGreatWhiteShark** [comment]
> But that behavior seems to never been implemented.

Well, it actually is. Whenever the rectangle is shown recording notes just works in the columns it covers.

I think it's fine the way it is and just needs to be added to the manual.
