### ISSUE TITLE
"Instruments->Clear all" Hangs Hydrogen

### ISSUE THREAD

**Issue by rock-hopper** [hydrogen-music/hydrogen#118]
As the title states, clicking "Instruments->Clear all" causes Hydrogen to hang. Using 0.9.6-beta3 on AVLinux

**Comment by thijz** [comment]
i rock-hopper
is this issue now solved for you?

grtz
thijs

**Comment by rock-hopper** [comment]
Hi thijz
Yes this is fixed. Just compiled the latest code from Git. Thanks!
