### ISSUE TITLE
[Bug] playback does not start after audio export

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#1185]
Hydrogen version *: 010e1c05d5cb24788c7a09c81b18d0f249e7396c
OS: Lubuntu 20
Audio Driver: alsa
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
If I export a song (audio) and close the export  dialog with "x" button on top right
![screenshot-bc7b2a8d](https://user-images.githubusercontent.com/54219881/108590538-5f6f8500-7364-11eb-8602-50cd69409804.jpg)
, the playback doesn't start.
Unless I close the dialog with "close" button.

**Comment by theGreatWhiteShark** [comment]
Do you mean playback in general or the playback track?

In case of the latter: Have you tried to press stop before starting transport? when looking into #946 I noticed that time is not reset after exporting but the transport position is. In other words, Hydrogen might just pretend to have move to the beginning while the playback track has already ended.

In case of playback in general: can you provide the debug log?

**Comment by oddtime** [comment]
I mean the general playback
 the stop button has like no effect and the play button remains always blue.

**Comment by theGreatWhiteShark** [comment]
> here's the log
file.zip

That's odd. Looks like the ALSA driver shutdown and the `DiskWriterDriver` was started up at the beginning of the export as expected. But afterwards the latter persists and is not replaced by the ALSA driver again.

**Comment by oddtime** [comment]
Thanks

**Comment by theGreatWhiteShark** [comment]
Thank you for reporting :)
