### ISSUE TITLE
Beta 0.9.6 (Feb 2011) and Windows 7 Home Premium 64bit

### ISSUE THREAD

**Issue by LHud** [hydrogen-music/hydrogen#119]
I am using the beta release mentioned above and it works well in windows but the only problem I am having so far is that I will get an error and a message from windows telling me it must shut Hydrogen down.  So far this has only happened when allowing a pattern to play for an extended period of time, more than 5 minutes easily in all circumstances but is likely closer to 10 minutes.  I have not had any other issues thus far and this one issue only during pattern play.

Faulting application name: Hydrogen.exe, version: 0.0.0.0, time stamp: 0x4d48a5bc
Faulting module name: ntdll.dll, version: 6.1.7601.18205, time stamp: 0x51db9710
Exception code: 0xc0000005
Fault offset: 0x0002e3be
Faulting process id: 0xbb4
Faulting application start time: 0x01ceb1bbed6a02a8
Faulting application path: C:\Music Tools\Hydrogen\Hydrogen.exe
Faulting module path: C:\Windows\SysWOW64\ntdll.dll
Report Id: 32e27442-1dc6-11e3-9b74-f8d1116e68d4

Athlon II X4 645 q/c cpu
Foxconn mobo
2GB RAM
M-Audio Delta 2496 pci sound card
Windows 7 H.P. 64bit SP1 utd

This is a dual boot system with Ubuntu Studio 12.04, Hydrogen works well with no problems in it so the problem must be related to MS windows, no?

**Comment by mauser** [comment]
I'm closing this since there is a new windows pre-release version at sourceforge.
