### ISSUE TITLE
OSC inconsistencies

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1195]
There are a couple of inconsistencies in the OSC API of Hydrogen

- toggling/changing a binary state is done in various ways (`MUTE` & `UNMUTE` & `MUTE_TOGGLE` vs. `RECORD_READY` & `RECORD_STROBBLE` & `RECORD_STROBBLE_TOGGLE` & `RECORD_EXIT` vs. `TIMELINE_ACTIVATION`)
- there is no way to set the tempo but just to decrease/increase it
- are both `BEATCOUNTER` and `TAP_TEMPO` required? And is there usage via OSC a good idea/do they yield reproducible results?
- `STRIP_VOLUME_RELATIVE` and `MASTER_VOLUME_RELATIVE` do support setting the parameter to 0 by passing `0`. `PAN_RELATIVE` does only support incrementing and decrementing
- `STRIP_VOLUME_RELATIVE`, `STRIP_VOLUME_ABSOLUTE`, `STRIP_MUTE_TOGGLE`, `STRIP_SOLO_TOGGLE` feature the word "STRIP" while the other strip-based commands `FILTER_CUTOFF_LEVEL_ABSOLUTE`, `PAN_ABSOLUTE` and `PAN_RELATIVE` do not 
- `FILTER_CUTOFF_LEVEL_ABSOLUTE` is the only instrument specific command altering a parameter that is not located in the mixer but in the instrument rack. And all the other parameters of the instrument rack are not covered
- `FILTER_CUTOFF_LEVEL_ABSOLUTE` is the only command requiring integer values in the range of [1,127] (and dividing them by 127.0). The `*_ABSOLUTE` commands requiring ranges as well do expect float values in e.g. a range of [0.0,1.5].

**Comment by mauser** [comment]
As a small note: Some of those inconsistencies will also apply to the MIDI mapping, since the OSC actions were build to mimic the behavior of the MIDI actions. So if we rename the OSC command, we should also rename the corresponding midi action (if existing). 
And if a rename happens, there should be an "upgrade" which handles the transition of the string in the users config file.

**Comment by theGreatWhiteShark** [comment]
Thanks for the suggestion. Your right.

In fact, I'm not quite sure whether we should change any of them at all since there are already tools depending on our OSC API (see #1182). But it would be nice to make a clear decision we can refer to and people can find via the issues. Also, it might be a good idea to propose an uniform schema future commands must follow. (But not necessary now since there are more important things to do).

**Comment by theGreatWhiteShark** [comment]
For now I would keep these inconsistencies because breaking the existing API is a really bad thing to do. If there for some reason will be a new major release in the future, this could be streamlined too. But not now.

> there is no way to set the tempo but just to decrease/increase it

This was implemented in #1569
