### ISSUE TITLE
Hydrogen Changes Speeds Randomely

### ISSUE THREAD

**Issue by AshtonTheNerd** [hydrogen-music/hydrogen#120]
So what I do with Hydrogen is, not only drum loops/patterns, but songs.

It all started at 9:29:53 PM. I turned on my computer, logged in, and went straight to Hydrogen. It loaded my most recent song as always. But when I hit the PLAY button, it started to sort of speed up at parts. And with each song, the sped up parts are at different times.

Any one got any solutions? I will be eternally grateful as I love Hydrogen very much.

**Comment by thijz** [comment]
hi Aston and haisojoko
can you please retest with the latest git code and let us know if you still have this issue ?

grtz
Thijs

**Comment by thijz** [comment]
hi Aston and haisojoko
there is a new 0.9.7beta for windows available
can you retest with that version ?

**Comment by haisojoko** [comment]
Will do! Thanks a lot for the update. Just started working with hydrogen
again.

**Comment by mauser** [comment]
Hi,

i'm closing this issue now due to the lack of feedback.

**Comment by haisojoko** [comment]
Alright cool thanks!

**Comment by mauser** [comment]
@haisojoko : Feel free to comment here at any time if the problem occurs again!

**Comment by haisojoko** [comment]
Got it. Thanks a lot man!
