### ISSUE TITLE
pre-1.1 issues while testing a build from master

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#1206]
Hydrogen version *          : GIT 4aa5668 (+ local French translation patch)
Operating system + version  : Debian 10 / LibraZiK 3
Audio driver + version      : JACK

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hi all, here are some findings from a first quick overlooking test while doing the French translation.
Hope that helps.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

![hydrogen-about-1](https://user-images.githubusercontent.com/8705846/110605323-50247000-8189-11eb-8ad0-270becbdb751.png)

If I'm clicking the "A full list of all contributors..." link, I'm expecting the link to be opened in a browser.
But I'm given a blank screen instead which is confusing from a user point of view.

![hydro-about-2](https://user-images.githubusercontent.com/8705846/110605342-54508d80-8189-11eb-9d54-ebbcb80929a3.png)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

![hydro-3](https://user-images.githubusercontent.com/8705846/110605778-c1fcb980-8189-11eb-9212-6a308b5b9c66.png)

What about adding a [20XX - now] next to your names @cme and @theGreatWhiteShark, such as for @mauser ?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The Info -> Donate button always goes to @mauser's paypal account. Is this to be expected? I vaguely remember that it used to be a choice between different options.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

![hydro-4](https://user-images.githubusercontent.com/8705846/110607348-64696c80-818b-11eb-9efe-03cf7547871e.png)

It seems I can't select or unselect those 2 options. Is that to be expected?

**Comment by theGreatWhiteShark** [comment]
Thanks for reporting! I will fix them in the beginning of the next week (I will be AFK for a couple of days).

> The Info -> Donate button always goes to @mauser's paypal account. Is this to be expected? I vaguely remember that it used to be a choice between different options.

Yes. The idea is to have a single account to support the development of Hydrogen. Right now this is the one of Mauser. Maybe there will be a shared one one day.

The second one that was formerly in place offered the possibility to donate explicitly for hosting (website and forum). Since both of them are now hosted at Github for free we did drop this option.

**Comment by trebmuh** [comment]
OK, thanks for caring about that.

We might consider a LiberaPay Team account one day. But this is for another thread.

**Comment by theGreatWhiteShark** [comment]
@trebmuh Could you try #1211 and check whether all the issues are addressed and fixed?

**Comment by trebmuh** [comment]
@theGreatWhiteShark just tested from #1211 and all those issues are solved. Thanks!

**Comment by theGreatWhiteShark** [comment]
close with #1211
