### ISSUE TITLE
There isn't an option to copy a pattern into another pattern

### ISSUE THREAD

**Issue by J-mountain** [hydrogen-music/hydrogen#1235]
Hydrogen version *          :
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

There isn't an easy way to duplicate a pattern into another pattern. If I want to copy pattern 1, I would have to copy it to pattern 11 rather than to the existing ones already there. If we have to create a new pattern every time we want to duplicate another, why give us 10 patterns to start with?

**Comment by mauser** [comment]
Hi,

the current development version of Hydrogen (which will become 1.1..) enables you to do this by just selecting all notes of a pattern via Ctrl + A  and then pasting it to the other pattern via Ctrl + V. Would this feature solve your issue?

**Comment by J-mountain** [comment]
Yes, that would be good, but it would be good to be able to do that from the context menu of the pattern names as well.

**Comment by mauser** [comment]
> Yes, that would be good, but it would be good to be able to do that from the context menu of the pattern names as well and have two ways of doing it.

A "duplicate" option is also present in the context menu with Hydrogen 1.1.

**Comment by J-mountain** [comment]
Sorry, I meant copy and replace

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by theGreatWhiteShark** [comment]
@J-mountain could you check whether the new features in [Hydrogen 1.1](https://github.com/hydrogen-music/hydrogen/releases/tag/1.1.0-beta1) fit your needs?

**Comment by theGreatWhiteShark** [comment]
> Yes, that would be good, but it would be good to be able to do that from the context menu of the pattern names as well and have two ways of doing it.

Apart from click-drag or keyboard selection and copy/paste/replace via Ctrl+X/C/V there is also a context menu when right clicking the selected patterns or notes. The "Select Notes" option in the context menu appearing when right-clicking the pattern name is more of a convenience function for very large patterns. Right-clicking the selection in the pattern editor itself to copy/paste it is almost no additional work and does not causes confusion as adding another "Cut/Paste/Copy Notes" option in the context menu of the pattern itself.
