### ISSUE TITLE
files LocalFileMgr.cpp, LocalFileMng.h

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#1250]
in directory `src/core/`
These files seem to be the same class, I would suggest rename "Mgr" into "Mng".
Does it mean "manager"?

**Comment by theGreatWhiteShark** [comment]
Thx for bringing this up. How about letting this class die?

The `LocalFileMgn::SongWriter` is the only instance of code responsible for writing a class to disk that is located outside of the class itself. I always search the `Basics/Song.cpp` for this code first. All the other XML helper functions could be moved to `core/Helpers/Xml`.

**Comment by oddtime** [comment]
It sounds logical

**Comment by theGreatWhiteShark** [comment]
Covered in #1617
