### ISSUE TITLE
Unable to print version in terminal

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1255]
Hydrogen version *          : d16cbf5a28c486b84aa613a9572475ab18a8f95a
Operating system + version  : Devuan Beowulf

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Is this just me (my system) or is it not possible to print the version of Hydrogen in a BASH?

```bash
hydrogen --version
```

> Hydrogen 

The culprit is easily found since the version is only set for the final `QApplication` and not for the `QCoreApplication` used to parse the command line arguments. The latter has different [fallbacks](https://doc.qt.io/qt-5/qcoreapplication.html#applicationVersion-prop) for different systems, So, the issue might not show up at all supported OSs.

**Comment by oddtime** [comment]
Me too
