### ISSUE TITLE
Clipping oddities

### ISSUE THREAD

**Issue by ajrock** [hydrogen-music/hydrogen#126]
Been exporting layered kick samples, which tends to cause clipping (no big deal). However, the clipped areas tend to reverse: A wave starting to clip at the top will reverse and clip through the bottom instead, generating really nasty clicks and pops. Easily fixable with some wave drawing, but kind of a pain. Any idea why this happens?

**Comment by thijz** [comment]
hi ajrock
can you please retest with the latest version (github) and let us know if this problem is still there ?

grtz
Thijs

**Comment by thijz** [comment]
hi ajrock
any update on this ?

grtz
Thijs

**Comment by ajrock** [comment]
So sorry, yes the initial problem was solved in the new version. I hadn't
checked for a new one in quite a while. Sorry for making you worry!

**Comment by mauser** [comment]
Thanks for re-checking!
