### ISSUE TITLE
Instruments made up of more than one sample bank playing simultaneously

### ISSUE THREAD

**Issue by jasper-lyons** [hydrogen-music/hydrogen#127]
This is a proposed enhancement. 

Currently an instrument can only support one bank of 16 samples, each sample played when a velocity, within the layer which holds the samples thresholds, is played. 

I would like to propose the addition of multiple sample banks for each instrument. This would allow a user to have, for example, a snare drum top, bottom, room, over head and bleed banks, each of which would have their samples played.

This would require the ability to decouple the instrument->channel link and allow a user, should they wish, to direct the audio output from any instruments sample bank to any channel. E.g. A user could direct sample audio from a snare instruments overhead sample bank, to an over head channel.

**Comment by thijz** [comment]
afaik this has been implemented and works (mostly :-)
