### ISSUE TITLE
rotary_center_images.png anomalies

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#1272]
There are some graphic anomalies in files:
`data/img/gray/mixerPanel/rotary_center_images.png`
`data/img/gray/mixerPanel/rotary_images.png`

The first has one less frame, but most important is not centered:
you can compare both in gimp and see that if you shift the first image by two frames to the right, the central (green) frame corresponds to the second.

I don't know if this is correct, however it was not described in the code that one image had less frames.
Currently there's a bug at development caused by #1013, where I dropped out some lines in the rotary class (now I understand).
Way to reproduce: pan an instrument at full right, save, close and reload the song => the knob image is broken.

I plan to fix it, if you are ok I will do it together with the deprecation of members `pan_L` `pan_R` which is almost ready to be pulled

**Comment by theGreatWhiteShark** [comment]
> if you are ok I will do it together with the deprecation of members pan_L pan_R which is almost ready to be pulled

Since the bug only affects development that's fine.

> There are some graphic anomalies in files:
data/img/gray/mixerPanel/rotary_center_images.png
data/img/gray/mixerPanel/rotary_images.png

Nice catch!

But I also think those pictures are quite likely to die prior to the 1.2 release as they need an update to SVGs.

**Comment by oddtime** [comment]
Ok, until the SVG or other type of GUI redesign will come the current png images are ok.
The bug is fixed in #1273 where the different number of frames is taken into account.

**Comment by theGreatWhiteShark** [comment]
implemented in #1282
