### ISSUE TITLE
CoreAudio driver does not verify audio format / sample rate parameters

### ISSUE THREAD

**Issue by cme** [hydrogen-music/hydrogen#1275]
Hydrogen version *          : 1.1 beta + all before
Operating system + version  :  MacOS X
Audio driver + version      :  CoreAudio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The CoreAudio audio driver for OS X attempts to set the sample rate and format, but does not 
  - check for an error returned from `AudioUnitSetProperty` when setting the format, or
  - verify that it actually got the sample rate and format it asked for.

I discovered this because my new bluetooth headphones don't support the sample rate that Hydrogen had been configured for.

That was unpleasant.

**Comment by cme** [comment]
After some more digging, there's some very odd behaviour from CoreAudio.

We fail to set the desired sample rate (48000) on the AudioUnit. Reported sample rates for the AudioUnit and the AudioDevice both agree on the sample rate of 44100. The device reports a buffer size of 512 as expected, but the audio callback asks for processing of (and provides a buffer sufficient for) *557* frames.  Suspiciously, 557/512 ~= 44100/48000.

It's *almost* as if CoreAudio is trying to allow the AudioUnit to speak in 48000 as it requested, and providing appropriate buffer space and sample count for it to do so (and, perhaps, CoreAudio intends to then downsample to 44100), except that the *AudioUnit* property reports that its sample rate is 44100. Apple's documentation doesn't seem to be very helpful.

It's *possible* that this is what it's doing, which I will test by setting a noticably different sample rate and seeing if the audio does get resampled.

It's possible it's just a weird buffer sizing bug, though, without any audio resampling. In which case, we should handle that buffer sizing. The CoreAudioDriver currently trusts the buffer size returned from CoreAudio as the number of samples to process (512), rather than using the nSamples parameter on the callback (557) which leads to junk past the end of the processed buffer being played.

We could handle this by reporting the CoreAudio-provided buffer as the buffer for the audio callback to use, though I think this might have some trouble because it only has a guaranteed lifetime within the callback (this is all that should be necessary), but I think it might be checked for existence at some point outside that callback. 

Yuck.

**Comment by theGreatWhiteShark** [comment]
Hmm. When using the *JACK* driver Hydrogen can only work with the sample rate the *JACK* server was started with and the option is disabled in the menu. I don't know how CoreAudio is designed but if a number of programs are connected to the AudioUnit/AudioDevice it could be quite hazardous to allow a single program to alter the sample rate because all others would have to listen to and adapt to the changes. And I bet such an update isn't implemented in the `CoreActionDriver`.

**Comment by cme** [comment]
Yep, it's designed explicitly to work well with multiple clients (and mostly seems to do so virtually flawlessly) and there's a HAL in between AudioUnits and the device. 

The behaviour seems to mostly make sense: setting the sample rate on an `AudioUnit` doesn't affect the *device* sample rate, and each call into the render callback asks for a number of frames corresponding to a unit of time that's the same as the connected *device*'s buffer size * same rate, with CoreAudio presumably resampling to rate-match them.

It's odd that reading back the stream info from the AudioUnit returns the sample rate of the device, though, rather than the sample rate of the AudioUnit, but since it's abstracted it seems there should be no need to read it back.

So, the Hydrogen bug here really seems to be assuming that the buffer size reported for the *device* will be the number of frames expected to be asked of the render callback.

This is not entirely trivial to fix because I haven't yet found a way to reliably get the *AudioDevice*'s buffer size in advance of entry to the render callback. This may be at least partially by design, because the number of frames needed by each render callback can differ due to jitter since the number of samples in the AudioUnit's sample rate doesn't necessarily map to the device's buffer time with an integer ratio.

Even if there's no way to query it in advance, it should be possible to calculate an upper bound using the device's buffer and sample rate and multiplying by the ratios of sample rates and rounding up -- this is needed for LADSPA buffer allocation and maybe other things too. There's also a few places where the assumption that the number of frames per callback is constant and equal to the buffer size, these I think should be easy to fix.

**Comment by cme** [comment]
It turns out that the buffer size, although passed to `audioEngine_setupLadspaFX()`, isn't actually used for anything, and is only checked for non-zero'ness. 

The only actual use of the buffer size is in attempting to compensate for the latency when getting the real time tick position. I've left that unchanged.
