### ISSUE TITLE
Sound Library Import window - not long enough for Windows 10

### ISSUE THREAD

**Issue by kb0pxn** [hydrogen-music/hydrogen#1283]
Hydrogen version *          : 1.1.0-beta1
Operating system + version  :  Windows 10
Audio driver + version      :  Not Applicable

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

'Sound Library Import' Window (in Windows) needs to be extended downward a bit. (longer length).
Can't find in config to extend it.  The download button at the bottom is almost entirely truncated.

Please and Thank you.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by mauser** [comment]
Hi! 

Coul you add a screenshot? What is your screen resolution? It looks perfectly fine with on my Windows 10 system:

This is how it looks for me:

![grafik](https://user-images.githubusercontent.com/202461/119253820-4ec4ea00-bbb3-11eb-8182-81dfd8bb68eb.png)

**Comment by cme** [comment]
The dialog is now using QLayouts so should be dynamically laid out correctly. I'm curious to see what way that fails in.

**Comment by cme** [comment]
Aah! I've reproduced what I suspect is the problem. It's a display scaling issue. It looks like the UI is scaled acording to the display scaling factor, but the windows are fixed size in pixels. >_<

**Comment by theGreatWhiteShark** [comment]
> This is, I think, a Qt bug, since on Linux the window sizes are correctly scaled by the UI scaling factor (this is how we're generating the new high-res screenshots for the manual)

Hmm. Is there anything we can do against it? It sounds general enough to affect other windows, like the PreferencesDialog or the SampleEditor, too

**Comment by kb0pxn** [comment]
Noob's Update:

I was running 150% size (recommended), but once I changed to 100% it was
showing fine. I will adapt to smaller - unless there is a fix  :) .

Thank you, I was intimidated to mention this (my first bug report ever) but
you folks are very attentive and I appreciate it.

I'm having too much fun with Hydrogen.  Thanks.  Jim

**Comment by cme** [comment]
After a bit more investigation, it seems it's not quite that, but rather it seems the sizes of the widgets aren't scaled linearly. I think in either case the answer is to make sure the layout hierarchy is fully connected and do an `adjustSize` on the dialog before fixing its size. There are a few places this affects.

**Comment by theGreatWhiteShark** [comment]
> I think in either case the answer is to make sure the layout hierarchy is fully connected and do an adjustSize on the dialog before fixing its size.

Is this only relevant for (free standing) windows or should we also adopt the usage of `adjustSize` in front of `setFixedSize` for other widgets too?

**Comment by cme** [comment]
> Is this only relevant for (free standing) windows or should we also adopt the usage of `adjustSize` in front of `setFixedSize` for other widgets too?

There aren't many other uses of `setFixedSize`, and I didn't see any others that looked suitable. In order to work right, it needs all containing children of the widget to have (or be) a `QLayout` so it can entirely rebuild the layout.

We might want that sort of functionality for eg. pattern / song editor lines, but  we don't have the right mechanisms to use `adjustSize` for them.

**Comment by theGreatWhiteShark** [comment]
> There aren't many other uses of setFixedSize, and I didn't see any others that looked suitable.

There are a couple calling `setMinimumSize` and `setMaximumSize` in a row - which you replaced by `setFixedSize` at some point in your PR - , like the `AboutDialog`, `MasterMixerLine`, `CpuLoadWidget`, and in the `LCD`s.

> In order to work right, it needs all containing children of the widget to have (or be) a QLayout so it can entirely rebuild the layout.

So, creating the widget in the QtDesigner is more favorable than doing so using `new XX` and `XX->move` commands like in the `InstrumentEditor`, right?

**Comment by cme** [comment]
> > In order to work right, it needs all containing children of the widget to have (or be) a QLayout so it can entirely rebuild the layout.
> 
> So, creating the widget in the QtDesigner is more favorable than doing so using `new XX` and `XX->move` commands like in the `InstrumentEditor`, right?

Wellll.... using `QLayout`s is generally preferable to using `XX->move`, I'm not entirely sure using QtDesigner, as a tool for achieving that, is better -- it can be finnicky, and `.ui` files are hard to diff. Explicitly writing C++ that uses `QLayout` might have some advantages, certainly in terms of adapting existing code. Hmm..... *ponders*

**Comment by theGreatWhiteShark** [comment]
> Explicitly writing C++ that uses QLayout might have some advantages, certainly in terms of adapting existing code.

Hmm. Never done that before. I'll give it a try.
