### ISSUE TITLE
Beat note bullet graphic in pattern editor is very small - possible to change it?

### ISSUE THREAD

**Issue by ViktorNova** [hydrogen-music/hydrogen#129]
I couldn't think of a more eloquent way to describe this, but I'm trying to make the "hit" graphic in the pattern editor larger, as it is very small. It looks like a little bullet point and only takes up 1/3 of the available vertical space

Is it possible to make this bigger, or even change it entirely? Is this an svg? I looked through the img directory and didn't see anything obvious. I managed to "elongate" it slightly by increasing patternEditorGridHeight to 45, and this helps, but not enough for the hi-res screen I'm working on, it's very difficult to see live.

**Comment by theGreatWhiteShark** [comment]
Hmm... TBH I don't like the idea much. It's true that the current note symbols do not fill much of the available space using the default zoom and resolution settings. But the moment you insert notes at a finer resolution, like 1/64 or using "off", your rectangles will overlap. In addition, when filling a lot of notes for multiple instruments, it will become harder to navigate by eye using the rectangles as they hide the tick marks on the grid lines.

There have been quite a number of things done in terms of UI and scaling on hi-res screens. I will close this issue for now but please feel free to reopen it in case the current state of note rendering does still not fit your needs.
