### ISSUE TITLE
system scalling ui is too big

### ISSUE THREAD

**Issue by Reaper10** [hydrogen-music/hydrogen#1347]
Hydrogen version *          : 1.02
Operating system + version  :  window 10
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

system scaling ui is too big

<img width="856" alt="Capture" src="https://user-images.githubusercontent.com/8137561/129744631-58420a43-2b55-4013-9958-00f4b0615b6d.PNG">

**Comment by cme** [comment]
Hi, can you explain what you mean by "too big"? That looks to be about the right proportions for linear scaling the UI. Do you mean that it appears disproportionately large? Or that the bottom is inaccessible due to the size it occupies? (this has annoyed me on occasion, I now realise).

**Comment by Reaper10** [comment]
<img width="833" alt="1" src="https://github.com/hydrogen-music/hydrogen/assets/8137561/15185faa-cb0c-4103-9742-29cf257d6601">
can't see

**Comment by Reaper10** [comment]
no its still too big
<img width="840" alt="Screenshot 2024-05-22 202855" src="https://github.com/hydrogen-music/hydrogen/assets/8137561/277c3701-f059-4a77-b96f-94d5fcd694c0">

**Comment by theGreatWhiteShark** [comment]
Fixed in #1980
