### ISSUE TITLE
Mixer not showing W10 64 .... solved

### ISSUE THREAD

**Issue by aomahana** [hydrogen-music/hydrogen#1369]
Hydrogen version *          :1.1.0
Operating system + version  : Windows 10 Pro 64 bit
Audio driver + version RME     : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hi,

Thanks for the new version 1.1.0!!

I have been having a problem with seeing the Mixer.
Reverting to earlier versions of Hydrogen didn't help.

My computer is set up with removable hard drives so I can use either Windows 10 64, or Windows 7 32.
It is also dual monitor.
When I loaded Hydrogen v1.1.0 in Win 7 32 it behaved as expected.

I had recently upgraded my GPU (MSI GTC 1050 TI). 
I was unsure if the problem was with Hydrogen, the Nvidia drivers, or Win 10 64.
I still don't know the answer to that ....

Eventually I  found that if I opened ....  
Options / Preferences / Appearance
Default interface layout   change from    Single pane    to     Tabbed Pane
I could now see the mixer when I clicked on the mixer tab.
When I reopened Hydrogen and then re-selected    Single pane   I could still see the mixer (Yay!!!)
I moved the mixer to my second monitor, saved, and now all is well.

My guess is that the mixer was always there, but hidden behind the main screen.

This solution took me quite some time to find.
This is why I leave this message, in case it can help someone else.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by cme** [comment]
Good find!

It looks like recorded window locations and sizes are applied without regard to the current screen size. We should
  * Clamp any window sizes to the maximum available display size, and
  * Adjust window locations so they're within the display area

**Comment by cme** [comment]
This is fixed by #1380 and #1385 which will be in the 1.1.1 release. Closing for now!
