### ISSUE TITLE
Hydrogen 1.1.0 stable version - problem with saving Preferences as below

### ISSUE THREAD

**Issue by YungPhil** [hydrogen-music/hydrogen#1375]
Hydrogen version *          :1.1.0 eda3557e
Operating system + version  : Windows 7 Home Premium service pack 1
Audio driver + version      : Port Audio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Good afternoon - I have downloaded the new 64 bit version of Hydrogen which has some great new features

My issues - In Options  - Preferences - changes I make to the various options e.g. Beat counter drift compensation, and Beat Counter Start Offset in m/s are not saved. I can change the m/s settings but when I apply close and then reopen they have reverted back to default settings as found when I open the tab. Also applies to tick boxes above. 
I have also check tick box options under the MIDI Tab - these selections are similarly not saved when I click OK and close 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by theGreatWhiteShark** [comment]
That's indeed quite odd

**Comment by theGreatWhiteShark** [comment]
This seems to be introduced in 30e569ba08fc19660afe13ce3a545cf43435d211 .

What happens behind the scene is that Hydrogen discards the changes applied using the Preferences Dialog whenever you reopen the dialog.

But all the changes done there are still applied. When closing Hydrogen and reopening it, all changes performed during the last opening of the Preferences dialog should still be present.

**Comment by YungPhil** [comment]
Yes you are right - I tried setting a few preferences/ticking boxes then saved and closed the file and the changes were there on reopening. If I understand correctly the Preferences info is therefore saved with a file

**Comment by cme** [comment]
Yep mea culpa! Thanks for finding @YungPhil.

We should push out a 1.1.1 (a very pleasing vernion number...) with the fix soon, after the dust settles a bit more.
