### ISSUE TITLE
Hi-Hats and mute group issues in drumkits

### ISSUE THREAD

**Issue by JosteinAndersen** [hydrogen-music/hydrogen#1407]
Hydrogen version *          : hydrogen-master (as of 2021-11-16 - 10:50)
Operating system + version  :  Kubuntu 20.04
Audio driver + version      :  

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Hi,

I'm testing the new GUI system (working fine and looking good so far) and using the GMRockKit, I noticed that it's no mute group for the HH. Then I tested the other drumkits as well and also here, it's without mute groups or closing the open HHs. The drumkits based upon real drum samples are gaining better quality, so it's important that this is done right in order to make things sound like a real HH.

As a thumb of rule, every HH sample should be in a mute group and every open HH should have the "Auto-Stop Note" option ticked, then everything will sound much more normal.

If you don't have time to fix it, then I can do it, but I do not know how to make a pull request (yet).

Jostein

**Comment by theGreatWhiteShark** [comment]
Hey @JosteinAndersen,

> I noticed that it's no mute group for the HH. Then I tested the other drumkits as well and also here, it's without mute groups or closing the open HHs. The drumkits based upon real drum samples are gaining better quality, so it's important that this is done right in order to make things sound like a real HH.

I agree. Having mute groups set for all hi-hats sounds like a good idea.

> every open HH should have the "Auto-Stop Note" option ticked, then everything will sound much more normal.

That might be more a matter of taste. If notes aren't triggered so rapidly, unchecking this option gives a rough "room" experience.

> If you don't have time to fix it, then I can do it, but I do not know how to make a pull request (yet).

Thing is, that whether these options are set or not is up to the person creating the drumkit (the drumkit itself is just a container for samples and settings. Each user can alter them and bundle the result into a new, custom kit). But mute groups might be a feature introduced after most kits have been created. So, there is room to argue that those changes might reflect the intention of the original design.

In addition, the kits aren't hosted at github itself but at (the old) sourceforge account. They can't be altered using a pull request but this has to be done manually.

**Comment by JosteinAndersen** [comment]
Thanks for answering!  :-)  

An open HH sound should not ring when one hit a closed HH or step on the HH pedal. Should this really be a default setting, it's after all an anomaly - taste or not. Two of these drumsets are intended to sound like real drums (at least the AVL drums), so why shouldn't the HH follow the same intention?

Well, I have had this discussion with several people in the LAU community over the years and it seems to me that most Linux Audio Users are working on electronic music where this matter has other priorities and wishes. 

I'm very grateful that the mute group capabilities are there. If I remember right, Sebastian or Comix kindly implemented this after I ask for it. That's some years ago now. :-)

I hope that this post can stay open a little while so we can talk a little mre about it.

**Comment by theGreatWhiteShark** [comment]
> An open HH sound should not ring when one hit a closed HH or step on the HH pedal. Should this really be a default setting, it's after all an anomaly - taste or not. Two of these drumsets are intended to sound like real drums (at least the AVL drums), so why shouldn't the HH follow the same intention?

I'm not quite sure whether we talk about the same thing. The behavior above should be determined solely by the mute group. The Auto-Stop-Note feature, on the other hand, will stop a note as soon as a new one from _the same_ instrument is present.

**Comment by JosteinAndersen** [comment]
I misunderstood what "Auto-Stop Note" is, so please, forget I mentioned it!  :-)

However I still strongly believe that the HHs in the kits should be in a mute group, but I can live with that no one does anything about it. :-)  Thanks for listening and showing patience when I mentioned "Auto-Stop Note". I close the issue now.
