### ISSUE TITLE
Select the current playing pattern from a PC keyboard

### ISSUE THREAD

**Issue by coldner** [hydrogen-music/hydrogen#1410]
Is it possible to select the current playing pattern by a keyboard shortcut?
It would be really nice for a manual switching current playing pattern (e.g. using numbers 1,2,3...), or at least switching by "next/previous" pattern.

**Comment by theGreatWhiteShark** [comment]
> Is it possible to select the current playing pattern by a keyboard shortcut?

Yes. You can either use the [MIDI API](http://hydrogen-music.org/documentation/manual/manual_en_single_page.html#chpt.midi) or [OSC API](http://hydrogen-music.org/documentation/manual/manual_en_single_page.html#chpt.osc.commands) to switch the current playing pattern. For MIDI you can use [VMPK](https://vmpk.sourceforge.io/) to directly bind the pattern change action to a specific keyboard key. Using OSC you can write a custom script e.g. using Python to achieve a lot more complex things.

**Comment by coldner** [comment]
I installed a virtual midi device, but when I try to use this device as input in Hydrogen, then the app crashes.

https://user-images.githubusercontent.com/35400886/142785044-57be189d-45c4-4fbf-b4bf-eabf2ee4abaf.mp4

**Comment by theGreatWhiteShark** [comment]
That doesn't sound good. Could you set the log level using menu > Debug > Log level to "Debug", open the log file, reproduce the crash, and post the log in here?

**Comment by coldner** [comment]
[hydrogen.log](https://github.com/hydrogen-music/hydrogen/files/7579855/hydrogen.log)

**Comment by theGreatWhiteShark** [comment]
Would you mind trying [this](https://ci.appveyor.com/project/mauser/hydrogen/build/job/h9ff229dqq30re0t/artifacts) version of Hydrogen and reporting back the log?

**Comment by coldner** [comment]
Good news. It works on `f55a6593` version. I'm able to control Hydrogen from VMPK using a PC keyboard.
I tested it with *LoopBe1* and *loopMIDI* and everything was fine.
I think this bug was already fixed on unstable branch.

Thank you very much!

**Comment by theGreatWhiteShark** [comment]
Great news!
