### ISSUE TITLE
Drumkits get messed up if their sample names are not unique

### ISSUE THREAD

**Issue by unfa** [hydrogen-music/hydrogen#142]
I was working on a drum kit - I prepared my samples in this manner:

```
kick/01.flac
kick/02.flac
kick/03.flac
kick/04.flac
snare/01.flac
snare/02.flac
snare/03.flac
snare/04.flac
...
```

After creating and saving the drum kit, restarting Hydrogen and loading it again - all instruments played the kick drum's samples (kick/01.flac played instead of snare/01.flac etc.). The instruments were completely messed up. I guess Hydrogen overwritten the samples in the drum kit package because their names were the same (I loaded them from different directories).

Please make Hydrogen resistant to this kind of issues - it could be prefixing each sample with a random unique ID (generated with command _pwgen -1 6 8_)

```
 ko0oLe_01.flac
 Iejei9_01.flac
 oSh6if_01.flac
 nuy8Ce_01.flac
 rai6Ai_02.flac
 Nahy3A_02.flac
 tiuv6O_03.flac
 Vahm0y_03.flac
 ...
```

or simply - a index number (assigned in order of loading samples to the drum kit)

```
 000001_01.flac
 000002_02.flac
 ...
 000013_01.flac
 000014_02.flac
 ...
```

...or even replacing the file name completely - then each sample can be referenced with just one int value, not a string of characters:

```
 000001
 000002
 000003
 000004
 ...
```

This can scare a lot of artists off - when their hard work is for nothing. I'm gonna make this kit anyway, but... hey! ;)

**Comment by thijz** [comment]
hi unfa
could you retest this and report back ?

grtz
Thijs

**Comment by thijz** [comment]
hi Unfa / Xnakos
any progress on this ?

grtz
Thijs

**Comment by jeremyz** [comment]
this feature exists for ages .. before e05cfcc7 2015-07-20

**Comment by unfa** [comment]
Hey, sorry. I haven't been making Hydrogen drumkits in years, and I forgot about this.

**Comment by jeremyz** [comment]
No problem, it's fun to be able to close an issue without any work ;)
