### ISSUE TITLE
crashes some times

### ISSUE THREAD

**Issue by Uhboy** [hydrogen-music/hydrogen#1422]
1.1.1 *          :
Windows + 10  : 
Windows /or default computer drives     : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

some times work perfectly, some times crashes, some time is imposible listen the imported samples

**Comment by trebmuh** [comment]
It will need to be much more precise in order for someone to try to help you.
Please describe as much as possible what you do (every step), what you expect the software to do, and what happens.

**Comment by theGreatWhiteShark** [comment]
Hey @Uhboy ,

Could you provide a step by step guide to reproduce this issue?

**Comment by theGreatWhiteShark** [comment]
Closed due to lack of information.
