### ISSUE TITLE
"Could not save pattern to temporary directory." (Pattern names used as temporary filenames)

### ISSUE THREAD

**Issue by cme** [hydrogen-music/hydrogen#1425]
Hydrogen version *          : 1.1.1 + all others
Operating system + version  : All (Windows in particular)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The Song Editor uses pattern names, without escapes, as the basenames for temporary files used to store patterns when deleting patterns. 

No restrictions are placed on pattern names in the Song Editor, so there's no guarantee they will be valid filenames on the host platform. Particularly on Windows where things like '~', '\', '::' etc aren't valid in filenames (and on other platforms, '/').

To reproduce: 
  - create a pattern named `Pattern 1/2\3~4::5`
  - try to delete it

(This is first noted in discussion in #1047)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by theGreatWhiteShark** [comment]
Nice find!

**Comment by cme** [comment]
Fixed with #1428
