### ISSUE TITLE
Segmentation fault on clicking del when no notes

### ISSUE THREAD

**Issue by lukakostic** [hydrogen-music/hydrogen#1448]
Hydrogen version *          : 1.1.1
Operating system + version  :  arch linux / manjaro
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

![image](https://user-images.githubusercontent.com/41348897/148783812-a978d47b-b32d-4729-abc5-6a55864c5eed.png)

Clicking del while the sequencer is in this state (no notes / pattern bars) leads to a segmentation fault.

You can also open any project (or a new one), select all notes (ctrl-A or select mode drag all) and click del twice.
del once deletes all, del second crashes with seg fault.

**Comment by cme** [comment]
Oops. Nice catch, thank you.

**Comment by theGreatWhiteShark** [comment]
Already fixed in `master`
