### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by blixa71** [hydrogen-music/hydrogen#1458]
Hydrogen version *          : 0.9.7
Operating system + version  : linux mint 19.3
Audio driver + version      : ALSA

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

While playing in song mode, auto focus on the actual pattern that is heard.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by cme** [comment]
Hi, this feature is already is in `master` and will be included in release 1.2.

**Comment by theGreatWhiteShark** [comment]
Closed with #1563
