### ISSUE TITLE
Fatal Issue: Autosave blanking out multiple works.

### ISSUE THREAD

**Issue by djearthquake** [hydrogen-music/hydrogen#1463]
Hydrogen 1.0.1 [Feb 19 2021] Linux ASSET_NAME 5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux
Autosave is blanking out entire projects. Hours wasted. It's too hard-coded and pushed making a mess of everything it touches. There's currently no way user can disable it?
[Was a problem 10 years ago also.](https://hydrogenaud.io/index.php?topic=99705.0)

**Comment by theGreatWhiteShark** [comment]
Hey @djearthquake ,

Could you describe - maybe in a step-by-step guide - how a project was lost? Autosave should only add another file next to the song you touched and not saved right away.

There is already #454 and a candidate solution #458. I guess we can integrate it in the next release.

> Was a problem 10 years ago also.

Yeah, there have been some additions to the development team recently and now we try to handle the big pile of issues in the little time we have. So, thanks for bringing it up again! It helps deciding which of all the open stuff is still annoying people.

**Comment by djearthquake** [comment]
@theGreatWhiteShark #458 is fine. I tried to recreate this quickly. Maybe that is enough to debug the feature for those who want it on. Save a song with new name. Make a beat. Add and name and spend hours on surgically cut layered instruments. Do not name the pattern. Click X. Was not asked if I want to save. It had autosaved many blank songs instead. There are other times all involving believing autosave works when existing project is opened and final cuts are made. Go back later. Never happened. See various files saved. Sometimes want original file back it's gone.

**Comment by theGreatWhiteShark** [comment]
Ah, I see.

This is a bug but, fortunately, it's already fixed (#1261). When upgrading to version 1.1.0 or 1.1.1 Hydrogen should always ask you whether you want to save your changes regardless of the autosave.

**Comment by djearthquake** [comment]
That would have saved the total loss only under that condition. Autosave is failing to regularly save as expected.  Abnormal exit / loss of power / version with it not asking each time to save on close. Autosave tends to make series of copies of original file instead autosave. The jam I was on all day. Many changes. All blank autosave files.

**Comment by theGreatWhiteShark** [comment]
> Autosave tends to make series of copies of original file instead autosave.

Well, there is certain stuff that can't be undone (yet). Also, the Undo history get's lost when reopening the application. I'm working on a patch that hopefully makes the whole thing a little more convenient.

Also, when using an empty or a demo song as starting point (without clicking "Save As") Hydrogen does currently not create autosave files as it tries to put them right next to those songs which are located in a read-only system area. This will also be dealt with in the patch. Then there should always be some autosave backup in the hydrogen user's data folder.

**Comment by djearthquake** [comment]
Thank you very much for #1465. It looks real good.
