### ISSUE TITLE
port audio adding ASIO capability

### ISSUE THREAD

**Issue by aomahana** [hydrogen-music/hydrogen#1480]
Hydrogen version *          : v1.1.1
Operating system + version  : Window 10 64
Audio driver + version      : Lynx 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Hydrogen V 1.1.1 is now working much better with Windows.
Thank you to those of you who are continuing development.

Hydrogen sees my audio devices, although I have to use WASAPI drivers rather than ASIO,
ASIO would allow more direct control, and better latency.
When I googled Port Audio ASIO, I see that others have already developed a linking code.
Perhaps this might be integrated into Hydrogen?

Here are three links, to check whether these codes could work with Hydrogen.
I am not a coder, so someone with knowledge needs to evaluate whether these ideas are viable for Hydrogen

https://hal.archives-ouvertes.fr/hal-02158911/document
https://github.com/EddieRingle/portaudio/blob/master/src/hostapi/asio/ASIO-README.txt
https://www.ee.columbia.edu/~mim/meap/paMat/portaudio_v18_1/docs/pa_tut_asio.html

Bye now,
aomahana.
< describe your issue or feature request here ** >

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by mauser** [comment]
Hi! 

it seems that the ASIO SDK is not free software, it is released under its own license. Unlike with VST, there is no GPL-dual licensing for the ASIO SDK (see license agreement in https://www.steinberg.net/asiosdk). So shipping Hydrogen with a portaudio version that has ASIO support is not a technical problem, but a legal one.

**Comment by aomahana** [comment]
What a shame ....
Thanks for checking it out.

**Comment by mauser** [comment]
No problem! Sadly Steinberg's licensing is always a bit unclear, which gives headaches to smaller projects like us who can't afford to take risks or employ a lawyer to analyse the situation. Lets hope that they will adopt the GPL dual-licensing model in the future for the ASIO SDK.
