### ISSUE TITLE
consider removing the License from the translation file (.ts)

### ISSUE THREAD

**Issue by nikoss** [hydrogen-music/hydrogen#149]
I just copied the License part from the .ts file... saved it as "license.txt"... and it is
 102.5KB. 
The .ts file (with part of the translations already done) is 
 217KB.

The License strings are more than half of the translation file!!!

1st:   No one is going to translate the license.
2nd: There are, already, translated versions of the license available on the web, for various languages.
3rd: If your computer is not that fast, it takes time for github to print the translation file, follow changes etc. Unnecessary workload for all of us.
4rth: Makes translation statistics useless (because you would have to calculate "minus" the license :confused: )

**Comment by mauser** [comment]
Hi! 

Thanks for reporting the issue, this has been resolved now (finally....).

**Comment by trebmuh** [comment]
Added to https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-0.9.7#all-platforms
