### ISSUE TITLE
Found some errors when filling notes

### ISSUE THREAD

**Issue by Djard** [hydrogen-music/hydrogen#1516]
Hydrogen version *          : 1.1.1
Operating system + version  : Win 10 Pro
Audio driver + version      :  Latest version of Realtek Hi-def audio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

< describe your issue or feature request here ** >
In Pattern Editor, right-click on an instrument -> Fill Notes. All values are OK except 1/2, 1/8 and 1/16. Below is what I get.

Fill All Notes: OK
1/2 Notes: Erroneously fills with 1/8ths. (should fill with 1/2 notes)
1/3 Notes: OK
1/4 Notes: OK
1/6 Notes: OK
1/8 Notes: Erroneously fills with 1/2 notes. (should fill with 1/8th notes)
1/12 Notes: OK
1/16 Notes: Erroneously fills with whole notes. (should fill with 1/16th notes)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by cme** [comment]
This is not an error, but perhaps a misunderstanding about what it's supposed to do based on ambiguity of the fractional way it's expressed in the menu items.

The fill notes function enters notes [based on the currently set grid resolution](http://hydrogen-music.org/documentation/manual/manual_en.html#chpt.song_editor.sidebar). Hence, "all notes" adds a note to each grid position -- "fill 1/2 notes" adds a note to every one out of 2 grid positions, "1/3" adds a note to every third grid position:

<img width="970" alt="image" src="https://user-images.githubusercontent.com/768466/157113563-6c1ed6f0-177b-4f2f-af98-0d0d21cbcffd.png">

It's unfortunate that expressing that in fractional short-hand happens to look like it's supposed to be referring to note values!

**Comment by Djard** [comment]
Thank you for the clarification. I am most grateful.
