### ISSUE TITLE
Segmentation falt loading drumket

### ISSUE THREAD

**Issue by worikgh** [hydrogen-music/hydrogen#1547]
Hydrogen version *          : Git master
```
patch@patchbox:~/hydrogen $ ./hydrogen -v
hydrogen 1.1.1-'ffe835d7'
```

Operating system + version  : patchboxos 1.3.2 (Raspberian based)
Audio driver + version      : jackd 1.9.12

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Start programme 
Wait for the flexing of windows to finish 
Go to `Drumkit` -> `Open`
GMRockit

Segmentation fault

```
Thread 1 "hydrogen" received signal SIGSEGV, Segmentation fault.
0x31002300 in ?? ()
(gdb) frame 0
#0  0x31002300 in ?? ()
(gdb) bt
#0  0x31002300 in ?? ()
#1  0x000be704 in HydrogenApp::onEventQueueTimer (this=0x532fd0) at /home/patch/hydrogen/src/gui/src/HydrogenApp.cpp:732
#2  0x00074d84 in HydrogenApp::qt_static_metacall (_o=0x532fd0, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0xbeffe89c) at /home/patch/hydrogen/build/src/gui/hydrogen_autogen/UVLADIE3JM/moc_HydrogenApp.cpp:93
#3  0xb5755244 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/arm-linux-gnueabihf/libQt5Core.so.5
#4  0xb57620f0 in QTimer::timeout(QTimer::QPrivateSignal) () from /lib/arm-linux-gnueabihf/libQt5Core.so.5
#5  0xb5755ba0 in QObject::event(QEvent*) () from /lib/arm-linux-gnueabihf/libQt5Core.so.5
#6  0xb5ed8db4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/arm-linux-gnueabihf/libQt5Widgets.so.5
#7  0xb5ee12a8 in QApplication::notify(QObject*, QEvent*) () from /lib/arm-linux-gnueabihf/libQt5Widgets.so.5
#8  0x00567658 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

< describe your issue or feature request here ** >

![image](https://user-images.githubusercontent.com/5387413/160271973-92e8c5c0-3c3f-41fb-9c83-add0d5cc3019.png)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
```
patch@patchbox:~/hydrogen $ git rev-parse HEAD
ffe835d72a2f01c142aff81f43c7bce925570186
``` 

** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by cme** [comment]
Thank you for finding and reporting!

Looks like the SoundLibraryPanel registers itself as an event listener, but doesn't unregister itself when it's closed. Will fix shortly!
