### ISSUE TITLE
separate manual from app and make it 'upgradable'

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#155]
Would it be possible to separate the Hydrogen app and manual AND create a mechanism that informs the user that an updated manual is available (+offer the option to auto-download it)
The benefits:
- undocumented features can be added after Hydrogen has been released
- the same goes for missing translations
- an unfinished manual doesnt delay the release of the app
- error corrections can be done whenever needed

To do this we would need a central 'repository' + a mechanism that checks for a more recent manual version (check on startup or something like that)

Note that we DONT want a 0.9.6 version to download a manual for 0.9.7 since this would make no sense
Note that the manual that is available at the time of release would still be packed with the app so the users DO have a manual available when they first install Hydrogen

Maybe we can generate a pdf and let Hydrogen simply launch an external PDF reader when the user wants to open the manual ?

**Comment by theGreatWhiteShark** [comment]
I'll close this for now. Reason:

- We finally updated the manual and it is now aligned with the release (and I intend to keep it this way).
- The structure of the manual itself has changed a lot (more HTML5 and CSS3) and is now best viewed with an internet browser (so, the one linked by our webpage might already be the more obvious choice for the users)
