### ISSUE TITLE
Midi problems (parameters, outgoing midi messages and modified Drumkit reopen) on Windows

### ISSUE THREAD

**Issue by philbee4** [hydrogen-music/hydrogen#1557]
Hydrogen version *          : 1.1.1 c845af2f (dec 5 2021) and 1.2.0-debug (march 6 2022)
Operating system + version  : Windows 64 bits 8.1
Audio driver + version      : 
1) internal : Realtek Audio 6.0.8746.1
2) external audio + midi : Motu ultralite mk3 4.0.6.6814

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Midi issues :
Version 1.1.1 : no midi out messages from Hydrogen sequencer (or individual clic on an instrument inside a drumkit) (of course, Midi out device was set, instrument channel set to >0

Version 1.2.0 : with same midi configuration, midi out messages ok (see my comments on https://github.com/hydrogen-music/hydrogen/discussions/1234) BUT : 
**** I save a drumkit (from standard GMRockKit with a new name, and after check that things are normal with pattern scheduling and midi out messages as expected) after having set new channels and notes number, everything seems ok until I reload the same drumkit :  channel numbers "randomly" transformed (as if instrument parameters had become corrupted), and  Hydrogen crashes without any message, just after 1 or 2 instrument played.
Joined : Debug file and .conf
Thanks for any help.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

[hydrogen.log](https://github.com/hydrogen-music/hydrogen/files/8412375/hydrogen.log)
[hydrogen.zip](https://github.com/hydrogen-music/hydrogen/files/8412383/hydrogen.zip)

**Comment by theGreatWhiteShark** [comment]
> Version 1.2.0 : with same midi configuration, midi out messages ok (see my comments on https://github.com/hydrogen-music/hydrogen/discussions/1234) BUT :
**** I save a drumkit (from standard GMRockKit with a new name, and after check that things are normal with pattern scheduling and midi out messages as expected) after having set new channels and notes number, everything seems ok until I reload the same drumkit : channel numbers "randomly" transformed (as if instrument parameters had become corrupted), and Hydrogen crashes without any message, just after 1 or 2 instrument played.

Thanks for reporting! I'll look into it

**Comment by theGreatWhiteShark** [comment]
Hey @philbee4 ,

Could you check whether the problem you had with version 1.2.0 still occurs in this patch?

[Hydrogen-1.1.1-win64.exe](https://ci.appveyor.com/api/buildjobs/2qm41yfy3qmtpb0f/artifacts/Hydrogen-1.1.1-win64.exe) or [Hydrogen-1.1.1-win32.exe](https://ci.appveyor.com/api/buildjobs/t6sgtpjs1702xg67/artifacts/Hydrogen-1.1.1-win32.exe)

**Comment by philbee4** [comment]
Hey GreatWhiteShark,
Tried it and seems ** OK ** with this version : no channel jam nor crash, here joined an audio result (Addictive Drums 2 driven by Hydrogen midi output via LoopBe1) to thank you for your test and mid/mod-ification.
One thing remains as a minor point, which could be intentional from Hydrogen conceptors : I noticed that when an instrument is part of a drumkit but not present as an audio file (examples: the 2 last instruments of GMRockKit : "hat semi open" and "bell"), no midi output occurs. Not a real issue, of course, but could be differently thought if small re-writing price.
Big thanks, best regards.
Phil
[Hydrogen111'a38e1640'-tst.zip](https://github.com/hydrogen-music/hydrogen/files/8452374/Hydrogen111.a38e1640.-tst.zip)

**Comment by theGreatWhiteShark** [comment]
> One thing remains as a minor point, which could be intentional from Hydrogen conceptors : I noticed that when an instrument is part of a drumkit but not present as an audio file (examples: the 2 last instruments of GMRockKit : "hat semi open" and "bell"), no midi output occurs. Not a real issue, of course, but could be differently thought if small re-writing price.

That's indeed a known issue for quite some time (see #63). It's one of those things that definitely deserve to be fixed no one had the time to do so. Unfortunately, it won't make it into the next release either because we are almost done and laid the focus on other things. But hopefully it's covered in the next next one.
