### ISSUE TITLE
Mute groups bug?

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#1573]
Hydrogen version *          : 2867c0b17
-----------

Do your mute groups work in the current master branch?

**Comment by theGreatWhiteShark** [comment]
No, mine neither. I'll look into it.

**Comment by theGreatWhiteShark** [comment]
Could you check whether the code in #1574 fixes the problem?

**Comment by theGreatWhiteShark** [comment]
Closed with #1574. Please feel free to reopen in case something is not working properly

**Comment by oddtime** [comment]
thanks, sorry I hadn't found the time to check it yet.
