### ISSUE TITLE
Incorrect MIDI note mappings in GMRockKit

### ISSUE THREAD

**Issue by dfkettle** [hydrogen-music/hydrogen#1576]
Hydrogen version *          : 1.1.1 [Dec 5 2021]
Operating system + version  : Windows 7 SP1 (64-bit)
Audio driver + version      : PortAudio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Some of the instruments in the default drum kit, GMRockKit, are mapped to the wrong MIDI note number (according to the documentation, anyway):

Cowbell - mapped to 56 (should be 47)
Ride - mapped to 51 (should be 48)
Ride 2 - mapped to 59 (should be 50)
Splash - mapped to 57 (should be 51)
Hat Semi-open - mapped to 82 (should be 52)
Bell - mapped to 81 (should be 53)

See http://hydrogen-music.org/documentation/manual/manual_en_chunked/ch04s03.html

**Comment by theGreatWhiteShark** [comment]
Hmm. Yes. I also wondered about this mismatch.

There are two conflicting incentives in here. 1. New users most probably expect the mapping to be correct and 2. established users are used to the incorrect one and might be mislead by fixing them.

On the other hand, the GMRockKit is one of the two kits we directly ship with the software and we update it on a regular basis to match newest release anyway. Also, mappings in existing songs would not be affected unless the user decides to reload the drumkit.

 I think it would be ok, to update them but I have no strong opinion on it. @cme, @mauser what do you think?

**Comment by dfkettle** [comment]
If you decide against correcting it, maybe just update the documentation so as not to confuse new users.

**Comment by theGreatWhiteShark** [comment]
Ah, okay. Now I get it. The note mapping in GMRockKit does already comply with the MIDI standard. It's the table in the docs that needs an update.

**Comment by theGreatWhiteShark** [comment]
Fixed in #1585 (two instruments had indeed a MIDI note associated that did not comply with GM standard.) and updated online. 

Thanks for reporting!

**Comment by dfkettle** [comment]
> Fixed in #1585 (two instruments had indeed a MIDI note associated that did not comply with GM standard.) and updated online.
> 
> Thanks for reporting!

Just two?

**Comment by theGreatWhiteShark** [comment]
> Just two?

Yes. The others had actually been fixed at some point in the past. But the doc was not updated to represent those changes.
