### ISSUE TITLE
No prompt to Save Changes

### ISSUE THREAD

**Issue by NoAliby** [hydrogen-music/hydrogen#1580]
v1.1.1-b39fcf77

If changes have been made in a song and you open a Recent Song, it does not prompt you to save,

Seems to be quite specific to get this bug to occur:

- If you use "OPEN" it does prompt you

- Changes to a note in the pattern editor and quickly then "OPEN RECENT" song, it does not recognize a change and no prompt
- Changes to a note in the pattern editor, and short wait, and then "OPEN RECENT" song quickly, it DOES prompt

- Changes the order of patterns in the Song editor and then "OPEN RECENT" song, no prompt
- Changes one thing (add a square on a timeline) in the Song editor and then "OPEN RECENT" song, no prompt
- Changes two things (add two separate squares on a timeline) in the Song editor and then "OPEN RECENT" song, it DOES prompt

Hopefully that helps reproduce the issue

**Comment by theGreatWhiteShark** [comment]
Thanks for reporting! Should be fixed now.
