### ISSUE TITLE
translations for the upcoming 1.2.0

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#1586]
Hi @theGreatWhiteShark @cme @mauser .
Hope everything is going well for you and yours.

I've read that 1.2.0 is not far from now. I'd like to be pinged here before the release, so I can rework the French translation before the launch.

**Comment by theGreatWhiteShark** [comment]
Sure. We plan to release a 1.2.0-beta in a couple of weeks and have the usual string freeze and testing period before launching the actual 1.2.0 one.

**Comment by trebmuh** [comment]
Nice. Feel free to ping then.

**Comment by theGreatWhiteShark** [comment]
@trebmuh ping. Turned out to be a lot more than a couple of weeks. Anyway, we are in string freeze now :)

**Comment by trebmuh** [comment]
@theGreatWhiteShark thanks for the ping
