### ISSUE TITLE
First beat skipped sometimes when jack transport is started elsewhere

### ISSUE THREAD

**Issue by xbug42** [hydrogen-music/hydrogen#1597]
Hydrogen version *          : 1.1.1
Operating system + version  : Kubuntu 22.04 with realtime kernel
Audio driver + version      : Jack 1.9.20

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When starting Jack transport from another software (tried with QjackCtl and Ardour), sometimes the first beat is not played.
- 1. In Hydrogen : "Jack Transport" is on and "Jack master" is off.
- 2. Set Jack transport to 00:00 (stop or rewind) from another application.
- 3. Start Jack transport (play) from another application
- 4. Sometimes the first beat is not played.

If the first beat was not played, the issue can always be reproduced by repeating steps 2, 3 and 4
If the first beat was played, the issue will never occur by repeating steps 2, 3 and 4

So far, I am unable to find a way to always reproduce the issue...

**Comment by theGreatWhiteShark** [comment]
There have been a number of changes to audio engine recently. Could you check whether this issue still occurs with the code on master?

**Comment by xbug42** [comment]
I just checked and unfortunately the issue still occurs on master...

**Comment by xbug42** [comment]
I think I noticed something useful...

When the transport is stopped : 
if the playhead is changed in Ardour, then the playhead position is updated in QjackCtl but not in Hydrogen
if the playhead is changed in QjackCtl, then the playhead position is updated in Ardour but not in Hydrogen

Maybe the issue is caused because when the JACK transport is started (PLAY) from somewhere else, then Hydrogen has to first set the playhead position. My guess is that maybe after the playhead has been updated, the transport is already AFTER the first beat so this is why it is skipped... 

Steps to always reproduce the issue :
- 1. In Hydrogen : "Jack Transport" is on and "Jack master" is off.
- 2. Start Jack transport (PLAY) from any application.
- 3. Stop Jack transport (STOP)
- 5. At this point, all the playheads (Hydrogen and all other Jack applications) are synchronized
- 6. Set Jack transport to 00:00 (STOP or REWIND) from another application (eg : Ardour).
- 7. At this point, playhead in Hydrogen is not synced (not at 00:00)
- 4. Start Jack transport (play) from another application
- 5. Hydrogen does not play the first beat 

If the Jack transport is set to 00:00 by Hydrogen in point 6, then all the playheads are synchronized and the issue does not occur !

So maybe if the playhead in Hydrogen could be synchronized even when the transport is stopped, it could solve this issue... What do you think ?

**Comment by theGreatWhiteShark** [comment]
> When the transport is stopped :
if the playhead is changed in Ardour, then the playhead position is updated in QjackCtl but not in Hydrogen
if the playhead is changed in QjackCtl, then the playhead position is updated in Ardour but not in Hydrogen

Yes. In it's current implementation Hydrogen only picks up relocations of the playhead if playback is rolling. I'll check whether there is an easy workaround to support an instantaneous update as well.

> Maybe the issue is caused because when the JACK transport is started (PLAY) from somewhere else, then Hydrogen has to first set the playhead position. My guess is that maybe after the playhead has been updated, the transport is already AFTER the first beat so this is why it is skipped...

In version 1.1.1 and below there was indeed a little bug that could make Hydrogen skip the first second after updating the playhead but still keep the overall transport in sync. However, this particular one is fixed in the code on master.

> So maybe if the playhead in Hydrogen could be synchronized even when the transport is stopped, it could solve this issue... What do you think ?

I don't think this is the cause of the problem. But it's a nice-to-have and I will take a look.

Unfortunately, I can not reproduce the skipping. Does it happen with all songs/drumkits? If not, could you share a faulty one? Could you also post your JACK configuration and version?

**Comment by theGreatWhiteShark** [comment]
> >    So maybe if the playhead in Hydrogen could be synchronized even when the transport is stopped, it could solve this issue... What do you think ?

> I don't think this is the cause of the problem. But it's a nice-to-have and I will take a look.

Could you test the code in #1603? It should keep the playhead in sync with all other JACK clients even in case transport is stopped.

**Comment by theGreatWhiteShark** [comment]
> So far, I am unable to find a way to always reproduce the issue...

One element I found to be quite erratic when working on the JACK driver was the whole Timebase master (TBM) subject (one JACK client registers as Timebase master on the JACK server and broadcasts additional tempo, measure, and position info to all other clients). The TBM implementation of a whole load of other applications was off (including the Ardour version I checked) and one never knew whether Hydrogen reacts on the plain transport position broadcasted via JACK or on the TBM information of another app. (But don't get me wrong, I don't want to bad-mouth other software. As you see, I didn't nailed it either :sweat_smile:  )

That might be the ingredient which makes it hard to reproduce. If so, the order you start up the JACK clients is crucial and toggling the J.Master button should ?fix? the behavior.

I'll include a clear visual feedback that signals to the user when Hydrogen is listening for TBM information of another app. Currently (master) this is only shown in a couple of tooltips).

**Comment by xbug42** [comment]
> Could you test the code in #1603? It should keep the playhead in sync with all other JACK clients even in case transport is stopped.

It looks fine : the playhead is now synchronized and I am unable to reproduce the issue anymore ! Thx :) 
Just before trying #1603, I was able to easily reproduce the issue with master, but only in "song" mode (not "pattern").

I will still answer your questions because only time will tell if this is really fixed...

> Does it happen with all songs/drumkits? 

Yes, I tried another very simple pattern (cowbell on every beat) and was able to reproduce the issue on master.

> Could you also post your JACK configuration and version?

I'm using Jack 1.9.20 (shipped by Kubuntu 22.04) and the low-latency Ubuntu kernel. 

Here is the content of my .jackdrc : 
`/usr/bin/jackd -dalsa -dhw:USB -r48000 -p128 -n3`

**Comment by xbug42** [comment]
> Via #1607 the "J.MASTER" button is now changing its color to red in case an external JACK clients is registered as Timebase master and Hydrogen tries to act on the incoming information on `master`. This might help you figuring out what's going on.

It works great thx ! But in this issue, "J.MASTER" was off... 

BTW, still unable to reproduce the issue with e68f45f1bc956fa2bfb8b8a0a67701e00d607b0c :)

I think it's best to close the bug and to reopen it it the issue still occurs...
