### ISSUE TITLE
First beat skipped second time the loop is played

### ISSUE THREAD

**Issue by xbug42** [hydrogen-music/hydrogen#1604]
Hydrogen version *          : 231cf22f2acbe77ba7ebe176b5f555a2bdb67b24
Operating system + version  : Kubuntu 22.04 with low-latency kernel
Audio driver + version      : Jack 1.9.20

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I made a very simple pattern with cowbell on every beat.
"Song" mode and "Loop" are enabled.
In the timeline, the pattern is defined only on the first bar.

When looping the song :
- Everything is played the first time the song is played.
- The 2nd time the song is played, the first beat is skipped.
- The 3rd time the song is played and after that, everything is played. 
 
This issue can always be reproduced.
This issue occurs whatever Jack transport is enabled or not.

[bug-loop.h2song.zip](https://github.com/hydrogen-music/hydrogen/files/8926168/bug-loop.h2song.zip)

**Comment by theGreatWhiteShark** [comment]
Thanks for reporting!
