### ISSUE TITLE
Playback jumps skipping the end of patterns

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#1664]
Hydrogen version *          : 64355a8186a622f31e3ee131107a2f2457966163
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

In some cases it happens that the playback (in song mode) jumps and does not play the end of the pattern.
I attach a short video showing how to reproduce it:

[video.zip](https://github.com/hydrogen-music/hydrogen/files/9772122/video.zip)

**Comment by theGreatWhiteShark** [comment]
Hey @oddtime ,

could you check whether #1666 is fixing this issue?

**Comment by oddtime** [comment]
> could you check whether https://github.com/hydrogen-music/hydrogen/pull/1666 is fixing this issue?

Here I am experiencing the same bug with loop mode enabled. When loop is disabled the first song column is played and then the playback stops.

**Comment by theGreatWhiteShark** [comment]
Could you try the code in #1666 again? This was a sneaky one which only occurred when altering pattern size in pattern mode. But it should be fixed now.

**Comment by oddtime** [comment]
Ok checked! Thank you

**Comment by oddtime** [comment]
sorry I am reopening the issue until #1666 gets merged
