### ISSUE TITLE
[BUG] [PATCH] Unbalanced pthread lock and unlock sequence makes Logger use all CPU!

### ISSUE THREAD

**Issue by hselasky** [hydrogen-music/hydrogen#1665]
Hydrogen version *          : 1.1.1
Operating system + version  : FreeBSD 13
Audio driver + version      : OSS and JACK

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Can you fix this bug. It affects FreeBSD apparently and not Linux :-(

```
--- src/core/Logger.cpp.orig	2022-10-16 14:13:55 UTC
+++ src/core/Logger.cpp
@@ -65,6 +65,7 @@ void* loggerThread_func( void* param ) {
 	Logger::queue_t::iterator it, last;
 
 	while ( logger->__running ) {
+		pthread_mutex_lock( &logger->__mutex );
 		pthread_cond_wait( &logger->__messages_available, &logger->__mutex );
 		pthread_mutex_unlock( &logger->__mutex );
 		if( !queue->empty() ) {

```

Thank you!

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by theGreatWhiteShark** [comment]
Hey @hselasky ,

Thanks for the patch! It was [already](https://github.com/hydrogen-music/hydrogen/commit/b4418a13020dc5cf66f6a794ea4ba7ddc017d596) introduced and will be part of the next release.
