### ISSUE TITLE
wrong translation tips?

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#1694]
https://github.com/hydrogen-music/hydrogen/blob/769ee9d3844dbd72448b18c36523741a6ee30b8c/src/gui/src/CommonStrings.cpp#L52

shouldn't that be "eight" and not "three" ?

https://github.com/hydrogen-music/hydrogen/blob/769ee9d3844dbd72448b18c36523741a6ee30b8c/src/gui/src/CommonStrings.cpp#L55

shouldn't that be "two" and not "eight" ?

**Comment by theGreatWhiteShark** [comment]
Yes, looks like a classic copy-paste error. Were those translation tips useful?

**Comment by trebmuh** [comment]
> Were those translation tips useful?

Definitely, I would encourage devs to add this type of comments more often.

**Comment by trebmuh** [comment]
@theGreatWhiteShark did you add the "invalid" tag on purpose?

**Comment by theGreatWhiteShark** [comment]
> Definitely, I would encourage devs to add this type of comments more often.

Awesome. I introduced a dedicated class bundling translatable strings. Hopefully, this will ease translating in the future.

> did you add the "invalid" tag on purpose?

Yeah. As those string are invalid :)

**Comment by trebmuh** [comment]
:+1:

**Comment by trebmuh** [comment]
:+1:
