### ISSUE TITLE
Unable to delete a pattern without a restart

### ISSUE THREAD

**Issue by Djard** [hydrogen-music/hydrogen#1747]
Hydrogen version *          :1.2.0.beta1 (Dec 15, 2022]
Operating system + version  :  Win 10
Audio driver + version      :  nVidia

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When I attempt to delete a pattern, I sometimes I get the following notification: "Could not save pattern to temporary memory." To delete the pattern in the top left panel, I must exit and relaunch Hydrogen.

**Comment by theGreatWhiteShark** [comment]
Hey @Djard ,

Any chance you are running out of free disk space? When either deleting a pattern or all pattern sequences/clicked boxes in the song editor, Hydrogen writes their internal representation to a temporary file. This is done to not consume too much memory of your system while allowing to undo and redo all of those actions. When quitting Hydrogen, all temporary files will be deleted (and freeing a tiny bit of disk space)

**Comment by cme** [comment]
It's also possible there might be some remaining issues with naming of the pattern files. Does your pattern have any interesting characters in its name, @Djard?

**Comment by Djard** [comment]
I see in Windows' Task Manager that I am using only a small fraction of resources, and my SSD have 400GB free space. But who knows if Microsoft software reports accurately, since closing and reopening the project lets me delete the obstinate pattern. I do name my patterns in Properties but without any special characters. I guess I will have to live with the workaround. Hopefully the next version will not be so limiting. I still think the app is excellent.

**Comment by trebmuh** [comment]
@Djard : can you try with the [1.2.0 version from a few days ago](https://github.com/hydrogen-music/hydrogen/releases/tag/1.2.0)?

**Comment by Djard** [comment]
I am not sure in which version I experienced the problem. But I am unable to reproduce the problem, using the latest beta version: I can delete patterns just fine.

**Comment by Djard** [comment]
Thanks!
