### ISSUE TITLE
Version 1.2.0 Beta has a bug

### ISSUE THREAD

**Issue by Djard** [hydrogen-music/hydrogen#1754]
Hydrogen version *          :1.2.0 beta1
Operating system + version  : Win 10
Audio driver + version      : Realtek

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
On my system, when exporting a song, the playback volume of the snare drum or side stick on the third beat is occasionally weak. The issue appears to occur randomly: in a project that is 108 bars long, the problem surfaced in bar #20, 23, 27, 31, 83, 87 and 91.

The problem is corrected when reverting to a previous version of Hydrogen.

**Comment by trebmuh** [comment]
Hi @Djard : the definitive [1.2.0 version](https://github.com/hydrogen-music/hydrogen/releases/tag/1.2.0) has been released a few days ago. Can you try with it and tell us if the issue is still reproductible?

**Comment by theGreatWhiteShark** [comment]
Hey @Djard,

> On my system, when exporting a song, the playback volume of the snare drum or side stick on the third beat is occasionally weak. The issue appears to occur randomly: in a project that is 108 bars long, the problem surfaced in bar https://github.com/hydrogen-music/hydrogen/issues/20, 23, 27, 31, 83, 87 and 91.

Ah, nice catch! I changed/fixed quite a lot in Hydrogen's audio engine between 1.1.2 and 1.2.0. Could you provide the .h2song, your `hydrogen.conf` file, and the log generated while this bug appears? Hopefully I will be able to reproduce it.

**Comment by Djard** [comment]
I did not experience any loss in volume of an instrument using the new, stable version. All is well. Thanks.
 
    On Thursday, April 27, 2023 at 10:18:54 AM EDT, theGreatWhiteShark ***@***.***> wrote:  
 
 


Hey @Djard,


On my system, when exporting a song, the playback volume of the snare drum or side stick on the third beat is occasionally weak. The issue appears to occur randomly: in a project that is 108 bars long, the problem surfaced in bar #20, 23, 27, 31, 83, 87 and 91.


Ah, nice catch! I changed/fixed quite a lot in Hydrogen's audio engine between 1.1.2 and 1.2.0. Could you provide the .h2song, your hydrogen.conf file, and the log generated while this bug appears? Hopefully I will be able to reproduce it.

**Comment by theGreatWhiteShark** [comment]
Great. But please reopen this issue in case you think the error did occur again
