### ISSUE TITLE
Importing certain drumkits will only load first layer for instrument

### ISSUE THREAD

**Issue by SMLiberator** [hydrogen-music/hydrogen#1759]
Hydrogen version *          : 1.20, latest release, built from source
Operating system + version  :  Ubuntu 18.04 LTS
Audio driver + version      : Jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Exactly as described on title. I believe it has something to do with the Hydrogen version in which said drumkits were made, and it can be reproduced with (at least) most multilayered drumkits available at Online Import. I tested it with BJA_Pacific, which has a noticeably different drumkit.xml format than the ones I made and that work correctly with the current version.

Upon importing said drumkit, a new drumkit.xml is created automatically (and the original backed up). However, the newly made xml only has one layer per instrument.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by theGreatWhiteShark** [comment]
Hey @SMLiberator ,

Thanks for reporting. Could you check whether #1762 fixes this issue at your end?

**Comment by SMLiberator** [comment]
Fixed
