### ISSUE TITLE
Hydrogen as JACK transport master sends garbage data

### ISSUE THREAD

**Issue by mrzapp** [hydrogen-music/hydrogen#1760]
Hydrogen version *          : 1.2.0-c92f204
Operating system + version  : Arch Linux, kernel 6.2.13-zen
Audio driver + version      : JACK through PipeWire 0.3.70

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When using Hydrogen as a JACK transport master, the position data it sends is unusable.

These are the issues:  

- [ ] The `bar` is just a constant 1, switching to 0 for a single tick. Should be >0: the first bar is bar '1'. 
- [ ] The `beat` has a similar issue, it's just -2 most of the time, occasionally flipping to 1. Should be >0 and <=beats_per_bar: the first beat is beat '1'. 
- [ ] The `tick` is always negative or 0. Should be >= 0 and < ticks_per_beat: the first tick is tick '0'. 
- [ ] The `bar_start_tick` is sometimes < 0. Should represent the number of ticks that have elapsed between frame 0 and the first beat of the current measure. 

The `usecs`, `framerate`, `frame`, `beats_per_bar`, `beat_type`, `beats_per_minute` and `ticks_per_beat` all seem fine to me.

The documentation for the JACK position struct is [here](https://jackaudio.org/api/structjack__position__t.html)

This is an example printout from a simple Python JACK client:

```
{'usecs': 49088424042, 'frame_rate': 48000, 'frame': 16126976, 'bar': 1, 'beat': -2, 'tick': -30, 'bar_start_tick': 0.0, 'beats_per_bar': 4.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 120.0}
{'usecs': 49088445377, 'frame_rate': 48000, 'frame': 16128000, 'bar': 0, 'beat': 1, 'tick': 0, 'bar_start_tick': -7680.0, 'beats_per_bar': 4.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 120.0}
{'usecs': 49088466712, 'frame_rate': 48000, 'frame': 16129024, 'bar': 1, 'beat': -2, 'tick': -1900, 'bar_start_tick': 0.0, 'beats_per_bar': 4.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 120.0}
{'usecs': 49088488047, 'frame_rate': 48000, 'frame': 16130048, 'bar': 1, 'beat': -2, 'tick': -1879, 'bar_start_tick': 0.0, 'beats_per_bar': 4.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 120.0}
{'usecs': 49088509381, 'frame_rate': 48000, 'frame': 16131072, 'bar': 1, 'beat': -2, 'tick': -1860, 'bar_start_tick': 0.0, 'beats_per_bar': 4.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 120.0}
{'usecs': 49088530717, 'frame_rate': 48000, 'frame': 16132096, 'bar': 1, 'beat': -2, 'tick': -1840, 'bar_start_tick': 0.0, 'beats_per_bar': 4.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 120.0}
{'usecs': 49088552051, 'frame_rate': 48000, 'frame': 16133120, 'bar': 1, 'beat': -2, 'tick': -1819, 'bar_start_tick': 0.0, 'beats_per_bar': 4.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 120.0}
{'usecs': 49088573386, 'frame_rate': 48000, 'frame': 16134144, 'bar': 1, 'beat': -2, 'tick': -1800, 'bar_start_tick': 0.0, 'beats_per_bar': 4.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 120.0}

```

This is the same printout with Qtractor as the JACK transport master:

```
{'usecs': 55942717476, 'frame_rate': 48000, 'frame': 19456, 'bar': 1, 'beat': 1, 'tick': 1814, 'bar_start_tick': 0.0, 'beats_per_bar': 8.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 140.0}
{'usecs': 55942738810, 'frame_rate': 48000, 'frame': 20480, 'bar': 1, 'beat': 1, 'tick': 1910, 'bar_start_tick': 0.0, 'beats_per_bar': 8.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 140.0}
{'usecs': 55942760143, 'frame_rate': 48000, 'frame': 21504, 'bar': 1, 'beat': 2, 'tick': 85, 'bar_start_tick': 0.0, 'beats_per_bar': 8.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 140.0}
{'usecs': 55942781475, 'frame_rate': 48000, 'frame': 22528, 'bar': 1, 'beat': 2, 'tick': 181, 'bar_start_tick': 0.0, 'beats_per_bar': 8.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 140.0}
{'usecs': 55942802807, 'frame_rate': 48000, 'frame': 23552, 'bar': 1, 'beat': 2, 'tick': 278, 'bar_start_tick': 0.0, 'beats_per_bar': 8.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 140.0}
{'usecs': 55942824141, 'frame_rate': 48000, 'frame': 24576, 'bar': 1, 'beat': 2, 'tick': 372, 'bar_start_tick': 0.0, 'beats_per_bar': 8.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 140.0}
{'usecs': 55942845475, 'frame_rate': 48000, 'frame': 25600, 'bar': 1, 'beat': 2, 'tick': 467, 'bar_start_tick': 0.0, 'beats_per_bar': 8.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 140.0}
{'usecs': 55942866810, 'frame_rate': 48000, 'frame': 26624, 'bar': 1, 'beat': 2, 'tick': 563, 'bar_start_tick': 0.0, 'beats_per_bar': 8.0, 'beat_type': 4.0, 'ticks_per_beat': 1920.0, 'beats_per_minute': 140.0}
```

**Comment by theGreatWhiteShark** [comment]
Hey @mrzapp,

That's strange. I can not reproduce it using JACK itself. Probably that's another PipeWire bug. Do you use the latest version of the latter?

Is JACK Timebase master working in other applications using your setup?

**Comment by mrzapp** [comment]
Hey @theGreatWhiteShark,

I'm using the latest PipeWire, yes. I included an example of Qtractor, which is running as expected. I am also able to run my own Python app as timebase master with no issues, relevant code [here](https://gitlab.com/mrzapp/lupa/-/blob/main/src/engine.py#L107-L114)

Maybe comparing the timebase master callbacks in [Hydrogen's code](https://github.com/hydrogen-music/hydrogen/blob/cf0d2da2133e793df1fa5c2c921b38223ccdc0de/src/core/IO/JackAudioDriver.cpp#L1077-L1152) and [Qtractor's code](https://github.com/rncbc/qtractor/blob/e82258c96b84ea3c0679de847ec7cc8a7c6ce5b7/src/qtractorAudioEngine.cpp#L1467-L1512) could reveal something useful. Nothing jumps out at me straight away though, since I'm not too familiar with the structure.

**Comment by theGreatWhiteShark** [comment]
> I included an example of Qtractor, which is running as expected. I am also able to run my own Python app as timebase master with no issues, relevant code [here](https://gitlab.com/mrzapp/lupa/-/blob/main/src/engine.py#L107-L114)

AFAICS the problem is not within the BBT information calculation. Under normal circumstances negative beats and ticks should never occur. And when looking at the code I also don't see how it could be possible. None of the involved variables for e.g. `beat` can be smaller than zero. No idea. My guess is that all data is pass properly from Hydrogen to PipeWire but the latter does not handle it properly. (Maybe because I do not touch `frame_time` and `next_time` fields of the position struct? They indeed contain garbage data. But they aren't set in QTractors code either).

Does this problem also occur when using plain JACK at your end? And is transport in general working within Hydrogen?

**Comment by mrzapp** [comment]
It does seem to work fine on plain JACK, and transport is working without issue.

**Comment by mrzapp** [comment]
@theGreatWhiteShark I shot a quick question about this at rncbc, the developer of Qtractor, and he did say it's likely a `pipewire-jack` issue, as he has recently been struggling with it too, hence [this issue](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3189)

We should probably open an issue on their GitLab about this. Do you have anything to add, or should I just send them what we have so far?

**Comment by cme** [comment]
We previously found this very similar-sounding one:

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1748

The fix does seem to be in 0.3.70, so probably not that exact one.

**Comment by theGreatWhiteShark** [comment]
> We should probably open an issue on their GitLab about this.

:+1: 

> Do you have anything to add, or should I just send them what we have so far?

For reference you can attach a sample of the data sent by Hydrogen. I still have some in a terminal value

> [Hydrogen] [JACK transport] frame: 4607488, frame_rate: 48000, valid: 0x10, bar: 48, beat: 1, tick: 190, bar_start_tick: 9024, beats_per_bar: 4, beat_type: 4, ticks_per_beat: 192, beats_per_minute: 120, frame_time: 1.02509e-312, next_time: 4.63642e-310
[Hydrogen] [JACK transport] frame: 4607744, frame_rate: 48000, valid: 0x10, bar: 48, beat: 1, tick: 191, bar_start_tick: 9024, beats_per_bar: 4, beat_type: 4, ticks_per_beat: 192, beats_per_minute: 120, frame_time: 1.02509e-312, next_time: 4.63642e-310
[Hydrogen] [JACK transport] frame: 4608000, frame_rate: 48000, valid: 0x10, bar: 49, beat: 1, tick: 0, bar_start_tick: 9216, beats_per_bar: 4, beat_type: 4, ticks_per_beat: 192, beats_per_minute: 120, frame_time: 1.02509e-312, next_time: 4.63642e-310
[Hydrogen] [JACK transport] frame: 4608256, frame_rate: 48000, valid: 0x10, bar: 49, beat: 1, tick: 0, bar_start_tick: 9216, beats_per_bar: 4, beat_type: 4, ticks_per_beat: 192, beats_per_minute: 120, frame_time: 1.02509e-312, next_time: 4.63642e-310

**Comment by mrzapp** [comment]
Alright, I've opened [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3202) issue. I'll close this one for now.
