### ISSUE TITLE
Hydrogen as JACK transport slave has no audio during playback

### ISSUE THREAD

**Issue by mrzapp** [hydrogen-music/hydrogen#1761]
Hydrogen version * : 1.2.0-c92f204
Operating system + version : Arch Linux, kernel 6.2.13-zen
Audio driver + version : JACK through PipeWire 0.3.70

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

With the JACK  audio system selected, playback works fine until I click "J.Trans", then the audio disappears. I can still hear the sounds when I click and place them, though. If I click "J.Master", the audio is back, so it only appears to happen when Hydrogen is in "slave" mode.

**Comment by theGreatWhiteShark** [comment]
Same here. Can't reproduce this with JACK itself. But it sounds especially weird.

Introducing myself to PipeWire is somewhere on my TODO list but it probably will take a couple of weeks till I have sufficient time at hand.

Does this issue happens to when you use a plain JACK server?

**Comment by mrzapp** [comment]
@theGreatWhiteShark you're right, I can't reproduce it with plain JACK. I'm not sure you need to dive too deep into PipeWire itself though, the whole purpose of it is that we should be able to just keep using JACK without worrying our pretty little heads about it.

I suspect getting to the bottom of #1760 will be more approachable, as there are some concrete numbers to work with, and that it might reveal something useful, but that's just a hunch.

**Comment by theGreatWhiteShark** [comment]
> I'm not sure you need to dive too deep into PipeWire itself though, the whole purpose of it is that we should be able to just keep using JACK without worrying our pretty little heads about it.

Sure. But its a fairly young and promising project. Running it locally and reporting bugs should not be too time consuming.

**Comment by mrzapp** [comment]
To be continued [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3202)
