### ISSUE TITLE
hydrogen crashes when using extreme timestretch settings

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#177]
when using a sample of aprox 4 sec setting the 'sample length to beat' to 1/64 (in the sample editor) hydrogen crashes when i hit apply

in a terminal i see this : 

(I) SampleEditor::SampleEditor INIT
**\* WARNING: increment -22 <= 0, rounding to zero
**\* WARNING: increment -23 <= 0, rounding to zero
**\* WARNING: increment -24 <= 0, rounding to zero
**\* WARNING: increment -25 <= 0, rounding to zero
**\* WARNING: increment -26 <= 0, rounding to zero
**\* WARNING: increment -28 <= 0, rounding to zero
**\* WARNING: increment -30 <= 0, rounding to zero
**\* WARNING: increment -32 <= 0, rounding to zero
**\* WARNING: increment -34 <= 0, rounding to zero
**\* WARNING: increment -37 <= 0, rounding to zero
**\* WARNING: increment -40 <= 0, rounding to zero
**\* WARNING: increment -43 <= 0, rounding to zero
**\* WARNING: increment -48 <= 0, rounding to zero
**\* WARNING: increment -53 <= 0, rounding to zero
**\* WARNING: increment -59 <= 0, rounding to zero
**\* WARNING: increment -68 <= 0, rounding to zero
**\* WARNING: increment -79 <= 0, rounding to zero
**\* WARNING: increment -95 <= 0, rounding to zero
**\* WARNING: increment -119 <= 0, rounding to zero
**\* WARNING: increment -158 <= 0, rounding to zero
**\* WARNING: increment -238 <= 0, rounding to zero
**\* WARNING: increment -475 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 37
**\* WARNING: distributeRegion returned wrong duration 512, expected 37
**\* WARNING: increment -84 <= 0, rounding to zero
**\* WARNING: increment -100 <= 0, rounding to zero
**\* WARNING: increment -125 <= 0, rounding to zero
**\* WARNING: increment -167 <= 0, rounding to zero
**\* WARNING: increment -250 <= 0, rounding to zero
**\* WARNING: increment -501 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 11
**\* WARNING: distributeRegion returned wrong duration 512, expected 11
**\* WARNING: increment -101 <= 0, rounding to zero
**\* WARNING: increment -126 <= 0, rounding to zero
**\* WARNING: increment -168 <= 0, rounding to zero
**\* WARNING: increment -252 <= 0, rounding to zero
**\* WARNING: increment -503 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 9
**\* WARNING: distributeRegion returned wrong duration 512, expected 9
**\* WARNING: increment -84 <= 0, rounding to zero
**\* WARNING: increment -100 <= 0, rounding to zero
**\* WARNING: increment -125 <= 0, rounding to zero
**\* WARNING: increment -167 <= 0, rounding to zero
**\* WARNING: increment -250 <= 0, rounding to zero
**\* WARNING: increment -501 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 11
**\* WARNING: distributeRegion returned wrong duration 512, expected 11
**\* WARNING: increment -38 <= 0, rounding to zero
**\* WARNING: increment -41 <= 0, rounding to zero
**\* WARNING: increment -44 <= 0, rounding to zero
**\* WARNING: increment -49 <= 0, rounding to zero
**\* WARNING: increment -54 <= 0, rounding to zero
**\* WARNING: increment -61 <= 0, rounding to zero
**\* WARNING: increment -70 <= 0, rounding to zero
**\* WARNING: increment -82 <= 0, rounding to zero
**\* WARNING: increment -98 <= 0, rounding to zero
**\* WARNING: increment -122 <= 0, rounding to zero
**\* WARNING: increment -163 <= 0, rounding to zero
**\* WARNING: increment -244 <= 0, rounding to zero
**\* WARNING: increment -489 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 23
**\* WARNING: distributeRegion returned wrong duration 512, expected 23
**\* WARNING: increment -50 <= 0, rounding to zero
**\* WARNING: increment -55 <= 0, rounding to zero
**\* WARNING: increment -62 <= 0, rounding to zero
**\* WARNING: increment -71 <= 0, rounding to zero
**\* WARNING: increment -82 <= 0, rounding to zero
**\* WARNING: increment -99 <= 0, rounding to zero
**\* WARNING: increment -124 <= 0, rounding to zero
**\* WARNING: increment -165 <= 0, rounding to zero
**\* WARNING: increment -248 <= 0, rounding to zero
**\* WARNING: increment -495 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 17
**\* WARNING: distributeRegion returned wrong duration 512, expected 17
**\* WARNING: increment -71 <= 0, rounding to zero
**\* WARNING: increment -83 <= 0, rounding to zero
**\* WARNING: increment -100 <= 0, rounding to zero
**\* WARNING: increment -125 <= 0, rounding to zero
**\* WARNING: increment -166 <= 0, rounding to zero
**\* WARNING: increment -250 <= 0, rounding to zero
**\* WARNING: increment -499 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 13
**\* WARNING: distributeRegion returned wrong duration 512, expected 13
**\* WARNING: increment -41 <= 0, rounding to zero
**\* WARNING: increment -45 <= 0, rounding to zero
**\* WARNING: increment -49 <= 0, rounding to zero
**\* WARNING: increment -55 <= 0, rounding to zero
**\* WARNING: increment -62 <= 0, rounding to zero
**\* WARNING: increment -70 <= 0, rounding to zero
**\* WARNING: increment -82 <= 0, rounding to zero
**\* WARNING: increment -98 <= 0, rounding to zero
**\* WARNING: increment -123 <= 0, rounding to zero
**\* WARNING: increment -164 <= 0, rounding to zero
**\* WARNING: increment -246 <= 0, rounding to zero
**\* WARNING: increment -492 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 20
**\* WARNING: distributeRegion returned wrong duration 512, expected 20
**\* WARNING: increment -49 <= 0, rounding to zero
**\* WARNING: increment -55 <= 0, rounding to zero
**\* WARNING: increment -62 <= 0, rounding to zero
**\* WARNING: increment -71 <= 0, rounding to zero
**\* WARNING: increment -82 <= 0, rounding to zero
**\* WARNING: increment -99 <= 0, rounding to zero
**\* WARNING: increment -124 <= 0, rounding to zero
**\* WARNING: increment -165 <= 0, rounding to zero
**\* WARNING: increment -247 <= 0, rounding to zero
**\* WARNING: increment -494 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 18
**\* WARNING: distributeRegion returned wrong duration 512, expected 18
**\* WARNING: increment -55 <= 0, rounding to zero
**\* WARNING: increment -62 <= 0, rounding to zero
**\* WARNING: increment -71 <= 0, rounding to zero
**\* WARNING: increment -83 <= 0, rounding to zero
**\* WARNING: increment -99 <= 0, rounding to zero
**\* WARNING: increment -124 <= 0, rounding to zero
**\* WARNING: increment -165 <= 0, rounding to zero
**\* WARNING: increment -248 <= 0, rounding to zero
**\* WARNING: increment -496 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 16
**\* WARNING: distributeRegion returned wrong duration 512, expected 16
**\* WARNING: increment -45 <= 0, rounding to zero
**\* WARNING: increment -49 <= 0, rounding to zero
**\* WARNING: increment -55 <= 0, rounding to zero
**\* WARNING: increment -62 <= 0, rounding to zero
**\* WARNING: increment -70 <= 0, rounding to zero
**\* WARNING: increment -82 <= 0, rounding to zero
**\* WARNING: increment -99 <= 0, rounding to zero
**\* WARNING: increment -123 <= 0, rounding to zero
**\* WARNING: increment -164 <= 0, rounding to zero
**\* WARNING: increment -246 <= 0, rounding to zero
**\* WARNING: increment -493 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 19
**\* WARNING: distributeRegion returned wrong duration 512, expected 19
**\* WARNING: increment -50 <= 0, rounding to zero
**\* WARNING: increment -55 <= 0, rounding to zero
**\* WARNING: increment -62 <= 0, rounding to zero
**\* WARNING: increment -71 <= 0, rounding to zero
**\* WARNING: increment -82 <= 0, rounding to zero
**\* WARNING: increment -99 <= 0, rounding to zero
**\* WARNING: increment -124 <= 0, rounding to zero
**\* WARNING: increment -165 <= 0, rounding to zero
**\* WARNING: increment -248 <= 0, rounding to zero
**\* WARNING: increment -495 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 17
**\* WARNING: distributeRegion returned wrong duration 512, expected 17
**\* WARNING: increment -62 <= 0, rounding to zero
**\* WARNING: increment -71 <= 0, rounding to zero
**\* WARNING: increment -83 <= 0, rounding to zero
**\* WARNING: increment -99 <= 0, rounding to zero
**\* WARNING: increment -124 <= 0, rounding to zero
**\* WARNING: increment -166 <= 0, rounding to zero
**\* WARNING: increment -248 <= 0, rounding to zero
**\* WARNING: increment -497 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 15
**\* WARNING: distributeRegion returned wrong duration 512, expected 15
**\* WARNING: increment -41 <= 0, rounding to zero
**\* WARNING: increment -45 <= 0, rounding to zero
**\* WARNING: increment -49 <= 0, rounding to zero
**\* WARNING: increment -55 <= 0, rounding to zero
**\* WARNING: increment -62 <= 0, rounding to zero
**\* WARNING: increment -70 <= 0, rounding to zero
**\* WARNING: increment -82 <= 0, rounding to zero
**\* WARNING: increment -98 <= 0, rounding to zero
**\* WARNING: increment -123 <= 0, rounding to zero
**\* WARNING: increment -164 <= 0, rounding to zero
**\* WARNING: increment -246 <= 0, rounding to zero
**\* WARNING: increment -492 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 20
**\* WARNING: distributeRegion returned wrong duration 512, expected 20
**\* WARNING: increment -49 <= 0, rounding to zero
**\* WARNING: increment -55 <= 0, rounding to zero
**\* WARNING: increment -62 <= 0, rounding to zero
**\* WARNING: increment -71 <= 0, rounding to zero
**\* WARNING: increment -82 <= 0, rounding to zero
**\* WARNING: increment -99 <= 0, rounding to zero
**\* WARNING: increment -124 <= 0, rounding to zero
**\* WARNING: increment -165 <= 0, rounding to zero
**\* WARNING: increment -247 <= 0, rounding to zero
**\* WARNING: increment -494 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 18
**\* WARNING: distributeRegion returned wrong duration 512, expected 18
**\* WARNING: increment -71 <= 0, rounding to zero
**\* WARNING: increment -83 <= 0, rounding to zero
**\* WARNING: increment -100 <= 0, rounding to zero
**\* WARNING: increment -125 <= 0, rounding to zero
**\* WARNING: increment -166 <= 0, rounding to zero
**\* WARNING: increment -250 <= 0, rounding to zero
**\* WARNING: increment -499 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 13
**\* WARNING: distributeRegion returned wrong duration 512, expected 13
**\* WARNING: increment -32 <= 0, rounding to zero
**\* WARNING: increment -35 <= 0, rounding to zero
**\* WARNING: increment -37 <= 0, rounding to zero
**\* WARNING: increment -41 <= 0, rounding to zero
**\* WARNING: increment -44 <= 0, rounding to zero
**\* WARNING: increment -49 <= 0, rounding to zero
**\* WARNING: increment -54 <= 0, rounding to zero
**\* WARNING: increment -61 <= 0, rounding to zero
**\* WARNING: increment -70 <= 0, rounding to zero
**\* WARNING: increment -81 <= 0, rounding to zero
**\* WARNING: increment -97 <= 0, rounding to zero
**\* WARNING: increment -122 <= 0, rounding to zero
**\* WARNING: increment -162 <= 0, rounding to zero
**\* WARNING: increment -244 <= 0, rounding to zero
**\* WARNING: increment -487 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 25
**\* WARNING: distributeRegion returned wrong duration 512, expected 25
**\* WARNING: increment -23 <= 0, rounding to zero
**\* WARNING: increment -24 <= 0, rounding to zero
**\* WARNING: increment -25 <= 0, rounding to zero
**\* WARNING: increment -26 <= 0, rounding to zero
**\* WARNING: increment -28 <= 0, rounding to zero
**\* WARNING: increment -30 <= 0, rounding to zero
**\* WARNING: increment -32 <= 0, rounding to zero
**\* WARNING: increment -34 <= 0, rounding to zero
**\* WARNING: increment -37 <= 0, rounding to zero
**\* WARNING: increment -40 <= 0, rounding to zero
**\* WARNING: increment -43 <= 0, rounding to zero
**\* WARNING: increment -48 <= 0, rounding to zero
**\* WARNING: increment -53 <= 0, rounding to zero
**\* WARNING: increment -60 <= 0, rounding to zero
**\* WARNING: increment -68 <= 0, rounding to zero
**\* WARNING: increment -80 <= 0, rounding to zero
**\* WARNING: increment -95 <= 0, rounding to zero
**\* WARNING: increment -119 <= 0, rounding to zero
**\* WARNING: increment -159 <= 0, rounding to zero
**\* WARNING: increment -238 <= 0, rounding to zero
**\* WARNING: increment -477 <= 0, rounding to zero
**\* WARNING: calculated output duration 512 != expected 35
**\* WARNING: distributeRegion returned wrong duration 512, expected 35
Jack: Process: graph not finished!
Jack: Process: waiting to switch delta = 11947
JackEngine::XRun: client = Hydrogen was not run: state = 1
JackEngine::XRun: client = hydrogen-midi was not run: state = 1
JackAudioDriver::ProcessGraphAsyncMaster: Process error
Jack: fPollTable i = 1 fd = 8

**Comment by thijz** [comment]
does anyone else see this ?

**Comment by thijz** [comment]
retested on 651435ed4ebe8d88ec6eb46a7d8eab15cbb28c0d
h2 does not crash, but there are error messages : 

`*** WARNING: increment -10 <= 0, rounding to zero
*** WARNING: increment -11 <= 0, rounding to zero
*** WARNING: increment -12 <= 0, rounding to zero
*** WARNING: increment -12 <= 0, rounding to zero
*** WARNING: increment -13 <= 0, rounding to zero
*** WARNING: increment -14 <= 0, rounding to zero
*** WARNING: increment -16 <= 0, rounding to zero
*** WARNING: increment -17 <= 0, rounding to zero
*** WARNING: increment -19 <= 0, rounding to zero
*** WARNING: increment -21 <= 0, rounding to zero
*** WARNING: increment -23 <= 0, rounding to zero
*** WARNING: increment -27 <= 0, rounding to zero
*** WARNING: increment -31 <= 0, rounding to zero
*** WARNING: increment -37 <= 0, rounding to zero
*** WARNING: increment -47 <= 0, rounding to zero
*** WARNING: increment -62 <= 0, rounding to zero
*** WARNING: increment -94 <= 0, rounding to zero
*** WARNING: increment -187 <= 0, rounding to zero
*** WARNING: calculated output duration 256 != expected 69
*** ERROR: distributeRegion returned wrong duration 256, expected 69
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -1 <= 0, rounding to zero
*** WARNING: increment -2 <= 0, rounding to zero
*** WARNING: increment -2 <= 0, rounding to zero
*** WARNING: increment -2 <= 0, rounding to zero
*** WARNING: increment -2 <= 0, rounding to zero
*** WARNING: increment -2 <= 0, rounding to zero
*** WARNING: increment -2 <= 0, rounding to zero
*** WARNING: increment -2 <= 0, rounding to zero
*** WARNING: increment -3 <= 0, rounding to zero
*** WARNING: increment -3 <= 0, rounding to zero
*** WARNING: increment -3 <= 0, rounding to zero
*** WARNING: increment -4 <= 0, rounding to zero
*** WARNING: increment -4 <= 0, rounding to zero
*** WARNING: increment -5 <= 0, rounding to zero
*** WARNING: increment -6 <= 0, rounding to zero
*** WARNING: increment -7 <= 0, rounding to zero
*** WARNING: increment -9 <= 0, rounding to zero
*** WARNING: increment -14 <= 0, rounding to zero
*** WARNING: increment -28 <= 0, rounding to zero
*** WARNING: calculated output duration 256 != expected 228
*** ERROR: distributeRegion returned wrong duration 256, expected 228
[New Thread 0x7fff723d9700 (LWP 3415)]
[New Thread 0x7fff71bd8700 (LWP 3416)]
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256

WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256

WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256

WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
WARNING: draining: shiftIncrement == 0, can't handle that in this context: setting to 256
[Thread 0x7fff71bd8700 (LWP 3416) exited]
[Thread 0x7fff723d9700 (LWP 3415) exited]
`

**Comment by theGreatWhiteShark** [comment]
closed with #1220
