### ISSUE TITLE
Playlist Tempo Bug

### ISSUE THREAD

**Issue by sgrace9** [hydrogen-music/hydrogen#1779]
Hydrogen version *          : 1.2.0
Operating system + version  :  Arch Linux (current)
Audio driver + version      :  JACK

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When recalling a song from a playlist, the song's tempo is sometimes (randomly?) set to 120 BPM instead of the tempo listed in the song file. This problem started with version 1.2.0.

Steps to reproduce:

1. Create two or more song files with tempos other than 120 BPM. Create a playlist of these files.

2. With the playlist active, use the F6/F5 keys to move through the playlist. The tempo will sometimes get set to 120 BPM in error. Moving to a different song and back to problem song once or twice will usually correct the tempo.

The problem can also happen when opening a song file from the Playlist Editor but seems to be more common when using the F6/F5 keys.

**Comment by theGreatWhiteShark** [comment]
Hey @sgrace9,

Thanks for reporting! Could you check whether #1781 does fix this issue at your end?

**Comment by sgrace9** [comment]
The description of #1781 seems plausible as a cause of my issue. However, using my existing version 1.2.0 I tried moving through a playlist slowly (waiting several seconds between songs) and still had incorrect song tempos.

If you're asking me to build Hydrogen from source, I'm not set up to do that. However, if you can upload a new binary somewhere I will test it.

**Comment by sgrace9** [comment]
I just installed 1.2.1 and the issue now appears to be fixed. Thanks.
