### ISSUE TITLE
BPM counter resets to 120 bpm

### ISSUE THREAD

**Issue by pragmaware** [hydrogen-music/hydrogen#1785]
Hydrogen version *  :  1.2.0 - self compiled from git
Operating system + version  :  linux - ubuntu 23.04
Audio driver + version  :  does not matter

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When switching to pattern mode from song mode the BPM counter always resets to 120 bpm.

It should either stay at the bpm currently set in the song or eventually return to the bpm that was set when the pattern was edited.

**Comment by theGreatWhiteShark** [comment]
That's probably #1781. Could you build the latest code from branch `master` (or `releases/1.2`) and check whether this issue still occurs?

**Comment by pragmaware** [comment]
Just tried latest master.

Still seems to happen.  Both when switching from song to pattern and from pattern to song. It's not systematic: it happens like 50% of the time, but it's very easy to reproduce. Just create a new project, set BPM to 160, switch to song mode and it will jump back to 120. Set again 160, switch to pattern mode and it's very likely to jump again to 120, and so on. 

Also with the current master there is a slightly different variation: sometimes the bpm counter remains at the correct value (160) but the playback speed switches to 120 bpm (so the UI and the playback do not agree).

**Comment by theGreatWhiteShark** [comment]
Ah, okay. Interesting. I'll try to reproduce it during the next couple of days.

**Comment by theGreatWhiteShark** [comment]
@pragmaware there was indeed still a bug I missed.

Could you check whether #1788 fixes this issue at your end?
