### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by hfiguiere** [hydrogen-music/hydrogen#1795]
Hydrogen version *          : 1.2.1 - commit 3dd2b451e6150338ef4d8836d826294ac8e78ad9 tag 1.2.1
Operating system + version  :  Linux + Flatpak KDE runtime
Audio driver + version      : PortMidi 217

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

It fail to build:
```
/run/ccache/bin/c++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -Dhydrogen_core_1_2_1_EXPORTS -I/run/build/hydrogen/src/core -I/run/build/hydrogen/src/core/hydrogen-core-1.2.1_autogen/include -I/run/build/hydrogen/src/core/include -I/run/build/hydrogen/src -I/run/build/hydrogen/include -I/run/build/hydrogen/src/core/.. -I/usr/include/opus -I/app/include/lash-1.0 -I/app/include/raptor2 -isystem /usr/include/QtCore -isystem /usr/lib/mkspecs/linux-g++ -isystem /usr/include/QtXml -isystem /usr/include/QtXmlPatterns -isystem /usr/include/QtNetwork -isystem /usr/include/QtGui -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -O3 -ffast-math -fno-implement-inlines -std=gnu++17 -fPIC -fPIC -MD -MT src/core/CMakeFiles/hydrogen-core-1.2.1.dir/IO/PortMidiDriver.cpp.o -MF src/core/CMakeFiles/hydrogen-core-1.2.1.dir/IO/PortMidiDriver.cpp.o.d -o src/core/CMakeFiles/hydrogen-core-1.2.1.dir/IO/PortMidiDriver.cpp.o -c /run/build/hydrogen/src/core/IO/PortMidiDriver.cpp
In file included from /run/build/hydrogen/src/core/IO/MidiInput.h:26,
                 from /run/build/hydrogen/src/core/IO/PortMidiDriver.h:26,
                 from /run/build/hydrogen/src/core/IO/PortMidiDriver.cpp:24:
/run/build/hydrogen/src/core/IO/PortMidiDriver.cpp: In member function ‘virtual void H2Core::PortMidiDriver::open()’:
/run/build/hydrogen/src/core/IO/PortMidiDriver.cpp:220:55: error: ‘const struct PmDeviceInfo’ has no member named ‘is_virtual’
  220 |                                          .arg( pInfo->is_virtual == TRUE ? "virtual " : "" )
      |                                                       ^~~~~~~~~~
/run/build/hydrogen/src/core/Object.h:229:163: note: in definition of macro ‘__LOG_METHOD’
  229 | #define __LOG_METHOD(   lvl, msg )  if( __logger->should_log( (lvl) ) )                 { __logger->log( (lvl), _class_name(), __FUNCTION__, QString( "%1" ).arg( msg ) ); }
      |                                                                                                                                                                   ^~~
/run/build/hydrogen/src/core/IO/PortMidiDriver.cpp:217:25: note: in expansion of macro ‘INFOLOG’
  217 |                         INFOLOG( QString( "%1%2%3%4device called [%5] using [%6] MIDI API" )
      |                         ^~~~~~~
[59/180] Building CXX object src/core/CMakeFiles/hydrogen-core-1.2.1.dir/License.cpp.o
ninja: build stopped: subcommand failed.
```

If the PortMidi version is insufficient it is not properly checked by the CMakeList
It is PortMidi 217.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by hfiguiere** [comment]
1.2.0 did build fine.

**Comment by theGreatWhiteShark** [comment]
Hey @hfiguiere ,

I see. Your repos do serve an ancient PortMidi version (almost [13 years old](https://sourceforge.net/projects/portmedia/files/portmidi/)). Virtual devices, however, were introduced in [PortMidi](https://github.com/PortMidi/portmidi) version 2.0.1 at the very end of 2021.

I just realized building is a little bit inconsistent on Linux. When doing the classical `mkdir build && cd build && cmake .. && make` PortMidi is not enabled per default. But when using the `build.sh` script it is. 

Are you actually using PortMidi? It wraps the ALSA MIDI interface but does not provide all the functionality Hydrogen's ALSA driver does. The main focus of the PortMidi driver is supporting MIDI on Windows while doing development on Linux or macOS.

If there are Linux folks using it, I would adjust it to be compatible with version 217 until newer PortMidi versions prevail in the package repos. If not, I would remove it from `build.sh` and adjust the minimum version in `CMakeLists.txt`

**Comment by hfiguiere** [comment]
the point is that if you check for portmidi, you should check the version. and mention it in the documentation.

I did update (that was my first move) and it works.

**Comment by theGreatWhiteShark** [comment]
> the point is that if you check for portmidi, you should check the version. and mention it in the documentation.

I totally agree with you. It's all on me because I thought I was dealing with an old and stable library and was not aware I used some cutting edge features. Still, there are two ways to go from here.
1. to adjust the code to properly work with version 217 (within the 1.2 release branch/family this new feature is only used in a log message)
2.  make the use of a more recent PortMidi version mandatory. But this might any some Linux users.

I would tend towards 2. as the main focus of PortMidi is Windows and not Linux. What's your opinion (as you seem to use PortMidi on Linux)?

**Comment by hfiguiere** [comment]
I have no opinion. I built with it because it was a dependency. It works. So does ALSA and JACK.

**Comment by theGreatWhiteShark** [comment]
Alright. Added notes about the required PortMidi version (and expect users to either upgrade or compile the code without PortMidi support).
