### ISSUE TITLE
Windows version: catastrophical export

### ISSUE THREAD

**Issue by belolo** [hydrogen-music/hydrogen#18]
im on a amd tri-core 8gb ram windows 7, using the preview version for windows,

and the thing is quite randomly but it makes my computer shut down

1)i make a pattern with my guitar drumkit loaded

2)i press ctrl+e to export the pattern

3)i press the "examinar" button, the one that opens a new window to change the name of the exported song, here i can see a peak on the three cores of 100% cpu usage but it does not collapse the computer

4) i change the name and click accept

5) and here comes the bug, when y press the drop down menu for the templates, the computer collapses and shuts down at once

**Comment by thijz** [comment]
hi belolo
can you still reproduce this issue ?

grtz
Thijs

**Comment by mauser** [comment]
There is a new version of hydrogen for windows available on Sourceforge which should fix most of the export problems with the last version.
