### ISSUE TITLE
Allow Midi Notes up to 127 in Instrument MIDI Output

### ISSUE THREAD

**Issue by PatDyn** [hydrogen-music/hydrogen#1828]
Hydrogen version *          : 1.2.1-1
Operating system + version  : Manjaro, installed via pamac
Audio driver + version      : Jack, 1.9.22

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I've been using hydrogen along with a launch pad mini, using its buttons to mute/unmute instruments in H2.
Having the midi note output is incredibly helpful as it visual feedback for the currently playing instruments on the launchpad.

However, this is limited by the cap on the MIDI note number output. That means visual feedback of playing instruments stops
in the middle of a row of buttons. Is there any specific reason why there is a limit? Or would it be possible to remove the cap and make all note numbers available for output?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info > About' in the GUI or 'hydrogen -v' on the command line. Also, please indicate how you installed it, e.g. binary downloaded from SourceForge/Github, brew (macOS), OS repo (Linux), flathub (Linux).
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by theGreatWhiteShark** [comment]
> Is there any specific reason why there is a limit?

No. That's a bug. Thanks for reporting!

**Comment by theGreatWhiteShark** [comment]
The fix will be part of the 1.2.2 patch release.

If you could check the fix in either the `releases/1.2` branch or in the latest developer version on `master`, this would be great.

**Comment by PatDyn** [comment]
Thanks! I built from master and everything works as expected.
