### ISSUE TITLE
Hydrogen instruments will not respond to external MIDI control pad despite Hydrogen detecting MIDI input

### ISSUE THREAD

**Issue by oferfuxake** [hydrogen-music/hydrogen#1848]
Hydrogen version *          :1.2.0
Operating system + version  : AV LINUX MX EDITION 21.2.1 "Consciousness"
Audio driver + version      : `jackd 1.9.21~dfsg-1~mx21+1`

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Drum kit will not respond to incoming MIDI notes from external MIDI controller (Alesis ControlPad.)  Instruments cannot be triggered or recorded.

Drum kit does respond to Hydrogen's virtual keyboard notes. ControlPad notes are set to the same values as virtual keyboard for triggering Hydrogen instruments.

In Preferences > MIDI System, the "Incoming Event" recorder records external MIDI inputs from the ControlPad, and MIDI channel is set to ALL. If an Action is assigned to an Incoming Event, the ControlPad will trigger the Action (Play, Stop, etc.)

MIDI activity LED in main screen does illuminate when ControlPad is used.

ControlPad can be routed to other MIDI instruments successfully.

**Comment by theGreatWhiteShark** [comment]
Hey @oferfuxake ,

Could you open Hydrogen via `hydrogen -VDebug` in a terminal and attach the log messages in here?

Also, have you checked the input mode and note mapping settings? (see http://hydrogen-music.org/documentation/manual/manual_en.html#chpt.midi.note) From what you describe MIDI message are already properly handled by Hydrogen. Maybe a small configuration detail is missing.

**Comment by oferfuxake** [comment]
Thank you for your response! I must admit, I wasn't really expecting this to be answered but thought it was worth a try. I keep thinking the same thing - it's got to be some really small, simple configuration setting that I've got wrong somewhere but I can't for the life of me think of what it could be.

I've attached the log file after opening with the -VDebug option and trying a brief recording in pattern mode, with input set to drumkit. I've tried this previously with "Use output note as input note" checked and unchecked and it didn't make any difference. I did notice that the MIDI channel appeared to be 0 according to the terminal window messages (despite my controller being set to channel 1) so I changed the controller to channel 11 which resulted in Hydrogen seeing notes on channel 10. Not sure what's up with that discrepancy, but I don't think it should have been an issue with the Hydrogen channel set to "All" in the MIDI preferences tab.

Thanks in advance for any insight, and thank you again for responding! I hope something in the log file provides a clue.

[hydrogen.log](https://github.com/hydrogen-music/hydrogen/files/12708850/hydrogen.log)

**Comment by theGreatWhiteShark** [comment]
Ah, I see.

The version of Hydrogen you are using (1.2.0) is suffering from a bug causing this issue (#1751).

You could use the [latest](https://github.com/hydrogen-music/hydrogen/releases/download/1.2.2/Hydrogen-1.2.2-x86_64.AppImage) version instead or, as a workaround, disable the Preferences > MIDI System > "Discard MIDI messages after action has been triggered" option.

**Comment by oferfuxake** [comment]
Issue fixed by un-checking "Discard MIDI messages after action has been triggered" option in Preferences > MIDI System.
Also downloaded v.1.2.2 for possible future use.
