### ISSUE TITLE
In portuguese language there are some weird characters

### ISSUE THREAD

**Issue by schirrel** [hydrogen-music/hydrogen#185]
I'm brazilian and my language setting is portuguese, the program presents instead of <ç  ã ẽ õ á ó é> some weird characters with a ? inside.

**Comment by thijz** [comment]
confirmed
see mail "Full translation of [hydrogen.pt_BR.ts] file" on the dev ML (19/1/2015) by Fernando Santucci
he is working on a new translation for portugese

**Comment by mauser** [comment]
Hi,

this problem should have been fixed with #583 .
