### ISSUE TITLE
PatternEditor issues

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#1859]
Hydrogen version *          : 1.2

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I just experienced some very strange behavior in the Pattern Editor

1. Create a new song
2. Fill the first instrument with notes
3. Select all notes and move them **up** by dragging them into the ruler
   -> the notes will disappear and don't show up in the .h2song when saving now. This shouldn't be possible
4. Hit <kbd>Ctrl</kbd> + <kbd>Z</kbd> to undo
   -> the notes reappear as **NoteOff** notes which can neither be selected using mouse dragging or <kbd>Ctrl</kbd>  + <kbd>A</kbd>. WTF?

Edit: moving notes out of the pattern is probably not a bad idea. But undo has to work.

---

- [x] Make undo work for notes moved outside of the editor
- [x] Allow to select NoteOff notes using drag select and keyboard select
- [x] Click and <kbd>Shift</kbd> + Click should remove an existing NoteOff note (only the one clicked)
- [x] Notes not reachable using the current pattern length should either not be rendered at all or rendered differently (see #1853)
- [x] Make NoteOff notes terminate the manually set length of a note (don't forget the corresponding redo)
- [x] When selecting notes using keyboard only <kbd>Up</kbd> and <kbd>Down</kbd> update the selection. For <kbd>Left</kbd> and <kbd>Right</kbd> just the rectangle changes.

**Comment by theGreatWhiteShark** [comment]
> Allow to select NoteOff notes using drag select and keyboard select

Hey @cme ,

In 

https://github.com/hydrogen-music/hydrogen/blob/master/src/gui/src/PatternEditor/PatternEditor.cpp#L237
https://github.com/hydrogen-music/hydrogen/blob/master/src/gui/src/PatternEditor/PatternEditor.cpp#L1048
https://github.com/hydrogen-music/hydrogen/blob/master/src/gui/src/PatternEditor/PatternEditor.cpp#L1137

NoteOff notes are intentionally excluded from being selected and rendered as selected. Do you know why?

I never used them in a real song but just quickly toying with them feels super strange as they do not behave like regular notes.

**Comment by theGreatWhiteShark** [comment]
We can do this (the NoteOff note is rendered blue):

![noteOffScreenshot](https://github.com/hydrogen-music/hydrogen/assets/14164547/e63813ce-c1af-4324-98a1-99a25fc755b7)

Triggering another note within the fixed length of a note is fine. But adding a NoteOff should cut the length of the note till the position of the stop note. Else the GUI suggests that the note will keep ringing. Which it does not.

**Comment by cme** [comment]
> > Allow to select NoteOff notes using drag select and keyboard select

> NoteOff notes are intentionally excluded from being selected and rendered as selected. Do you know why?

Looks like I accidentally inherited that logic from the original drag event handlers which were set up only to handle start notes because the previous functionality was to change the lengths by dragging. No explicit stop notes in the demo songs meant I ended up not noticing.
