### ISSUE TITLE
Right-click menu in pattern editor does not work on my system

### ISSUE THREAD

**Issue by ViktorNova** [hydrogen-music/hydrogen#187]
When I right click on an instrument in the pattern editor, the menu flashes visible for a split second and then immediately disappears, usually too quick to even tell it appeared at all. I've been having this issue for awhile, and it still occurs on master, although I think it may have to do with some underlying library or something because it does not occur on my Arch box, even though that version of Hydrogen is built from the same master. I compiled them on the same day (yesterday) to verify. On my Debian Wheezy box, this wrong behavior is consistent, I no longer have access to Copy Pattern, Clear Notes, etc. 

I have tried many versions, including stable binary from the KXStudio repo, and tried swapping out a clean .hydrogen config folder and changing QT styles in Hydrogen - the menu still does not stay up. Any idea what's going on?

**Comment by thijz** [comment]
hi Viktor
do you still see this ?

grtz
Thijs

**Comment by ViktorNova** [comment]
Well I haven't been able to reproduce this on any other machine, even when compiling from the same exact same source, so I can only assume it had something to to with my QT theme (Bespin with lots of custom options) or  window manager configuration (i3 with at least a few Hydrogen-specific rules)

I apologize for not closing this sooner (slipped my mind), I am not expecting it to pop up again but I'll re-open it if it does and I have something more substantial
