### ISSUE TITLE
Hydrogen as jack transport master messes up sync

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#190]
(using code from github of today (july 30), but i see the same behavior on older 0.9.6 versions)

I have been playing around with Hydrogen and jack_midi_clock (see http://www.teuton.org/~gabriel/jack_midi_clock/) to sync the arpeggiator of a hardware synth to hydrogen 
Basically i set hydrogen as jack master, start jack_midi_clock (and connect that to my midi output port in qjackctl) and connect my midi out port of my pc to the midi in of the synth
That works fine, but i noticed that when i play around with the tempo (in hydrogen) i start to get an offset between hydrogen and the synth
the tempo on the synth still changes when i change tempo in hydrogen, but there is an offset that seems to grow

i tried to find an easy way to reproduce this without the need for a hardware synth and i think i was able to do that with this config :

1) start jack, open hydrogen
2) create a pattern with 4 beats on the 1,2,3 and 4 (i used 'click' from the gmkit)
3) use this pattern to create a 4-bar song
4) set hydrogen in (looped) song mode and set a tempo change on bar1 (120) and one on bar 3 (200)
5) enable jack transport AND jack master

6) open a second instance of hydrogen
7) create a pattern with 4 beats on the 1,2,3 and 4 (here i used 'cowbel' from the gmkit, so it is easy to hear the difference between the 2 hydrogen instances)
8) use this pattern to create a 4-bar song
9) set hydro to  song mode (looped)
10) enable jack transport (NOT master)

11) on the first hydrogen instance press stop (to make sure that the transport position is at 'position 0')
12) on the first hydrogen instance press play

what i expect to see :
both hydrogen instances play in perfect sync

what i see instead :
after the first tempo change both hydrogen instances are out of sync

i also did this extra test with jack_transport
1) make sure that 'transport master ' is disabled on both hydrogen instances
2) in a terminal start jack_transport
3) make it master by typing 'master'
4) set a tempo : 'tempo 120'
5) start transport : 'play'
6) while playing change the tempo : 'tempo 200'
7) while playing change the tempo : 'tempo 120'

in this setup both hydrogen instances are in perfect sync, so it seems to be an issue with hydrogen as master

**Comment by xjjx** [comment]
Hi, so what is the status ? Can we go to the official repo with this code or not ?

**Comment by thijz** [comment]
yes
tested and approved !  :-)
