### ISSUE TITLE
Hydrogen gets a MIDI message, but no instrument is triggered

### ISSUE THREAD

**Issue by quasilyte** [hydrogen-music/hydrogen#1919]
Hello. :christmas_tree: 
I'm having trouble making Hydrogen work responsively with my drumkit and Linux.

* I have a Roland TD02kv electronic drum
* It's connected via the USB to the Linux Mint laptop
* I'm using the Hydrogen 1.1.1 dev build
* I'm using the qjackctl to connect the TD-02 midi as the hydrogen input

The problem: Hydrogen ignores the hi-hat instrument more often than not. I see the midi-in indicator in the top part of the Hydrogen main UI flickering, as it's receiving the input, but the instrument is not triggered.

It doesn't matter how hard I hit the hi-hat.

I think I either need to debug a MIDI stream to see what messages does the Hydrogen receive or maybe I need to configure the Hydrogen to handle these messages correctly.

Here is the qjackctl screenshot:

![image](https://github.com/Shopify/hydrogen/assets/6286655/e601db96-c397-429f-92b0-779dd87e3585)

The Hydrogen clearly getting some sort of an input from the drumkit:

![image](https://github.com/Shopify/hydrogen/assets/6286655/499c2c61-84d0-414c-ae38-5b43a6281c7f)

But the instrument is not triggered. I see no sound, and the relevant icon isn't flashing inside the mixer:

![image](https://github.com/Shopify/hydrogen/assets/6286655/282ec65d-2bc9-4c2c-b84a-de8c64a30c58)

If I get lucky, sometimes it's activated, but the sound looks reduced or whatever:

![image](https://github.com/Shopify/hydrogen/assets/6286655/e6df9417-37a7-47e4-98e8-ec6a9fb624d9)

Observation: only one part of the hi-hat is being this tricky. If I hit the back part of the pad, it plays 100% of the time.

Another weird thing is that there is a ~100% chance that the hi-hat instrument will be triggered IF I trigger some other instrument right before it. But if I go on with a hi-hat alone after that, it will eventually start to ignore it after a 3 or 4 hits.

I thought that it could be related to the note-off setting, but switching it off doesn't help here.

These are the settings I'm using:

![image](https://github.com/Shopify/hydrogen/assets/6286655/e020cae7-2444-4c91-ad54-7e781b7cafa4)

I tried using the TD2 as an input device; the results are the same.

Some extra info:
```
$ uname -a
Linux lispbook2 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/asound/cards
 0 [sofhdadsp      ]: sof-hda-dsp - sof-hda-dsp
                      HP-HPEliteBook63013inchG9NotebookPC--897A
 1 [TD02           ]: USB-Audio - TD-02
                      Roland TD-02 at usb-0000:00:14.0-3, full speed
```

Maybe there is some feature or setting I'm missing?

**Comment by quasilyte** [comment]
I did some MIDI debugging.
I connected the TD midi stream to both Hydrogen and midisnoop to log the messages.

This is an example of a single hi-hat hit that makes no sound in Hydrogen:

![image](https://github.com/hydrogen-music/hydrogen/assets/6286655/e5bb3d37-60d7-46fc-b183-596c5d0debcf)

This is an example of the same hi-hat making the sound:

![image](https://github.com/hydrogen-music/hydrogen/assets/6286655/6823143d-060d-44ad-8483-9a871ca05268)

**Comment by quasilyte** [comment]
It almost looks like the note is the case here.
Maybe the sound bank doesn't have the note 26 available?
I tried it multiple times and I get the same results.

This is **very** rought experience for a beginner.
I doubt everyone would lean towards the MIDI message debugging.
Perhaps there should be some sort of a notice to the user like "hey, it looks like your drumkit is emitting a note that we can't play with these settings"

**Comment by quasilyte** [comment]
But user-friendliness issues aside, I hope there is a way to map the non-existing note to some closest one.
I would like to use the builtin drum kits to get more familiar with this software.
To use them, I need to make this note 26 work. :)

**Comment by theGreatWhiteShark** [comment]
Hey @quasilyte ,

> The problem is: the user doesn't know which side has an issue.

You should take a look in Hydrogen's log (start it via `hydrogen -VDebug`). Then Hydrogen should talk about each incoming MIDI message, whether it can handle it, and if it can be mapped to an instrument of your current drumkit.
But I would highly recommend doing so with a more [recent version](https://github.com/hydrogen-music/hydrogen/releases/download/1.2.2/Hydrogen-1.2.2-x86_64.AppImage).

> I thought that it could be related to the note-off setting, but switching it off doesn't help here.

There was actually bug in this very setting at some point. But the more recent version should fix that too.

> Maybe the sound bank doesn't have the note 26 available?

Yes. Most kits will not respond to note 26. But you can adjust which note an instrument is listening too in the Instrument Editor (see http://hydrogen-music.org/documentation/manual/manual_en.html#chpt.midi.note). I know it's not intuitive. Especially since the corresponding label reads "MIDI Output". But it grew that way in the past and we try to make the best out of it. :)

> I think a notice to the user when they're trying to play a note that is not covered by a sound bank could be a good first step in making it less frustrating for the end-users.

I know. Somewhere deep, deep down my TODO list I also want to make the MIDI-In LED clickable and show a nice summary of incoming and outgoing MIDI messages, note mapping etc. But no idea when or if that will happen :|

**Comment by quasilyte** [comment]
@theGreatWhiteShark just so you know, I find this software amazing, and I want to explore more of it. :)
I'll try to follow your suggestions. I can't wait to play around with my drums and Hydrogen some more.

**Comment by quasilyte** [comment]
Enabling the "use output note as input note" plus assigning the output note value to the instrument manually fixes my issue.
I believe the only thing I need to do now is to copy/paste the hi-hat instrument so it can handle both notes (it's OK for me if they sound identical for now).
This issue can be closed.
