### ISSUE TITLE
Better visual feedback for current note & pattern being triggered as they are playing

### ISSUE THREAD

**Issue by ViktorNova** [hydrogen-music/hydrogen#192]
Something I am constantly finding myself doing is squinting to see where in the pattern or song editor that tiny little cursor at the top is floating to see where in the song or pattern I am at the moment. It is also hard to line it up iwhile watching the thing play when there is a page and a half of instruments or patterns loaded and the instrument or pattern being played is nowhere near the only position indicator

I propose 2 new things to address this:
1. A vertical line that extends down from the cursor and goes to the bottom of the song/pattern editor area, moving with the cursor and showing the current position through the whole page. Almost every sequencer does this and it should be pretty easy to implement, I'm going to take a stab at this one this week
2. As a sample is being triggered, that note glows a different color for a moment to let you know it is currently sounding. In the song editor, any patterns being played glow a different color until they are finished playing. Maybe they even flash or pulsate with the beat =)

Any thoughts about this?

**Comment by theGreatWhiteShark** [comment]
1. was implemented in #1544 

For the 2. part: it would be in principle possible to implement such a thing but it would probably introduce a significant increase of Hydrogen's CPU load. I can see where you are coming from but I think highlighting the current note is sufficiently done using the full-height playhead. 

I will close this issue for now. But feel free to reopen it if there is something missing or the implementation #1544 is not sufficient for your needs.
