### ISSUE TITLE
Problems connecting to Jack on Manjaro Linux

### ISSUE THREAD

**Issue by chippisc** [hydrogen-music/hydrogen#1923]
Hydrogen version * :  1.2.2
Operating system + version:  Manjaro Linux - Kernel 6.1.69-1-MANJARO 
Audio driver + version:  Jack version 1.9.22 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hydrogen crashes when trying to export a song. Error printed repeatedly in log:
```
E) ::static int H2Core::AudioEngine::audioEngine_process(uint32_t, void*) Failed to lock audioEngine in allowed 11.577 ms, missed buffer
```
If a complete error log would help, please let me know.

`.log/jack/jackdbus.log` outputs
```
Unknown destination port in attempted (dis)connection src_name [Hydrogen:out_L] dst_name [alsa_pcm:playback_1]
Mon Jan  1 00:22:10 2024: ERROR: JackEngine::XRun: client = Hydrogen was not finished, state = Running
Mon Jan  1 00:22:10 2024: ERROR: JackAudioDriver::ProcessGraphAsyncMaster: Process error
Mon Jan  1 00:22:11 2024: ERROR: Failed to find port 'Hydrogen:out_L' to destroy
Mon Jan  1 00:22:11 2024: ERROR: Failed to find port 'Hydrogen:out_R' to destroy
Mon Jan  1 00:22:11 2024: ERROR: Cannot write socket fd = 28 err = Broken pipe
```

I cannot exactly track down what caused the error to appear. I updated from Kernel 5.15 to 6.1 and did a complete system update at the same time.

I start Jack using Cadence. This seems to puts up a correctly working instance as I can use it with Reaper and other Software.
Hydrogen seems to be using Jack.
![image](https://github.com/hydrogen-music/hydrogen/assets/56129198/a543cc66-ccd6-45cb-ba20-db52e29ef117)

I made sure to put correct settings for audio and realtime in `/etc/security/limits.d/audio.conf`.
`ulimit -r` outputs `99`.

Is there a difference between exporting and just playing audio that could help identify the error?

**Comment by theGreatWhiteShark** [comment]
Hey @chippisc ,

Could you check whether the crash still occurs in [this version](https://ci.appveyor.com/api/buildjobs/u6io05ii3l0121ff/artifacts/Hydrogen-1.2.2-96-gc0cb947f4-x86_64.AppImage) of Hydrogen?

> Is there a difference between exporting and just playing audio that could help identify the error?

Yes. During export Hydrogen shuts down its JACK driver, starts up a driver dedicated to writing audio to a file, and then brings up a new instance of the JACK driver. But there seems to be a bug in newer versions of JACK where our client crashes at shutdown and kills Hydrogen along with it.

I'm in the process of finding a solution for this very problem :)

(Duplicate of #1902)

**Comment by chippisc** [comment]
Fixed in above version.

Very sorry for the duplicate, I only checked the open issues :o

You guys are amazing, thank you!
