### ISSUE TITLE
Mention PulseAudio driver in the manual

### ISSUE THREAD

**Issue by gbonik** [hydrogen-music/hydrogen#193]
In chapter 1, section "Preferences > The Audio System tab" is missing the newly added PulseAudio backend.

**Comment by trebmuh** [comment]
+1

**Comment by mauser** [comment]
Closed: Has already been fixed in my commit 405338c2112ad5e19f4.

**Comment by trebmuh** [comment]
added here : https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-0.9.7
