### ISSUE TITLE
strange buzzing during startup

### ISSUE THREAD

**Issue by Reaper10** [hydrogen-music/hydrogen#1932]
Hydrogen version *         :   1.2.3
Operating system + version  :  wIn 10 22H2
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

strange buzzing when starting 
[h2 sound bug.zip](https://github.com/hydrogen-music/hydrogen/files/13980624/h2.sound.bug.zip)

**Comment by theGreatWhiteShark** [comment]
Thanks for reporting!

That's very strange. But I can reproduce it and will have a look.

**Comment by theGreatWhiteShark** [comment]
Closed with #1937
