### ISSUE TITLE
Option missed: MIDI input without notes, only cc messages

### ISSUE THREAD

**Issue by jduemes** [hydrogen-music/hydrogen#195]
On version 0.9.5 it was possible to send CC messages to Hydrogen without play the notes. Now on version 0.9.6 is no possible anymore.
I am trying now from git repo (0.9.7-'9e45663') and it has the same problem.

More infos: http://hydrogen.popez.org/hcms/node/13079

**Comment by thijz** [comment]
similar to #63 and #57

**Comment by mauser** [comment]
Hi,

sorry for the long delay! The option is now available again..

**Comment by trebmuh** [comment]
Added here : https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-0.9.7
