### ISSUE TITLE
install not going to /usr/lib but only /usr/local/lib

### ISSUE THREAD

**Issue by wolftune** [hydrogen-music/hydrogen#1956]
Hydrogen version *          : 1.2.3
Operating system + version  : KDE Neon (Ubuntu based)

As discussed in https://github.com/hydrogen-music/hydrogen/issues/677 I built and installed, could not run, and making a symlink of libhydrogen-core-1.2.3.so linking /usr/local/lib/ at /usr/lib allowed it to work.

**Comment by theGreatWhiteShark** [comment]
Hey @wolftune ,

Seems like your Linux distribution is more user than developer focused. It added `/usr/local/bin` to `$PATH` but not `/usr/local/lib` to `$LD_LIBRARY_PATH`.

Installing your local build to `/usr/local` is more or less standard. `/usr` should be used by your package manager. This allows you to manually compile and install custom Hydrogen versions without messing with the system's one.

You could use a different installation prefix when building Hydrogen. But I would strongly discourage that. As discussed in #677, you could instead

1. run `sudo ldconfig` and check whether this already fixes your issue
2. open Hydrogen via the command line using `LD_LIBRARY_PATH=/usr/local/lib hydrogen`
3. add `export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}` to your `$HOME/.profile`
4. set the symlink as you mentioned

Do you think there is anything else to be done to keep this issue open?

**Comment by wolftune** [comment]
Well, the one thing maybe to do is to note this issue in the build instructions. Your reply here is amazingly thorough and clear. Only thing is, your list looks like a 4 step process, but I think you meant it as a weakly-sorted list of options to try (where any one of them alone could work), right?

I have it working now, and I'm just wanting to keep it working in the future and for others to know what to do.

Thanks!

**Comment by theGreatWhiteShark** [comment]
> Well, the one thing maybe to do is to note this issue in the build instructions.

We already had a paragraph in [INSTALL.md](https://github.com/hydrogen-music/hydrogen/blob/master/INSTALL.md#error-loading-shared-libraries). But it was that accessible. Just updated it :)
