### ISSUE TITLE
Add MIDI action for coarse pitch of whole instrument

### ISSUE THREAD

**Issue by jklerch** [hydrogen-music/hydrogen#1967]
Hydrogen version *          : 1.2.3
Operating system + version  : Arch Linux (EndeavourOS), Kernel 6.6.23.28
Audio driver + version      :  snd_hda_intel, srcversion B73042A27E10BB0B6D2E39E

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

At http://hydrogen-music.org/documentation/manual/manual_en_chunked/ch16s04.html it is described how to change the coarse pitch of an instrument's layer using MIDI commands. However, I would like to be able to change the coarse pitch of the instrument using a MIDI command. Unfortunately, I cannot find a MIDI action that does that in the documentation of H2. Would it be possible for you to add such a MIDI action?

Best regards

**Comment by theGreatWhiteShark** [comment]
> Would it be possible for you to add such a MIDI action?

Sure. Here you go

https://ci.appveyor.com/api/buildjobs/v7gwrud871vhuv9b/artifacts/Hydrogen-1.2.3-39-ga9e057272-x86_64.AppImage

The new MIDI action is called `INSTRUMENT_PITCH`.

(Honestly, I'm a little puzzled when it comes to our MIDI API. A lot of rather useful actions, like setting various instrument parameters, humanization etc, are missing but some almost too specialized ones, like setting pitch and gain of a single layer, made it into the API. At some point we might introduce a large set of new actions covering meaningful actions that can be performed in Hydrogen. But this would require a refresh of some GUI parts too and is not of high priority right now).

**Comment by theGreatWhiteShark** [comment]
closed with #1969

**Comment by emilaxelsson** [comment]
Hm.. I guess the range 64..127 makes up two octaves.

But nevermind, I just realized it's better to use input mode for what I'm trying to achieve. Then I can set pitch in `NOTE_ON` and use `SET_INSTRUMENT` to switch between instruments.
