### ISSUE TITLE
Feature request: toggle recording while hydrogen playing

### ISSUE THREAD

**Issue by jklerch** [hydrogen-music/hydrogen#1968]
Hydrogen version * : 1.2.3
Operating system + version : Arch Linux (EndeavourOS), Kernel 6.6.23.28
Audio driver + version : snd_hda_intel, srcversion B73042A27E10BB0B6D2E39E

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

There is the possibility to activate the recording in hydrogen by toggling the recording button and pressing play afterwards. During hydrogen is playing, recording cannot be ended (following my knowledge). However, for live performances, it would be really really nice if there was the option to just disable the recording while the track is still playing. Would it be possible to add such a feature?

**Comment by theGreatWhiteShark** [comment]
Hey @jklerch ,

> During hydrogen is playing, recording cannot be ended (following my knowledge).

That should be possible by clicking the record button again while playing. This UX feels kinda awkward nowadays. It seems to be modeled after recording on old tape decks.

You can also toggle recording via MIDI using `RECORD/STROBE_TOGGLE`.

And there is a third option: you can draw a punch in area in the timeline (where the tempo markers live) by pressing and holding the right mouse button and moving the mouse pointer to the _right_. (a somewhat esoteric feature a developer smuggled into Hydrogen)
