### ISSUE TITLE
Unable to get sound from drum kit

### ISSUE THREAD

**Issue by aamarioneta** [hydrogen-music/hydrogen#1983]
Hydrogen version *          : 1.2.0-beta
Operating system + version  : Ubuntu Studio 24.04 LTS Live
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

As the title says: i am not hearing sounds when hitting the drum kit.
I can hear all sounds when i click on the different instruments.
![grafik](https://github.com/hydrogen-music/hydrogen/assets/2805397/18975ead-3c03-4015-aa8a-9c016596ce99)

I can hear the metronome.

I can see the MIDI-In blink when i hit anything on the kit.

![grafik](https://github.com/hydrogen-music/hydrogen/assets/2805397/e8cc536c-2194-4131-8a1e-a19c5295015a)

MIDI config:
![grafik](https://github.com/hydrogen-music/hydrogen/assets/2805397/89969322-3679-4676-baed-503c0723a90b)

This is the jack config:
![grafik](https://github.com/hydrogen-music/hydrogen/assets/2805397/27466bd7-d300-4ea0-a9fd-9ce3027ba397)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by theGreatWhiteShark** [comment]
Hey @aamarioneta 

The version of Hydrogen you are using (1.2.0) is suffering from a bug causing this issue (https://github.com/hydrogen-music/hydrogen/issues/1751).

You could use the [latest](https://github.com/hydrogen-music/hydrogen/releases/download/1.2.3/Hydrogen-1.2.3-x86_64.AppImage) version instead or, as a workaround, disable the Preferences > MIDI System > "Discard MIDI messages after action has been triggered" option.

**Comment by aamarioneta** [comment]
> Hey @aamarioneta
> 
> The version of Hydrogen you are using (1.2.0) is suffering from a bug causing this issue (#1751).
> 
> You could use the [latest](https://github.com/hydrogen-music/hydrogen/releases/download/1.2.3/Hydrogen-1.2.3-x86_64.AppImage) version instead or, as a workaround, disable the Preferences > MIDI System > "Discard MIDI messages after action has been triggered" option.

Thanks. That fixed it.
