### ISSUE TITLE
vers 1.2.3 - No MIDI devices found in windows 10 64bit

### ISSUE THREAD

**Issue by pepelevamp** [hydrogen-music/hydrogen#1999]
Hydrogen version *          : 1.2.3-win64
Operating system + version  :  windows 10 64bit
Audio driver + version      : saffire mixcontrol, VK-25 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
When I select a MIDI device it shows no devices listed either using the PortMidi or the Jack options. 

I'm uncertain how to get further information to help assist.

I have both a Saffire pro40 midi in/out devices and a VK-25 midi device. They are completely different devices and they appear fine in REAPER and anywhere else.

Is there a different program which also uses PortAudio which I could try & see if it sees my MIDI devices?
Is there an older version or different fork of hydrogen worth trying?

I installed Hydrogen-1.2.3-win64.exe from the hydrogen home page.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info > About' in the GUI or 'hydrogen -v' on the command line.

**Comment by theGreatWhiteShark** [comment]
Hey @pepelevamp ,

> When I select a MIDI device it shows no devices listed either using the PortAudio or the Jack options.

Just to be sure: audio drivers handle the exchange of audio data while MIDI drivers handle the exchange of MIDI messages. The audio drivers `PortAudio` and `JACK` can be chosen in the Audio tab and `PortMidi` and `JACK-Midi` in the [MIDI tab](http://hydrogen-music.org/documentation/manual/manual_en.html#chpt.preferences.midi_tab). The latter is what you need.

In case this is not your problem, could you [attach your log messages](https://github.com/hydrogen-music/hydrogen/wiki/Accessing-log-messages-of-Hydrogen)?

**Comment by pepelevamp** [comment]
Hi there. Wow a very fast response :)

Oh yah I put in my audio driver because the template asked me to :P But it seems to have fixed itself. I do not know how. I did these things:

1. Uninstalled
2. Installed 0.97
3. having the same issue
4. reinstalled1.2.3
5. ran as Administrator for a joke. same issue.
6. Then ran from the command line with --verbose "DEBUG"

Now the issue seems to have resolved itself that Im looking at debug log !?

I have no idea how.  
In the output log it shows my MIDI devices after PortMidiDriver::open, so who knows.

If it happens again I will let ya know.
`(I) AudioEngine::setSong Set song: Untitled Song
(I) Preferences::savePreferences Saving preferences file C:/Users/me/.hydrogen/hydrogen.conf
(I) PortMidiDriver::getOutputPortList Pro40 MIDI
(I) PortMidiDriver::getOutputPortList V25 MKII
(I) PortMidiDriver::getOutputPortList MIDIIN2 (V25 MKII)
(I) PortMidiDriver::getInputPortList Microsoft MIDI Mapper
(I) PortMidiDriver::getInputPortList Microsoft GS Wavetable Synth
(I) PortMidiDriver::getInputPortList Pro40 MIDI
(I) PortMidiDriver::getInputPortList V25 MKII
(I) PortMidiDriver::getInputPortList MIDIOUT2 (V25 MKII)
(I) AudioEngine::stopAudioDrivers
(I) PortMidiDriver::close [close]
(I) AudioEngine::startAudioDrivers
(I) AudioEngine::createAudioDriver Creating driver [PortAudio]
(I) PortAudioDriver::connect [connect]
(E) PortAudioDriver::connect Can't use device '', using default stream
(E) PortAudioDriver::connect Can't use device '', using default stream
(I) PortAudioDriver::connect Opened device ''
(I) PortAudioDriver::connect PortAudio outpot latency: 0.180317 s
(I) PortMidiDriver::open [open]
(I) PortMidiDriver::open Found available output device called [Microsoft MIDI Mapper] using [MMSystem] MIDI API
(I) PortMidiDriver::open Found available input device called [Pro40 MIDI] using [MMSystem] MIDI API
(I) PortMidiDriver::open Using input device called [V25 MKII] using [MMSystem] MIDI API
(I) PortMidiDriver::open Found available input device called [MIDIIN2 (V25 MKII)] using [MMSystem] MIDI API
(I) PortMidiDriver::open Found available output device called [Microsoft GS Wavetable Synth] using [MMSystem] MIDI API
(I) PortMidiDriver::open Found available output device called [Pro40 MIDI] using [MMSystem] MIDI API
(I) PortMidiDriver::open Found available output device called [V25 MKII] using [MMSystem] MIDI API
(I) PortMidiDriver::open Found available output device called [MIDIOUT2 (V25 MKII)] using [MMSystem] MIDI API
(I) PortMidiDriver::open No MIDI output device selected
(I) ::void* H2Core::PortMidiDriver_thread(void*) PortMidiDriver_thread starting
(I) Preferences::savePreferences Saving preferences file C:/Users/me/.hydrogen/hydrogen.conf
(I) PreferencesDialog::~PreferencesDialog ~PREFERENCES_DIALOG`

**Comment by pepelevamp** [comment]
It seems to be persisting now with my midi devices visible. I guess unless there's any objections I'll close it as unreproducable? Maybe find this later if the problem arises.

**Comment by theGreatWhiteShark** [comment]
> it seems to have fixed itself

Glad to hear.

Maybe it is a timing issue? The preferences dialog of Hydrogen does not support hot plugging. Your device needs to be already there before opening.

**Comment by pepelevamp** [comment]
cheers yep they were already plugged in & ready to go before opening hydrogen.

my cheap seat thoughts: this may have been a bug with neither midi engine loaded up with the initial config. it wasn't originally prompting me with the 'this will require restarting the engine' message when i selected a new midi engine (jack or portmidi).

now that it does prompt me with that dialog, i click OK & it disappears. i then revisit the options/preferences/MIDI system tab and it can see my midi devices.

either way thanks very much for ya attention its appreciated. hydrogen is an awesome program.
