### ISSUE TITLE
hydrogen does'nt make one jack output per instrument since  0.9.6 

### ISSUE THREAD

**Issue by Houston4444** [hydrogen-music/hydrogen#200]
since last version, when I start Hydrogen , there is only the general output in jack. The option "create one output per instrument" is still checked, but I need to restart the output to get all my needed ports !

Sorry for my english!

houston
Kubuntu 14.04 (64bits) + KXstudio repos

**Comment by 7W33D** [comment]
Sorry for revisiting a closed issue.
I'm experiencing this exact issue in 0.9.6.1 (Jan 6 2015) from KxStudio repos.
Is this supposed to be fixed.  Does KxStudio build need updated?
Thanks for any help with this.

**Comment by 7W33D** [comment]
forgot to mention,  most recent kxstudio iso and repos.
thanks

**Comment by 7W33D** [comment]
Sorry for revisiting a closed issue.
I'm experiencing this exact issue in 0.9.6.1 (from Jan 6 2015) from most recent KxStudio repos.
Is this supposed to be fixed. Does KxStudio build need updated?
Thanks for any help with this.

**Comment by mauser** [comment]
Hi @7W33D,

sorry for the late reply.. The bug has been fixed in the 0.9.7 branch, but has not been back-ported to 0.9.6.

**Comment by 7W33D** [comment]
On 10/04/2015 11:59 AM, Sebastian Moors wrote:
>
> Hi @7W33D <https://github.com/7W33D>,
>
> sorry for the late reply.. The bug has been fixed in the 0.9.7 branch, 
> but has not been back-ported to 0.9.6.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hydrogen-music/hydrogen/issues/200#issuecomment-145362026>.
>
Thanks for letting me know about the fix!
Just built 0.9.7 and per-inst outs works great!
Thank you!

-- 
www.the-temp-agency.com/lollipop-factory
