### ISSUE TITLE
Pattern Editor in Piano input mode; not able to create a note

### ISSUE THREAD

**Issue by abemarsh** [hydrogen-music/hydrogen#2017]
Hydrogen version *          : 1.2.0~beta1+dfsg-1build4
Operating system + version  : Ubuntu Studio 24.04 LTS
[hydrogen.log](https://github.com/user-attachments/files/16664360/hydrogen.log)

Audio driver + version      :  

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

< describe your issue or feature request here ** >
I teach a music technology class and on every laptop recently installed with Ubuntu Studio 24.04, Hydrogen won't allow us to write pitched notes for the drums on the piano roll input. When I click on a higher or lower note in Piano Roll mode, the selected sample plays correctly but no note/ "black dot" appears. 
Looking in the log I see lots of entries that say PianoRollEditor::addOrdDeleteNoteAction Instrument [0] could not be found... I'm attaching the log. 
[hydrogen.log](https://github.com/user-attachments/files/16664400/hydrogen.log)

It also looks like some drumkits are corrupt and if we drag a sample from, for example, Electric Empire, the sample has a yellow warning icon and won't play. I'm not sure if that's related to the issue. 

This is a fresh install on about 20 computers, and the piano roll input mode is a beloved function that I've taught for 12 years. Thanks for any help you can provide!

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info > About' in the GUI or 'hydrogen -v' on the command line. Also, please indicate how you installed it, e.g. binary downloaded from SourceForge/Github, brew (macOS), OS repo (Linux), flathub (Linux), AppImage (Linux).
** if you are reporting a bug, please describe how the bug can be reproduced and add the corresponding [log messages](https://github.com/hydrogen-music/hydrogen/wiki/Accessing-log-messages-of-Hydrogen)

**Comment by theGreatWhiteShark** [comment]
Hey @abemarsh ,

Ubuntu Studio does, unfortunately, ship an outdated beta version (see #2010). In the latest 1.2.3 version this should already be fixed.

Nowadays we also provide an [AppImage](https://github.com/hydrogen-music/hydrogen/releases/download/1.2.3/Hydrogen-1.2.3-x86_64.AppImage) your can just (tell your student's to) download, make it executable, and just run it without installation. So, there should be no need to compile the code 20 times from source.

> It also looks like some drumkits are corrupt and if we drag a sample from, for example, Electric Empire, the sample has a yellow warning icon and won't play. I'm not sure if that's related to the issue.

Does this still occur in the 1.2.3 release?

**Comment by abemarsh** [comment]
OMG, Thank you very much! The AppImage indeed fixed the problem. Too bad about the Ubuntu Studio release. 

I'll do exactly that with my students. Appreciate it!
