### ISSUE TITLE
hydrogen as slave to qtractor results in loss of first beat

### ISSUE THREAD

**Issue by spectromas** [hydrogen-music/hydrogen#202]
I first reported this as a qtractor issue but I have since tried with other instruments and I don't get the same problem so it does seem to be an issue with Hydrogen. 

Here are the steps: 

1) open qtractor and hydrogen, hydrogen as a slave
2) create midi track in qtractor with a midi clip playing a hit every beat 
3)  connect midi output/bus to hydrogen and loop the midi clip in qtractor

what I expect: the loop to play and all beats to be heard every time it loops
what happens: it loops but every time it gets to the first beat there is silence, the first hit gets missed

I've tried with alsa midi and jackmidi and the same thing happens with both. Strangely I can't replicate the issue with Ardour, which is why I thought it was a qtractor issue at first. There also seems to be a problem with hydrogen picking up the bpm of the jack transport but maybe that is another issue. 

I am using the latest git version but I have experienced this is previous stable versions as well.

**Comment by thijz** [comment]
hi spectromas
a number of jack-transport related fixes have been added in the xjjx branch (https://github.com/xjjx/hydrogen) 
can you retest using that branch ?

grtz
Thijs

**Comment by thijz** [comment]
hi spectromas
can you please retest on the xjjx branch (see previous comment)

grtz
Thijs

**Comment by xjjx** [comment]
few days ago my branch and master has been synchronized, so you can just pull latest master branch.

**Comment by spectromas** [comment]
Sorry for the late reply. Unfortunately it doesn't seem to have fixed it for me, it is still missing the first beat when the loop goes back to the start each time. If you're not able to replicate it then maybe it is something on my end?

**Comment by thijz** [comment]
hi spectromas
can you please retest (again) on the main branch ?
thanks !

grtz
Thijs

**Comment by spectromas** [comment]
Hi thijz, sorry for the delay. I'm having some trouble building hydrogen at the moment: 

    cmake -DCMAKE_INSTALL_PREFIX=/opt/hydrogen .. 
    -- Checking SSCANF useability - TRUE
    -- Checking RTCLOCK useability - TRUE
    -- Checking for module 'LADSPA'
    --   235 plugins found.
    -- checking for module 'oss'
    --   package 'oss' not found
    -- Could NOT find OSS (missing:  OSS_LIBRARIES) 
    -- checking for module 'portaudio-2.0'
    --   package 'portaudio-2.0' not found
    -- Could NOT find PORTAUDIO (missing:  PORTAUDIO_LIBRARIES PORTAUDIO_INCLUDE_DIR) 
    -- checking for module 'portmidi'
    --   package 'portmidi' not found
    -- Could NOT find PORTMIDI (missing:  PORTMIDI_LIBRARIES PORTMIDI_INCLUDE_DIR) 
    -- checking for module 'pulseaudio'
    --   package 'pulseaudio' not found
    -- Could NOT find PULSEAUDIO (missing:  PULSEAUDIO_LIBRARIES PULSEAUDIO_INCLUDE_DIR) 
    -- checking for module 'lash-1.0'
    --   package 'lash-1.0' not found
    -- Could NOT find LASH (missing:  LASH_LIBRARIES LASH_INCLUDE_DIR) 
    -- checking for module 'cppunit'
    --   package 'cppunit' not found
    -- Could NOT find CPPUNIT (missing:  CPPUNIT_LIBRARIES CPPUNIT_INCLUDE_DIR) 
    qmake: could not find a Qt installation of ''
    CMake Error at /usr/share/cmake/Modules/FindQt4.cmake:1326 (message):
     Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
    Call Stack (most recent call first):
      CMakeLists.txt:225 (FIND_PACKAGE)

Am I missing a QT package?

**Comment by mauser** [comment]
This should be fixed with #678 (and Hydrogen 1.0), so i'm closing this issue.
