### ISSUE TITLE
MP3 file support?

### ISSUE THREAD

**Issue by 7z3m** [hydrogen-music/hydrogen#2023]
Hydrogen version *          : 1.2.2
Operating system + version  : gentoo linux
Audio driver + version      : alsa

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

mp3 files not showing, i only get empty folders when i look for drumkit after clicking on import from the menu. I enabled mp3 and mpgeg use flags. I added the drumkit to /usr/share/hydrogen/data/drumkits and to the home folder hydrogen/data/drumkits and its not showing either.

log messages show (E)Filesystem: <name of drumkit> is not usable

i compiled hydrogen from the official gentoo repo.

**Comment by theGreatWhiteShark** [comment]
Hey @7z3m ,

Currently Hydrogen does only support MP3 encoded audio due to an [upstream limitation](http://www.mega-nerd.com/libsndfile/FAQ.html#Q020). But it should be feasible since the corresponding patents expired.

**Comment by 7z3m** [comment]
you mean currently it does not* ? is there an update in the works?

**Comment by theGreatWhiteShark** [comment]
> you mean currently it does not* ? 

Let's say it does not work properly yet.

In case your system ships `libsndfile` >= v1.1 (as Gentoo does) the library we use to load sample files did already "healed" itself and Hydrogen is able to load and play MP3 samples. But filters in file dialogs have not been adopt to allow MP3 files yet. You have to manually edit the corresponding `.h2song` and `drumkit.xml` file to include them.

> is there an update in the works?

Hmm.. Maybe I'm missing something but this seems like a fairly easy patch. I'll look into it soon.

**Comment by 7z3m** [comment]
that would be great, maybe post on here the progress so i can get notified? i can give u a lot of mp3 drum kits as a thank you ;)

**Comment by theGreatWhiteShark** [comment]
> that would be great, maybe post on here the progress so i can get notified? 

Sure

> i can give u a lot of mp3 drum kits as a thank you ;)

Awesome :)

**Comment by 7z3m** [comment]
im gonna post it here before u close this issue.

i put the sounds i use in the making of each track on my website, its hosted on github.

github.com/kingillmusic/website/static/mp3

www.kingillmusic.com (click on the right side of the track, the arrow pointing down)

**Comment by theGreatWhiteShark** [comment]
> i put the sounds i use in the making of each track on my website, its hosted on github.
>
> github.com/kingillmusic/website/static/mp3
>
> [www.kingillmusic.com](http://www.kingillmusic.com/) (click on the right side of the track, the arrow pointing down)

Awesome! Nice beats! Thanks for sharing.

**Comment by theGreatWhiteShark** [comment]
Hey @7z3m ,

Could you check whether MP3 support works properly in [this version](https://ci.appveyor.com/api/buildjobs/4rp4iiwjcp9m62c8/artifacts/Hydrogen-1.2.3-310-g1a9d8b010-x86_64.AppImage) of Hydrogen?

**Comment by 7z3m** [comment]
its giving me "no such file or directory" when in try to run the appimage. i have fuse enabled in kernel, i compiled libfuse through portage, and i have hydrogen compiled through portage and working just fine, so i don't think its a dependency issue.

**Comment by theGreatWhiteShark** [comment]
Hmm. Maybe this one helps https://wiki.gentoo.org/wiki/AppImage.

But since you already compiled Hydrogen yourself: the AppImage corresponds to the code in branch `phil-fix-libsndfile-additional-formats-2023-artifacts`. You could also compile it from there.

**Comment by theGreatWhiteShark** [comment]
Implemented in #2034 . If anything does not work as expected, please feel free to reopen this issue
