### ISSUE TITLE
OSX libarchive Linker error

### ISSUE THREAD

**Issue by AndersenTobias** [hydrogen-music/hydrogen#206]
After exporting `LIBRARY_PATH=/usr/local/lib/` (for a Homebrew version of `libsndfile`) and adding these lines to `CMakeLists.txt`:

```
set(LIBARCHIVE_INCLUDE_DIR "/usr/local/opt/libarchive/lib")
include_directories(/usr/local/opt/libarchive/include,/usr/local/include)
target_link_libraries(${PROGRAM_NAME} /usr/local/lib/libsndfile.a)
```

I get this linker error:

```
Linking CXX executable h2cli.app/Contents/MacOS/h2cli
ld: warning: directory not found for option '-L/opt/local/lib'
Undefined symbols for architecture x86_64:
  "_archive_read_free", referenced from:
      H2Core::Drumkit::install(QString const&) in libhydrogen-core-0.9.7.a(drumkit.cpp.o)
  "_archive_read_support_filter_all", referenced from:
      H2Core::Drumkit::install(QString const&) in libhydrogen-core-0.9.7.a(drumkit.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/cli/h2cli.app/Contents/MacOS/h2cli] Error 1
make[1]: *** [src/cli/CMakeFiles/h2cli.dir/all] Error 2
make: *** [all] Error 2
```

Anyone knows how to fix this?

**Comment by jdekozak** [comment]
Hi @mauser @jeremyz 

Starting from this commit https://github.com/hydrogen-music/hydrogen/commit/a1e10bcd7282c5e38e2c21a63083d16673538240 the Travis CI build for MacOS is failing with the above mentioned error.

Regards,

**Comment by jeremyz** [comment]
Hi @mauser can you help me with that ???
https://travis-ci.org/hydrogen-music/hydrogen/jobs/261417839

**Comment by elpescado** [comment]
It looks like cmake is linking to system version of libarchive, not the one from homebrew.

BTW, I run `brew link libarchive` to make libarchive available in /usr/local (opposed to /usr/local/Cellar/wehatever) on my mac.

**Comment by mauser** [comment]
Hi everyone,
sorry for the delay, i was also in holiday mode in the last week  :) 

@jeremyz: At the moment i can't help with debugging the OS X Build since my Macbook is now outdated and does not receive any new OS updates, so it is not possible to use HomeBrew anymore to install software like cmake. 

Currently @elpescado is providing the mac binaries at the moment (thanks for that!!). I can only agree with his statement that cmake now picks up the wrong location of the libarchive libraries. libarchive is pre-installed on Macs, but in an older API version then the version of libarchive which comes via HomeBrew or MacPorts (those are third-party package managers). The problem seems to be that cmake picks up the header of one version and the libs of the other. My half-knowledge of cmake is not good enough to judge whats going on exactly, but maybe @jeremyz has an idea how to spot the difference with some cmake output / environt variables from @elpescado ?

**Comment by elpescado** [comment]
BTW it would be nice to see actual invocation of commands that failed.

**Comment by jeremyz** [comment]
Hi,
thanks, I fully undersand the issue now.
@elpescado can you provide me with a diff of build/CMakeCache.txt between a successfull and a HEAD build ?
there should be something easy to undersand and fix with the LIBARCHIVE_ variables.

**Comment by elpescado** [comment]
Hi, here is my CMakeCache.txt from revision gfb64b7f7: https://gist.github.com/elpescado/da0fd01ad77c2a8d3a1a775b58fa049f

After pulling (note it builds fine):
https://gist.github.com/elpescado/82b5c5771369b3447d8507e4dd302cef

My build procedure:
```
mkdir build
cd build
QTDIR=/usr/local/Cellar/qt5/5.6.1-1/ CMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.6.1-1/ cmake .. -GNinja
ninja
```

**Comment by jeremyz** [comment]
Thanks,
what I see is that at rev fb64b7f7
LIBARCHIVE_INCLUDE_DIR:PATH=/usr/local/Cellar/libarchive/3.2.1/include
LIBARCHIVE_LIBRARIES:FILEPATH=/usr/local/Cellar/libarchive/3.2.1/lib/libarchive.dylib
where used in src/core/CMakeLists.txt

at rev 9c99b935
LIBARCHIVE_INCLUDE_DIRS:INTERNAL=/usr/local/Cellar/libarchive/3.2.1/include
LIBARCHIVE_LIBRARIES:INTERNAL=archive
are used.

which might lead to a linking to system libarchive, not corresponding to 3.2.1 header.
that's what happens https://travis-ci.org/hydrogen-music/hydrogen/builds/262287395

**Comment by elpescado** [comment]
Couple notes about my setup that might matter here. I have libarchive linked (`brew link libarchive`) in Homebrew. I have also symlink `/opt/local` pointing to `/usr/local` (Homebrew dir).

In this invocation:

`/Applications/Xcode.app/Contents/Developer/usr/bin/g++    -O0 -std=gnu++11 -g  -arch x86_64 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/tests.dir/adsr_test.cpp.o CMakeFiles/tests.dir/automation_path_serializer_test.cpp.o CMakeFiles/tests.dir/automation_path_test.cpp.o CMakeFiles/tests.dir/instrument_list_test.cpp.o CMakeFiles/tests.dir/main.cpp.o CMakeFiles/tests.dir/midi_note_test.cpp.o CMakeFiles/tests.dir/note_test.cpp.o CMakeFiles/tests.dir/pattern_test.cpp.o CMakeFiles/tests.dir/rubberband.cpp.o CMakeFiles/tests.dir/xml_test.cpp.o  -o tests  -L/opt/local/lib  ../core/libhydrogen-core-1.0.0.a -lcppunit -larchive -lsndfile -ljack -lpthread -framework AudioUnit -framework CoreServices -framework coreaudio -framework coremidi -lpulse /usr/lib/libz.dylib /usr/local/opt/qt/lib/QtXml.framework/QtXml /usr/local/opt/qt/lib/QtXmlPatterns.framework/QtXmlPatterns /usr/local/opt/qt/lib/QtNetwork.framework/QtNetwork /usr/local/opt/qt/lib/QtCore.framework/QtCore -Wl,-rpath,/opt/local/lib `
there's no `-L` flag corresponding to `libarchive` installation directory.

**Comment by elpescado** [comment]
BTW. libarchive is special as it is not linked by default by Homebrew. Other libraries might also exhibit this behavior when not linked to `/usr/local`.

**Comment by jeremyz** [comment]
Hi,
thanks for your input, I think this is over now,
feel free to reopen it if not
9557d424d3b0be5447d5935a4c64997
