### ISSUE TITLE
Sound Blaster Audigy Fx v2 Driver Issues

### ISSUE THREAD

**Issue by gjberg74** [hydrogen-music/hydrogen#2074]
Hydrogen version *          :1.2.3
Operating system + version  : WIn 10 64bit
Audio driver + version      : Sound Blaster Audigy Fx v2

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Software does not recognize my Sound Blaster Audigy Fx v2 driver.
![Hydrogen](https://github.com/user-attachments/assets/d84fbbd4-4ad2-4f6a-83a2-ee470df6c400)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info > About' in the GUI or 'hydrogen -v' on the command line. Also, please indicate how you installed it, e.g. binary downloaded from SourceForge/Github, brew (macOS), OS repo (Linux), flathub (Linux), AppImage (Linux).
** if you are reporting a bug, please describe how the bug can be reproduced and add the corresponding [log messages](https://github.com/hydrogen-music/hydrogen/wiki/Accessing-log-messages-of-Hydrogen)

**Comment by gjberg74** [comment]
I now get this when I start the app:

**Comment by theGreatWhiteShark** [comment]
> I now get this when I start the app:

You probably did try to add some attachment to the response main, right? Github does not put it in the resulting post. Could you upload it the to platform and thread directly?

**Comment by gjberg74** [comment]
I got the driver to work somehow, but the "sounds" are all messed up in the app, but the audio is fine when I export to WAV.
The drum sounds almost sound like ringing bells. no matter what drum piece.

**Comment by theGreatWhiteShark** [comment]
Hey @gjberg74 ,  any luck trying other parameter sets?

**Comment by gjberg74** [comment]
Sorry for the late delay.
Don’t know what I did, but I got it working again.
Thank you for all your assistance.

Greg
