### ISSUE TITLE
Hue slider is incorrect

### ISSUE THREAD

**Issue by autumnull** [hydrogen-music/hydrogen#2081]
Hydrogen version *          : 1.2.4
Operating system + version  : Arch Linux 6.10.2-rt14-arch1-3-rt
Audio driver + version      : unrelated

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The hue slider in the theme menu is programmed wrong: it goes from red through green through blue but not back to red, so you can't pick any magenta-like colors and it doesn't differentiate between blue and purple colors.

**Comment by theGreatWhiteShark** [comment]
Hey @autumnull ,

Nice catch! Could you check whether #2082 fixes your issue?

**Comment by autumnull** [comment]
Thanks pal I can't actually build the program very easily but I'm sure it does fix it, you seem to know what you're doing. As long as it goes red, yellow, green, cyan, blue, magenta, red, then you're all good

**Comment by theGreatWhiteShark** [comment]
Closed with #2082
