### ISSUE TITLE
Segfault when starting Hydrogen with "create per-instrument outputs" checked

### ISSUE THREAD

**Issue by rock-hopper** [hydrogen-music/hydrogen#211]
The latest code compiles and runs in KXStudio 14.04 but after checking "create per-instrument outputs" Hydrogen segfaults when next launched.

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff7b68ee0 in H2Core::Song::get_component(int) () from /usr/lib/libhydrogen-core-0.9.7.so

I only tested the code in the bugfix-200 branch on AVLinux (where no issues arose) so I don't know if this bug was present then or if it appeared after the merge with the master branch.

**Comment by mauser** [comment]
Hi! The bugfix from @blablack is now merged (thanks a lot!!!). I'll leave this ticket open for your comment about the order of the instrument names. Has this changed from an 0.9.6 (final) to 0.9.7 (current version) or is this an effect of the latest commit?

**Comment by rock-hopper** [comment]
I think the ordering of the instrument names is the result of the latest commit, I've been using 0.9.7 for a while and haven't seen that happen until now.

**Comment by thijz** [comment]
retested on 0.9.6-beta2-371-gdebffb8 : OK
closing this ticket
