### ISSUE TITLE
separate gain per bank

### ISSUE THREAD

**Issue by funkmuscle** [hydrogen-music/hydrogen#213]
Hey, I like the idea of multi-banks per instrument. The issue is that the way it is now, the bank gain is share.
for example, 2 instruments, kick and snare. I create the main(direct) kick and wanted to add say a reverb layer and the same for snare.
when I create the bank for the kick reverb, the bank shows in the snare also and now they're sharing the same gain..
can each instrument have it's own bank and not shared so that way we can mix and nice blend for each instrument?
thanx
funkmuscle(Harv)

**Comment by funkmuscle** [comment]
did you say I could do a pull now?

**Comment by funkmuscle** [comment]
hey, awesome, the crashing at launch is fixed. The multi-bank instrument is
working kind of.
I started with kick, snare and HH closed, foot pedal but when I tried to
create the opened HH, I can see the sample of the instrument but nothing in
the layer and no sound.

**Comment by thijz** [comment]
hi funkmuscle
can you retest this and report back ?
thnx

**Comment by funkmuscle** [comment]
I just did and it works amazingly now..

thanx guys

Harv
