### ISSUE TITLE
Cannot export at 88200 Hz

### ISSUE THREAD

**Issue by Ghaydn** [hydrogen-music/hydrogen#216]
Hydrogen-git (0.9.6- [Sep 30 2013]) allows to export at samplerates: 22050, 44100, 48000, 96000, 192000. Where is 88200?

**Comment by xjjx** [comment]
It's only not presented in gui, but you can use h2cli for export song. I added it to the gui in my repo. Pull request is on the way.

**Comment by thijz** [comment]
tested 88200 export : works OK

**Comment by Ghaydn** [comment]
Thank you!
