### ISSUE TITLE
hydrogen Multi Audio output

### ISSUE THREAD

**Issue by Reaper10** [hydrogen-music/hydrogen#221]
Hydrogen could use Multi audio  output so you can have all the drums on there own track in your daw and you should be ble to put more then one sound on one output if you want to. Ie 

master out all drums
kick out 1
snare out 2
snare drage out 2
snare flame out 2
hi hat closed out 3
hi hat opened out 3
hi hat petal out 3
low tom out 4
low tom flame out 4
and so on.

**Comment by thijz** [comment]
+1
i like this idea

**Comment by Reaper10** [comment]
Thanks:)

**Comment by trebmuh** [comment]
What would be the difference with: Menu ->Tools -> Preferences -> Audio System -> "create pair instrument output" (available when you using the "jack" driver) ?
![hydrogen-preferences](https://cloud.githubusercontent.com/assets/8705846/6584153/9aa19968-c769-11e4-9ce9-93dc6e641480.png)

**Comment by thijz** [comment]
this will create a AUDIO output for each instrument
in jack you will see that hydrogen will have multiple outputs : 1 for snare, 1 for kick, 1 for hihat ...
that way you can route all sounds in to your DAW individually and mix everything in your DAW

this has no impact on MIDI in/out

**Comment by thijz** [comment]
hi Reaper10,
for some reason i assumed that you were talking about MIDI outputs
is this correct ?  or do you mean multiple AUDIO outputs ?

**Comment by Reaper10** [comment]
multiple AUDIO outputs

**Comment by trebmuh** [comment]
So @Reaper10 , I repost my question: what would be the difference with: Menu ->Tools -> Preferences -> Audio System -> "create pair instrument output" (available when you using the "jack" driver) ?

**Comment by mauser** [comment]
I'm closing this, multiple audio outputs are possible with jackd.
