### ISSUE TITLE
playlist editor : load playlist doesnt work

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#222]
on the main branch (0.9.6-beta2-371-gdebffb8) and also the xjjx branch (0.9.6-beta2-271-g7c7206b)

how to reproduce : 
- open hydrogen, create a new song
- save song
- open playlist editor, add the song you just saved to the playlist
- save the playlist

now open the playlist you just saved > this doesnt work, and terminal shows this : 
(E) PlaylistDialog::loadList Error loading the playlist

**Comment by thijz** [comment]
just retested using the -p cli option to load a playlist > same result : playlist does not load

**Comment by xjjx** [comment]
I sent patch for this in October 2014 to the mailing lists. I didn't want apply this to my repo then , cause I was in the middle of battle with JackTransport.

**Comment by xjjx** [comment]
Please confirm is this works for you.

**Comment by thijz** [comment]
just pulled the fix, build hydrogen and importing playlists works again :-)
thanks !!
could you create a pull request for the main branch ?

**Comment by xjjx** [comment]
Done ;-)

**Comment by mauser** [comment]
Thijs, can you conform if this works now for you with the master branch?

**Comment by thijz** [comment]
works OK on the master branch
