### ISSUE TITLE
hydrogen crashed on midi learn

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#224]
when sending midi data from a controller to hydrogen for a knob that is not midi operable hydrogen crashes with this message : 

MidiSenseWidget.cpp:88: void MidiSenseWidget::updateMidi(): Assertion 'action' failed.
Aborted (core dumped)

this is 100% reproducible when trying to learn the filter cutoff knob of an instrument : 
- Shift-rightclick the cutoff knob
- widget appears saying 'this knob is not midi operable'
- press any button or turn a knob on your midi controller
> crash

**Comment by mauser** [comment]
Hi, 

this should be fixed now in the latest version. However, if you're sending a note message, the note value to a midi learn widget, the note parameter seems to be ignored :-/ But this is another bug.

**Comment by thijz** [comment]
retested : closing this ticket
(creating new ticket for note learn issue described above)
