### ISSUE TITLE
Option -s (--song FILE) doesn't work when Hydrogen compiled with NSMSESSION checked

### ISSUE THREAD

**Issue by wkoziej** [hydrogen-music/hydrogen#226]
Hi,
I've compiled latest hydrogen (default configuration) from git repo and hydrogen cannot load songs files from command line (-s option).
I've checked sources and then compiled hydrogen without NSMSESSION. With this configuration loading files from command line works fine.

Is this correct behavior? 

BTW 
Great software :).

**Comment by mauser** [comment]
Hi! 

Sorry for the inconvenience. I hope that it works now!

**Comment by wkoziej** [comment]
Yes, It works. Thanks!
