### ISSUE TITLE
Post-fader outputs don't work

### ISSUE THREAD

**Issue by youkii** [hydrogen-music/hydrogen#227]
Setting up the outputs on post-fader is impossible. Each time it's coming back to the pre-fader setting.

I's related with the language used as the solution is to start Hydrogen from commandline with "LANG=EN hydrogen". See the topic on Hydrogen forum : http://www.hydrogen-music.org/hcms/node/14199

**Comment by thijz** [comment]
hi youkii
can you please retest this with the latest code ?

grtz
Thijs

**Comment by youkii** [comment]
Hi. I tried 5 minutes ago. It works with the latest code from git

Thanks.

**Comment by thijz** [comment]
great :-)
