### ISSUE TITLE
midi learn for midi notes doesnt work

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#229]
when using the Shift+Click method to trigger midi learn for a specific button the note parameter is not saved

how to reproduce : 
- open hydrogen, connect midi keyboard
- Shift+click the Play button on the gui : the 'waiting for midi input' window pops up
- pres any key on your keyboard : the window closes. midi learn is done

expected : 
- the key you just pressed starts playback

what really happens : 
- nothing

this works fine with all other controllers that dons send midi NOTE messages
if you goto Tools - Preferences - Midi system, press the 'record' button and then hit the keyboard the midi learn works just fine

**Comment by mauser** [comment]
Hi Thijs, can you test if this still happens?

**Comment by thijz** [comment]
retested and works ok  :-)
