### ISSUE TITLE
Hydrogen disconnects other audio players from speakers

### ISSUE THREAD

**Issue by cyclonecat5** [hydrogen-music/hydrogen#230]
When I use Hydrogen, it somehow disconnects all other adio systems from sound outputs ie, I cant hear sound if I play a song after I open Hydrogen, even after I have closed Hydrogen. I need to reboot the computer before I can hear sound again

**Comment by mauser** [comment]
Hi! What you're observing is most probably that hydrogen is starting the jack audio server, which is then blocking your soundcard. You can change that behaviour by using a different audio driver in the hydrogen preferences dialog (or kill jackd afterwards..).

**Comment by cyclonecat5** [comment]
Hi Sebastian
Thanks for the tip. I will give it a shot, hopefully I can I figure out how.
Cheers

Date: Wed, 18 Feb 2015 12:51:07 -0800

**Comment by thijz** [comment]
hi cyclonecat5,
can you tell us if you were able to fix the issue ?

in the link below you can see how to configure the audio server : 
http://hydrogen-music.org/hcms/node/5#sect.preferences.audio_tab

grtz
Thijs

**Comment by cyclonecat5** [comment]
Hi Thijs
I went through every possible driver I could find, tried every combination of restarting etc and could not get VLC media player to have sound. I also played around with changing the audio drivers on VLC, still no joy. I did work out a way to play mp3's/mp4's with Hydrogen open and that was by using Audacity to play them.
Thanks for the manual though, I didnt have that with Hydrogen.
Michael

Date: Fri, 20 Feb 2015 03:38:10 -0800

**Comment by thijz** [comment]
does VLC show up in the QjackCtl patchbay ?
IIRC VLC will only expose its outputs to jack when you hit play on VLC

**Comment by cyclonecat5** [comment]
Not sure what you mean by QjackCtl patchbay
I am 100% sure I tried everything while VLC was running but I will double check.

Date: Sat, 21 Feb 2015 09:07:10 -0800

**Comment by thijz** [comment]
sounds like you are not using jack, or are not aware of it
try this : 
while hydrogen is running (and sound is ok) open a terminal, enter 'ps ax | grep jack' and post the output here
also post the output of this command : 'cat .hydrogen/hydrogen.conf | grep audio_driver'

**Comment by thijz** [comment]
closing this since there is no more feedback

**Comment by cyclonecat5** [comment]
Hi
Please accept my apologies, I have not had a chance to look into our last correspondence due to work.
Kind regards
Michael

Date: Sun, 22 Mar 2015 03:40:28 -0700
