### ISSUE TITLE
Stop button behaves like pause (buttons and midi actions) 

### ISSUE THREAD

**Issue by wkoziej** [hydrogen-music/hydrogen#231]
Hi,

I want to use hydrogen as jackd timemaster and play different patterns live and I found following problem: 

In pattern mode STOP button behaves like PLAY/PAUSE button.
Also (in pattern mode)  STOP and PAUSE midi actions (or PLAY/STOP_TOGGLE and PLAY/PAUSE_TOGGLE) behaves like PAUSE action.

What should I do to return playhead to start when working in pattern mode?

It will be great :)

**Comment by thijz** [comment]
hi,
what version are you using, on what OS?
there have been some changes made around this issue

**Comment by wkoziej** [comment]
$ uname -a
Linux lubudu 3.14.31-rt28 #1 SMP PREEMPT RT Sat Feb 14 10:38:04 CET 2015 i686 i686 i686 GNU/Linux

hydrogen was built a few days ago.

now, I'm testing version 0.9.7-'cc40c30' and it works :). 0.9.7-'cc40c30'
I'll be watching.

I think this issue is closed for now.

Thanks
