### ISSUE TITLE
cant control master Mute via MIDI

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#233]
- shift-click on the master mute button in the mixer
- hit a key in your midi controller
- midi learn done

expected :  hitting the same key on the midi controller toggles the mute on/off
what really happens : nothing

when i look at the learned midi bindings (tools - preferences - midi tab) the mute_toggle function is linked to the midi key, but it has no effect

tried with CC and NOTE

**Comment by mauser** [comment]
Actually the sound gets muted, but the button does not show the "muted" state.. so it kind of works, but the gui is not updated..

**Comment by mauser** [comment]
Hi,

this should work now...

**Comment by trebmuh** [comment]
@mauser : just tested from a fresh rebuild (https://github.com/hydrogen-music/hydrogen/commit/93551fc12e94d2d6830a0c33ad1bc6bcabb64b17) and it does work as expected, ie: the MUTE button is turning red when muted and back to blue when non-muted.

Added to: https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-0.9.7#all-platforms
