### ISSUE TITLE
hydrogen crashes when you edit a new instrument layer

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#236]
- goto Instruments - Clear all
- select 'instrument 1' in the pattern editor
- goto Layers > Load layer
- i select a mono wav file (containing 25sec of silence - created with audacity, 16bit WAV)
- now click edit layer
- in the sample editor hit Play
> hydrogen crashes

i did the test in debug mode also, but the only output i get is 'core dumped'

**Comment by pvint** [comment]
Just thought I'd try this to see if I got a core I could look at but it worked fine here. (Just tested with a randomly selected stereo WAV). Just for fun tried making a silent wav file in audacity the same way - no crash.

**Comment by thijz** [comment]
i just tried it again (on your fork btw :-) and i can still crash hydrogen

i uploaded the wav to my drive:
https://drive.google.com/file/d/0B1eVS8jzLhY9Zkt4N3g5V244X2c/view?usp=sharing

this is what mediainfo has to say about the file : 

...tvanseve@tvanseve-ThinkPad-W530:~/Desktop$ mediainfo silence25sec.wav 
General
Complete name                            : silence25sec.wav
Format                                   : Wave
File size                                : 2.33 MiB
Duration                                 : 27s 723ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 706 Kbps

Audio
ID                                       : 0
Format                                   : PCM
Format settings, Endianness              : Little
Codec ID                                 : 1
Duration                                 : 27s 723ms
Bit rate mode                            : Constant
Bit rate                                 : 705.6 Kbps
Channel(s)                               : 1 channel
Sampling rate                            : 44.1 KHz
Bit depth                                : 16 bits
Stream size                              : 2.33 MiB (100%)...

**Comment by blablack** [comment]
Issue happens in the SampleEditor class on the lines that move the playhead.

```
m_pMainSampleWaveDisplay->paintLocatorEvent( m_pPositionsRulerPath[frame] / m_divider + 25 , true);
m_pSampleAdjustView->setDetailSamplePosition( m_pPositionsRulerPath[frame], m_pZoomfactor , 0);
```

Somehow for that 25 sec empty file, this array m_pPositionsRulerPath doesn't seem to be setup properly because this m_pPositionsRulerPath[frame] is what crashes Hydrogen...

More investigation to follow, except if someone beats me to it :)

**Comment by blablack** [comment]
Further investigation - if in the GUI you manually set Start, Loop and End to their default value then you cannot reproduce the issue.

I think it's still lead to a problem with m_pPositionsRulerPath because changing these values changes how the array is setup in the method createPositionsRulerPath.

**Comment by blablack** [comment]
I investigated more, but cannot find a  fix to this problem:
- The crash happens in the method updateMainsamplePositionRuler, when it tries to access m_pPositionsRulerPath[frame]
- Setting the End spinbox to the exact same value it is initially (1222594 in the example sample sent by @thijz) is a workaround to this problem
- As far as I can see, m_pPositionsRulerPath is set properly in the method createPositionsRulerPath
- As far as I can see, __loops.end_frame, is set to what it's supposed to be for that sample, I cannot find any properties set to the wrong reason

If someone wants to have another look at this :)

**Comment by thijz** [comment]
just retested on the main branch (4c9c69d  jul 29 2015) and the problem is still there
however, it sometimes works, but 75% of the time it crashes

**Comment by mauser** [comment]
Hi everyone,

i might have fiixed this one. Could someone re-test the issue?

**Comment by thijz** [comment]
retested with 0.9.7-'9b60629' [oct 22 2015] : problem fixed
