### ISSUE TITLE
man page - update needed

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#237]
The CLI command "man hydrogen" is talking about hydrogen 0.9.4 on a Debian Jessie standard installation (ie: the official debian package). I'm guestimating here, that the hydrogen dev team is providing and shipping the manpage.

**Comment by mauser** [comment]
No, the man-page was generated by debian, have a look at their changelog (http://metadata.ftp-master.debian.org/changelogs//main/h/hydrogen/hydrogen_0.9.6.1-1_changelog, section 0.9.4-3):

* Install manpage generated using help2man (and ship with source - for
    some reason it fails to work as part of normal builds). Update TODO.

So they generated the man page once and took the output of 'hydrogen --help' as an input.

**Comment by mauser** [comment]
I'm closing this issue since we can't fix this.. you could contact the debian multimedia team about this!
