### ISSUE TITLE
Song mode does not show the corresponding patterns automatically as they are being played

### ISSUE THREAD

**Issue by Palmirez** [hydrogen-music/hydrogen#239]
The pattern screen gets stuck in whatever pattern is last chosen, the song does sound correctly when pressing play, but the pattern screen no longer switches from one pattern to the next as they are being played; instead, it remains frozen in the pattern last selected by the user. To show a different pattern, the user must select it manually. The playhead shows up in the pattern screen only when the selected pattern happens to be the one that is being played, and the rest of the time disappears.

This problem appears suddenly, after many days of Hydrogen working properly, and once it appears it continues happening even after a Hydrogen reinstall or even reinstalling the distro.

**Comment by thijz** [comment]
i dindnt know that hydrogen ever did that ?
i have never seen the pattern editor jump to another pattern while playing a song

**Comment by ninuzzo** [comment]
Why do you think this is not an important feature? It would be very useful for someone who is learning to play another instrument (e.g. a guitar) "a tempo", while the drum is played by hydrogen.
