### ISSUE TITLE
Error on website: Drumkits link

### ISSUE THREAD

**Issue by pvint** [hydrogen-music/hydrogen#240]
On http://hydrogen-music.org/hcms/node/16 the link at "All officical Hydrogen drumkits are hosted on SourceForge. " for drumkits takes the user to sourceforge and starts downloading hydrogen-0.8.x.

Oops!

Correct URL should be http://sourceforge.net/projects/hydrogen/files/Sound%20Libraries/Main%20sound%20libraries/

Cheers

**Comment by wolkstein** [comment]
thx,
fixed :)
