### ISSUE TITLE
what is the migration path for 0.9.6 > 0.9.7

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#241]
i have been going back and forth between 0.9.6 and 0.9.7 betas
frequently i bump into an 'incompatibility' between the 2 versions : the drumkits i have installed in 0.9.6 are gone in 0.9.7
this is due to the new location for drumkits (i think) and is not a big deal, but it will confuse a lot of users
i'm not 100% sure but i think this is only related to drumkit location, and does not affect song or pattern file locations (?)

to avoid lots of frustration and questions on the forum i think we must add some sort of wizard when a user runs 0.9.7 for the first time

eg "this is the first time you run 0.9.7, do you want to import the drumkits from the previous hydrogen version?"

> this could copy the installed drumkits from the old > new location

a second issue is that song that have been made in 0.9.6 will not play in 0.9.7 because the drumkit location has changed

> can this also be fixed using a 'first run' wizard ?

important remark : once a user converts its songs to '0.9.7 format' he wont be able to go back to 0.9.6, right ?
IMHO we need to be very careful about all this ...

ideas ?

**Comment by mauser** [comment]
Hi Thijs! 
I'm not aware of a new location for drumkits.. Where are your drumkits in 0.9.6 and where in 0.9.7?

**Comment by thijz** [comment]
hi Sebastian
you are probably right, but how come that the system drumkits that are installed in 0.9.6 are not there any more when i run 0.9.7 ?

grtz
thijs

**Comment by mauser** [comment]
Thats strange, indeed.. Could you paste the log somewhere?

**Comment by mauser** [comment]
About the song format and "i have been going back and forth between 0.9.6 and 0.9.7 betas": As you have already guessed, it is not a good idea :) If you load a 0.9.7 song in 0.9.6 again and save it, you will lose data. 0.9.7 has a different file format (especially for the drumkit components), so opening 0.9.7 songs in 0.9.6 is not supported.

**Comment by thijz** [comment]
suggestion : 
can we add a field in the XML that indicates on what version the song was saved ?

this can then be used in future versions to warn the user when he wants to load a song that was created in an older/newer version of hydrogen : "you are trying to load a song that was saved in version x.x.x but you are running version y.y.y.  This is not supported and might break your song"

i guess that upgrading wont be a problem, but downgrading will

**Comment by mauser** [comment]
Yes, i've talked with Aurelien about this and we also want to provide an "Export drumkit to older versions" functionality. We have to check if this makes also sense for songs.

**Comment by dreaming-augustin** [comment]
Speaking of drumkit migration path, a migration from 0.9.5 to 0.9.6 is lacking and needed.
See:
https://github.com/hydrogen-music/hydrogen/issues/348
