### ISSUE TITLE
Customize standard save paths

### ISSUE THREAD

**Issue by HinzundKunz** [hydrogen-music/hydrogen#243]
I'd like to have hydrogen always save my stuff in a certain path. Right now hydrogen always defaults to ~/.hydrogen/data/... I would like to be able to change that in hydrogen settings.

**Comment by thijz** [comment]
+1

**Comment by blablack** [comment]
+1

**Comment by trebmuh** [comment]
+1
For information : check https://github.com/hydrogen-music/hydrogen/pull/353

**Comment by theGreatWhiteShark** [comment]
Implemented in #1399

Starting with v1.2 Hydrogen will remember the last used path.
