### ISSUE TITLE
High memory consumption and samples shortened with drag/drop

### ISSUE THREAD

**Issue by blablack** [hydrogen-music/hydrogen#249]
When drag/dropping samples between drumkits I noticed:
- the memory consumption is very high - if I save the drumkit with the new dragged instruments, closed Hydrogen, reopen and reload the drumkit, the memory is not as high even though it is the same number of instruments loaded.
- the samples when played are cut short. Saving the drumkit/restarting hydrogen/reloading drumkit does fix that as a workaround

**Comment by blablack** [comment]
It looks like the fix in https://github.com/hydrogen-music/hydrogen/issues/235 fixes that problem as well.

**Comment by thijz** [comment]
hi blablack
can you confirm this is fixed ?

**Comment by mauser** [comment]
I've just pushed the fix for #235 to the repository

**Comment by blablack** [comment]
@thijs I'm not experiencing this issue anymore.
