### ISSUE TITLE
Pattern description cannot be saved

### ISSUE THREAD

**Issue by swingnjazz** [hydrogen-music/hydrogen#261]
I'm using Hydrogen 0.9.6-beta3 on Ubuntu 14.04 LTS and I like it very much. In song editor I can enter a pattern description (see attached screenshot). However this is gone after the hydrogen file is saved, closed and re-opened.

In the .h2song file there is no <description> tag or the like in section <pattern> of the <patternList>:

     <patternList>
      <pattern>
       <name>my pattern</name>
       <category>bass practicing</category>
       <size>192</size>
       <noteList>
        <note>
         <position>0</position>
         ...
![pattern_properties](https://cloud.githubusercontent.com/assets/12883802/8149312/4fa22eb8-12bf-11e5-9876-2ad490db4403.png)

**Comment by mauser** [comment]
Hi! 
Thanks for the report, indeed it looks like the pattern description is only respected if you save the pattern via its own context menu (and save it into a seperate h2pattern file..).

**Comment by mauser** [comment]
This problem should be solved now in our git repository..

**Comment by swingnjazz** [comment]
Hi Sebastian,

I would gladly test the fix, but unfortunaely I don't have a build 
environment at hand to build the application from git.

Do you have some links to How-to's or tutorials for me to learn how to 
setup a build and test environment. Help would be much appreciated.

Greetings
Alfred Peters

Am 19.06.2015 um 21:37 schrieb Sebastian Moors:

**Comment by mauser** [comment]
Hi Alfred,

here is a tutorial for linux: https://github.com/hydrogen-music/hydrogen/wiki/Building-Hydrogen-from-source-%28LINUX%29

**Comment by swingnjazz** [comment]
Hi Sebastian, 
I have set up a build environment to test the fix. The tutorial helped me a lot. Thank you for your support.

Your fix works fine, Hydrogen behaves as expected.
Thank's a lot.

Alfred
