### ISSUE TITLE
audio mute <> midi/note mute

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#266]
the mute buttons that currently exist in the hydrogen mixer are 'audio' mute buttons
this means that they work just like the mute button on a hardware mixer
this is ok, but ...

if you want use hydrogen live, and want to be able to switch a specific instrument on/off on the fly (eg in dance music, you will want to mute the kick for 1 bar) you can do this by turning the instrument volume down, or by hitting the mute button
this works, but when you have an instrument like a crash (with a long tail) an 'audio' mute doesnt work well because you can clearly hear when you mute the instrument

therefore it would be nice if we could add a 'midi mute' (or note mute)
the idea is that the samples of an instrument are not triggered while the note-mute is enabled
this way you dont affect the samples that are playing (like the tail of a crash), but you simply prevent the sample from being triggered

does this make sense ?

**Comment by thijz** [comment]
also muting can cause clicks since the audio just gets cut off when you mute

**Comment by mauser** [comment]
Thanks to @ julienmoumne , this feature is now available in the master branch.

**Comment by trebmuh** [comment]
_for the readers: see #706_
