### ISSUE TITLE
hydrogen crashes when auditing a sound after deleting the main bank

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#270]
start hydrogen (using 0.9.7-'4c9c69d' (jul 29 2015)
- select any instrument
- goto the instrument > layers tab
- click on the bank dropdown button
- select 'add' > enter a name > press enter
- click on the bank dropdown button > select the main bank
- click on the bank dropdown button > delete the main bank

- goto the sound library tab
- expand any drumkit (press the [+])
- double-click on a instrument in that click
- now hydrogen crashes with this message : 
Error XSDError in file:///home/tvanseve/.hydrogen/data/drumkits/Roland%20TR-626/drumkit.xml, at line 11, column 17: Element {http://www.hydrogen-music.org/drumkit}instrumentList is not defined in this scope.
Segmentation fault (core dumped)

**Comment by mauser** [comment]
Hi Thijs! 

Could you re-test this?

**Comment by thijz** [comment]
retested on 0.9.7-'4c9c69d'
problem solved  :-)

this also solves an issue where hydrogen crashes when you clear all instruments and drag an instrument from the library to the pattern editor
