### ISSUE TITLE
Empty layer properties after adding a component

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#273]
After adding a new component, some properties of the instrument layer view are not initialised correctly:

![bildschirmfoto vom 2015-08-07 15 47 47](https://cloud.githubusercontent.com/assets/202461/9137106/cd950daa-3d1b-11e5-9d20-2c879e0bbbb8.png)

**Comment by blablack** [comment]
Is the issue that the Bank Volume is set to 1.00 or that the 3 others are set to nothing?

**Comment by blablack** [comment]
Easy fix - patch below :)

```
diff --git a/src/gui/src/InstrumentEditor/InstrumentEditor.cpp b/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
index 39c3f2c..e78b80a 100644
--- a/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
+++ b/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
@@ -999,6 +999,9 @@ void InstrumentEditor::selectLayer( int nLayer )
 			m_pLayerGainRotary->setValue( 1.0 );
 			m_pLayerGainLCD->setText( "" );
 
+			m_pCompoGainRotary->setValue( 1.0 );
+			m_pCompoGainLCD->setText( "" );
+
 			// Layer PITCH
 			m_pLayerPitchCoarseRotary->setValue( 0.0 );
 			m_pLayerPitchFineRotary->setValue( 0.0 );
@@ -1014,6 +1017,9 @@ void InstrumentEditor::selectLayer( int nLayer )
 		m_pLayerGainRotary->setValue( 1.0 );
 		m_pLayerGainLCD->setText( "" );
 
+		m_pCompoGainRotary->setValue( 1.0 );
+		m_pCompoGainLCD->setText( "" );
+
 		// Layer PITCH
 		m_pLayerPitchCoarseRotary->setValue( 0.0 );
 		m_pLayerPitchFineRotary->setValue( 0.0 );
```

**Comment by mauser** [comment]
What i meant in the first place is that the LCDs for pitch, layer gain and fine are empty (after adding a new component). 

But i've already seen that in Hydrogen 0.9.6, this was also the case.. so the "difference" here is that "Bank volume" shows 1.0, while every other LCD is empty.  At the moment i'm not sure what the default should be, but i guess it would make more sense if the other LCDs would also show the current value of their associated controls

**Comment by blablack** [comment]
Ok, the fix I done is the opposite - one a new bank it would be empty.

I checked the code, it's written this way on purpose.

Let me know what you think.

**Comment by mauser** [comment]
Thanks!
