### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#275]
I might be wrong, but the message "No valid song selected!" in src/gui/src/PlaylistEditor/PlaylistDialog.cpp on line 708 does'nt appears to be translatable. I mean I can't find it in https://github.com/hydrogen-music/hydrogen/blob/master/data/i18n/hydrogen.fr.ts neither in the majority of other translation files. That said, it does appears in https://github.com/hydrogen-music/hydrogen/blob/master/data/i18n/hydrogen.gl.ts .

So I'm just wondering if should just add the missing part in the
 ```
<context>
<name>PlaylistDialog</name>
...
```

part ?
Would it then be OK ?

**Comment by mauser** [comment]
Hi trebmuh,
the translation files had to be updated. I've done this now and pushed the change to the github repository. This pushes the changed strings from the source code in the .ts files. If you have such a problem again, you can try run the "updateTranslations" shell script in the data/i18n folder.

**Comment by trebmuh** [comment]
Sweet. I'll be trying to keep this in mind, thanks.
Thanks to this, I've been able to make another update which is in this pull request : https://github.com/trebmuh/hydrogen/commit/d898f687d1884e49dd10ce09b34eb093bfad084f
