### ISSUE TITLE
Windows 10 bugs

### ISSUE THREAD

**Issue by Reaper10** [hydrogen-music/hydrogen#276]
I can't see all of the gui  when in full screen mode or when it's not in full screen.
<img width="521" alt="capture" src="https://cloud.githubusercontent.com/assets/8137561/9151175/47361674-3dbf-11e5-8cc0-ea125cc2f245.PNG">
update
My pc crashed I had get a new one, that fixed it.

I tried open an an old h2 file on  my new pc it just opens as a blank file.

**Comment by mauser** [comment]
Which screen size and resolution are you using?

**Comment by Reaper10** [comment]
My pc crashed I had get a new one, that fixed it.

**Comment by Reaper10** [comment]
I tried open an an old h2 file on  my new pc it just opens as a blank file.

**Comment by mauser** [comment]
Hi @Reaper10,

could you test this again with the new Windows installer?

**Comment by Reaper10** [comment]
I did

**Comment by mikotoiii** [comment]
I haven't been able to replicate with any of the files i have from 0.9.6 Windows to 0.9.7 Windows. There's the issue of the drumkits not loading properly, thus no sound is made when playing rhw song / pattern until you load your drumkit.

I'm thinking the issue might be in your h2 file.

**Comment by thijz** [comment]
@Reaper10 : 
thanks for reporting this, but please dont use 1 ticket to report multiple issues - that's just too confusing for my simple brain ;-)
you retested with the new windows version and the result was the same, or different ?
also, what do you mean with blank, no notes in the song, or no instruments in the drumkit, or something else ?

grtz
Thijs

**Comment by Reaper10** [comment]
I retested with the new windows version and the result was the same, ie no notes in the song.

**Comment by mauser** [comment]
Hi,

could you provide this file somehow to us? Either upload to a filehoster or you could send it via email to me (mauser@smoors.de)

**Comment by Reaper10** [comment]
https://drive.google.com/file/d/0B0Ar66xX6aiRQ0l5RlZha0p3bVE/view?usp=sharing

**Comment by mauser** [comment]
Hi,

i've attached a screenshot of hydrogen after i have opened your file. I can see all the notes in the file. As far as i can see, it looks ok to me.. Could you make a screenshot of your problem? I will try to re-test it again under windows soon, at the moment i'm using the linux version of hydrogen (which should have no differences regarding the loading of songs/pattern.

![emptysong](https://cloud.githubusercontent.com/assets/202461/10125072/00b8763a-6568-11e5-9d7c-07efccdd2223.png)

**Comment by Reaper10** [comment]
![image](https://cloud.githubusercontent.com/assets/8137561/10174156/f054dd82-66ad-11e5-8091-32426792dae6.png)

**Comment by mauser** [comment]
The title of the window is "Untitled song", which means that no song is loaded. Is that the hydrogen window *after* you have tried to load "Dona Dona Distortion.h2song"? Where there any errors when you tried to open the song?

**Comment by Reaper10** [comment]
Yes that's the window after I tried to load the h2 file. No I didn't see any errors.

**Comment by mikotoiii** [comment]
I can do some Windows testing for you if you need mauser, I have both an up to date version that I compiled yesterday, as well as the preview image that we released. I also have a system running Windows 7, and a new test system will have Windows 10 on it later today.

I went to get the h2 file but it is no longer hosted.
