### ISSUE TITLE
Pattern size vs. transport

### ISSUE THREAD

**Issue by blablack** [hydrogen-music/hydrogen#277]
I noticed a behaviour that is quite annoying when syncing Hydrogen with other software.
(Or there is something I don't understand properly in Hydrorgen!)

If you use patterns of different size and put a few of them in the song editor and start the transport from the beginning it will play along nicely. If now you start from bar 4 in the transport, it will start at bar 4 in Hydrogen's song editor which might not be bar 4 in reality as the patterns are of different size.

An example might be clearer:
1. Let's a 4/4 song
2. Let's have a pattern size 16 in Hydrogen (or 2 bars)
3. Let's put 4 of those in the song editor to make 8 bars

If you ask jack transport to play from the beginning by the time the transport indicates it's at bar 2, in Hydrogen we will still be in first block of the song editor as it is of 2 bar length.
If now you ask the jack transport for example to start at bar 2, Hydrogen will make it start at the second block in the song editor but in the configuration described above that's in reality bar 3.

Is this something I don't understand from Hydrogen?
I think it's still weird that the positioning behaviour is different if we start from the beginning or try to start in the middle of the song.

**Comment by thijz** [comment]
i also bumped into that one in the past, very annoying
i think there are several tickets related to this (jack transport in general). i'll see if i can find them

**Comment by xjjx** [comment]
I'm not sure if I understand this correctly but .. Actually in Hydrogen there is no such thing meter. You can't just set 4/4 for whole song. For jack transport it get pattern size and divide it by 4 ;-) If I recall correctly ( need to check later ) - for pattern that is two bar long it set meter to 8/4. Strange , but it works ... mostly ;-)

**Comment by theGreatWhiteShark** [comment]
Well, I think there is not too much we can do about it aside from calling it an unfortunate design decision in hindsight.

There have been some changes in the song editor allowing to show patterns of different length in one column by partially filled grid cells. This at least gives kind of an impression the user might deal with something else than "bars". In addition, I replace the term "bar" by "column" in doc, code, and interface little by little. This does not really solve things but hopefully make it slightly less confusing.
