### ISSUE TITLE
Preview-Sound from wrong component

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#280]
After adding a new, empty component "New component" to an instrument with an already existing component "A",  you can hear the preview-sound of the existing component "A" if the empty area below the component name label ("New component") gets clicked. 

![snapshot1](https://cloud.githubusercontent.com/assets/202461/9366469/e142f8da-46b7-11e5-9f75-60ac10f7936f.png)

**Comment by mauser** [comment]
... just realised that this behaviour might be a feature, since it previews the complete instrument with all its components. @blablack is this intentional?

**Comment by blablack** [comment]
Hmmm, good question :) some part of the port to multi-bank especially sound-previews might have been overlooked.

In the design I had in mind
* if you click (preview) an instrument you should hear all the banks
* if you click (preview) a specific layer you should only hear the layer of the selected bank

Let me know if the behaviour you encounter match.

**Comment by mauser** [comment]
Hi! 
Since the space above the layers could be considered as "belonging to the whole instrument", this certainly makes sense. I'll close this ticket and name it a feature ;-)
