### ISSUE TITLE
mute button mutes sound in sample editor

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#281]
when you have a instrument muted and you go to the sample editor you cant hear the sound
this doesnt really make sense
IMHO the mute state of an instrument should be ignored when working in the sample editor

easy enough to unmute the instrument before you edit it, but still

**Comment by mauser** [comment]
This is only consistent since the complete layer tab does not output sound if the instrument is muted (no layer sound preview for example). I would like to leave it that way and not introduce another special-handling in the code :)
