### ISSUE TITLE
Interment optioons menu

### ISSUE THREAD

**Issue by Reaper10** [hydrogen-music/hydrogen#282]
The right click Interment option menu doesn't show up.

**Comment by mauser** [comment]
Hi,

which version of hydrogen are you running? And on which platform?

**Comment by Reaper10** [comment]
h2 0.9.6 windows 10

**Comment by mauser** [comment]
Could you try this version? It's a new windows preview version which needs some testing right now: http://sourceforge.net/projects/hydrogen/files/Hydrogen/0.9.7%20Binaries/hydrogen-0.9.7-windowsPreview-win32.exe/download

**Comment by Reaper10** [comment]
that works would like to test it?

**Comment by mauser** [comment]
Sure! Could you Check of your other Problems are also fixed?

**Comment by Reaper10** [comment]
an old file opns with no midi in it

**Comment by mauser** [comment]
Could send me that song file to mauser@smoors.de or put it somewhere where i can download it?
