### ISSUE TITLE
a part of the screen is blacked when starting hydrogen

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#297]
Hi, I just build https://github.com/hydrogen-music/hydrogen/commit/eed4d32b7a0313a72836915467c514841c508ea6 on an updated debian Jessie.
When I launch it, I've got a part of the screen which is black as following:
![hydrogen-bug-1](https://cloud.githubusercontent.com/assets/8705846/9971693/1e362d4e-5e5e-11e5-81eb-be2559d919ac.png)
If I change "velocity" to something else, the black part of the window is refreshed. If I then come back to "velocity", everything works as expected as following:
![hydrogen-bug-2](https://cloud.githubusercontent.com/assets/8705846/9971716/4d7e573e-5e5e-11e5-8ae1-b3128f33f3a3.png)
Now, if I'm closing Hydrogen and reopening it, it's back to black.

If you would need some more info, tell me.

**Comment by mikotoiii** [comment]
I am getting the same thing on the Windows port, except instead of black,
it's a graphical rainbow. It also appears to  mess with the scroll bars. It
seems to fix itself on Windows at least when you click on any of the
glictched parts, or scroll the velocity window.

**Comment by trebmuh** [comment]
Thanks for your comment. I can confirm that I don't need to play with velocity, pan or other. Clicking somewhere on the black part is successful to get the normal display.

**Comment by thijz** [comment]
this is something i have also seen on a number of occasions
looks like that part of the gui is not properly initialized ?

**Comment by mauser** [comment]
Hi, 
this is a very old bug in hydrogen.. I had the impression that i fixed it in 0.9.6, but IIRC we had to remove some parts of my fix since it introduces new problems.

**Comment by trebmuh** [comment]
Thanks for commenting guys. It's not a big bug but it's rather minor since it doesn't look to affect anything more. I just wanted to mentioned it as it could look a bit bugish for a new user. Maybe we can put a note on the release version if the bug is still there.

**Comment by thijz** [comment]
fyi: i have this now when i open hydrogen (using code of today : 9ff99e7)

**Comment by trebmuh** [comment]
Hi all, try to build Hydrogen from today's GIT (ie  d7dacfe), this bug is still here, and I can confirm what @thijz said in https://github.com/hydrogen-music/hydrogen/issues/325 : after choosing to click on the 'dont show this any more' option when starting hydrogen, closing once Hydrogen and restarting it, the bug disappears.
Hope that helps.

**Comment by pvint** [comment]
I just had this too! Trying not to get distracted from what I am doing, but after I deleted my preferences file, the next startup it happened.

**Comment by pvint** [comment]
Fixed in 512d903cdd34f22efd7b03eb95286fceac059f83 and pushed to master.

It seems that spawning this dialog after the main app was created caused the corruption. In particular, moving the call to "showDevelWarning() above the following line was the key:
`h2app = new HydrogenApp( this, pSong );`

**Comment by trebmuh** [comment]
I can confirm that it's not here anymore on a fresh rebuild from https://github.com/hydrogen-music/hydrogen/commit/3002477bfc6cb450b988f49d0a8a643a84e9530d
Thanks @pvint !
