### ISSUE TITLE
Issue with importing drumkit (2/2)

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#299]
Following the first importing drumkit issue (https://github.com/hydrogen-music/hydrogen/issues/298 ), I'm reporting here that the drumkit "K-27 Trash Kit" is not downloadable at all. When trying to, the process is going very fast and there is no error message, but the drumkit is staying as "New" on the list, and nothing is written in  ~/.hydrogen/data/drumkits/

**Comment by mauser** [comment]
Hi,

Thanks for reporting this case, it seems that the server which hosts the kit is down. I'll see if this is a temporary issue or if the domain has changed or sth...

**Comment by thijz** [comment]
related to #269 ?

**Comment by thijz** [comment]
i can confirm this : just retested with todays code > issue still present

**Comment by trebmuh** [comment]
@mauser : an user can understand that a 3rd party furnished piece of code can fails because of an unreachable server. The frustration part is that I didn't have any pop up message about that so I was lucky that you answer my question here :) Would it then be possible to add such a pop up windows saying "sorry dude, the server which usually delivers "best-hydrogen-drumkit-ever" looks to be dead at the moment. Please retry later or contact the hydrogen-dev team (or whoever relevant)" ?
Cheers.

**Comment by mauser** [comment]
Yes, it would be helpful if there would be such a message.. i will see if the API that we're using returns meaningful error values. Btw, the error message from QT is directly printed at the hydrogen debug log (you can that in a terminal if you start hydrogen from a terminal).

**Comment by trebmuh** [comment]
Sweat. Let me know if you want some testing about this, I'd be more than happy to help this way since I'm not into coding.

**Comment by mauser** [comment]
Hi,

I rewrote the code now and introduced a new error handling. Please try again.. Btw, if not corrected the entry on the server yet, so that you could test the new error handling.. Will fix that if this is confirmed.

**Comment by trebmuh** [comment]
Sweat, the pop up message works fine as follow:
![capture-hydrogen](https://cloud.githubusercontent.com/assets/8705846/10117205/047adc1e-644f-11e5-99a7-8b119285cf30.png)
that said, after cliking OK on it, I still had this one:
![capture-hydrogen-1](https://cloud.githubusercontent.com/assets/8705846/10117208/128060b8-644f-11e5-92c3-ddb5b8f73f9f.png)
which is confusing for an user perspective: "has it been downloaded or not ?"
Would that be possible to remove the 2nd message in this case scenario ?

**Comment by mauser** [comment]
Thanks for the hint, this is now also fixed.

**Comment by trebmuh** [comment]
Sweat, thanks for fixing this. I just tested it with the 0.9.7beta1 and it's all good now.
I'm closing this issue then.
