### ISSUE TITLE
Hydrogen does not prompt to save playlist when closing application

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#309]
if you create a playlist, but forget to save it, the playlist will be lost since hydrogen does not inform you about this

been there, done that  :-(

it would make more sense if the user was notified about the unsaved playlist + asked if it had to be saved
this can be when you close the playlist editor, but also when closing the application

**Comment by mauser** [comment]
Hi,

have a look at the current git version. At the moment the dialog just gives you the chance to discard the changes or to go back to hydrogen, no direct saving..

**Comment by thijz** [comment]
having a save button in the dialog would indeed be better, but this will already avoid losing the work you do on the playlist  :-)

maybe the texst in the popup can be slightly adapted : 
     The _current_ playlist contains unsaved changes.
     Do you want to discard the changes?
     _(go back to the Playlist editor to save your playlist)_

i wonder if it would be better if this popup was shown as soon as you close the playlist editor ? (instead of waiting to prompt the user until he closes hydrogen ?

i also noticed that you can still loose your playlist if you goto  Playlist - New playlist
i guess that you should also be prompted to save your work first ?
> just like the popup you get when you goto Project - New : 

![image](https://cloud.githubusercontent.com/assets/1384210/10410666/1c53f168-6f49-11e5-81cd-3ab2be5004a9.png)

**Comment by mauser** [comment]
Ok, i'm going to adjust the text and also take "New playlist" into account. 

About showing the popup when you close the editor: The playlist isn't lost then and i guess that some people just want a "temporary playlist", so this could be a bit too much for them.

**Comment by thijz** [comment]
great !
"temp list" > that makes sense

**Comment by mauser** [comment]
Fixed.
