### ISSUE TITLE
Export to older version of Hydrogen

### ISSUE THREAD

**Issue by blablack** [hydrogen-music/hydrogen#310]
With the addition of the Components functionality in Hydrogen 0.9.7, the export functionality needs to be extended to enable exporting to previous version of Hydrogen.

**Comment by blablack** [comment]
@mauser @thijz 
I created this branch for this functionality: https://github.com/blablack/hydrogen/tree/export_to_old

If you guys get the chance, could you review the form:
![screenshot from 2015-10-01 21 56 40](https://cloud.githubusercontent.com/assets/1472461/10233618/82ac1d0a-6887-11e5-8ac5-dd6eb19cbd51.png)

After having a look into how the export works, I saw it basicaly compress whatever it finds in the folder where the drumkit is stored.
The idea I have is that for versions that don't support components, the user can decide which of the components she actually wants to export.

My idea then is that:
1. Hydrogen will generate a new drumkit.xml file in the tmp folder
2. When creating the .h2drumkit archive:
  1. It will add the drumkit.xml from the tmp folder
  2. It will only select the files used by that components

What do you guys think?

**Comment by mauser** [comment]
What about adding a version enum as a parameter to the save drumkit save functionality and save the complete drumkit to /tmp before exporting?

**Comment by mauser** [comment]
Ah, forget to write about the rest of the dialog :)  Looks very good so far! It would convenient if the lower part is greyed out if there is only one component.

**Comment by mauser** [comment]
Hi, 
The new export dialog is now in-place and ready for testing. Can someone test this?

**Comment by trebmuh** [comment]
Hi,
I did compile this export-to-old branch and when trying to export, I can see the dialogue.
What would need to be tested more than this?

**Comment by thijz** [comment]
Export a drumkit in 0.9.7 (in 0.9.6 format) and import it 0.9.6 would be
the ultimate test i guess
Op 31-okt.-2015 22:52 schreef "trebmuh" <notifications@github.com>:

**Comment by mauser** [comment]
It would be better to test this on hydrogen's main branch, since i added some code after merging the branch. 
For the test cases: 
1. Create a drumkit with multiple, easy distinguishable components in 0.9.7 
2. Export them to 0.9.6 format and select one of those components
3. Load the kit in 0.9.6 or 0.9.5 and check if the correct samples are played

Of course a kit which has been exported for 0.9.7 should also load fine in 0.9.7 :)

**Comment by mauser** [comment]
I'm closing this ticket, as the code is now in the main branch.
