### ISSUE TITLE
hydrogen does not show song name in window top bar

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#314]
normally the 'top bar' (dont know the correct name for it) should show the current song name but it always shows 'untitled song'

**Comment by mauser** [comment]
Oops, that was my fault. Should be fixed again.

**Comment by thijz** [comment]
looks like this one is back again
git --describe tag : 0.9.7-beta1-60-g2db8f6b

**Comment by mauser** [comment]
@thijz: Can you re-test this?

**Comment by thijz** [comment]
retest OK
@jbrew8 : congrats on your first commit !  :-)

**Comment by trebmuh** [comment]
Thanks for that !
