### ISSUE TITLE
pattern editor note properties window black on first run

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#325]
upon the first run (or when you delete your hydrogen.conf file) the pattern editor note properties window is black

_scenario 1:_
- rm hydrogen.conf
- start hydrogen
- click the 'dont show this any more' option in the "you are using a development version of hydrogen ..." popup
- close hydrogen
- restart hydrogen
- the note properties window is OK

_scenario 2:_
- rm hydrogen.conf
- start hydrogen
- click the 'OK' option in the "you are using a development version of hydrogen ..." popup
- close hydrogen
- restart hydrogen
- the note properties window is still black

this is something that has been noticed by other users also (recently in the hydrogen forum i think) but this is the first time that i noticed that there is a link between what you click in the "development version" warning popup and the window update

**Comment by mikotoiii** [comment]
Just making a note here that this issue references [#297](https://github.com/hydrogen-music/hydrogen/issues/297).

**Comment by thijz** [comment]
thanks mikotoiii
i knew that there was a ticket or email about this but couldnt find it :-)

**Comment by mauser** [comment]
Hi, i'm closing this one since it's a duplicate and #297 is older and has some screenshots..
