### ISSUE TITLE
Path issues for drumkits on Windows

### ISSUE THREAD

**Issue by mikotoiii** [hydrogen-music/hydrogen#326]
Supposed to install to:
C:\Users\username\\.hydrogen\data\drumkits

Actually installs to:
32 Bit Regular User - C:\Users\username\AppData\Local\VirtualStore\Program Files (x86)\Hydrogen\hydrogen\data\drumkits
32 Bit Administrator - C:\Program Files (x86)\Hydrogen\hydrogen\data\drumkits
64 Bit Regular User - UAC installs kits as Administrator (see below)
64 Bit Administrator - C:\Program Files\Hydrogen\hydrogen\data\drumkits

Notes:
C:\Users\username\\.hydrogen folder is created and the hydrogen.conf and data folder are put there at runtime from a clean install.
Kits that are installed as administrator can not be deleted by users (permissions problem since it installs to Program Files x86 - 32 Bit only)
0.9.6 does not exhibit this behavior, it installs kits properly to C:\Users\username\\.hydrogen\data\drumkits
Patterns seem to save into the correct location at C:\Users\username\\.hydrogen\data\patterns in both 0.9.6 and 0.9.7

edited to fix the paths: github treats the backslash like an escape character when a dot is next to it.

**Comment by mikotoiii** [comment]
The path should be: C:\Users\username\.hydrogen\data\drumkits

My editor messed up the path.

**Comment by mikotoiii** [comment]
This ticket also references https://github.com/hydrogen-music/hydrogen/issues/284
once this path is fixed it should also fix the need for UAC on the exe.

**Comment by mauser** [comment]
Hi,
i'm closing this ticket now, the functionality is now in the hydrogen's main branch.
