### ISSUE TITLE
Cannot undo adding component

### ISSUE THREAD

**Issue by blablack** [hydrogen-music/hydrogen#329]
If a component is added to a drumkit, an undo cannot be done on it.

Only if an instrument with additional components is dragged/dropped and undo is used the component is removed.

**Comment by blablack** [comment]
After further testing and code checking I noticed modifying a layer cannot be undone either.
Therefor I would be encline 
* NOT to do the undo for Component
OR
* Keep undo for Component for 0.9.8 and create another issue for undo Layer change

**Comment by mauser** [comment]
I'm closing this since for since it is also impossible to undo layer actions..
