### ISSUE TITLE
Previously installed drumkits not listed as installed on program update

### ISSUE THREAD

**Issue by mikotoiii** [hydrogen-music/hydrogen#331]
Drumkits that were installed with a previous version of Hydrogen (just an upgrade in my case 0.9.7 32-bit to 0.9.7-64 bit on Windows) seem to not be recognized as being installed when the new version is installed. The files reside at the proper location in the .hydrogen folder, and can be accessed and used by the program out of the box. The drumkit is simply not listed as installed (Status: New) on the Instruments -> Import Library screen.

**Comment by trebmuh** [comment]
Hi @mikotoiii 
Which drumkit ? It might be related to https://github.com/hydrogen-music/hydrogen/issues/298

**Comment by mikotoiii** [comment]
I was doing my testing with the first couple kits, DeathMetal and
VariBreaks, though it should work on any kit.

It can be replicated on Windows anytime since it won't remove the .hydrogen
folder at uninstall time, so all you need to do is re-install the program.

On linux i'm not sure if it will leave the .hydrogen folder when you
uninstall it or replace / upgrade the inatalled package.

**Comment by trebmuh** [comment]
The "DeathMetal" is one of the problematic one (https://github.com/hydrogen-music/hydrogen/issues/298). But the VariBreaks isn't. So it may be another issue.

**Comment by mikotoiii** [comment]
So after some further testing, it looks like this may in fact be a duplicate of https://github.com/hydrogen-music/hydrogen/issues/298. The VariBreaks kit as well as several other kits in the list are showing as installed after uninstalling and re-installing. I think the DeathMetal kit was just throwing me off since I was testing other parts of the program at the time.
