### ISSUE TITLE
the latest pull

### ISSUE THREAD

**Issue by funkmuscle** [hydrogen-music/hydrogen#335]
since the latest git pull, adding patterns or creating a drumkit is not possible. the window will not close.
At that point, I have to xkill H2. Tried rolling back to earlier versions and the same happens.
I'm using Archlinux64

**Comment by blablack** [comment]
Hello,

This issue is already fixed in this pull request:
https://github.com/hydrogen-music/hydrogen/pull/327

**Comment by funkmuscle** [comment]
I just flushed and clean everything out, did a flesh pull and the same thing is happening.

**Comment by blablack** [comment]
@funkmuscle  it is not in the master branch just yet but in a pull request.
@mauser needs to first review it before being merged with the master branch.

**Comment by funkmuscle** [comment]
@blablack how do i pull that specifically? can't even change the res.

**Comment by blablack** [comment]
TBH, i'm not sure.
Did you check this out?
http://stackoverflow.com/questions/6743514/how-can-i-fetch-an-unmerged-pull-request-for-a-branch-i-dont-own

**Comment by mauser** [comment]
Hi Guys, 
sorry for the long delay, a lot of work has piled up here.. i've just merged the pull request!

**Comment by mauser** [comment]
@funkmuscle : Can you confirm that your issue is now fixed?

**Comment by funkmuscle** [comment]
yep.. all is fine now. thanx
