### ISSUE TITLE
Does not save jack sessions after exporting a track

### ISSUE THREAD

**Issue by worikgh** [hydrogen-music/hydrogen#340]
When I am using Jack and I connect the output from Hydrogen to other than the first and second channels of the system playback after I do an export the output of Hydrogen is reset to the first and second channels of system playback

**Comment by xjjx** [comment]
H2 for export use other driver than jack, let's call it disk writer. After export it once again init jack driver. It's like restart entire application from jack perspective.
H2 can't store connection ( AFAIK ).
This is job for session manager.
You could try ajsnapshot or pathbay in qjackctl, or try jack_session_notify.
