### ISSUE TITLE
Enhancement to pattern editor?

### ISSUE THREAD

**Issue by Peregrino69** [hydrogen-music/hydrogen#344]
Hi all

Currently the options to choose Velocity, Pan, Lead/Lag and NoteKey apply only to one note. Could it be possible to enhance this so that multiple notes in the pattern could be chosen? 

For example to create a laid-back feeling on the beat I drop the snare slightly behind the beat. Or to make a basic 1-2-3-4 hi-hat pattern sound livelier I leave third beat on default, increase velocity to accent the first, and decrease velocity on every 2nd and 4th beat.  

This kind of adjustments would be a lot easier and faster to do if I could choose all notes / multiple notes in the pattern to manipulate them as a group. 

Cheers
Pg69

**Comment by xaptronic** [comment]
+1 It would be amazing to be able to use the mouse to select multiple notes and the apply a given option to them all at once. Misha Mansoor from periphery uses a feature like this in Cubase in a drum programming video.

**Comment by mevsme** [comment]
U see fellas, I don't believe a slight disposition of notes gonna happen in Hydrogen. Cuz it's a drum machine. And it is pretty grid strickt. And you asking a DAW functionality. I am agree that select tool would be nice in "edit" space. Like other 100500 tools othe DAW has, and Hydrogen - no. 1/64 or 1/128 - it's too much for disposition. Its sound wrong. But in HDGN you can put notes only on grid.

**Comment by Peregrino69** [comment]
Mevsme, it's already there. You can adjust lag/lead of each hit in a pattern individually. This causes Hydrogen to trigger the sample behind or ahead the beat (or grid), whichever way you go. "Humanize" knobs in the mixer do the same, it just affects all the samples adding some randomness to the timing or velocity to imitate a live drummer.

Thanks a lot thijz, I missed the memo. I can hardly wait :)

**Comment by theGreatWhiteShark** [comment]
This is already implemented since v1.0
