### ISSUE TITLE
Element {http://www.hydrogen-music.org/drumkit}isLocked is not defined in this scope.

### ISSUE THREAD

**Issue by dreaming-augustin** [hydrogen-music/hydrogen#349]
Related to #348. 

Trying to upgrade the drumkits available at http://www.hydrogen-music.org/feeds/drumkit_list.php , 
I find that they all define:
`<isLocked>false</isLocked>` .

unfortunately, the drumkits available in the source: 
GMkit  TR808EmulationKit
never defined isLocked, even before the schema upgrade patch.
So, basically, I don't know how to upgrade that. 
Can all references to isLocked be deleted?
Or is there a new element with a different name but a similar functionality?

**Comment by mauser** [comment]
Hi! 
I can't say anything about this tag, at least it is not used by the sourcecode at the moment, so you can delete it. It seems to be used in the demo songs as well (which are shipped with hydrogen).
