### ISSUE TITLE
Song mode crashing

### ISSUE THREAD

**Issue by TuoppiPatxaran** [hydrogen-music/hydrogen#350]
On version 0.9.7 compiled from git repository and also on 0.9.6 from debian repository. When clicking on the "song mode" to reproduce the patterns the program crashes with the following error:

ASSERT: "uint(i) < uint(size())" in file /usr/include/qt4/QtCore/qbytearray.h, line 414
Aborted

When the program is configured for Jack as the audio backend, when pressing the Jack Master button the program also crashes with the same error.

libQt4 seems to be version 4.8.7 in my system

**Comment by mauser** [comment]
Hi,

i tried to reproduce this on my system (Ubuntu 15.10), but had no luck. Can someone else reproduce the problem?

**Comment by trebmuh** [comment]
Hello, I tried to reproduce the 2 issues here on 2 system, with both the 0.9.6 official package from debian and a fresh compile of git acb8332 and can't reproduce.
libqt4 seems to be 4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 (given in synaptic).
Hope that can help.

**Comment by thijz** [comment]
is this with a specific song ?
or does it always happen ?

**Comment by mauser** [comment]
Closed due to lack of feedback (i can't reproduce it on my system).
