### ISSUE TITLE
Changing "release" on instrument in song saves in format which can't be read

### ISSUE THREAD

**Issue by JohnCPun** [hydrogen-music/hydrogen#361]
Windows 7 x64
Hydogen 0.9.7-windowsPreview [Aug 31 2015]

Create a new song
Change the "release" property of an instrument
Save the song
Now release the song

Expected:
Release property is loaded as it was set

Observation:
Release property is set completely to 0
I have noticed this happens when the release property is save as a floating point number (so with decimals).
When I change the xml of the song to remove the decimals (making it an integer) it will load the release property correctly

**Comment by mauser** [comment]
Can someone re-test this issue?

**Comment by JohnCPun** [comment]
Hi Mauser, I'd love to retest this, but how do I go about getting myself a copy?

**Comment by mauser** [comment]
Hi! 
I've uploaded a beta2 version for windows yesterday: https://sourceforge.net/projects/hydrogen/files/Hydrogen/0.9.7%20Binaries/Hydrogen-0.9.7-beta2-win32.exe/download . This should be ok for testing!

**Comment by JohnCPun** [comment]
Thanks :)
It's working correctly for me now :)

**Comment by mauser** [comment]
Perfect, thanks for testing!
