### ISSUE TITLE
Use relative path to save playlist

### ISSUE THREAD

**Issue by JohnCPun** [hydrogen-music/hydrogen#362]
Make a playlist of various songs.
Save the play list.
Now copy the songs and playlist to another location.
Open the playlist.

The playlist can't open the songs as in the playlist a absolute path is stored.
It would be nice if the playlist would store a relative path, so the songs can be opened when copying like this.

For myself I see it mostly as being able to set up a playlist on my PC at home and then copy it to the laptop I have at the rehearsal space, which I use for live shows, etc. Right now I can't do that and have to make the playlist on the laptop I will be using live (or edit the path in the XML).

**Comment by trebmuh** [comment]
It might be related to https://github.com/hydrogen-music/hydrogen/pull/353

**Comment by xjjx** [comment]
Actually , items on playlists can use relative paths. I use it in that way, but you need create/tweak your playlist manualy i.e. it works only for load, not for save.
I also added support for load song relative to Jack Session ( SESSION_DIR environment variable ).
( SongReader::getPath method in code ).
Maybe it should search for file also in directory where playlist is stored ?

**Comment by xjjx** [comment]
Oh .. and I see that I added also support for save playlist during saving session ( JackSession ). It copy all songs to session directory and use relative paths on new playlist ;-)

**Comment by JohnCPun** [comment]
Yeah, that is pretty much guaranteed :)
So making it an option sounds like the best way to go.

**Comment by mauser** [comment]
Hi,

this is now implemented. I've added an option to the preferences dialog which allows you to configure if the playlist uses relative or absolute paths.
