### ISSUE TITLE
Wrong Playback Speed before export

### ISSUE THREAD

**Issue by puenka** [hydrogen-music/hydrogen#37]
Mac OS X 10.6.8 - Hydrogen 0.9.6-beta1

When playing a song inside the program it plays about 10 BPMs faster than the displayed BPM. Only after exporting the tempo is correct.

**Comment by thijz** [comment]
hi puenka, mauser
is this ticket still valid?
can it be retested ?

grtz
Thijs

**Comment by puenka** [comment]
Actually, it's been quite some time since i've been using hydrogen, so to
me it's not of importance any longer.
Am 10.08.2015 10:33 schrieb "thijs" <notifications@github.com>:

**Comment by thijz** [comment]
hi Mauser
is this ticket still valid ?

**Comment by mauser** [comment]
I'm closing this since i can't reproduce it any longer..
