### ISSUE TITLE
Hydrogen 'Fill/delete' instrument, right click doesnt work

### ISSUE THREAD

**Issue by Cheesecakeone** [hydrogen-music/hydrogen#370]
I've been using Hydrogen on two different computers. Since my older one is quite outdated and slow i switched to a newer one and installed Hydrogen on it. Now somehow i cant fill or delete all notes for one instrument by right clicking, as shown in the manual. When i rightclick an instrument simply nothing happens. There is no window opening where i could choose from. I tried uninstalling Hydrogen, downloading it anew from the Hydrogen Homepage (v 0.9.6. preview release for windows) but that didnt change anything. Is there any way i can fix this?
Thank you so much for your help and have a wonderful day

**Comment by mauser** [comment]
Hi! 

You could try to use the [hydrogen 0.9.7-beta2](https://sourceforge.net/projects/hydrogen/files/Hydrogen/0.9.7%20Binaries/Hydrogen-0.9.7-beta2-win32.exe/download) package for windows. Which version of windows are you using?

**Comment by Cheesecakeone** [comment]
I am using Windows 10 but I had the same Problem on Windows 8.1 


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Sebastian Moors <notifications@github.com> 
Datum: 15.04.2016  22:11  (GMT+01:00) 
An: hydrogen-music/hydrogen <hydrogen@noreply.github.com> 
Cc: Cheesecakeone <mgahbler@hotmail.de> 
Betreff: Re: [hydrogen-music/hydrogen] Hydrogen 'Fill/delete' instrument,
  right click doesnt work (#370) 

Hi! 

You could try to use the hydrogen 0.9.7-beta2 package for windows. Which version of windows are you using?

**Comment by mauser** [comment]
Hi,

for Windows 8 this problem is currently documented in our [FAQ](http://hydrogen-music.org/hcms/node/392). It would be nice to know if it happens also with the 0.9.7-beta2 installer (which works well on my Windows 7 system, unfortunately i don't have a Windows 10 System to test it).

**Comment by Cheesecakeone** [comment]
Hey,
updating to the new 0.9.7 Beta fixed everything. so i can say it works perfectly fine with windows 10.
Love the 'copy pattern' 'fill pattern' function by the way. makes working with hydrogen so much easier!
thanks for your help, hope you have a wonderful day =)

Date: Sat, 16 Apr 2016 03:10:52 -0700

**Comment by mauser** [comment]
Thanks, that's good news! I will extend our FAQ so that other people can solve that problem too..
