### ISSUE TITLE
Jack Connections and Non Session Manager

### ISSUE THREAD

**Issue by 0mk** [hydrogen-music/hydrogen#374]
Hydrogen seems to automatically connect its audio outputs to the system playback ports when run in jack mode. When running under NSM, this causes problems. If another application is placed in the audio path between hydrogen and system playback, closing and reopening the session under NSM, the jack connections are wrong. I.e there is an extra pair of connections from hydrogen audio out to system playback which should not be there.

**Comment by mauser** [comment]
Hi! 

there's the "connect to default output pair" checkbox in the Preferences/Audio System tab. Have you tried to disable it?

**Comment by 0mk** [comment]
That's perfect! Sorry I didn't spot it myself.
