### ISSUE TITLE
Hydrogen doesn't show non-latin characters

### ISSUE THREAD

**Issue by elpescado** [hydrogen-music/hydrogen#375]
Hydrogen 0.9.7-beta2 on Windows doesn't show non-Latin characters anywhere in UI. Moreover, text looks terribly pixelated:

![hydrogen](https://cloud.githubusercontent.com/assets/1619113/14815129/e36ca22a-0ba9-11e6-8863-21414acaba8c.png)

**Comment by elpescado** [comment]
Changing font in preferences seems to fix this issue - moth missing glyphs, and pixelated look. Maybe Hydrogen should provide better defaults?

![hydro2](https://cloud.githubusercontent.com/assets/1619113/15148002/b71dd214-16c3-11e6-9a97-71a5161a3699.png)

**Comment by mauser** [comment]
Hi @elpescado,

at the moment i don't see a reason to change the default font, since it seems to work on all my systems (even with non-latin characters, for example german umlauts). On my Windows 7 system the font looks crisp and absolutely unlike your example screenshot. I suspect that this might be an effect of QT trying to find a suitable font and ending up with an unsuiting one.. Have you checked which font was chosen previously and if that font existed on the system?

**Comment by elpescado** [comment]
Hi,

I have uninstalled Hydrogen, removed settings, and installed again with the same results - pixelated fonts with no diacritics. I've had a little time to investigate it a bit further and found that Hydrogen uses by default Lucida Grande font, which is missing on my Windows, so Qt falls back to some legacy font. Moreover, Lucida Grande seems to ship only with OSX, to this problem affects Linux too, it is just not that much noticeable - probably Qt picks some saner default there.

According to Wikipedia, Lucida Sans Unicode is goor replacement for Lucida Grande on Windows. Changing Hydrogen settings to Lucida Sans Unicode fixes this problem.

https://en.wikipedia.org/wiki/Lucida_Grande
http://superuser.com/questions/486344/how-can-i-use-the-lucida-grande-font-in-windows

**Comment by trebmuh** [comment]
Would it maybe help to make Hydrogen looking for one preferred font, then if it doesn't find it, looks for a second preferred font, then a third one? That way, it could help with not ending up to this kind of issue.
I'm not really sure about the efficiency of this approach, just leaving this thought here as a suggestion for further discussion if relevant.
Hope that helps,
Olivier

**Comment by elpescado** [comment]
Why Hydrogen is using custom font in the first place? Bonus points: why it is using font that is not available on most computers (Linux and Windows)?

I think sticking to system font would fix this issue. It would look better as well.

**Comment by theGreatWhiteShark** [comment]
fixed in #1282
