### ISSUE TITLE
Surface

### ISSUE THREAD

**Issue by Ingool** [hydrogen-music/hydrogen#378]
I'm trying to use hydrogen on my surface book. The aspect ratio is 3:2 and hydrogen doesn't adapt very well and there doesn't seem to be a zoom option, hopefully the image loads.. But anyway, it is very difficult to see what I am doing or indeed to create anything as it is all so small.
![image](https://cloud.githubusercontent.com/assets/19530830/15468935/f8d1ef5e-20de-11e6-8730-28207b99bb76.png)

**Comment by mauser** [comment]
Hi,

thanks for the screenshot! The hydrogen gui is based on a pixel-design at the moment, most UI elements aren't vector graphipcs but jpg/png's. We need to redesign the complete UI to support for high resolution displays in a sensible way..

**Comment by mauser** [comment]
Hi! 

The current beta version (Hydrogen 1.0 beta1) has an improved support for high resolution devices. It still is far away from beeing perfect, but maybe it improves things for you?

**Comment by trebmuh** [comment]
@Ingool : can you please check with Hydrogen 1.0beta?
