### ISSUE TITLE
Allow changing drumkit with midi events

### ISSUE THREAD

**Issue by LemarinelNet** [hydrogen-music/hydrogen#380]
Hi

I plan to use H2 as a midi drum machine.
I'm making my own electronic trigger, which will send midi notes etc...
It would be awesom to be able to switch from a drumkit to another via a program change (or a sysex, or some other midi event ?)

**Comment by mauser** [comment]
Hi,

how do you want to specifiy the drumkit which hydrogen should use next? I think there could be an action like "load the n-th drumkit of the soundlibrary", but of course then the behaviour changes after a new drumkit gets installed..

**Comment by LemarinelNet** [comment]
Yes, that's what I was thinking about : load n-th drumkit...

In facts, since I was missing this feature, I though of making my own software, and gone ahead writing it !
There's a lot to finish it, but it's more dedicated to drums...
Maybe this feature would interrest other people anyway !

**Comment by theGreatWhiteShark** [comment]
Since #1473 there is now an OSC command to load a drumkit by name. (will be introduced in version 1.2.)

```bash
oscsend localhost 9000 /Hydrogen/LOAD_DRUMKIT s GMRockKit
```
