### ISSUE TITLE
Hydrogen does not compile with latest Jack 1

### ISSUE THREAD

**Issue by blablack** [hydrogen-music/hydrogen#383]
Since the last git of Jack 1 (10 July 2016), hydrogen does not compile.

The error is the following:

[ 15%] Building CXX object src/core/CMakeFiles/hydrogen-core-0.9.7.dir/src/IO/jack_output.cpp.o
cd /«PKGBUILDDIR»/obj-i686-linux-gnu/src/core && /usr/bin/g++   -Dhydrogen_core_0_9_7_EXPORTS -I/«PKGBUILDDIR»/src/core/include -I/«PKGBUILDDIR»/include -I/«PKGBUILDDIR»/obj-i686-linux-gnu/src/core/include -I/usr/include/qt4/QtDesigner -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4/QtScriptTools -I/usr/include/qt4/QtDBus -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtHelp -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtTest -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtSvg -I/usr/include/qt4/Qt3Support -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore -I/usr/share/qt4/mkspecs/default -I/usr/include/qt4  -O2 -std=gnu++11 -Wno-deprecated-register -fno-implement-inlines -g  -fPIC   -o CMakeFiles/hydrogen-core-0.9.7.dir/src/IO/jack_output.cpp.o -c /«PKGBUILDDIR»/src/core/src/IO/jack_output.cpp
/«PKGBUILDDIR»/src/core/src/IO/jack_output.cpp: In member function ‘void H2Core::JackOutput::setTrackOutput(int, H2Core::Instrument*, H2Core::InstrumentComponent*, H2Core::Song*)’:
/«PKGBUILDDIR»/src/core/src/IO/jack_output.cpp:707:84: error: ‘jack_port_rename’ was not declared in this scope
  jack_port_rename( client, track_output_ports_L[n], ( chName + "L" ).toLocal8Bit() );

**Comment by jdekozak** [comment]
Hi

https://github.com/hydrogen-music/hydrogen/pull/365

Have you rerun the cmake configuration script before compiling ? it should detect automatically if this function is available or not in jack library.

Regards,

**Comment by blablack** [comment]
Indeed - my appologies - after reruning CMake init it did work.
