### ISSUE TITLE
Move hydrogen to QT5

### ISSUE THREAD

**Issue by timtas** [hydrogen-music/hydrogen#386]
Hi all
First, thanks for this great piece of software!
As hydrogen is currently the only program left on my system with qt4, I wondered if there are any plans to move to qt5?

**Comment by mauser** [comment]
Hi! 

Yes, this is definitely on my list for the next version of hydrogen (0.9.8). I've started to look into the documentation changes some time ago, but for 0.9.7 it is too late.

**Comment by mauser** [comment]
Hi,

QT5 support has landed in the master branch..
