### ISSUE TITLE
cant preview standard kit samples

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#388]
complete fresh build (using code from today 15juli2016)

how to reproduce:
- open hydrogen
- goto the sound library
- double click on one of the samples of the default GMkit : no sound and i see this debug output : 

```
Error XSDError in file:///home/tvanseve/Code/prive/hydro15juli/data/drumkits/GMkit/drumkit.xml, at line 11, column 16: Element {http://www.hydrogen-music.org/drumkit}componentList is not defined in this scope.
(I) SoundLibraryPanel::on_DrumkitList_itemActivated GMkit, instr:Tom Mid
(I) Drumkit::load Load drumkit /home/tvanseve/Code/prive/hydro15juli/data/drumkits/GMkit
(E) XMLDoc::read XML document /home/tvanseve/Code/prive/hydro15juli/data/drumkits/GMkit/drumkit.xml is not valid (/home/tvanseve/Code/prive/hydro15juli/data/xsd/drumkit.xsd), loading may fail
(E) Legacy::load_drumkit loading drumkit with legacy code
(D) XMLNode::read_string Using default value  for image
(D) XMLNode::read_string Using default value undefined license for imageLicense
(W) Sampler::__render_note NULL sample for instrument Tom Mid. Note velocity: 1
```

if i click on the same sample of the loaded GMkit in the pattern editor i _do_ hear the sample

now it gets really interesting :  if i load the GMkit (the one that _is_ already loaded) i dont hear the sample any more if i click on the sample name in the pattern editor

if i load any other non-standard kit that works just fine

**Comment by blablack** [comment]
I'll have a look at this - it looks like my code :)

**Comment by blablack** [comment]
@thijz I can't reproduce in the latest git
Can you confirm?

**Comment by trebmuh** [comment]
@thijz and @blablack : from a clean rebuild from yesterday's GIT (https://github.com/hydrogen-music/hydrogen/commit/d7dacfedf73ede1af24ddedf260cfce5ca77df18) (+ patches https://github.com/hydrogen-music/hydrogen/pull/360 and https://github.com/hydrogen-music/hydrogen/pull/338 for completeness sake), I can't reproduce this issue. Double-clicking is providing the sound.

**Comment by trebmuh** [comment]
@thijz and @blablack : from a clean rebuild from yesterday's GIT (https://github.com/hydrogen-music/hydrogen/commit/d7dacfedf73ede1af24ddedf260cfce5ca77df18) (+ patches https://github.com/hydrogen-music/hydrogen/pull/360 and https://github.com/hydrogen-music/hydrogen/pull/338 for completeness sake), I can't reproduce this issue. Double-clicking is providing the sound.

**Comment by thijz** [comment]
retested using 0.9.7-'2e23685' > OK
