### ISSUE TITLE
Pattern line disappearing

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#390]
While looking at https://github.com/hydrogen-music/hydrogen/issues/235 a few minutes ago, I faced up a strange behavior where a pattern line is deleted when drag'n'dropping an instrument from the sound library (yes, I guess it's not supposed to be used like that :) ).
Screencast: http://download.tuxfamily.org/librazik/volatile/hydrogen-issue390.mp4

**Information:**
* Fresh git build from yesterday (ie: https://github.com/hydrogen-music/hydrogen/commit/d7dacfedf73ede1af24ddedf260cfce5ca77df18) + patch from https://github.com/hydrogen-music/hydrogen/pull/360 (nothing relevant here I guess, just to explain what is the build I'm using)
* Updated Debian Jessie.

**Comment by mauser** [comment]
Ah, a nice method to delete a pattern :) 

I will see what's wrong there..

**Comment by trebmuh** [comment]
Maybe we could leave it as is and document this "feature" in the manual? ;)
Feel free to ping me if you need testing later on.

**Comment by mauser** [comment]
Should be fixed now.

**Comment by trebmuh** [comment]
Just rebuild current git https://github.com/hydrogen-music/hydrogen/commit/8b24339433151ad44dfc73bc054da66e55a30e01 which includes your fix and retested. It looks to be fixed, thanks for the quickness!

PS: I'm closing this issue then.
