### ISSUE TITLE
Jack Transport not active when "auto" engine is used (even if it selects JACK)

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#392]
I was just reading at this discussion: https://github.com/hydrogen-music/hydrogen/issues/379 and playing around with Hydrogen when I suddenly faced up a strange behavior:

Screencast: http://download.tuxfamily.org/librazik/volatile/hydrogen-issue392.mp4

**Comments about the screencast:**

1. Hydrogen is first set up _menu -> Tools -> Preferences -> audio system : auto_ and is using JACK as you can see in the Catia connexion manager. The JACK-transport buttons are not here.
2. Then I'm setting Hydrogen to _menu -> Tools -> Preferences -> audio system : Jack_, and restarting the output. You can see that Hydrogen flickers in Catia which indicates that the output is effectively restarted. Then, I'm closing the Preferences window, and the JACK-transport buttons appear.
3. Then, I'm resetting Hydrogen to _menu -> Tools -> Preferences -> audio system : auto_ and restarting the output. Once again, Catia flickers which indicates that the Hydrogen output in "auto" mode is restarted and is choosing to use JACK. Then, I'm closing the Preferences window, and the JACK-transport buttons disappear.

**What would I be expecting ?**

As a user, I'd expect Hydrogen to show my the JACK transport controls whether I select manually the audio-engine to be JACK, or if the "auto" mode is choosing JACK as the audio engine.

Hope that helps.

**Comment by mauser** [comment]
Should be fixed now..

**Comment by trebmuh** [comment]
OK, I can confirmed that the butons are shown now whether I select manually the audio-engine to be JACK, or if the "auto" mode is choosing JACK as the audio engine.

Then a second bug is appearing: when "auto", if I click on one of those 2 buttons, I've got a pop up windows telling me "JACK-transport will work only with JACK driver".

Hope that helps.

**Comment by mauser** [comment]
Sorry, i forgot to modify the checks for the transport/master buttons. Please check again :smile:

**Comment by trebmuh** [comment]
Frsh rebuild from today's GIT (https://github.com/hydrogen-music/hydrogen/commit/cd9b7e1ea34f309d679aeb4c0df10178e9dc935b) and I can confirmed that the pop-up windows is not coming anymore.

I've checked with a 0.9.6.1 and this (unexpected/incorrect) behavior was already there so I did put a line on the "bugs fix" section here https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-0.9.7

I'm closing this issue and removing the screencast then.
Thanks @mauser !
