### ISSUE TITLE
H 0.9.7-beta 2 - OS W10 - Could not load FX

### ISSUE THREAD

**Issue by herenciano243** [hydrogen-music/hydrogen#396]
Hello everyone,
I just installed Hydogen 0.9.7-beta 2 (French version) in my PC whose work system is Windows 10, and I love the improvements that have been made since the 0.9.6 release. However I can not load any plugin for FX.
I examined the repertoire of installing Hydrogen, and I see that in the ... \ Program Files (x86) \ Hydrogen \ plugins \ ladspaplugs it is over a hundred plugins.
I must say that in the 0.9.6 version I used a long time, it was working properly.
I have to do something? or it is a bug?
Tank you to all who will help me.
Best greeting to all
Manuel Sanchez

**Comment by trebmuh** [comment]
Salut @herenciano243 :
duplicate: https://github.com/hydrogen-music/hydrogen/issues/341
