### ISSUE TITLE
i18n issues

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#397]
I've spotted few issues where the translated messages doesn't fit in the space available on the GUI and then, the translated message are cut. Below are some examples (with a French GUI) for memories. I'll try to update this thread as I'm finding others.

![hydrogen-bug-i18n](https://cloud.githubusercontent.com/assets/8705846/17648371/9e044c0a-6212-11e6-9647-e158375bba2c.png)

![hydrogen-bug-i18n-2](https://cloud.githubusercontent.com/assets/8705846/17648372/9fcbe1ec-6212-11e6-81d7-c2f5033dd737.png)

**Comment by pvint** [comment]
@trebmuh  Try https://github.com/hydrogen-music/hydrogen/commit/93b5bca012df59ecd5c306c2827bb150a3c8b68d

**Comment by trebmuh** [comment]
I'll be away from my computer for the next 4 or 5 days. I'll check this one out then.
Merci beaucoup :)

**Comment by elpescado** [comment]
Does Hydrogen use some automatic layout mechanism in its dialogs or are they fixed?

**Comment by pvint** [comment]
These particular ones are fixed, as I believe most of them are. I was thinking it would be nice to make these more flexible, but gui layout really isn't my forte.

**Comment by trebmuh** [comment]
@pvint: tested on a fresh rebuild from master today + your patch, and it's much better, thank you !

I spotted another one:
![hydrogen-bogue](https://cloud.githubusercontent.com/assets/8705846/18128132/9d36846c-6f84-11e6-9c52-582e43460dcd.png)

Here the "Mode Jack-Time-Master Inact" should be "Mode Jack-Time-Master Inactif".

**Comment by mauser** [comment]
Hi @pvint , 

could you create a pull request for your fixes? 

About the latest issue: I'm currently thinking about removing the complete LCD display. It is not able to display non-ascii characters and the whole thing seems to be quite redundant for me. Take the depicted scenario for exmaple.. you can easily by looking at the GUI that the Jack master button inactive. You don't need the status to say the same thing again..

**Comment by trebmuh** [comment]
I kind of agree with that @mauser 

So bad for the red dot design award ;)

**Comment by trebmuh** [comment]
@pvint: I've wandered around Hydrogen, fresh rebuild from 40 minutes ago ( https://github.com/hydrogen-music/hydrogen/commit/eae444fa49185bcb52a50a5688b67314ccf327b6 ) and I clicked everywhere I could! Then, I found this bunch of other ones:

1) menu -> Project -> Export as wav:
![capture-exporter le morceau](https://cloud.githubusercontent.com/assets/8705846/20469697/1c92db54-afa2-11e6-9fa2-0848b6fa5569.png)

2) menu -> Drumkits -> Save as:
![capture-enregistrer la bibliotheque de sons](https://cloud.githubusercontent.com/assets/8705846/20469764/95632250-afa2-11e6-9b6a-1b470a68704c.png)

3) menu -> Drumkits -> Import online:
![capture-importation de la bibliotheque de sons](https://cloud.githubusercontent.com/assets/8705846/20469800/fbefa732-afa2-11e6-9c7b-e81d12069785.png)

4) menu -> Options -> Preferences -> Audio Engine (2nd tab)
![capture-preferences](https://cloud.githubusercontent.com/assets/8705846/20469900/e2a60432-afa3-11e6-98cf-1f8a27dc71ac.png)

5) menu -> Options -> Preferences -> Appearence (4th tab)
![capture-preferences-2](https://cloud.githubusercontent.com/assets/8705846/20469901/ea959e64-afa3-11e6-9419-dff916ba9c9c.png)

6) Instruments -> "Layers" -> "LOAD LAYERS" (three in one here):
![capture-navigateur de fichiers audio](https://cloud.githubusercontent.com/assets/8705846/20470019/10b22a76-afa5-11e6-91f1-49b73e93a6e1.png)

7) Instruments -> "Layers" -> "EDIT LAYERS" (two in one here):
![capture-sampleeditor fsharp minor7b5_00 flac](https://cloud.githubusercontent.com/assets/8705846/20470064/590fdf16-afa5-11e6-93aa-35d9a003daa3.png)

Would you min applying your magics coding things on it? :)

**Comment by thijz** [comment]
the only time i look at the LCD is when i hit Ctrl-s to check if the song is actually saved

**Comment by trebmuh** [comment]
Sounds like a great idea @thijz . Keeping the momentum while removing the issue with accentuated letters.

**Comment by pvint** [comment]
@trebmuh  I have *improved* the spacing for most or all of the items you mentioned (thanks for the clear indications of what needed to be done - that made it easy!). Try it out at https://github.com/hydrogen-music/hydrogen/tree/i18n_space_397
Note: This isn't really *fixing* the issue, just helping it some. In some of the dialogs it is difficult to provide much more room, since it would require making the dialogs larger, which might be bad for people with low resolutions.

Also - although I like the LCDs, maybe it is a good idea to ditch them

**Comment by elpescado** [comment]
I think the real solution would be to use layouts to lay out widgets in dialogs instead of manually placing widgets.

http://doc.qt.io/qt-5/layout.html
http://doc.qt.io/qt-5/examples-layouts.html

**Comment by trebmuh** [comment]
@pvint : tested and looks great so far but the "3. menu -> Drumkits -> Import online:" which is the same.
Thanks for your magics ! :)

@elpescado : it does sounds to be the real solution yes. How much time could that involved to change the layout of the whole H2 interface?

**Comment by pvint** [comment]
@trebmuh Thanks for the testing, and for the reminder about that one. Since strings for that one could be quite long I skipped it for the moment; I think for that one maybe we should have it just truncate the string and make a tooltip popup that displays the full string.

Example:
![snapshot31](https://cloud.githubusercontent.com/assets/608740/20582369/a8394900-b1ae-11e6-80c3-2fa64a4f8562.png)

**Comment by trebmuh** [comment]
I agree, that's a great idea!

**Comment by elpescado** [comment]
> @elpescado : it does sounds to be the real solution yes. How much time could that involved to change the layout of the whole H2 interface?

I'm not that proficient in Qt, but as far as I know this can be done in Qt Designer, so it should not involve any coding at all.

**Comment by mauser** [comment]
@elpescado : Not every dialog is build in Qt Designer, some are handcoded and/or composed from custom widgets, so there will be coding involved. But that's not a big deal in most cases

**Comment by mauser** [comment]
I'm adding here the images which were reported by @nikoss in #443: 

![hydrogen_in_greek_001](https://cloud.githubusercontent.com/assets/4921343/20686032/9b620bb2-b5bf-11e6-967c-b42cf496ad75.jpg)
![hydrogen_in_greek_002](https://cloud.githubusercontent.com/assets/4921343/20686031/9b5d78fe-b5bf-11e6-8d92-ebafc3d4c6ef.jpg)
![hydrogen_in_greek_003](https://cloud.githubusercontent.com/assets/4921343/20686033/9b6bf942-b5bf-11e6-88d4-55a6ccdc838b.jpg)

**Comment by nikoss** [comment]
Some thoughts on the matter...

Windows, dialogues, boxes, etc, with fixed dimensions look cool, but they cause problems with the translations.
Is there a middle way?

I was thinking.... For example, in the Sample Editor picture, above, at the first row, there are 5 boxes (with values) and 1 button.
You could have 1 row per box, but that would increase the window height, which would be a problem for smaller screens.

Tabs are a good solutions. The "Tabbed" version of Hydrogen's main window works really well in my small 1024x768 screen.

On the other hand, of course, you can't have too many tabs, because it gets confusing (like in many Microsoft's Windows properties dialogues)

There might be other ways to have many options, in one window, and yet keep the window's dimensions relatively small.
But I wouldn't know.
Just giving my feedback as a simple user.

**Comment by pvint** [comment]
Thank you @nikoss for all of the pictures - it really helps.

I have made a few updates:
- Drumkit Export: Added a form layout and the labels should resize nicely now
- Drumikit Save: Same
- Project->Export Song: Completely rewrote this one. The spacings will now adjust nicely using a form layout, and the dialog window will size itself appropriately

I went ahead and committed these to the master branch, so any update as of commit 97fecf9fe6cf70b6fd4e8df20afea92acf652a0b  or newer.

I will keep working on the other dialogs.

Paul

**Comment by trebmuh** [comment]
@pvint : I did a fresh rebuild and this looks fine, congratz!

Would you mind adding a bit of (padding-)space here on _Hydrogen's menu -> Drumkits -> save As_:

![hydrogen](https://cloud.githubusercontent.com/assets/8705846/20948881/a51dbcfc-bc16-11e6-81d5-e16757feb24f.png)

**Comment by pvint** [comment]
Thanks, @trebmuh  ))

It's a good learning experience, since I have little experience with GUI stuff.

There's still more to do... 

Thanks for pointing out the padding on the Save As dialog - I caused that! Now it's fixed in 98f5b1f33d30b4a988e16e7ac997de3d1f539720

Paul

**Comment by trebmuh** [comment]
Fresh rebuild from https://github.com/hydrogen-music/hydrogen/commit/1297e0977c3fcad5026b3b2dfb311cb6c5babc7b and it's all good. Thanks @pvint !

**Comment by trebmuh** [comment]
Hi @pvint and all!
I've been doing a fresh build from https://github.com/hydrogen-music/hydrogen/commit/f665c86999a456a405cef1317055afe93405dc8d and I found 2 spots where the same kind of size-issues occurs. Here we are:

Hydrogen menu -> Drumkits -> Online import
![hydrogen-bug1](https://user-images.githubusercontent.com/8705846/37480567-d9be85aa-287f-11e8-96a3-bc6289d78622.png)

Hydrogen menu -> View -> Director
![hydrogen-bug5](https://user-images.githubusercontent.com/8705846/37480571-dc422976-287f-11e8-8619-d6ca07fec917.png)

Let me know if I can help with testing or anything else, I'm trying to free up a bit of time to help with the 1.0.0 release.

**Comment by nikoss** [comment]
For 
 |  Hydrogen 1.0.0-beta1 (March 16 2018)

Under 
 |  wine, 32bit

in 
|   Mageia 6, 64bit

with
|   Greek language

Go to Menou --> Prefferences --> OSC

![hydrogen_in_greek_004](https://user-images.githubusercontent.com/4921343/39665828-9f644e80-50a2-11e8-98de-9b1334dfaa99.jpg)

**Comment by heit0r** [comment]
I didn't got time to test it on pt_br translation yet, but i'm willing to do so in the next few days.

**Comment by nikoss** [comment]
Another one.
(
in Greek 
Hydrogen 1.0.0-beta1 (March 16 2018)
wine, 32bit 
Mageia 6, 64bit
)

Go to
Menu --> Debug --> Sound Driver Info
![hydrogen_in_greek_005](https://user-images.githubusercontent.com/4921343/39902652-ea897f3c-54d7-11e8-8249-8179c82d9794.jpg)

**Comment by nikoss** [comment]
Again...
(
in Greek
Hydrogen 1.0.0-beta1 (March 16 2018)
wine, 32bit
Mageia 6, 64bit
)

Menu --> Drumkits --> Properties
"Drumkit License"
![hydrogen_in_greek_006](https://user-images.githubusercontent.com/4921343/39903102-2a281fac-54da-11e8-9272-2a4c9ded0df8.jpg)

**Comment by nikoss** [comment]
(
in Greek
Hydrogen 1.0.0-beta1 (March 16 2018)
wine, 32bit
Mageia 6, 64bit
)

Menu -->  Drumkits --> Import
![hydrogen_in_greek_007](https://user-images.githubusercontent.com/4921343/39903553-5fa672b2-54dc-11e8-8a06-a6e670418689.jpg)

**Comment by trebmuh** [comment]
A few other i18n issues here: #1089

**Comment by trebmuh** [comment]
I can confirm 3 and 6.

Here is some details for 3:
- the green dotted one changes after the selection of a sample
- strangely, the blue dotted ones change there translation after the selection of a sample

Before:
![3-1](https://user-images.githubusercontent.com/8705846/104222559-c4b98780-5442-11eb-8e52-f5aa7d8067f5.png)

After:
![3-2](https://user-images.githubusercontent.com/8705846/104222564-c8e5a500-5442-11eb-81e8-4d7ff18fa617.png)

**Comment by theGreatWhiteShark** [comment]
> I think the real solution would be to use layouts to lay out widgets in dialogs instead of manually placing widgets.
>
> http://doc.qt.io/qt-5/layout.html
http://doc.qt.io/qt-5/examples-layouts.html

@trebmuh do you remember if anybody tried this and if it proved to be a proper solution?

**Comment by trebmuh** [comment]
@theGreatWhiteShark : I can't recall anything like that.

**Comment by theGreatWhiteShark** [comment]
How about we select one widget/window which has issues in multiple languages and port it to dialogs. Then we can see if this would fix the issue. (But right now I can not really see what could be done if e.g. "Mixer" is translated to something requiring 100 UTF8 symbols. Maybe translatable tooltips for those things?)

**Comment by trebmuh** [comment]
> How about we select one widget/window which has issues in multiple languages and port it to dialogs. Then we can see if this would fix the issue.

I'm not sure to understand what that implies (not a programmer here), but if you think that could fixes some of the issue, I think trying is a good option to go for.

> (But right now I can not really see what could be done if e.g. "Mixer" is translated to something requiring 100 UTF8 symbols. Maybe translatable tooltips for those things?)

I'm not sure what issue you're referring to here.

**Comment by theGreatWhiteShark** [comment]
> I'm not sure which specific issue you're referring to here. Does that refer to (example) this one:
hydrogen-bug-i18n-2
where the space available isn't large enough to cater for the French translation?

Yeah, this one will do. I give it a try and convert it into a `QDialog` some time soon and we can check whether this would solve it.

**Comment by trebmuh** [comment]
@theGreatWhiteShark please, note that this one has already been fixed by @pvint :

![h2](https://user-images.githubusercontent.com/8705846/104469583-f48a9b80-55b8-11eb-8326-456a188f147c.png)

Let me find one which is still holding this issue and I'll come back here.

**Comment by trebmuh** [comment]
OK, I've rebuild from ecc6339 to ensure that I'm up-to-date, and I've got one:

![h2-size-issue](https://user-images.githubusercontent.com/8705846/104480219-a24f7780-55c4-11eb-9162-cfb7e2f069d0.png)

Please, note that is is shorted by a very small amount in this very case since it's only the [last letter of the translated sentence](https://github.com/hydrogen-music/hydrogen/blob/master/data/i18n/hydrogen_fr.ts#L4005) which is cut.

**Comment by theGreatWhiteShark** [comment]
> Edit: another one, a bit more annoying because that's about license:
>
> menu -> Drumkits -> Online Import

I tried tweaking it for hours yesterday but I just don't get the hang QtDesigner.

There is no coding or any knowledge of Hydrogen required so I guess we could split the issues with those individual views of into separate issues (to make them less frightening), tag them with "good first issue", and hope someone with more time at hand will take care of them.

But I will look into the ones which aren't labeled translatable in the code or have this weird switching behavior.

**Comment by trebmuh** [comment]
OK, no worries. Thanks for having had a look at it.
After #1100 will be merged, I'll do a rebuild from master, and I'll separate the problems still present here into smaller issue. I will then close this thread that is getting longer and longer and longer and longer...!

**Comment by aaronbcn** [comment]
> I'm unsure about 1 and 4 so, not commenting on those two.
> 
> I can't reproduce 2 and 5 with my build from GIT [b17f662](https://github.com/hydrogen-music/hydrogen/commit/b17f662f49ef32c6825a2ad727fcf1080a28a636) (end of November 2020). Everything is translatable and translated into French for me. @aaronbcn did you updated your translation .ts file?
> 
> I can confirm 3 and 6.
> 
> Here is some details for 3:
> 
> * the green dotted one changes after the selection of a sample
> * strangely, the blue dotted ones change their translations after the selection of a sample
> 
> Before:
> ![3-1](https://user-images.githubusercontent.com/8705846/104222559-c4b98780-5442-11eb-8e52-f5aa7d8067f5.png)
> 
> After:
> ![3-2](https://user-images.githubusercontent.com/8705846/104222564-c8e5a500-5442-11eb-81e8-4d7ff18fa617.png)

Sorry for the late reply.

I suppose the reason why you cannot reproduce the bugs is because the French .ts file has those strings as source text, while I used U.S. English .ts file to localize, which has no strings presented in 2, 4, and 5. 

I have checked in the build [b17f662](https://github.com/hydrogen-music/hydrogen/commit/b17f662f49ef32c6825a2ad727fcf1080a28a636) , and it seems that only French .ts file has these strings.

**Comment by trebmuh** [comment]
As said above @aaronbcn 

> did you updated your translation .ts file?

If not, you probably want to go to the data/i18n/ directory and run the updateTranslations.sh script which will update the ts files.

**Comment by aaronbcn** [comment]
> As said above @aaronbcn
> 
> > did you updated your translation .ts file?
> 
> If not, you probably want to go to the data/i18n/ directory and run the updateTranslations.sh script which will update the ts files.

I believe that I did update it, though there might be some errors as I am not very familiar with GitHub workflow.

I suggest you search "BBT" presented in 5 in the latest files. If I was right, the search would have one hit in French .ts file hit, while in English or Spanish ones, there were not.

**Comment by theGreatWhiteShark** [comment]
> I suggest you search "BBT" presented in 5 in the latest files. If I was right, the search would have one hit in French .ts file, while in English or Spanish ones, there were not.

The BBT stuff was introduced quite recently and @trebmuh already updated the French translation to cover it. We are restructuring some parts and also introduced some new stuff. That's why there might now be even more things that are not present in your .ts file yet. To be sure to not update your translation over and over again, you could wait till #1100 is merged. After that there should be most likely no more changes in the translation till the 1.1 release.

**Comment by trebmuh** [comment]
I've opened #1207 now.
I'm closing this one which is starting to be wayyyyy to long :)
