### ISSUE TITLE
MIDI select playlist song

### ISSUE THREAD

**Issue by michielderoo** [hydrogen-music/hydrogen#410]
The MIDI action PLAYLIST_SONG is not taking the right parameter. On line 769 of midi_action.cpp it  should be pAction->getParameter1() instead of pAction->getParameter2(). I tested it and it works when modified like that.

**Comment by mauser** [comment]
Thanks! It makes indeed more sense to use parameter1. Parameter2 makes only sense for CC messages, so parameter1 makes this action more generic. 

I've pushed the change already to our master branch.
