### ISSUE TITLE
NSM supports fails if NSM session name contains accents

### ISSUE THREAD

**Issue by Houston4444** [hydrogen-music/hydrogen#420]
Hy.
All is in the title. My NSM session name is: éfe
non-session-manager launched from terminal, it says:
(E) SongReader::getPath Song file /home/houston/NSM Sessions/Ã©fe/Hydrogen.nXOYQ not found.

Obviously hydrogen can't open song.

**Comment by mauser** [comment]
Hi! 

Thanks for reporting the issue. The problem is now fixed in our git repository. Hydrogen is now handle any command line arguments with non-ascii charactersets better.

**Comment by trebmuh** [comment]
Written here: https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-1.0
