### ISSUE TITLE
New midi input note: Plays only one pattern in stacked mode.

### ISSUE THREAD

**Issue by vudone** [hydrogen-music/hydrogen#421]
Hi there.

First of all, sorry for my english :)

I write you because i have writte a new patch to the 0.9.7 hydrogen version. 

I have added a new MIDI input action that queued one, and only one, pattern. I use hydrogen with my guitar and foot controller. I want to queue a pattern and I dont want to listen the other patterns in the next loop.

Maybe it could be useful for others.
[hydrogen.0.9.7.patch.zip](https://github.com/hydrogen-music/hydrogen/files/534354/hydrogen.0.9.7.patch.zip)

**Comment by vudone** [comment]
this is the idea. It is inspired in the beatbuddy guitar pedal.

https://www.youtube.com/watch?v=3cJpWb35mN8

:)

**Comment by mauser** [comment]
Hi @vudone , 

thanks for your patch (and the nice demonstration :smile: ) ! I don't have time now to test and merge it, but i will do so for sure after 0.9.7 has been released!

**Comment by heiko-coursera** [comment]
Hi!
@vudone: nice idea, I was looking for a "software beatbuddy"
@mauser: was the patch accepted?

**Comment by elpescado** [comment]
@vudone Nice idea! Maybe could you create a pull request with your patch?

**Comment by vudone** [comment]
mmm

I am not sure about how to do a pull request :(

I thought that the developers could apply the patch directly in the git branch if they considered the pacth interesting.

**Comment by elpescado** [comment]
Hi, There's guide:
https://github.com/hydrogen-music/hydrogen/wiki/How-to-contribute-code-using-Github

**Comment by vudone** [comment]
@elpescado Ok, I have just created the pull request

I have updated my patch from hydrogen 0.9.7 to hydrogen 1.0.0

It is here: https://github.com/hydrogen-music/hydrogen/pull/659

**Comment by jeremyz** [comment]
great, merged !!
