### ISSUE TITLE
Can't post on the forum

### ISSUE THREAD

**Issue by bmentink** [hydrogen-music/hydrogen#424]
Hi, I am trying to post a question on the forum, but can't seem to.

I created a login and password which works ok, I edit a post and see a preview button and then a save button, but there is no "post" button ... and save does not seem to post either,  cause my post does not appear in the category I posted it in (Hydrogen Users)

Help please, where is the post button?

**Comment by trebmuh** [comment]
Try using the preview button first, then the save button may appear after.

**Comment by bmentink** [comment]
I did, but like I said, when I hit save ... nothing happened ... no post in that topic.

**Comment by trebmuh** [comment]
This is normal, there is a moderation process before you're post will appear.

**Comment by mauser** [comment]
As trebmuh already wrote, all posts are moderated. This process can take some time, i'm not monitoring the forum constantly.

**Comment by bmentink** [comment]
ok, thanks
