### ISSUE TITLE
1 drum kit / 1 row

### ISSUE THREAD

**Issue by roseuser** [hydrogen-music/hydrogen#43]
My apologies if this has already been raised before (I'm a Hydrogen newbie) but is it possible to have 1 drum kit and have all its different patterns on 1 row (instead of 1 drum kit with its patterns on multiple rows)?

I think this would enhance your software (and make it even more popular) because....

01 - There would be less of a learning curve (and thus less confusion/easier) for those coming from other software (eg - Cubase) who expect things to be 1 instrument / 1 row.

02 - If everything was on one row you wouldn't need to scroll up and down the list of patterns if you have a lot of patterns in a song (ie - there's less work to do/less clicking involved, especially if you're going from pattern to pattern on a regular basis).

03 - One row would make it easier (from a visual point of view) to work out where the patterns are located on the song's overall grid (eg - if there's a pattern on the 20th row, does it start at position 63 or 64 or 65?).

04 - And, if implemented, only having 1 row of patterns on the screen would mean that there would be more space on the screen for the person to view other parts/features of the program.

Okay, thanks for reading and thanks also for all your time and effort!

**Comment by theGreatWhiteShark** [comment]
> [...] but is it possible to have 1 drum kit and have all its different patterns on 1 row (instead of 1 drum kit with its patterns on multiple rows)?

There is plenty of other software doing this and IMHO the two dimensional grid in the song editor was one of the selling points of the application back than. Anyway, displays are becoming larger and larger than nowadays people ask for scaling factors to make the whole application larger. Space is not an issue anymore.

> what might be interesting (this idea has been posted before) is the option to change the colors of the blocks in the song editor so you can easily see the difference between certain parts of the song or the different patterns

This is already implemented.

> perhaps another way to adress this, without making a major change to the gui (i think) would be (in addition to being able to change the color of a pattern)
1_ to be able to assign a color for each drumkit, and that when we add an instrument, that color gets displayed somehow on the instrument list of the pattern editor
2_ to being able to import an entire drumkit to the pattern editor, in a similar way that we can now add a single instrument
>
> that way we could see now on the pattern editor itself, to what drumkit belongs each instrument, making it easier to compose with different drumkits, and identify more easily the patterns

The drumkits shipped with H2 or available for downloads are in essence just containers around samples and default settings for the associated parameters, like pitch shift, sample volume, mapping to note velocity etc. To talk about independent ones only is useful when loading whole drumkits. If you add individual instruments manually, you effectively create a brand new drumkit and associating the added instruments to the former container via a color does not yield much information. Or another question in this vain: how much can the buttons of the ADSR parameters or pitch be altered with the imported instrument still being the ?same? as the one in the former drumkit?

I will close this issue for now. If you think I may got something wrong, please don't hesitate and reopen it.
