### ISSUE TITLE
instrument layer popup flickers

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#432]
when i hit the layer dropdown button in the instrument editor the popup where i can select main/add/delete/rename pops up but constantly flickers
QT5 related ?

i took a screenshot, but since this is a static picture it doesnt show the flickering  :-)

![image](https://cloud.githubusercontent.com/assets/1384210/20455899/4b641844-ae67-11e6-856f-8f74f1e62f8a.png)

**Comment by trebmuh** [comment]
I can confirm that on a git built with Qt5 from https://github.com/hydrogen-music/hydrogen/commit/b19ba20489588e4b40031235ecd3157610760a85 but not on the 0.9.7 release built with Qt4.
Qt5 migration issue maybe?

**Comment by pvint** [comment]
I am not getting this on mine with QT 5.6.2 - I will try later on another machine with different QT version

**Comment by mauser** [comment]
I can see the behaviour with QT4 and QT5, but not with every QT theme :-/

**Comment by trebmuh** [comment]
more precision on my setup : Qt4 debian stable (Jessie): 4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 , Qt5 debian stable (Jessie): 5.3.2-3 .

**Comment by xnakos** [comment]
There is something really wrong here. Try this patch on the latest master:

```
diff --git a/src/gui/src/InstrumentEditor/InstrumentEditor.cpp b/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
index 0698f6f..30a5413 100644
--- a/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
+++ b/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
@@ -632,6 +632,7 @@ void InstrumentEditor::selectedInstrumentChangedEvent()
                itemsCompo.append("add");
                itemsCompo.append("delete");
                itemsCompo.append("rename");
+               std::cout << "haha" << std::endl;
 
                update();
 
```

Compile, run, and see what happens. Spoiler alert for what follows.

Right from launching it prints "haha" without stopping.

I tried the patch on the 0.9.7 version (`458b39c224b64c44f8a66482f7da4d74bde845c3`, `Updated man page`) and it printed 5 "haha" when launching. It also printed 2 "haha" after each operation, e.g. add or delete. Just some quick testing. I am on Qt 5.5.1.

**Comment by thijz** [comment]
@xnakos : i dont get it ... what is so funny about this bug ??  ;-D

when i switch to the 'windows' theme the flickering is not there any more
using Qt version 5.5.1

**Comment by mauser** [comment]
Hi, 

thanks @xnakos , that made it easier for me to spot the problem. The problem has been introduced in #137 by adding a timer which triggers the selectedInstrumentChanged event a lot. This has slipped my attention when accepting/merging that pull request. 

IMHO the QTimer is the wrong approach here. The core should notify the gui via an event.. 

I've pushed a fix to the master branch which removes the timer. This breaks the gui update for the added actions at the moment, but i'm currently working on the midi code (other parts..) and will fix that later on with my changes..

**Comment by jdekozak** [comment]
Hi @mauser,

Quote : "The core should notify the gui via an event.."

I have introduced the problem, so I would be glad to help you here, but I don't understand your sentence, would you please add some details or pointers at the code ?

Regards,

**Comment by mauser** [comment]
Hello Julien! 

The core of hydrogen should push notifications about state updates to the user interfaces by using an event. The event is added to an event queue by the core (in this case, the midi action manager). The user interface (HydrogenApp::onEventQueueTimer()) polls this queue and looks for new events. 
If it discovers a new, it populates this event to all attached event handlers. 

For an example the core pushes a metronome event to this queue, which gets consumed by HydrogenApp. HydrogenApp then calls the corresponding EventListener which updates the Gui State to create a blinking led (which represents the metronome ticks).

**Comment by jdekozak** [comment]
Hi,

I have read the code, and I understand what to do, but I have a question before trying to submit something.

Do you expect a new event to be dedicated to this or am I allowed to reuse one that already triggers UI refresh ?

Regards,
