### ISSUE TITLE
compile problem: ‘songFilename’ was not declared in this scope

### ISSUE THREAD

**Issue by jduemes** [hydrogen-music/hydrogen#452]
Hi Folks,

I am really not sure if this is the right place for this kind of report, anyway... I am getting this errror:

`/tmp/yaourt-tmp-jduemes/aur-hydrogen-git/src/hydrogen/src/gui/src/main.cpp: In function ‘int main(int, char**)’:
/tmp/yaourt-tmp-jduemes/aur-hydrogen-git/src/hydrogen/src/gui/src/main.cpp:312:6: error: ‘songFilename’ was not declared in this scope
      songFilename = "";
      ^~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
make[2]: *** [src/gui/CMakeFiles/hydrogen.dir/build.make:1656: src/gui/CMakeFiles/hydrogen.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:402: src/gui/CMakeFiles/hydrogen.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
`

I don't understand C++ but I think (songFilename = "";) is not the C++ way to declare variables, is it ?

PS 1.: I am using a Arch Linux tool which automates the compile process in this Distro. As I can understand, it clones the source codes from git to temporary dir, compiles and packages it.

**Comment by mauser** [comment]
Hi,

this should be fixed now. The code did not compile when LASH was activated, i've tested my changes only without LASH support.

**Comment by jduemes** [comment]
Hi Sebastian,
thanks a lot, it compiled now. But the raptor libs on my system are under /usr/include/raptor2 which for some reason can not be found by the compilation process. I did a dirty fix sym-linking raptor.h and raptor2.h to /usr/include and it compiled very fine.

Is only me or H2 is opening faster now ?

I don't even know what lash is for but if I activate "Use lash" on H2 and reinitialize it, I get a core dump. I need to edit hydrogen.conf and deactivate it again to have H2 back to work.

**Comment by pvint** [comment]
Regarding the raptor2 bit - I have had the same things on my Gentoo machine, but it doesn't seem to be an issue with any other machine.

If you have a minute, can you let me know what distribution you are running, and also the output from "`pkg-config raptor2 --cflags`" please?

Also, one more thing I would be interested to see - if you remove the symlink, then in CMakeLists.txt remove "RAPTOR2" from line 257 and try rebuilding (do `./build.s r` and them `./build.sh m` ) ie:
`SET(STATUS_LIST LIBSNDFILE LIBTAR LIBARCHIVE LADSPA ALSA OSS JACK JACKSESSION NSMSESSION COREAUDIO COREMIDI PORTAUDIO PORTMIDI PULSEAUDIO LASH LRDF RUBBERBAND CPPUNIT )`

Paul

**Comment by jduemes** [comment]
Hi Paul,

I am running and compiling H2 on machines with Arch Linux distro.
$ pkg-config raptor2 --cflags
-I/usr/include/raptor2

If I remove the raptor symlinks the compilation does NOT work anymore.

The only "raptor" I can find in CMakeLists.txt is on line 236 (257 is empty).
FIND_HELPER(RAPTOR raptor2 raptor.h raptor).

**Comment by mauser** [comment]
Hi,

I'm closing this issue since the original compile problem has been resolved. The raptor2 issue is already documented in other issues.
