### ISSUE TITLE
Clean of of Error messages when loading drumkit

### ISSUE THREAD

**Issue by pvint** [hydrogen-music/hydrogen#457]
There are some misleading "Errors" that show up in the console when loading drumkits. Not a big deal, but it is a bit misleading and I wanted to get this on here as a reminder for myself. 

Example:

`(E) XMLDoc::read XML document /home/pvint/.hydrogen/data/drumkits/becks/drumkit.xml is not valid (/usr/local/src/hydrogen/data/xsd/drumkit.xsd), loading may fail
(E) Legacy::load_drumkit this code should not be used anymore, it belongs to 0.9.6`

The first one is a valid message, but it is not really an "error" since what it is warning you about normally isn't a problem (ie: the kit loads fine). I say we demote this from being an "Error" to a "Warning"

The second one, IIRC is because of a "legacy" kit causing legacy code to run. There may be something n the code to improve to prevent this, but if not, I think we should also change this to a "Warning" so it doesn't confuse or mislead users.

**Comment by trebmuh** [comment]
It would be great. I agree that it's misleading for an user.

**Comment by thijz** [comment]
+1

**Comment by mauser** [comment]
Hi! 

The most error messages which were coming from a failed XSD check should be gone now (or more precise: they are now warnings). There will be still warning from the XSD parser, but those are not from our logging system. I will see if i can silence those warnings as well..
