### ISSUE TITLE
Overhead - Direct - Under

### ISSUE THREAD

**Issue by blablack** [hydrogen-music/hydrogen#46]
Hello, 

Some drumkit libraries I own have three types of files representing where the mic was when the recording was done:
- Overhead: Two or more mics over the whole drumkit
- Direct: One mic for each instruments directly on top of it
- Under: One mic for each instruments directly under it.

The way you would mix them is that at the general drumkit level, you would define how much of the overhead you want for example compared to the direct takes (more overhead makes the drumkit sound further away).

This would be great to have that in Hydrogen as it would really make it compete with big names in drumkit software.

If you would like more information, let me know!

Aurélien

**Comment by mauser** [comment]
This is now part of hydrogen (0.9.7).
