### ISSUE TITLE
Bad OSX Download Link on Webpage

### ISSUE THREAD

**Issue by oblivionratula** [hydrogen-music/hydrogen#461]
I'm not sure if this is the right place to report this, but:

On the download page (http://hydrogen.popez.org/hcms/node/21 ), the link for "MacOS X binaries (0.9.7):  OS X (Intel)" is dead. 

Link address is: http://hydrogen.popez.org/hcms/node/%20%20https://sourceforge.net/projects/hydrogen/files/Hydrogen/0.9.7%20Binaries/Hydrogen-0.9.7.dmg/download

Result is "Page not found."

**Comment by pvint** [comment]
This is a good place to report it, thanks!

I don't think I have access to that - but I took a look, and it looks like just an error in a Copy-Paste.

@mauser  The link simply has '%20%20' in front of the "https" in the URL.  :)

@oblivionratula  I presume you found it, but just in case the correct link is https://sourceforge.net/projects/hydrogen/files/Hydrogen/0.9.7%20Binaries/Hydrogen-0.9.7.dmg/download

Paul

**Comment by oblivionratula** [comment]
@pvint I did, thank you. Unfortunately I'm still on 10.10 and it requires 10.12. I'll stick a pin in this and revisit it. I used Hydrogen on linux several years ago. Never thought of running it on OSX until now.

**Comment by mauser** [comment]
Thanks for reporting the broken link, it should work now!

**Comment by elpescado** [comment]
I have contributed Mac builds, so I'll take a look at compatibility issues. In the meantime, you could try one of earlier releases (-rc1 or -beta3). I used to test them on 10.8 VM, so they should work on 10.10.

https://sourceforge.net/projects/hydrogen/files/Hydrogen/0.9.7%20Binaries/

**Comment by elpescado** [comment]
@oblivionratula could you post error messages that you are getting while running Hydrogen on OSX 10.10, preferably as a new issue? I could look into that issue. I have run 0.9.7 dmg on 10.8 VM without problems. I don't have 10.10 installation at the moment, though.
