### ISSUE TITLE
Export dialog: Mute and Solo lost after exporting

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#465]
The mute and solo settings of all instruments are lost after a song is exported as a wav file.

**Comment by mauser** [comment]
Fixed with 48e69ef.

**Comment by trebmuh** [comment]
Added here : https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-1.0#fixes-for-the-export-dialog
