### ISSUE TITLE
Export dialog: Save defaults

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#466]
The export dialog always forgets the current setting (Directory, export mode, sample rate etc). It forgets those settings even between different exports in the same session...  

The dialog should save those settings and present them to the user the next time the dialog is opened.

**Comment by theGreatWhiteShark** [comment]
Implemented in bc575989fb5009433cae9ad7ce9f9741901d5dd2 and e77bce75fe0c796f88c06b7bd698f45fb0a22a9f
