### ISSUE TITLE
Export dialog: Notes being played after export is finished

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#468]
Sometimes a number of notes are being played after an export has been done. The notes are being played in an short interval.

**Comment by mauser** [comment]
Fixed with 48e69ef386c35afb4aba19fb78bfc401eb3cbef5.

**Comment by trebmuh** [comment]
Added here : https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-1.0#fixes-for-the-export-dialog
