### ISSUE TITLE
F12 (panic) should also send out a 'stop all notes' midi mesage

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#473]
when you use H2 as sequencer for external synths (via MIDI) it sometimes happens that the synth received a note ON, but never receives a note OFF message
This can happen when you mess around with patterns or during the creation of the pattern

for F12 to be a real panic button it should also send a 'all notes off' message to all midi channels that are in use by 1 or more instruments
this is currently not the case : only the internal sampler is muted and a note off is sent out on the 'base' note of each midi-enabled instrument

**Comment by mauser** [comment]
I suppose that it would make sense that this functionality should also be reachable via the GUI..

**Comment by jduemes** [comment]
I am not aware wheter it already exists or not a discussion about this somewhere, but tt is also very useful to be able to choose what key is going to be the panic button. And to be able to trigger it via midi.

**Comment by thijz** [comment]
closing since all midi related stuff will be gathered here : 
https://github.com/hydrogen-music/hydrogen/issues/63
https://github.com/hydrogen-music/hydrogen/wiki/MIDI-implementation
