### ISSUE TITLE
H2 crashes when adding a new layer and rubberband is on

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#474]
steps to reproduce:
1) open a new song and disable rubberband
2) goto Instrument tab > Layers
3) click on the dropdown next to 'Main'
4) select 'Add' and create a new layer called 'BASS', hit OK
5) enable rubberband
6) H2 crashes

running H2 with verbose output does not give me more info
all i get is 'segmentation fault (core dumped)'

**Comment by trebmuh** [comment]
confirmed from a fresh rebuild https://github.com/hydrogen-music/hydrogen/commit/ff19658563afddd96ac6e08b3ef7e809694c2a6a

**Comment by xnakos** [comment]
QuickCrash:

1. Launch Hydrogen
2. Layers -> Dropdown -> add -> OK
3. Toggle Rubberband OFF
4. Toggle Rubberband ON

Try this:

```
diff --git a/src/gui/src/InstrumentEditor/InstrumentEditor.cpp b/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
index 0698f6f..46a62a1 100644
--- a/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
+++ b/src/gui/src/InstrumentEditor/InstrumentEditor.cpp
@@ -1351,7 +1351,11 @@ void InstrumentEditor::rubberbandbpmchangeEvent()
                        assert( pInstr );
                        if ( pInstr ){
                                for ( int nLayer = 0; nLayer < MAX_LAYERS; nLayer++ ) {
+                    std::cout << "m_nSelectedComponent = " << m_nSelectedComponent << std::endl;
+                    assert(pInstr->get_component(m_nSelectedComponent));
+                    std::cout << "Assert was fine" << std::endl;
                                        InstrumentLayer *pLayer = pInstr->get_component(m_nSelectedComponent)->get_layer( nLayer );
+                    std::cout << "The above would crash" << std::endl;
                                        if ( pLayer ) {
                                                Sample *pSample = pLayer->get_sample();
                                                if ( pSample ) {
```

It should output this:

```
m_nSelectedComponent = 1
hydrogen: /home/xnakos/Projects/hydrogen/src/gui/src/InstrumentEditor/InstrumentEditor.cpp:1355: virtual void InstrumentEditor::rubberbandbpmchangeEvent(): Assertion `pInstr->get_component(m_nSelectedComponent)' failed.
Aborted (core dumped)
```

**Comment by jeremyz** [comment]
remember : gdb is your friend

#0  0x0000555555677778 in H2Core::InstrumentComponent::get_layer(int) (this=0x0, idx=0) at /home/jeyzu/usr/git/hydrogen/src/core/include/hydrogen/basics/instrument_component.h:109
#1  0x00005555556869e2 in InstrumentEditor::rubberbandbpmchangeEvent() (this=0x555555f5bb90) at /home/jeyzu/usr/git/hydrogen/src/gui/src/InstrumentEditor/InstrumentEditor.cpp:1387

this=0x0 call to H2Core::InstrumentComponent::get_layer(int)
component is null !!

**Comment by jeremyz** [comment]
27d664c0480adbaf6e14ce71b0cbc1
