### ISSUE TITLE
is there a binary for OSX 10.11.6 ?

### ISSUE THREAD

**Issue by ainthek** [hydrogen-music/hydrogen#475]
thanx a lot

**Comment by elpescado** [comment]
There's Mac binarny on Download page.
http://www.hydrogen-music.org/hcms/node/21

**Comment by ainthek** [comment]
Thanx, the question is for OSX 10.11.6
IMHO: None of the binaries there can be installed on EL Capitan

Latest binary says: OSX 10.12 required

Thanx for help

**Comment by elpescado** [comment]
Hi,

Thanks for your report. I build Mac packages on Sierra (10.12) and test on Mountain Lion VM (10.8) to ensure backwards compatibility. I have to look into this issue, but I need some time, as I don't have currently any El Capitan VM.

In the meantime: Could you post exact error message?

![virtualbox_mountain lion_12_02_2017_18_23_58](https://cloud.githubusercontent.com/assets/1619113/22865180/e428624e-f15e-11e6-82ed-375e5c30a7d5.png)

**Comment by ainthek** [comment]
Sorry, i gave up and have upgraded to Siera already:-(
