### ISSUE TITLE
add in-app 'gather system info' function and/or 'create bug report' function

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#481]
it would be nice to have a 'gather system info' function in H2, and maybe even a 'create bug report' option

This would be especially handy for the less tech-savvy H2 users, just to avoid that we need to ask questions like 'what OS are you using, what H2 version are you running, what audio driver and version are you using ...

**Comment by trebmuh** [comment]
What a clever idea!

**Comment by mauser** [comment]
Hi! 

I would like to close this feature request as this seems to be unrealistic for Hydrogen, at least at the moment. 

This would require some server-side infrastructure for gathering bug reports. Besides this, it would rise legal questions about which kind of data we can collect etc. In my opinion the benefit of this feature would not be large enough to justify the effort to implement such a system.
