### ISSUE TITLE
h2synth

### ISSUE THREAD

**Issue by ndowens** [hydrogen-music/hydrogen#485]
I am getting include/hydrogen/hydrogen.h:60: static H2Core::Hydrogen* H2Core::Hydrogen::get_instance(): Assertion `__instance' failed. When running h2synth

**Comment by mauser** [comment]
Hi! 

Is there a specific reason/use case for which you need h2synth? I've always thought about removing it since h2cli is part of hydrogen.

**Comment by ndowens** [comment]
Not for me no. Trying to package it for nixos

**Comment by mauser** [comment]
Thanks for the feedback! 

I've removed h2synth now from hydrogen. If someone stumbles upon this issue and used h2synth for a feature which isn't in h2cli, please contact me.
