### ISSUE TITLE
website: typo on front page

### ISSUE THREAD

**Issue by bradfitz** [hydrogen-music/hydrogen#486]
http://www.hydrogen-music.org/hcms/ says:

> It's main goal is to bring professional yet simple and intuitive pattern-based drum programming.

That first word should be **Its** without the apostrophe. (possessive, not a contraction)

I tried to find the code to send a patch, but looks like it's in a CMS somewhere.

**Comment by mauser** [comment]
Hi! 

Thanks for the hint, should be fixed now!
