### ISSUE TITLE
Revisiting raptor2: New configuration misses include

### ISSUE THREAD

**Issue by schivmeister** [hydrogen-music/hydrogen#496]
I refer to an older issue https://github.com/hydrogen-music/hydrogen/issues/194

And:

- https://github.com/hydrogen-music/hydrogen/issues/342
- https://github.com/hydrogen-music/hydrogen/pull/395

I apologize for not being able to test that last change to the CMake config, but now that I did (I left hydrogen out-of-date on Arch Linux for a long time), it appears @mauser's suspicions came true..

This is what make tries to do:

```
[  0%] Building CXX object src/core/CMakeFiles/hydrogen-core-0.9.7.dir/src/fx/effects.cpp.o
cd /home/schiv/arch/hydrogen/trunk/src/hydrogen-0.9.7/src/core && /usr/bin/c++   -Dhydrogen_core_0_9_7_EXPORTS -I/home/schiv/arch/hydrogen/trunk/src/hydrogen-0.9.7/src/core/include -I/home/schiv/arch/hydrogen/trunk/src/hydrogen-0.9.7/include -I/usr/include/qt4/QtDesigner -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4/QtScriptTools -I/usr/include/qt4/QtDBus -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/phonon -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtWebKit -I/usr/include/qt4/QtHelp -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtTest -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtSvg -I/usr/include/qt4/Qt3Support -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore -I/usr/share/qt4/mkspecs/default -I/usr/include/qt4  -O2 -std=gnu++11 -Wno-deprecated-register -fno-implement-inlines -g  -fPIC   -o CMakeFiles/hydrogen-core-0.9.7.dir/src/fx/effects.cpp.o -c /home/schiv/arch/hydrogen/trunk/src/hydrogen-0.9.7/src/core/src/fx/effects.cpp
In file included from /home/schiv/arch/hydrogen/trunk/src/hydrogen-0.9.7/src/core/src/fx/effects.cpp:36:0:
/usr/include/lrdf.h:8:20: fatal error: raptor.h: No such file or directory
 #include <raptor.h>
                    ^
```

Notice that there is no `-I/usr/include/raptor2`, but that is what is needed and is what makes this behave. I am not exactly sure how to make CMake include that using the existing approach, but it shouldn't be too difficult or unusual, as the LRDF stack pretty much assumes a standard toolchain.

In the worst case, this can be included in the global headers if raptor2 is found.

**Comment by vladimir-kirillovskiy** [comment]
I've created a PR which possibly will fix this issue. It works for me on Arch Linux, but I'm not sure about other systems as I only use Arch.

**Comment by mauser** [comment]
Hi, 

the fix for this problem is now available in the master branch. Could someone else re-test this on arch linux?

**Comment by jeremyz** [comment]
yes check please, it seems to be fixed
#521

**Comment by pvint** [comment]
Also tested on my Gentoo system that had the same issue and works fine now! :)
