### ISSUE TITLE
Swing function not working

### ISSUE THREAD

**Issue by funkypou** [hydrogen-music/hydrogen#497]
Hi. Thank you for this beautiful piece of software.

I've tried version 0.9.6.1 in Xubuntu 16.04 and Debian Jessie Xfce. I have the same issue with both computers : the swing knob has no effect even at the max position (no shuffle on 8th notes).
I installed the kxstudio ppa on Xubuntu to get version 0.9.7.2 but the issue is still there.
If I can help by giving more information or doing further testing, let me know.

**Comment by trebmuh** [comment]
confirmed with Hydrogen from git 3002477

**Comment by funkypou** [comment]
Hi trebmuh. Thanks for answering me.
Sorry but I don't understand what you mean. Firstly,  your link is about velocity. I don't know if this piece of code manages the swing function. And I'm not used to the functioning of Github so I don't know what to do after seeing this commit.

**Comment by trebmuh** [comment]
I was just confirming that the same is happening to me with Hydrogen built from the git revision 30002477. My previous message wasn't really for you but an information for the Hydrogen developers.

**Comment by theGreatWhiteShark** [comment]
As of version 1.1 this bug is resolved. For a discussion about the details of how the swing does work please see https://github.com/hydrogen-music/hydrogen/discussions/1328
