### ISSUE TITLE
Saving doesn't work as it should

### ISSUE THREAD

**Issue by mmj12** [hydrogen-music/hydrogen#498]
When I go to save my song on the Windows 0.97 version, it doesn't save any new positions of the patterns, they appear only like they did when I made the first save. Other things like bpm markings and the patterns themselves are saved, but not how the patterns are positioned on the track.

**Comment by mauser** [comment]
Hi @mmj12 ! 

What do you mean by "how the patterns are positioned on the track" ? Could you make a screenshot before saving vs. after loading?

**Comment by mmj12** [comment]
![before](https://cloud.githubusercontent.com/assets/28447635/25770420/abad4cde-323d-11e7-93f9-41c06591a4e4.png)
![after](https://cloud.githubusercontent.com/assets/28447635/25770421/afa60290-323d-11e7-8e3b-e27f9924a563.png)

Everything is the same, including the number of blue dots, but the positions change. And only some of them, weirdly enough.

**Comment by mauser** [comment]
Hi! 

it seems that you have two patterns in the song which are named both "Pattern 2". This is not supported by Hydrogen, the patterns must have a unique name. This is the reason why the elements of the second "Pattern 2" appear in the first "Pattern 2". Have you an idea how you ended up with two Patterns named "Pattern 2" ? 

The only way i have found is to drag a pattern from the soundlibrary to the song editor.

**Comment by mmj12** [comment]
I just imported a pattern called "pattern 2" that I'd saved previously and it seemed to work fine as I didn't get any error message. Didn't find a reason to rename it as I remembered what it was there for. But thanks for the explanation, it all makes sense now.

**Comment by mauser** [comment]
Thanks! i've added some checks yesterday which should prevent this situation in the future..
