### ISSUE TITLE
No sound MAX_LAYERS higher than 16

### ISSUE THREAD

**Issue by blablack** [hydrogen-music/hydrogen#501]
Hello,

Since Hydrogen supports round robin, my drumkits now have many layers and I need to compile Hydrogen with a higher MAX_LAYERS than 16 in the CMakeLists.

In the latest git, if I increase the MaxLayers I do not get any sound - I tracked it down to commit 48e69ef386c35afb4aba19fb78bfc401eb3cbef5 as the first one not working.

To summarize:
* 48e69ef386c35afb4aba19fb78bfc401eb3cbef5 with MAX_LAYERS = 64 - NO SOUND
* 48e69ef386c35afb4aba19fb78bfc401eb3cbef5 with MAX_LAYERS = 16 - SOUND
* 22af78405f7243153b62be33703cff311f4d06db (previous commit) with MAX_LAYERS = 64 - SOUND

After further investigation, I narrowed it down to this line in the sampler:
`bool isMutedForExport = (pEngine->getIsExportSessionActive() && !pInstr->is_currently_exported());`

It seems to always return true with MAX_LAYERS higher than 16.

**Comment by mauser** [comment]
Hi @blablack ,

that was my commit.. I will have a look at the problem, but i can't promise if it will be the case before the weekend..

**Comment by elpescado** [comment]
Round robins are implemented as multiple layers with overlapping velocity ranges, am I right? If so, maybe we should think about increasing default for this number, as 16 sounds very limiting these days. Not mentioning that I have seen drumkits with 127 velocity layers alone...

BTW, whats the reason for this limit?

**Comment by mauser** [comment]
@blablack: Aurelien, could you please re-test the latest master branch? It seems like an unitialized member caused the trouble.

@elpescado : Those limits are quite old... we discussed that limit when PCs with 512mb ram were common and disk streaming was the big thing to enable the use of large sample libraries. I have no idea what the exact reasons were to limit the number of layers in the first place.. maybe to make loops more efficient which are looping up to MAX_LAYER? Those can be found quite often in the time critical sections / audio driver callback.

**Comment by elpescado** [comment]
Maybe we could store layers in a `std::vector` instead of fixed size array?

**Comment by blablack** [comment]
@mauser Yes it is fixed

**Comment by mauser** [comment]
@elpescado: Dynamic data structures are tricky in realtime threads. You have to make sure that they don't resize. This is possible with std::vector, but more complicated than using plain C arrays. In hydrogen we've tried to avoid such data structures in the realtime code paths. What would really be needed is that someone has to go through our code, have a look where MAX_LAYER is used and make some timing benchmarks. 

@blablack : Thanks for testing!

**Comment by elpescado** [comment]
OK, I get it now. I'm not much familiar with realtime programming.

However, the layers vector shouldn't resize during "normal" playback - only when user modifies instrument settings, which is quite rare event. Or am I missing something?

**Comment by mauser** [comment]
Hi! 

Yes, the std::vector is even capable of manually allocating memory up-front (have a look at http://www.embedded.com/design/programming-languages-and-tools/4429790/How-to-make-C--more-real-time-friendly for a good discussion). 

But using a run-time configurable number of layers would also be technically possible without std::vector, so this is really not the problem at this point. It has to be analysed why this is a build-time constant in the first place and what depends on it..
