### ISSUE TITLE
Tags moveable/shiftable 

### ISSUE THREAD

**Issue by jduemes** [hydrogen-music/hydrogen#503]
Inside the tags editor is possible to move tags of a selected range of bars grabbing them with left mouse button **(1)**. But this is not very practical if you want to move let's say a range - from a given point till the end of the song - beyond the end of the song, extending the length of it.

I really believe that the above described desired behavior should be possible to achieve, because after all the work of tagging a song one finds out some bars were forgotten at the beginning of the song.

**(1)** the tags in this case are in fact copied and not moved. I understand the copy-behavior should also be there but only if the user wants that, using a modifier like the CTRL key, for instance.

**OS:** Arch Linux
Hydrogen 1.0.0-'4ba33f83'

**Comment by mauser** [comment]
Hi! 

Is this the same issue as https://github.com/hydrogen-music/hydrogen/issues/30 ? Or do you want to move the tags without the need to open the tag editor?

**Comment by jduemes** [comment]
Yes Sebastian, 
I just realized I mixed up two different problems in my comment. Pinecone1200 referred to one of them(1) using other names and described the problem from a different perspective.

1. the user try to move the tag's content from one bar to another bar and tags editor act visually like this move action has been done, but in reality the content has been copied. The user only notice that the content was copied and messed up after reopening tags editor. This is confusing and sounds like a bug.

The other thing I was talking about:
2. Inside the tag editor to be able to insert tags beyond the end of the song. I use the Director in the same way Pinecone1200 described, building the song structure in H2 which helps me to learn the song.

**Comment by mauser** [comment]
Ok! Then i get your idea. In theory we could enlarge the list to the maxium number of song squares. I'm not sure if this is a good idea from the usability point of view. But on the other hand, the usability of this dialog is already quite bad :) 

I suppose it might be easier to add tags by right-clicking on the timeline. In addition, i guess it would be nice if there would be a tooltip at those "T" icons which shows the name of the tag. There much to be improved on this feature...

**Comment by jduemes** [comment]
I am totally for a change on that "T". The "T" makes difficult to visualize the timeline numbers. I think maybe a "-" or a "." would be enough.

**Comment by trebmuh** [comment]
+1 for the "T" tooltip showing the tag name. Great idea!
