### ISSUE TITLE
Song Editor not being displayed

### ISSUE THREAD

**Issue by CianOG123** [hydrogen-music/hydrogen#504]
I am running windows 10. I tried Hydrogen 0.9.6 and 0.9.7 both of them seem to have this problem. The song editor is not being displayed and I don't know why. Please help.
![image](https://cloud.githubusercontent.com/assets/29048772/26560578/b039ddf6-44af-11e7-9b54-7e4d076bda17.png)

**Comment by mikotoiii** [comment]
Could be a configuration issue. Try deleting the hydrogen config found at: C:/Users/username/.hydrogen/hydrogen.config

**Comment by CianOG123** [comment]
Thanks that fixed it, you're a life saver.
