### ISSUE TITLE
Enhancement - Indicator for open windows

### ISSUE THREAD

**Issue by mikotoiii** [hydrogen-music/hydrogen#505]
I was playing around with Hydrogen on a single monitor system today, and noticed that there is no indication when you have additional windows open like the mixer, director, playlist editor, etc. 

Since these things are sometimes useful to have open, and can be buried by other windows, especially on multi-monitor systems, having a check mark or something similar to indicate the open windows in the tools drop down would be useful, especially in determining if you're turning a feature on or off. 

Most programs have a similar indicator to show which toolbars and options you have selected.

It also looks like there is reserved space for something like that, though I haven't looked at the code to confirm, and can't remember if previous versions did this. Tried it on commit d162754 compiled for Windows X64, and on the latest commit a530b90 compiled for Debian.

**Comment by mauser** [comment]
Hi @mikotoiii! 

Thanks for the suggestion, i like the idea. To my knowledge, earlier versions of hydrogen haven't supported this.

**Comment by vladimir-kirillovskiy** [comment]
I've implemented this feature and added pull request you can review. 
https://github.com/hydrogen-music/hydrogen/pull/511

**Comment by mauser** [comment]
Hi! 

The feature is now in the main branch.
