### ISSUE TITLE
Song editor next to the patterns is not showing 

### ISSUE THREAD

**Issue by blinkfan1** [hydrogen-music/hydrogen#506]
the color squares for song editor is not showing and it is not letting me pick the order of which patterns I want to take place so I can only play a pattern and a time :(

**Comment by mauser** [comment]
Hi! 

Is this the same situation as in this [issue](https://github.com/hydrogen-music/hydrogen/issues/504)? If yes, could you attach your hydrogen config file (C:/Users/username/.hydrogen/hydrogen.config) to this issue before deleting/renaming the file?

**Comment by blinkfan1** [comment]
awesome it worked like that!!! and thank you !!!! I was worried lol
