### ISSUE TITLE
playlists will not open

### ISSUE THREAD

**Issue by smneeb** [hydrogen-music/hydrogen#507]
Running Hydrogen 0.9.6.1, on more than one (type of) computer, one running lubuntu, one running raspbian.
Hydrogen fails to open playlists in both the gui's playlist editor, and at the terminal using -p.
Output at the terminal:
> (E) PlaylistDialog::loadList Error loading the playlist

Playlists work when you are creating them, but once they are saved and you attempt to reopen, you get nothing.
Looking at the playlists, they are normal looking xml.

**Comment by mauser** [comment]
Hi! 

The bug is reproducible for me. 
I remember that there have been some bugfixes for the Playlist handling in Hydorgen 0.9.7. Could you try that version on your systems?

**Comment by smneeb** [comment]
I confirm that Hydrogen 0.9.7 seems to fix it. Sorry to bother, I just hadn't tried the newest version since it isn't included in most repositories. After compiling 0.9.7, playlists load normally.

Thanks

**Comment by mauser** [comment]
Hi! 

No worries, it was absolutely ok to create this issue. Great that it works in 0.9.7!
