### ISSUE TITLE
No mention of currently used license except in the program

### ISSUE THREAD

**Issue by mikotoiii** [hydrogen-music/hydrogen#510]
Hey,

I happened to be doing some poking around in the source to double check the license, only to find that the only place I could find it was in the binary of the program itself. Checking against other open source projects, most have a LICENSE doc in the root of the project which outlines which license the developers, contributors, and users need to adhere to.

Should be an easy enough fix to put it into the root of the project. We can also make sure that it is copied into the Windows package when a fat build is chosen. Since the main release of Hydrogen for Windows is as a pre-compiled binary anyway, and the source code is not present it might not matter if we include the license outside the binary (I'm not 100% on this though).

**Comment by mauser** [comment]
Hi! 

We have a COPYING file at the root level which includes the license. 

The website: http://www.gnu.org/licenses/gpl-howto.html says:

> You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs the license is usually in a file called COPYING.

Does this soive your issue? Or did you meant sth. else?

**Comment by mikotoiii** [comment]
Nope, that's the file, I just didn't see it. (Was pretty sure I checked every file but must have missed that one). Consider this a non-issue.
