### ISSUE TITLE
Menu View/Director appears twice

### ISSUE THREAD

**Issue by jduemes** [hydrogen-music/hydrogen#512]
I just compiled H2 and the Director entry inside the View menu appears twice.

Running system:
$ hydrogen --version
Hydrogen 1.0.0-'fb64b7f7'
$ uname -r
4.11.6-1-ARCH

**Comment by mauser** [comment]
Hi! 

Thanks for the report, this happend during a merge and will be fixed soon..

**Comment by mauser** [comment]
The issue has been resolved now.
