### ISSUE TITLE
The font selection in Appearance Tab - what for ?

### ISSUE THREAD

**Issue by jduemes** [hydrogen-music/hydrogen#514]
![screenshot_20170703_133835](https://user-images.githubusercontent.com/1682407/27791570-fc9c2b2a-5ff5-11e7-9d5c-a281c014bf2f.png)
It is not clear for me what for are the two font selection in Appearance Tab. The first one - I just noticed - controls the font shape of the song ruler counter in song editor. The second one sometimes has effect on the font shape of pattern names but not on the font shape of instrument names.

**Comment by theGreatWhiteShark** [comment]
This will be covered by #1271

**Comment by theGreatWhiteShark** [comment]
implemented in #1271 and #1282
