### ISSUE TITLE
Song ruler and horizontal scroll problems

### ISSUE THREAD

**Issue by jduemes** [hydrogen-music/hydrogen#515]
1. Song ruler does not scrolls anymore and
2. The automatic horizontal scroll jumps to the "end of the solar system" when playing a big(1) song and the playhead reaches the not visible part of the song.

(1) big here means a song bigger than the window. 

Running system:
$ hydrogen --version
Hydrogen 1.0.0-'fb64b7f7'
$ uname -r
4.11.6-3-ARCH

**Comment by mauser** [comment]
Hi! 

I guess that the song ruler scroll problem is caused by my Playbacktrack changes. Thanks for reporting the problem!

**Comment by mauser** [comment]
Hi! 

This issue is now solved with in the current master branch of Hydrogen.
