### ISSUE TITLE
More than one tag a bar / Tag edition disappears

### ISSUE THREAD

**Issue by jduemes** [hydrogen-music/hydrogen#517]
Some times when I use tags editor I re-edit a tag but the change disappears.

Using a text editor I took a look inside the song file and found my change in there. As you can see here:
```
  <newTAG>
   <BAR>53</BAR>
   <TAG>|eyes                |were s-</TAG>
  </newTAG>
  <newTAG>
   <BAR>53</BAR>
   <TAG>|eyes                       |were s-</TAG>
  </newTAG>
  <newTAG>
   <BAR>53</BAR>
   <TAG>|eyes                       |were s-</TAG>
  </newTAG>
  <newTAG>
   <BAR>53</BAR>
   <TAG>|eyes                       |were s-</TAG>
  </newTAG>
  <newTAG>
   <BAR>54</BAR>
   <TAG>|tabbed                       |by the</TAG>
  </newTAG>
```

Notice the repetition of tags for the same bar number.

IMPORTANT: This is not a new problem and happens on all different compilations of recent versions of Hydrogen.

**Comment by pvint** [comment]
I haven't been able to reproduce this.

Questions:
1. You said "sometimes" it happens - is it possible to find a process to reproduce the issue?
2. You mentioned that it was tested on recent versions - was it recent versions from git or from release versions?

Thanks for the report!

**Comment by jduemes** [comment]
> I haven't been able to reproduce this.

I just tried a fresh installation of 0.9.6.1 (from Arch Linux repo) without removing the ".hydrogen" directory: it happened on my first try. After I removed ".hydrogen" the problem does NOT happen. But I have many files with this problem.

> You mentioned that it was tested on recent versions - was it recent versions from git or from release versions?

I normally compile the master branch from git. Well, the yaourt tool from Arch does it for me. :-P

On my first attempt with Hydrogen 1.0.0-'9c99b935':
```
  <newTAG>
   <BAR>0</BAR>
   <TAG>firt</TAG>
  </newTAG>
  <newTAG>
   <BAR>1</BAR>
   <TAG>secnd</TAG>
  </newTAG>
  <newTAG>
   <BAR>1</BAR>
   <TAG>secnd</TAG>
  </newTAG>
  <newTAG>
   <BAR>2</BAR>
   <TAG>trird</TAG>
  </newTAG>
  <newTAG>
   <BAR>3</BAR>
   <TAG>four</TAG>
```
It happened again. But it does NOT happen always. I will inform here if a find a way to reproduce this issue.

**Comment by trebmuh** [comment]
@jduemes hi Jeff, could you please give it a try with [1.0.0-beta1](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0-beta1) and report here if it is still the case or not?
Thanks.

**Comment by jduemes** [comment]
Yes, it is still happening.

**Comment by trebmuh** [comment]
Hi @jduemes and thanks for the feedback.

We need to find a reproducible way for that to happen. Have you got the time to fiddle around and find an easy step-by-step how-to-reproduce scenario?

Doing that, we'll ensure that the developers can work on this issue.

**Comment by theGreatWhiteShark** [comment]
I was not able to reproduce this issue but introduced some counter measures in #1418. It shouldn't happen anymore
