### ISSUE TITLE
Some detection errors in root CMakeLists.txt

### ISSUE THREAD

**Issue by nick87720z** [hydrogen-music/hydrogen#518]
During configuration i got errors about missing variables:
for rubberband - RUBBERBAND_INCLUDE_DIR (there is RUBBERBAND_INCLUDE_PATHS instead)
for oss - OSS_LIBRARIES (we have OSS_LIB_PATHS instead)
and raptor2 - FIND_HELPER gets wrong lib name (must be raptor2, but it is raptor)

Though i noticed, that nearly all raptor stuff is removed from trunk version of CMakeLists.txt,
first two are actual.

p.s. After reading about FindHelper.cmake - strange, why pkg-config method doesn't work (pkg-name's in CMakeLists.txt are all correct).

**Comment by jeremyz** [comment]
Hi, yes, but the specification of the header to look for was wrong
c8cba3cc85f9b08e101
I wont look into oss, this backend should just die ...
If you realy want it, open onather ticket please.

**Comment by vladimir-kirillovskiy** [comment]
Hi @jeremyz 

I'm using Arch linux and it doesn't like a line FIND_HELPER(LRDF lrdf lrdf.h lrdf). I've replaced it when I was fixing bug #496.

**Comment by jeremyz** [comment]
Hello, me too ... what the hell then ?!?!?!

OS: Arch Linux x86_64
Kernel: 4.11.9-1-ARCH

jeyzu@H: hydrogen (master) $ ls -l /usr/include/lrdf.h
-rw-r--r-- 1 root root 6931 Feb 24 23:47 /usr/include/lrdf.h
jeyzu@H: hydrogen (master) $ cat CMakeLists.txt | gawk '/lrdf.h/{print $0;}'
FIND_HELPER(LRDF lrdf lrdf.h lrdf)
jeyzu@H: hydrogen (master) $ ./build.sh r m 2>&1 | grep LRDF
-- Found LRDF: /usr/lib/liblrdf.so
* LRDF                         : + used  ( /usr/lib/liblrdf.so )
^C

it build fine ...
jeyzu@H: hydrogen (master) $ ldd ./build/src/gui/hydrogen | grep lrdf
        liblrdf.so.2 => /usr/lib/liblrdf.so.2 (0x00007f4f1e581000)
and run fine


now I see that RAPTOR thing, that CMakeLists.txt advertise about but don't look for it ... what a mess ;)))

**Comment by jeremyz** [comment]
ok /usr/lib/liblrdf.so.2.0.0 depends on libraptor2.so.0
and /usr/lib/pkgconfig/lrdf.pc advertise for it
  Libs.private: -lraptor2 -lcrypto
  Cflags: -I/usr/include/raptor2 -I${includedir}
so that RAPTOR dead thingy in CMakeLists.txt should die ...

**Comment by vladimir-kirillovskiy** [comment]
Nope :( it doesn't build. Same old error:
/usr/include/lrdf.h:8:10: fatal error: raptor.h: No such file or directory

**Comment by jeremyz** [comment]
do you have raptor installed ?
jeyzu@bigdaddy: ~  $ pacman -Qo /usr/include/raptor2/raptor.h
/usr/include/raptor2/raptor.h is owned by raptor 2.0.15-6

**Comment by jeremyz** [comment]
if so /usr/lib/pkgconfig/lrdf.pc
adverdise for it, so everything should be ok,
hydrogen does and should only cares about lrdf, not lrdf's dependencies.
I'll be fully available tomorrow to fix that tomorrow

**Comment by nick87720z** [comment]
Why i wondered about raptor - on attempt to build with lrdf enabled, compilation fails at some point, failing to find some raptor header. I guessed, that it is because it was not configured properly.

**Comment by vladimir-kirillovskiy** [comment]
@jeremyz, yes I have it installed. It just this line doesn't work for me - FIND_HELPER(LRDF lrdf lrdf.h lrdf), but this one works - FIND_HELPER(LRDF lrdf lrdf/lrdf.h lrdf).

[vladk@r930 hydrogen-fork]$ pacman -Qo /usr/include/raptor2/raptor.h
/usr/include/raptor2/raptor.h is owned by raptor 2.0.15-6
[vladk@r930 hydrogen-fork]$ ls -l /usr/include/lrdf.h
-rw-r--r-- 1 root root 6931 Feb 25 01:47 /usr/include/lrdf.h

**Comment by vladimir-kirillovskiy** [comment]
@jeremyz Have you looked at my fix for #496 ? Was it wrong?

**Comment by nick87720z** [comment]
About lrdf headers - i have
/usr/include/lrdf.h 
/usr/include/lrdf_types.h 
...any without package dir
Is not it everywhere? On my system it seems to be installed without any movements.

**Comment by jeremyz** [comment]
that is uterly weird, how would FIND_HELPER(LRDF lrdf lrdf/lrdf.h lrdf) find /usr/include/lrdf.h
and FIND_HELPER(LRDF lrdf lrdf.h lrdf) not, it looks into /usr/include by default ... and lrdf.h is in it.
as sure as hell if I set the lrdf/lrdf.h version on my system, it fails to build, which is excpected.
I'm very puzzled here.
Do you really clear your build directory before, cmake caches a lot of things ...

**Comment by vladimir-kirillovskiy** [comment]
Yes, it is strange, I can't explain it. I run "./build.sh r c" every time before build.

**Comment by jeremyz** [comment]
can you please enable (and fix) the debug output in cmake/FindHelper.cmake
->
MESSAGE(STATUS  " LDFLAGS       ${PC_${prefix}_LDFLAGS}" )
MESSAGE(STATUS  " CFLAGS        ${PC_${prefix}_CFLAGS}" )
MESSAGE(STATUS  " INCLUDEDIRS   ${PC_${prefix}_INCLUDE_DIRS}" )

and do
$ mkdir aaa && cd aaa && cmake .. -DWANT_LRDF=1
and also
$ pkg-config --cflags lrdf
and
$ pkg-config --libs lrdf
and maybe join me on irc #hydrogen that will be easier to debug things

**Comment by nick87720z** [comment]
They all are empty :)

**Comment by nick87720z** [comment]
jeremyz, on freenode?

**Comment by jeremyz** [comment]
yep, I saw you ;) I even talked ;) jeyzu is may name

**Comment by jeremyz** [comment]
relevant commits july-august 2017 :
https://github.com/hydrogen-music/hydrogen/commit/8711bb2f141de195ec2123604525efc64f4e0bd5
https://github.com/hydrogen-music/hydrogen/commit/bad832394542f2c1962a6ef3713ff38d8a039028
https://github.com/hydrogen-music/hydrogen/commit/a18495aa342541cb642f8a703c5b837c75f99185
https://github.com/hydrogen-music/hydrogen/commit/c764db517454ae49eacd94c6b3047fd871106181
