### ISSUE TITLE
some PNGs contain non-free embedded ICC data

### ISSUE THREAD

**Issue by jonassmedegaard** [hydrogen-music/hydrogen#519]
The following PNG image files contain embedded ICC color calibration data, which is copyright Hewlett Packard and lack a liberal or copyleft license, and is therefore not permitted by HP to redistribute, use, and change freely:

+ data/img/gray/playerControlPanel/statusLED_off.png
+ data/img/gray/playerControlPanel/statusLED_on.png
+ data/img/gray/skin_btn_off.png
+ data/img/gray/skin_btn_over.png

Even if you may consider ICC profiles to not be what you consider "code" and therefore irrelevant for _your_ redistribution, this issue still affects some of your users - in particular Debian where image data _is_ considered code.

What I use to inspect metadata of embedded data like ICC profiles in images is the commandline tool exiftool included with the CPAN module Image::ExifTool - available in Debian (and derivatives like Ubuntu, I guess) as the package libimage-exiftool-perl.

**Comment by mauser** [comment]
HI @jonassmedegaard ,

to which version of Hydrogen or to which state of our git repository are you referring to? I have converted/updated some pngs this week with mogrify and i'm not able to find ICC data there, at least 'identify -verbose skin_btn_off.png' doesn't show any iCCP chunk anymore. Or is iCCP something else then ICC?

**Comment by jonassmedegaard** [comment]
Latest release (packaged for Debian).

Sorry i forgit to mention that earlier. If you did cleanup a week ago then I guess you already addressed it. Thanks!

Den 19. juli 2017 20.52.57 CEST, Sebastian Moors <notifications@github.com> skrev:
>HI @jonassmedegaard ,
>
>to which version of Hydrogen or to which state of our git repository
>are you referring to? I have converted/updated some pngs this week with
>mogrify and i'm not able to find ICC data there, at least 'identify
>-verbose skin_btn_off.png' doesn't show any iCCP chunk anymore. Or is
>iCCP something else then ICC?
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/hydrogen-music/hydrogen/issues/519#issuecomment-316482316

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
