### ISSUE TITLE
cmake/pkgconfig problem (raptor.h: No such file or directory)

### ISSUE THREAD

**Issue by nick87720z** [hydrogen-music/hydrogen#521]
This is under gentoo, with latest code (cloned in this hours).
Just after they removed raptor stuff from CMakeFile.txt.
Imho, either lrdf should include raptor2/raptor.h, or we should add include dir with pkg-config.
Though i noticed some problems with pkg-config in cmake, as in many cases pkg-config detection way doesn't work, and only header / library files checking do.

Full text:
cd /var/calculate/tmp/portage/media-sound/hydrogen-0.9.7-r1/work/hydrogen-0.9.7_build/src/core && /usr/bin/x86_64-pc-linux-gnu-g++   -I/var/calculate/tmp/portage/media-sound/hydrogen-0.9.7-r1/work/hydrogen-0.9.7/src/core/include -I/var/calculate/tmp/portage/media-sound/hydrogen-0.9.7-r1/work/hydrogen-0.9.7/include -I/var/calculate/tmp/portage/media-sound/hydrogen-0.9.7-r1/work/hydrogen-0.9.7_build/src/core/include -I/usr/include/qt4/QtDesigner -I/usr/include/qt4/QtAssistant -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4/QtScriptTools -I/usr/include/qt4/QtDBus -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtWebKit -I/usr/include/qt4/QtHelp -I/usr/include/qt4/QtUiTools -I/usr/include/qt4/QtTest -I/usr/include/qt4/QtScript -I/usr/include/qt4/QtSvg -I/usr/include/qt4/Qt3Support -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore -I/usr/share/qt4/mkspecs/default -I/usr/include/qt4 -I/usr/include/lash-1.0   -DNDEBUG -std=gnu++11 -Wno-deprecated-register -fno-implement-inlines   -o CMakeFiles/hydrogen-core-0.9.7.dir/src/fx/effects.cpp.o -c /var/calculate/tmp/portage/media-sound/hydrogen-0.9.7-r1/work/hydrogen-0.9.7/src/core/src/fx/effects.cpp
In file included from /var/calculate/tmp/portage/media-sound/hydrogen-0.9.7-r1/work/hydrogen-0.9.7/src/core/src/fx/effects.cpp:36:0:
/usr/include/lrdf.h:8:20: fatal error: raptor.h: No such file or directory
compilation terminated.

Seems to be same as #342 - and root is indeed in unworking pkg-config in some cases.
As all it gives is this:
# pkg-config --cflags lrdf
-I/usr/include/raptor2

**Comment by nick87720z** [comment]
So, it seems to be rather cmake/pkg-config issue, but not raptor :)

**Comment by jeremyz** [comment]
Hi,
your pkg-config output is nice, but I don't see any  '-I/usr/include/raptor2' in your compilation command !!
I've got :
hydrogen (master) $ cat build/CMakeCache.txt | grep raptor
LRDF_CFLAGS:INTERNAL=-I/usr/include/raptor2
LRDF_INCLUDE_DIRS:INTERNAL=/usr/include/raptor2
LRDF_STATIC_CFLAGS:INTERNAL=-I/usr/include/raptor2
LRDF_STATIC_INCLUDE_DIRS:INTERNAL=/usr/include/raptor2
LRDF_STATIC_LDFLAGS:INTERNAL=-llrdf;-lraptor2;-lcrypto
LRDF_STATIC_LIBRARIES:INTERNAL=lrdf;raptor2;crypto

what do you have ?

**Comment by nick87720z** [comment]
Same.
Sorry for long reaction.

**Comment by jeremyz** [comment]
well, it works on my archlinux boxes
I've just tested it with travis on ubuntu
yakkety https://travis-ci.org/hydrogen-music/hydrogen/builds/261411078
trusty https://travis-ci.org/hydrogen-music/hydrogen/builds/261411882
I'm really puzzled here ?!??!?!?
LRDF_INCLUDE_DIRS is set and is referenced in src/core/CMakeLists.txt
why is there no -I/usr/include/raptor2 in your compile command ??

**Comment by nick87720z** [comment]
Don't you look to that command, in topic start?
I tried to build with LRDF and VERBOSE_MAKEFILE on (snapshot a18495aa3425), it has raptor2 include:
https://gist.github.com/nick87720z/74761d0871a3a4688a0e65b34aa07146

**Comment by jeremyz** [comment]
yes I did look in the command in topic start and it is not present,
thus it obviously won't compile.
now that gist looks fine. Just like my command line (I've got dbus stuff in extra),
so what is your situation right now, you've got the good include and your compiler does not find raptor.h ?

**Comment by nick87720z** [comment]
It seems to be fixed. To be sure i made search for raptor word, then modified FIND_PACKAGE entry so, that header and lib lookup methods look for lrdf/lrdf instead of pure lrdf.
So, pkg-config method is ok. No problems with that anymore.

**Comment by jeremyz** [comment]
perfect, OS X linking still needs fixin' !!

**Comment by jeremyz** [comment]
relevant commits july-august 2017 :
https://github.com/hydrogen-music/hydrogen/commit/8711bb2f141de195ec2123604525efc64f4e0bd5
https://github.com/hydrogen-music/hydrogen/commit/bad832394542f2c1962a6ef3713ff38d8a039028
https://github.com/hydrogen-music/hydrogen/commit/a18495aa342541cb642f8a703c5b837c75f99185
https://github.com/hydrogen-music/hydrogen/commit/c764db517454ae49eacd94c6b3047fd871106181

**Comment by duck57** [comment]
I'm not sure where the best place to put this is, but I had an issue where building 1.0.1 stopped when `/usr/include/lrdf.h` under Debian asked to include a non-existent `raptor.h`.  I fixed the issue and got Hydrogen to build by changing `#include <raptor.h>` in lrdf.h to `#include <raptor2/raptor2.h>`.

I hope this is useful to anyone in the future who encounters this problem.

**Comment by theGreatWhiteShark** [comment]
> I'm not sure where the best place to put this is, but I had an issue where building 1.0.1 stopped when /usr/include/lrdf.h under Debian asked to include a non-existent raptor.h. I fixed the issue and got Hydrogen to build by changing #include <raptor.h> in lrdf.h to #include <raptor2/raptor2.h>.

> I hope this is useful to anyone in the future who encounters this problem.

This got probably fixed with #1085
