### ISSUE TITLE
Trying to 'Open' a new file results in 'jack driver : server shutdown'

### ISSUE THREAD

**Issue by lfzawacki** [hydrogen-music/hydrogen#522]
I'm using the latest version from GIT (1.0.0-'9c99b93') and whenever I try to open a new file via the Project -> Open option I get the popup telling jack server has shutdown. It has not actually shutdown (other applications run in the background) but Hydrogen needs to be restarted after that to actually play sound again. Here's a screenshot:

![hydrogen 1 0 0- 9c99b93 - drums h2song modified _010](https://user-images.githubusercontent.com/33211/29294454-c915c53a-8125-11e7-93a2-e355d6702590.png)

This seems to not be a problem in the latest package from KXStudio "0.9.7 [Apr 14 2017]"

I know there's still no official release, but should I let you know.

Cheers

**Comment by jeremyz** [comment]
Hi,
I just tried with current HEAD : https://github.com/hydrogen-music/hydrogen/commit/512da4e39a799d99c8db8fbf7d414a288f82be80
can't reproduce it.
Can you please again and confirm or close this issue ?
Many thanks

**Comment by lfzawacki** [comment]
I can't reproduce it in master as well. Closing.

**Comment by Scribbler2099** [comment]
I have this same issue on ubuntu 17.

**Comment by jhachtel** [comment]
@Scribbler2099 I have the same issue. Your fix works for me, and I also find it annoying. I'm on Fedora 28.

**Comment by jeremyz** [comment]
@Scribbler2099, @jhachtel 
thanks for your report,
but as stated above this bad behaviour can't be reproduced in the upstream code.
as there is nothing I can do that would impact the packages provided to you by your respective distributions, you should consider compiling hydrogen yourself.
instructions can be found here :  https://github.com/hydrogen-music/hydrogen/wiki/Building-Hydrogen-from-source-(LINUX)
I would gladly help you if needed.
