### ISSUE TITLE
Can't open track.

### ISSUE THREAD

**Issue by Alex-Monon** [hydrogen-music/hydrogen#523]
I recently made a beat late at night but when I woke up the next morning the file was somehow corrupted . When I opened the file from my file browser by clicking "open file" it came up with an alert saying "Error loading song" but when I open the file from outside the software the wrong song is loaded. But, the file that I am trying to load is of a different file size from the one that is loaded, showing that they are different files that hold different data, it is like the file that I want to open has become a shortcut to a different file when I try to open it from my file explorer, and the file is corrupted when I try and open it from within the software. 

I am utterly confused by this one.

Thank you for your time and for creating banging free software!

Alex.

**Comment by trebmuh** [comment]
@Alex-Monon : what operating system and version, and what hydrogen version are you using?

Would you please be kind enough to attach the "_corrupted file_" for us to have a look at please?

**Comment by mauser** [comment]
CLosed due to lack of feedback.
