### ISSUE TITLE
 The search field of the hydrogen website does not work

### ISSUE THREAD

**Issue by handsaway** [hydrogen-music/hydrogen#527]
Not sure if it's the right place to report, as it is about the forum. It is quite a drawback so I thought it's important to notify the developers.

The search box always answers with: 

> "You must include at least one positive keyword with 4 characters or more"

 for any search request. So it is essentially unusable.
I tried one or several words, longer than 4 characters, like "drumkit", "instrument order", etc.

**Comment by mauser** [comment]
Hi! 

the forum has a lot of problems :-/ It might be the best to use your favourite search engine for searching the forums. It is likely that there will be a new forum software in the future!
