### ISSUE TITLE
Imported item failed: SSL handshake failed

### ISSUE THREAD

**Issue by DavePist** [hydrogen-music/hydrogen#532]
Couldn't seem to find an answer in the FAQ. What does this error mean and how do I fix it?
Thanks.

**Comment by mauser** [comment]
Hi! 

I suppose this happened while loading a soundlibrary from a server. Does this happen everytime?

**Comment by mauser** [comment]
Hi,

i'm closing this issue since the circumstances of its occurence are not clear. Can be reopened anytime new information is available.
