### ISSUE TITLE
ternary rhythms

### ISSUE THREAD

**Issue by BerndSx** [hydrogen-music/hydrogen#536]
Hi,
I don't have a bug but a wish for a feature:
hydrogen only works with binary rhythms. I'd like to get the opportunity to create ternary rhythms
Could that be done?
Kind regards
Bernd

**Comment by megaknoc** [comment]
What do you mean exactly?

When choosing 4T/8T/16T/32T in the patern editor you get a /3 subdivision of beats. Is'nt that what you mean/need?

**Comment by mauser** [comment]
Hi! 

I'm going to close this issue since the feature is already part of Hydrogen. Just answer again if this is not what you wanted or if you have further questions.
