### ISSUE TITLE
Hydrogen can only be built with empty cmake cache

### ISSUE THREAD

**Issue by m-grabner** [hydrogen-music/hydrogen#539]
cmake stores the paths of found libraries and header files in its cache. However, when running cmake a second time without clearing the cache before (a common scenario when working with Qt Creator), libraries which were found in the first pass are now reported as "not found". A proposed fix is here:

https://github.com/m-grabner/hydrogen/commit/72494f255c054f44092de228988ee2fe5440929b

Kind regards,
Markus

**Comment by jeremyz** [comment]
sounds good to me, set a pull request and I'll merge it !
thanks !!

**Comment by mauser** [comment]
Hi everyone,

is this issue fixed with #540 or is this a different issue?

**Comment by trebmuh** [comment]
@m-grabner @jeremyz : ping

**Comment by m-grabner** [comment]
Yes, it is fixed, issue #539 and pull request #540 refer to the same (solved) problem.

**Comment by trebmuh** [comment]
Thanks, closing then.
Happy drumming!
