### ISSUE TITLE
Rewrite the LCD widget

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#54]
The LCD widget which is used in several central positions needs to be rewritten to be more flexible. The old widget uses a set of pixel graphics to display a very limited amount of characters and numbers. A new implementation should be more flexible and work with UTF characters.

**Comment by mauser** [comment]
It has been accepted that this widget should be dropped instead of beeing re-written.

**Comment by elpescado** [comment]
Does this apply to all instances of LCD widget?

**Comment by trebmuh** [comment]
(just for the sake of later reader, it's been accepted that this widget should be dropped here : https://github.com/hydrogen-music/hydrogen/issues/397)

**Comment by elpescado** [comment]
That thread mentions only LCD widget in upper right-hand corner of Hydrogen window. LCD widget is used in other places as well. Most notably, it is used in pattern editor to switch modes:
![zrzut ekranu 2016-11-29 o 21 29 24](https://cloud.githubusercontent.com/assets/1619113/20727712/ec4bad42-b67a-11e6-89a3-7d94beebd141.png)
You can see lack of support for non-latin characters.

**Comment by mauser** [comment]
Hi @elpescado ,

i'm sorry,

**Comment by theGreatWhiteShark** [comment]
implemented in #1282
