### ISSUE TITLE
Notes get cut off, when playing back sequences

### ISSUE THREAD

**Issue by sehrcoolermensch** [hydrogen-music/hydrogen#542]
_(Note: message edited by @trebmuh for better readability using the so-called "Insert code" tag)_

I usually use Hydrogen with Ardour through JACK. I mostly create some 4-to-the-floor drum sequences. Ardour is JACK-master of course & sync source is JACK. And at some point (usually after the 9th bar) the first note on Hydrogen is almost silent. It sounds like the sound has a really short decay & release, so that it sounds like a gated "zap" or something. Has anyone else experienced this before? What can I do to fix this issue? Did I mess up something?:D

Strange is, that in Hydrogen I read "128 samples" buffer size, whereas qjackctl & Ardour are set to "256 samples". And I can not change the buffer size within Hydrogen. The button does not react to clicking on it. Does this cause the problem or is this normal?

I'm running PureOS 8 (based on linux-libre) & the `uname -a` command prints following text:

`Linux DAW 4.13.0-1-amd64 #1 SMP Debian 4.13.13-1 (2017-11-16) x86_64 GNU/Linux`

The command `jackd -V` prints following text:

```
jackdmp 1.9.11
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
jackdmp version 1.9.11 tmpdir /dev/shm protocol 8
```

Other useful facts:

Ardour is "rev 1:5.12.0-2"
Hydrogen is version "0.9.7 [Sep 19 2017]"

**Comment by thijz** [comment]
hi @sehrcoolermensch 
i have experienced this a long time ago
IIRC The 'zap' you are hearing is actually the sample that is player twice at almost the exact same time.  I have not seen this in recent releases, but you can try this test : 
- set h2 to a high resolution
- move your first note 1 position further (= to the right)
- compensate the offset by using the note lead/lag

**Comment by trebmuh** [comment]
_(possibly related to https://github.com/hydrogen-music/hydrogen/issues/379)_

@sehrcoolermensch : is that still the case with [Hydrogen 1.0.0-beta1](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0-beta1) ? Please, try and report back here.

**Comment by trebmuh** [comment]
No answer for 2 years and a half.
Closing.
Feel free to reopen if needed.
