### ISSUE TITLE
Drum kit samples deloading/removing when opening saved files

### ISSUE THREAD

**Issue by MahBoyz** [hydrogen-music/hydrogen#543]
Whenever i make a kit which is comprised of a loaded kit (e.g 808 Emulator) and some other drums from another kit, it will work for the session. Then, even if i save this new hybrid kit, when i load up the saved song/sequence the kit is there and its in the right order and all, but the samples all are not there, instead it just says ( - ) where the sample name is. As a consequence the song doesnt play as all the drum samples are just silence. This has been a problem for a while now im sure someone else must have said sumthin about it.

Im using hydrogen on Windows 10, i have the latest version also. Thanks for reading this and i hope it gets solved in a future patch.

**Comment by mauser** [comment]
Hi,

which version of Hydrogen are you using on Windows? There has been such an issue with Hydrogen 0.9.6, but it should be fixed in later version

**Comment by trebmuh** [comment]
@MahBoyz : can you try with the [1.0.0-beta1](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0-beta1) to check if it is still the case?

**Comment by trebmuh** [comment]
@MahBoyz This one is probably fixed by the commit just before this very message. If possible, could you please retest from a fresh build?
