### ISSUE TITLE
Hydrogen crashed when trying to save.

### ISSUE THREAD

**Issue by cxbvagafjkwbnjkaiou3** [hydrogen-music/hydrogen#544]
Spent two hours putting together a song demo for my band. pressed save, hydrogen crashed. 
opened the program back up, had lost all traces of my song. not even in the recent list.
Please do something to fix this.. you know.. because its' a a bit annoying.
cheers. ✌️

**Comment by trebmuh** [comment]
@cxbvagafjkwbnjkaiou3 which version of Hydrogen and which operating system?

**Comment by cxbvagafjkwbnjkaiou3** [comment]
0.97??

**Comment by trebmuh** [comment]
@cxbvagafjkwbnjkaiou3 and which operating system (ie: macOS, windows, GNU/Linux, ...) and which version of it?

**Comment by cxbvagafjkwbnjkaiou3** [comment]
MacOS

**Comment by mauser** [comment]
Hi! 

did this happen only once or can you reproduce the problem?

**Comment by trebmuh** [comment]
@cxbvagafjkwbnjkaiou3 ping
