### ISSUE TITLE
500 bpm?

### ISSUE THREAD

**Issue by intherightdirection** [hydrogen-music/hydrogen#545]
I was just playing around with the buttons, and rapidly pressed the comma key.
When it hits "R" the bpm jumps to 500 bpm. I thought it was capped at 400 bpm. Kind of funny and no big deal but it may relate to another issue because of how something is calculated.

**Comment by trebmuh** [comment]
Confirmed.

**Comment by mauser** [comment]
Hi,

this issue is now fixed in the master branch.
