### ISSUE TITLE
tagged release

### ISSUE THREAD

**Issue by dvzrv** [hydrogen-music/hydrogen#551]
Hi!

It would be great to have a new tagged release. There are many fixes, that need to be included since the last official release and currently (on Arch) it is no longer easily possible to even build 0.9.7!

**Comment by dvzrv** [comment]
I'd be happy with a patch release for 0.9.7, as I'm unable to build it (suffering from e.g. #496 #521) and therefore Arch is still stuck on 0.9.6.1.

If 1.0 is not far, I can wait ;-)

**Comment by elpescado** [comment]
I have recently mentioned this on mailing list.

Are there plans for 1.0.0 release? I think there are already enough features to justify new release:
https://github.com/hydrogen-music/hydrogen/wiki/New-features-in-Hydrogen-1.0

**Comment by mauser** [comment]
@elpescado : Yes, there are plans for a release. As already said on the mailing list: It takes time, i've justed started again to work on it.

@dvzrv : The issues which you have mentioned are fixed in 1.0, but are still open in 0.9.7 (if im not completely mistaken), so those commits would have to be backported first

**Comment by dvzrv** [comment]
@mauser I guess I'd rather wait for 1.0 then. Seems a lot of backporting.

**Comment by elpescado** [comment]
I mean on more general level - do you feel master branch is more or less ready for release candidate, or are there features "in the pipeline" that should be integrated before that.

**Comment by mauser** [comment]
Ah, ok, now i understand what you mean with your question. From my point of view, the code is more or less ready for a first release and no feature is missing. Following our scheme, it will be sth. like a beta1. Currently i'm writing some basic documentation on OSC and preparing the move from our current website to the Github Pages page. Another thing which has to be done for first is to make sure that all remaining links/references to the GMKit (like its use in the Demos) gets cleaned up.

**Comment by christophski** [comment]
@mauser Great to see this being worked on actively again! Is there anywhere I can donate? I've been using Hydrogen for all my releases for years

**Comment by dvzrv** [comment]
Okay, I've now updated hydrogen for Arch to 0.9.7.
As you can see, there's [a long list of patches required](https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/hydrogen) (that I thankfully received from a member of the community). Therefore I think it would probably (at this time) not at all be benificial to provide a patch release for 0.9.7, if 1.0 is around the corner.

However, it might be a good place to check, whether those patches are needed or not (e.g. rubberband is in version 1.8.1 on Arch and doesn't get properly recognized by the build script, which is why I leave it disabled).

**Comment by mauser** [comment]
@christophski : At the moment you can only donate via paypal, there a donation menu reachable in the Hydrogen application via "Info -> Donate".

@dvzrv : Thanks a log, i suppose some of those patches originate from Debian? I will have a look at them, i suppose that some things are already fixed in 1.0

**Comment by mauser** [comment]
Hi,

i've set now the tag for the 1.0.0-beta1 release. Anouncement to the mailing list and Windows installers will follow later today or tomorrow.

**Comment by dvzrv** [comment]
Awesome news! Will ship as soon as you're out of beta!

**Comment by trebmuh** [comment]
@mauser : the [1.0.0-beta1 tar.gz](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.0-beta1) looks to be missing the data/doc/ files (git submodules). I'm not sure if this is done on purpose.

**Comment by mauser** [comment]
@trebmuh : Those packages are generated automatically by GitHub. Our documentation is now in a seperate repository, so GitHub does not add the files to the automatically generated archives. The documentation will be in the 'official' tar.gz archives and installers to be published later (which will also be published to SourceForge).

**Comment by trebmuh** [comment]
@mauser : ok, thanks for the explanation.

**Comment by dvzrv** [comment]
Sorry for necro-bumping, but qt4 is more than EOL and I really need to update (packaging this for Arch).
Is it possible to release hydrogen in its current state? I have the feeling this will otherwise never happen and end up in constant limbo, like lmms (where eventually I started shipping the RCs, as upstream maneuvered itself into a deadlock about what and when to release - currently all the containered builds there also ship the latest version already, same as here with flatpack).

**Comment by elpescado** [comment]
I second that! 1.0.0-beta1 was releases 11 months and 336 commits ago, plus there are some cool PRs for bugfixes. I think it's high time we released next beta and I hope final 1.0 release is soon!

**Comment by dvzrv** [comment]
@mauser I see that there are still [many open issues until version 1.0](https://github.com/hydrogen-music/hydrogen/milestone/4), but it would be very helpful to release a new beta/ a release candidate, as I really have to update hydrogen or drop the package from the official repositories on Arch.
Please tag a (stable) release!

**Comment by mauser** [comment]
Hi! 

good timing :) I've started last week to prepare the next beta release by adopting the last changes from MXE. 

Btw., don't take that Github Milestones for Hydrogen too seriously. People use this here more as a wishlist then for serious release planning, so it has to be read like "It would be nice if those issues would be fixed". In my opinion, a stable release is currently only hindered by problems with memory management (which led to access violations when loading/changing drumkits) and problems with loading kits from older versions of Hydrogen. Those are really showstoppers, and i don't think it would make sense to release a stable version of Hydrogen with such bugs present (knowingly).

**Comment by dvzrv** [comment]
@mauser thanks, that's good news!
Please go ahead! :)

**Comment by dvzrv** [comment]
As announced [Arch Linux has now started the purge of qt4](https://lists.archlinux.org/pipermail/arch-dev-public/2019-April/029560.html).

I will try to package the beta1, but I think it's a rather unfortunate situation.
