### ISSUE TITLE
H2 'per instrument output' labels are in reverse order

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#552]
Hi All !

When you enable the 'per instrument output' feature in H2 in it seems that the Jack port order is the exact opposite of the instrument order

![image](https://user-images.githubusercontent.com/1384210/36376706-5651b8b8-1574-11e8-90fb-1faae76b6e4f.png)

instrument 1 ('Kick') = Track 5
...
instrument 5 ('HH") = Track 1 

Does anyone know what the logic behind this is ?

Grtz
Thijs

**Comment by mauser** [comment]
Hi! 

I'm also a little bit surpised about this.. it should be in correct order now in the master branch. If anyone nows why this was reversed before, please speak up :)

**Comment by thijz** [comment]
... i was not using the latest code ... :-S
retested with current master and the order is ok

sorry for the noise !

**Comment by mauser** [comment]
What i meant to say was: I was also surprised, but i fixed it yesterday in the code. So reporting that issue was fine, i was just quick with the fix ;-)

**Comment by thijz** [comment]
:-D
Thanks Sebastian !
