### ISSUE TITLE
output of 'git describe' shows 0.9.6-beta2

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#553]
Thank you for taking the time to report an issue with Hydrogen, or suggest a new feature !
Please try to provide a clear and complete answer to the questions below.  
Don't worry of you don't know the answers to all questions, but more info means a better chance to a fix.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

== I WANT TO REPORT A BUG ==

1)  Hydrogen version (see Info - About) : 1.0.0-'f4d85ba'
2)  In case you build Hydrogen from source, git commit hash (git rev-parse HEAD) : c1d98104d651b7cdf86ba4bba5348bdd9a0bfb5b
3)  Operating system + version (eg Win 7, Ubuntu 16.04...) : ubuntu 16.04
4)  Audio driver (eg Jack, ALSA, Core Audio ...) + version : jack

5)  Steps to reproduce the issue :
execute 'git describe'

6)  What you expect to see :
something like '1.0.0'

7)  What you see instead :
0.9.6-beta2

8)  Other useful info :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

== I HAVE A FEATURE REQUEST ==

Let us know what is missing in Hydrogen :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by mauser** [comment]
Hi! 

'git describe' does exactly what it should. Github seems to use lightweight tags (when you use the tagging feature), but "git discribe" uses the last annotated tag. 

You can use it with the --tags parameter to use lightweight tags:

git describe --tags
0.9.7-281-gf4d85baf

It does not show a 1.0 tag because there is simply no 1.0 tag at the moment (there hasn't been a 1.0 release yet).

**Comment by mauser** [comment]
I suppose you can first create an annotated tag with the git command line client (or whatever someone wants to use) and then add the release information in GitHub.

**Comment by mauser** [comment]
Fixed: 1.0.0-beta1 is now an annotated tag.
