### ISSUE TITLE
desktop file icon missing (in correct location)

### ISSUE THREAD

**Issue by dvzrv** [hydrogen-music/hydrogen#558]
Hydrogen version *          : 0.9.7
Operating system + version  : Arch Linux
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The [hydrogen.desktop](https://github.com/hydrogen-music/hydrogen/blob/master/linux/hydrogen.desktop#L29) file states `h2-icon` as its icon. However, after `make install`, the only file that is named that way ends up in `/usr/share/hydrogen/data/img/gray/h2-icon.svg` (additionally the same file gets installed as `icon.svg` to the same folder).

This then breaks the displaying of an icon when launching hydrogen through a XDG aware menu or launcher (as those accept locations such as `/usr/share/pixmaps` or `/usr/share/icons/hicolor/scalable/apps` for applications).
It would be nice if this could be addressed in a pull request and won't have to be dealt with downstream.

Apart from the location of the `.svg` file, it is usually good style to name it the same way as the application (i.e. `hydrogen.svg`).
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by mauser** [comment]
Hi! 

Could you re-test this with Hydrogen 1.0? This should be fixed with commit b5b9cb902e84917753899eb3d10d70b6df82dc24 .

**Comment by mauser** [comment]
Closing this since it seems to work fine with the current git version of Hydrogen (1.0) . Just mention it if it should be re-opened because sth. is missing.

**Comment by dvzrv** [comment]
The icon should actually be installed as `/usr/share/icons/hicolor/scalable/apps/hydrogen.svg` and the desktop file (i.e. `org.hydrogenmusic.Hydrogen.desktop`) should either not even mention an icon (and default to its own name) or specify hydrogen.
Also, the desktop file name should be simply `hydrogen.desktop`. It's not a dbus configuration ;-)
