### ISSUE TITLE
Bell and HatSemiOpen samples missing in GMRockKit

### ISSUE THREAD

**Issue by SpotlightKid** [hydrogen-music/hydrogen#561]
Hydrogen version *          :  1.0.0.beta1 (git tag 36fc60c7) (https://aur.archlinux.org/packages/hydrogen-git/)
Operating system + version  :  Arch Linux
Audio driver + version      :  JACK 1.9.12

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The `drumkit.xml` for the GMRockKit included with the hydrogen sources refers to two instruments named "Hat Semi-Open" and "Bell", but the sample files referenced in the layers of those instruments are missing.

    {Bell,HatSemiOpen}-{Softest,Soft,Med,Hard;Hardest}.wav

**Comment by mauser** [comment]
Hi! 

Thanks for the report, i will add them..

**Comment by mauser** [comment]
Could you pull again and see if all of the sample are now in their correct place?

**Comment by SpotlightKid** [comment]
Yes, the files are there now.
