### ISSUE TITLE
i18n missing translations

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#565]
From a fresh build from https://github.com/hydrogen-music/hydrogen/commit/f665c86999a456a405cef1317055afe93405dc8d , I've spotted a 5 places where translations are missing:

Hydrogen menu -> Drumkits -> Open
![hydrogen-bug3-traduction_manquante](https://user-images.githubusercontent.com/8705846/37481189-6de49bd8-2881-11e8-9071-83d833596ef0.png)

Hydrogen menu -> View -> Playlist editor -> Open Playlist
![hydrogen-bug4-traduction_manquante](https://user-images.githubusercontent.com/8705846/37481196-7388ac28-2881-11e8-847c-ab351433bff8.png)
_(in other places, the "Hydrogen Playlist" is translated into "Liste de lecture Hydrogen" in the French version)_

Hydrogen menu -> View -> Mixer
![hydrogen-bug6-traduction_manquante](https://user-images.githubusercontent.com/8705846/37481203-7752a1ec-2881-11e8-81a9-a152e8c9d561.png)
_(the window's title should be translated into "Mixeur" in French)_

Hydrogen main window
![hydrogen-bug7-traduction_manquante](https://user-images.githubusercontent.com/8705846/37481208-7a0d99be-2881-11e8-9614-5136997373de.png)
_(when mouseovering)_

Hydrogen menu -> Options -> Preferences -> OSC tab
![hydrogen-bug8-traduction_manquante](https://user-images.githubusercontent.com/8705846/37481216-7ec46320-2881-11e8-90f4-031493340944.png)

Hope that helps.

**Comment by mauser** [comment]
Hi! 

Thanks for the report, Olivier. All mentioned places should be translatable by now.

**Comment by trebmuh** [comment]
@mauser thanks ! Just FYI, I've rebuild from a fresh https://github.com/hydrogen-music/hydrogen/commit/bfc355ee5c3fa1a62f12d056427bc1a827764a61 + a local patch to update the FR translation (see https://github.com/hydrogen-music/hydrogen/pull/566) and everything is perfect. Thank you!
