### ISSUE TITLE
Plugins do not work

### ISSUE THREAD

**Issue by phelpsscofield** [hydrogen-music/hydrogen#574]
Hydrogen version *          : 0.9.7
Operating system + version  : Ubuntu Studio 18.04 Beta
Audio driver + version      :  DUOCAPTURE [DUO-CAPTURE], dispositivo 0: USB Audio [USB Audio]

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When I try to insert an audio plugin as a compressor this does not work

**Comment by mauser** [comment]
Hi! 

Which plugin are you using exactly?

**Comment by phelpsscofield** [comment]
Calf Studio Gear Plugins, I try Calf Compressor.

**Comment by trebmuh** [comment]
@phelpsscofield : do you happen to have a package named `calf-ladspa` installed?
If so, you might be hitting the [same bug than here](https://github.com/LMMS/lmms/issues/3942). A workaround is to remove the `calf-ladspa` package, or not use any calf (LADSPA) plugin with Hydrogen at all.

**Comment by thijz** [comment]
hi @phelpsscofield 
I see you gave the comment of @trebmuh a 'thumbs up'.  Does this mean that your problem is fixed ?

**Comment by phelpsscofield** [comment]
Yes, the problem has been solved, thank you.

**Comment by thijz** [comment]
issue was external to H2 and has been resolved
