### ISSUE TITLE
While in "song mode", pattern editor should jump automatically to the pattern currently played

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#575]
Hydrogen version           : git https://github.com/hydrogen-music/hydrogen/commit/bfc355ee5c3fa1a62f12d056427bc1a827764a61
Operating system + version  : Debian 9
Audio driver + version      : any

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

While in "song mode", pattern editor should jump automatically to the pattern currently played. This would help users when working on a song, learning a new pattern,...

Background information can be found here: https://github.com/hydrogen-music/hydrogen/issues/239

**Comment by theGreatWhiteShark** [comment]
Closed with #1563
