### ISSUE TITLE
[enhancement] export

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#577]
Hydrogen version *          : git master https://github.com/hydrogen-music/hydrogen/commit/5556c8dbc2a2c58f1441281739eab444273861d0
Operating system + version  : Debian Stretch 9
Audio driver + version      : (tested with) jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Scenario: I'm exporting a version 1 song in WAV , then I work again on the song and want to export it on version 2. Then Hydrogen doesn't remain where I've saved the version 1 wav file and take me back to a defaulting path... and I have to choose again where I want the file to be saved in.

From a user perspective, I'd like Hydrogen to remind where I did save the previous WAV file and use it as the default one when I'm requesting to save the version 2 of my song. 

Guestimation is this will match 95% of users' workflows.

**Comment by theGreatWhiteShark** [comment]
Implemented in #1399
