### ISSUE TITLE
A link to the users forum from the GUI

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#578]
_(coming from here: https://github.com/hydrogen-music/hydrogen/pull/405)_

@trebmuh : Also, while we are here talking about the `AboutDialog.cpp` file, wouldn't you think that putting a link straight to the users forum would make sense? It would make the user to know directly (from the Hydrogen GUI) where the best place to go for a user is. What do you think?

@mauser : About the forum link: We're currently working on a new homepage, so the link to the forum will most certainly change in the next time. I would like to keep it off the current version, but this is of course a good idea for the future. We could also create a `visit forum` or `hydrogen community` entry in the `info` menu.

**Comment by mikotoiii** [comment]
If we had control of the dns, we could set a cname record that would point
wherever we wanted. I know Mauser has been working on the dns stuff.

**Comment by mauser** [comment]
Hi @mikotoiii , 

I'm not in direct control of the DNS settings, the domaín is managed by @cominu .

**Comment by mauser** [comment]
Closed: the forum is completely gone now..
