### ISSUE TITLE
Crash after changing Pattern Resolution

### ISSUE THREAD

**Issue by pvint** [hydrogen-music/hydrogen#579]
Hydrogen version *          :  Commit 4560040    (Git as of 20180323)
Operating system + version  : Gentoo Linux
Audio driver + version      : N/A

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

On a fresh compile (and after deleting ~/.hydrogen), after changing resolution the "beat" markers disappear from the pattern editor. Clicking to drop a note causes a crash.

Backtrace:
```
Core was generated by `./hydrogen -VDebug'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00000000005569f5 in DrumPatternEditor::getColumn (this=0x5eb9a80, ev=0x7ffc5369ced0) at /home/pvint/hydrogen/src/gui/src/PatternEditor/DrumPatternEditor.cpp:141
141             nColumn = (nColumn * 4 * MAX_NOTES) / (nBase * m_nResolution);
[Current thread is 1 (Thread 0x7f6385c77800 (LWP 30750))]
(gdb) bt
#0  0x00000000005569f5 in DrumPatternEditor::getColumn (this=0x5eb9a80, ev=0x7ffc5369ced0) at /home/pvint/hydrogen/src/gui/src/PatternEditor/DrumPatternEditor.cpp:141
#1  0x0000000000556ae6 in DrumPatternEditor::mousePressEvent (this=0x5eb9a80, ev=0x7ffc5369ced0) at /home/pvint/hydrogen/src/gui/src/PatternEditor/DrumPatternEditor.cpp:158
#2  0x00007f638520230f in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#3  0x00007f63851c061c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#4  0x00007f63851c91c5 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#5  0x00007f63826333a9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#6  0x00007f63851c76db in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib64/libQt5Widgets.so.5
``` 

Screenshot after changing resolution from 8 to 16 (note that after selecting 16 the resolution still displays 8):
![sable20](https://user-images.githubusercontent.com/608740/37859900-c820da28-2ef1-11e8-89af-f2a613bc4eff.png)

After seeing the screen as shown in the SS clicking to leave a note causes the crash on every test I have tried.

**Comment by trebmuh** [comment]
@pvint : duplicate of https://github.com/hydrogen-music/hydrogen/issues/538 ?

**Comment by pvint** [comment]
@trebmuh  Yes - it definitely looks like the same thing! Forgot about that (and apparently was too tired and skipped searching... oops)

I will close this and continue there.
