### ISSUE TITLE
[FEATURE REQUEST] Changing the volume of a groupe notes all at once

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#581]
_(quoting from http://hydrogen.popez.org/hcms/node/18886)_

> Can I change the volume of a group of notes all at once, rather than tug each volume bar one at a time?

**Comment by theGreatWhiteShark** [comment]
I just implemented such a feature in pull request #664

**Comment by theGreatWhiteShark** [comment]
Yes. #964 included a wonderful implementation of this feature.
