### ISSUE TITLE
Why is nsm client in core and not in gui ?

### ISSUE THREAD

**Issue by Houston4444** [hydrogen-music/hydrogen#582]
Hello. I just take a look to the NSM implementation because I think it could be better done.

I just can't see why the nsm client is in core and not in gui section as it is in ardour code (for example).
The way it is done, it replies too early to NSM that hydrogen song is loaded, it's impossible to implement nsm switch and to send to NSM a dirty state. It's quite a shame.

Is there a good reason for this ?

thanks

**Comment by jeremyz** [comment]
Hello,
I haven't looked at that NSM code yet, but will try to !
I am very surprised by your comment about where it should lay in the source tree. I totally fail to see how such a feature is related to GUI.
To me GUI should only contain widgets (enabling/disabling sending messages to each others ...)
talking to a lower API.
so if you what to implement a CLI, another GUI, whatever ... you talk to that lower API and have access to all the features.

feedbacks always welcome,
cheers

**Comment by Houston4444** [comment]
> To me GUI should only contain widgets (enabling/disabling sending messages to each others ...)
> talking to a lower API.

That seems logic you're right. But here what is written in /src/core/src/nsm_client.cpp , line 63:

```
the hydrogen core is not responsible for managing
song loading on startup. Therefore we use store
the desired song name and let the GUIs do the actual work.
```

This way NSM can't know if song load failed, or when song is really ready. And as I said, it's not possible to improve NSM implementation. Or, core should have to load song himself (and not just remember a name for GUI). If this can be done, it's nice.

Note after tests: Sometimes, I don't know why, hydrogen launched under NSM don't opens the desired file, it opens an Untitled Song.


I was talking about GUI because NSM implementation has been made in GUI section in ardour (it was maybe easier to do this way), and I did NSM switch implementation (not merged this day, devs are working on other things). [](https://github.com/Ardour/ardour/pull/389
)

I also devellope [Ray Session](https://github.com/Houston4444/RaySession), alternative to Non Session Manager.

cheers.

**Comment by theGreatWhiteShark** [comment]
Hey @Houston4444!

The NSM implementation has been revised and I think all aspects you mentioned were covered. Therefore I will close this issue. But if you have any questions or comments, please feel free to reopen it.

**Comment by Houston4444** [comment]
All seems to be ok, Thanks a lot !
