### ISSUE TITLE
Faster playback when pressing play

### ISSUE THREAD

**Issue by sparkycasegbr** [hydrogen-music/hydrogen#587]
Hydrogen version *          :1.0.0 beta1
Operating system + version  : Ubuntu Budgie17.10
Audio driver + version      : Unknown

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When playing back a pattern it initially plays back faster than normal, then slows to the correct speed.

**Comment by trebmuh** [comment]
@sparkycasegbr :

- does it slows straight, or is the slowing down is done smoothly a progressively?
- what happen if you ask to play a second time? Does the same happens or does it play at the correct speed?
- have you tried with another pattern? Does it do the same with any pattern?

**Comment by trebmuh** [comment]
@sparkycasegbr 

>  It started about 5-10bpm faster, then slowed to the correct speed.

Just to be sure, did it start à 5-10bpm faster, then suddenly went to the normal bpm or does it start with the first play at 10bpm faster, then 8 bpm fast, the 5bpm faster, the 2bpm faster, then to normal bpm?

**Comment by sparkycasegbr** [comment]
@trebmuh 
It started faster for the 1st bar, then went down to normal tempo.

**Comment by mauser** [comment]
Hi,

i would like to close down this issue. If you're using just alsa as a sounddriver, other processes can influence the processing of your sound driver and cause those slow downs/speed ups. This is a problem with the general sound driver setup, not with Hydrogen itself.

**Comment by Megver83** [comment]
> Hi,
> 
> i would like to close down this issue. If you're using just alsa as a sounddriver, other processes can influence the processing of your sound driver and cause those slow downs/speed ups. This is a problem with the general sound driver setup, not with Hydrogen itself.

I was having a similar problem (Hydrogen was playing like 20bpm faster), I changed the sound driver to PulseAudio and it got fixed. However, there's also JACK and PortAudio, which one is more recommended? just wondering, as you said that other processes can influence the sound driver (which affects ALSA) I'd like to know which one is the more stable or less prone to suffer issues like this one.

**Comment by trebmuh** [comment]
JACK
