### ISSUE TITLE
Non-Session: Does not save / link drumkit samples in NSM session dir

### ISSUE THREAD

**Issue by diovudau** [hydrogen-music/hydrogen#590]
Hydrogen version *          : 0.9.7
Operating system + version  :  Arch Linux 
Audio driver + version      :  Jack2 1.9.12

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
NSM benefits from storing all non-program data like samples or hydrogen drumkits in the session dir.
To avoid redundancy it is recommended to link the data into the session dir on first use and from then on only use the link.

Other NSM aware programs like DrumkV1 already use this method.

Relevant section of the NSM Api:
http://non.tuxfamily.org/nsm/API.html#n:1.1.2.2.

1.1.2.2. External Files
Files required by the project but external to it (typically read-only data such as audio samples) SHOULD be referenced by creating a symbolic link within the assigned session area, and then referring to the symlink. This allows sessions to be archived and transported simply (e.g. with "tar -h") by tools that have no knowledge of the project formats of the various clients in the session. The symlinks thus created should, at the very least, be named after the files they refer to (some unique component may be required to prevent collisions)

**Comment by theGreatWhiteShark** [comment]
Closed with #792
