### ISSUE TITLE
[OT] website and drumkits server is down

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#591]
I sent a message on the devel list yesterday and I'm saying it here in case you didn't see it yet.

@mauser @wolkstein and others who have access to it.

**Comment by mauser** [comment]
Hi! 

I only have access to the content of the website, not to other aspects like the configuration of the webserver. This is something @wolkstein has to check. Wolke, you could you check if there is some maintenance or sth. going on?

**Comment by disciplesdeyehovah** [comment]
website not work is normal ?

**Comment by trebmuh** [comment]
The drumkits server is down as well. People can still use another server (such as https://musical-artifacts.com/hydrogen_drumkits.xml or http://freepats.zenvoid.org/hydrogen.xml ).

@wolkstein have you got some news on what's going on?

**Comment by trebmuh** [comment]
Better to be on https://github.com/hydrogen-music/hydrogen/issues/591

**Comment by thiagonasper** [comment]
Does anyone knows how can i do to download FLAC_GSCW-1 Drumkit?
That Drumkit was present in the old hydrogen server list.
But the list sugested by trebmuh does not contain the GSCW Drumkit.
Thanks Everyone!

**Comment by mauser** [comment]
@thiagonasper: Just try the original URL List (http://hydrogen-music.org/feeds/drumkit_list.php), it is back online again.

**Comment by thiagonasper** [comment]
It's true. Thank you mauser, the original URL is online again.
Sorry trebmuh, for the wrong post.
