### ISSUE TITLE
server for download instrument do not work

### ISSUE THREAD

**Issue by disciplesdeyehovah** [hydrogen-music/hydrogen#593]
server for download intrument not work

**Comment by trebmuh** [comment]
The website is down at the moment and the dumkits server is probably hosted on the same machine.
You can use alternate servers such as https://musical-artifacts.com/hydrogen_drumkits.xml or http://freepats.zenvoid.org/hydrogen.xml for examples.

**Comment by mauser** [comment]
This is technically the same issue as #591 .
