### ISSUE TITLE
Two Drumkits work for the first save but after are in permanent mute

### ISSUE THREAD

**Issue by JosephSchwabauer** [hydrogen-music/hydrogen#596]
Hydrogen version *          : 0.9.7
Operating system + version  :  Mac 10.13.4 High Sierra 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I'm new to Hydrogen so this may be a really obvious issue but. I've made a few songs with a variety of kits. There are two that I used and for some reason they work fine but when I save and come back to them they no longer play. Also of note, when I reopen that file the instruments in the opened file are all on 'M'. I switch them off mute but there is no sound  when I play them. Please help!

The two kits this is a reoccurring issue with are: Boss DR-110 and belofilms.com-AC-Guitar-Strums (flac)

thanks!

**Comment by trebmuh** [comment]
@JosephSchwabauer This one is probably fixed by the commit just before this very message and the message 18 days ago. If possible, could you please retest from a fresh build?

**Comment by mauser** [comment]
Closed (seems to be fixed).
