### ISSUE TITLE
Build documentation outdated

### ISSUE THREAD

**Issue by foobuntu** [hydrogen-music/hydrogen#597]
Hydrogen version *          : 4ae42ba1755d6fc7d784b328d1494f7573e1d246
Operating system + version  : Xubuntu 18.04
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I followed the build instructions step by step. I wanted to create a deb package so I run `fakeroot dpkg-buildpackage` and the first error I encounter is about missing dependencies _libarchive-dev liblo-dev libpulse-dev libcppunit-dev_. After installing the missing packages I run `fakeroot dpkg-buildpackage` again and then I run into  

> CMake Error at CMakeLists.txt:134 (FIND_PACKAGE):
>   By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
>   project has asked CMake to find a package configuration file provided by
>   "Qt5LinguistTools", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5LinguistTools"
>   with any of the following names:
> 
>     Qt5LinguistToolsConfig.cmake
>     qt5linguisttools-config.cmake
> 
>   Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
>   set "Qt5LinguistTools_DIR" to a directory containing one of the above
>   files.  If "Qt5LinguistTools" provides a separate development package or
>   SDK, be sure it has been installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/username/hydrogenSrc/hydrogen/builddebian/CMakeFiles/CMakeOutput.log".
> debian/rules:31: recipe for target 'configure-stamp' failed
> make: *** [configure-stamp] Error 1
> dpkg-buildpackage: Error: debian/rules build subprocess returned exit status 2

Neither the [online build documentation](https://github.com/hydrogen-music/hydrogen/wiki/Building-Hydrogen-from-source-(LINUX)) nor the INSTALL.txt says how to deal with that exactly.  
For an experienced dev this might be done in a breeze but I'm a building and compiling noob, who just wants more than the 16 default layers available.

**Comment by mauser** [comment]
Hi! 

i can reproduce the problem here with Ubuntu 18.04. @jeremyz , do you know which package is required or what exactly is missing? I've already installed qttools5-dev-tools, but this didn't help here.

**Comment by jeremyz** [comment]
hi @mauser ,on a debian vm I had to install qttools5-dev-tools, qtbas5-dev, qtbase5-dev-tools and

**Comment by mauser** [comment]
Thanks Jeremy! 

But it seems that the package contents differ on Ubuntu and Debian. The debian package of qttools5-dev-tools includes the Qt5LinguistToolsConfig.cmake file, the Ubuntu package does not. After  quick search it turned out that on Ubuntu the packge qttools5-dev is required instead.

**Comment by jeremyz** [comment]
I have updated the wiki page
