### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by nikoss** [hydrogen-music/hydrogen#600]
Hydrogen version *          : Hydrogen 1.0.0-beta1 (March 16 2018)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I found this string in the translation file:

> Unsaved changes left. This changes will be lost. 
> Are you sure?

Maybe it should be:
> These changes will be lost.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by mauser** [comment]
Hi! 

Thanks for the report, this is now fixed in the source code.
