### ISSUE TITLE
Crash on (some) file browser actions

### ISSUE THREAD

**Issue by aleeusgr** [hydrogen-music/hydrogen#601]
Hydrogen version *          :1.0.0-beta1
Operating system + version  : AVlinux 2018.4.2.
Audio driver + version      : jackdmp version 1.9.12 tmpdir /dev/shm protocol 8

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
On actions involving file browser I get crash.
Reproduce: 
Select instrument -> layers -> load layer-> select .wav file in /home/-> (load, play, play by clicking then click)
(I) PlaylistDialog::PlaylistDialog INIT
(I) AudioFileBrowser::AudioFileBrowser INIT
*** Error in `hydrogen': double free or corruption (!prev): 0x000055cca5dd45a0 ***

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

[hydrogen_verbose_debug_out.txt](https://github.com/hydrogen-music/hydrogen/files/1986790/hydrogen_verbose_debug_out.txt)

**Comment by thijz** [comment]
this is a showstopper ... :-(
anything i can test to make fixing this one easier ?

**Comment by mauser** [comment]
Hi! 

Please check again if he bug is fixed now in the master branch...

**Comment by thijz** [comment]
hi @mauser 
i just retested but it seems the issue is still there

**Comment by mauser** [comment]
Hmpf :-/ 

I've tried to reproduce the bug now, but i can't make it happen again. Can you validate that you're working with the recent git version? If the bug still occurs, is the backtrace the same? Especially the "double free or corruption" part is interesting for me..

**Comment by thijz** [comment]
just retested (fresh git clone) and the problem seems to be fixed

**Comment by mauser** [comment]
Perfect! I'm going to close this issue then..
