### ISSUE TITLE
INSTALL.txt is outdated

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#604]
Hydrogen version * : git 4ae42ba
Operating system + version : ubuntu 16.04 64bit
Audio driver + version : jack (jackdmp 1.9.11) + QjackCtl 0.4.2
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

INSTALL.txt contains links to obsolete trac pages :
http://trac.assembla.com/hydrogen/wiki/development%3AcompileOSX
http://trac.assembla.com/hydrogen/wiki/coding%3Apackagingwin

It also contains outdated info on how to build the code : 
make && sudo make install 
this does not work : 
`make: *** No targets specified and no makefile found.  Stop.`

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by trebmuh** [comment]
I've replaced the 2 dead links with current ones.
For the other issue (make && sudo make install), it needs a bit of more check.

**Comment by thijz** [comment]
hi Olivier,
I personally have several versions of H2 compiled on the same pc without installing them.  That way i can switch between versions to test.  Up until now i was able to simply clone into a nwe directory, run build.sh m and i was able to start H2 in that new directory.

For this release i created a new account on my laptop (so no official h2 release was ever installed on this account) and now when i start H2 via cli in the build directory i get "/usr/local/share/hydrogen/data/ is not a directory"
So i figured that i just needed to run a 'make && sudo make install' and all would be ok, but this is not the case

**Comment by thijz** [comment]
fyi : the "/usr/local/share/hydrogen/data/ is not a directory" issu has been solved
see https://github.com/hydrogen-music/hydrogen/issues/598
so it is just the "make && sudo make install" issue that is still open

**Comment by jeremyz** [comment]
2cbb04f8
that should be ok, `make && sudo make install` are working if you do the `mkdir build && cd build && cmake ..` before
