### ISSUE TITLE
timeline is black + empty song editor

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#605]
Hydrogen version *          : dea84656afeb056f4f9ff73da40153bd484649b6
Operating system + version  : ubuntu 16.04 64 it
Audio driver + version      : jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

upon starting H2 for the first time (after building it from code) the top 'timeline' area is black and whwn playing a demo song the playhead is drawn multiple times (see picture)

the song editor area is also empty

![image](https://user-images.githubusercontent.com/1384210/40019793-8cc8e72a-57c0-11e8-91e8-da2135c88e39.png)

**Comment by thijz** [comment]
update : 
after deleting my hydrogen.conf file the problem was fixed ...
i will leave the ticket open in case anyone needs more info

**Comment by jeremyz** [comment]
@thijz,
next time, could you please save a copy of your non-working hydrogen.conf,
it would be very interesting to see if it can be used to reproduce that weird behaviour (or another).

If you don't have it anymore, and can't find a way to reproduce it, I think you should close that issue,
info is here, that's important, but if nothing is expected to be done about it, it should be closed.

**Comment by thijz** [comment]
cant reproduce this, so i'm closing the ticket
