### ISSUE TITLE
Automation path check is never set

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#606]
Hydrogen version *          : git dea84656afeb056f4f9ff73da40153bd484649b6
Operating system + version  : ubuntu 16.04 64bit
Audio driver + version      : jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

when switching on the 'automation path' using 'Alt-A' or via 'View - Automation path' this works just fine,
however, the checkmark next to 'Automation path' (in the View menu) is never set

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by mauser** [comment]
Fixed in #623 , thanks to @francismaria !
