### ISSUE TITLE
Bars not available

### ISSUE THREAD

**Issue by Dannymur** [hydrogen-music/hydrogen#607]
Hydrogen version:  1.0.0. - beta1
Operating system + version: Windows 8.1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

![image](https://user-images.githubusercontent.com/39299774/40057125-b1300f0c-584d-11e8-90f6-4dfcb37bee0d.png)
In pattern editor for size s i have only s/2 bars available for editing. I downloaded Hydrogen today, it worked normally for a few minutes before this occured. I tried reinstalling, deleting all the files and I can't fix it. 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by trebmuh** [comment]
What if you change the value for "SIZE=7" to something like "SIZE=16" ?

**Comment by Dannymur** [comment]
Sorry, I meant beats instead of bars. If I set size to 16, I have 8 beats

wt., 15.05.2018, 23:35 użytkownik Olivier Humbert <notifications@github.com>
napisał:

**Comment by mauser** [comment]
Hi! 

You have to adjust the "Resolution" (the combobox beside of size). If you set it to "8", you have the desired amount of beats.
