### ISSUE TITLE
[feature request] Some things that would be great

### ISSUE THREAD

**Issue by aleeusgr** [hydrogen-music/hydrogen#608]
General midi-learn (say through a config-file) for gui elements ,IMO, would transfer Hydrogen from "very good" to "incredibly awesome"  I'd have tons of fun with instrument's release\decay knobs, to mimic classic house techniques. 

Ability to select an instrument without triggering sample would be cool also.  

And last, but not least - it'd be amazing to have control over size of squareboxes, ones that mark if pattern is played or not. Would work great with touchscreen, works great now, but is bit difficult to hit the one you're aiming for.

**Comment by trebmuh** [comment]
Interesting. Please @aleeusgr , open one feature request per feature request and close this one.
