### ISSUE TITLE
no way to choose device for portaudio (critical for windows version)

### ISSUE THREAD

**Issue by nick87720z** [hydrogen-music/hydrogen#611]
Device option, in settings, needs to provide list of existing devices. At least for portaudio (not bothering too much about pulseaudio/alsa). Even with missing jack it is possible to use asio jackrouter, but even current text field is blocked for all drivers besides alsa.

update: Looks like it is hardcoded to use default device.

**Comment by cme** [comment]
#1344 adds a menu of existing devices for PortAudio, CoreAudio and ALSA.
