### ISSUE TITLE
Export to separate tracks not exporing final instrument

### ISSUE THREAD

**Issue by DarkRoastStudio** [hydrogen-music/hydrogen#612]
Hydrogen version *          :0.9.6.1
Operating system + version  : Linux Mint 18.3 x64
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When exporting a song, selecting export to separate tracks, the last instrument in the pattern is not exported. You can do a work around by just adding another empty track.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by trebmuh** [comment]
Hi @DarkRoastStudio could you try with a 1.0.0-beta1 version to check if the issue is still here please? I kind of remember someone working on and fixing that issue.

**Comment by mauser** [comment]
Yes, this should be fixed in the current version of Hydrogen. I've rewritten almost the complete export logic..

**Comment by mauser** [comment]
Closing this because lack of feedback, just comment if this issue is still present in Hydrogen 1.0.
