### ISSUE TITLE
H2 crashes when lastPlaylistFilename contains non existing file

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#613]
Hydrogen version *          : git 2cbb04f85d84bddb5a8a1caf614837cbe5323292
Operating system + version  : ubuntu 16.04
Audio driver + version      : jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
when upgrading to the latest git code H2 crashes on startup.
This is because the old hydrogen.conf file contains a reference to the last loaded playlist that is not valid (maybe related to the 'use relative paths for playlist' option ?)

if you edit the config file and enter any random string for the lastPlaylistFilename item, H2 crashes on startup.

example : 
`<lastPlaylistFilename>blablabla</lastPlaylistFilename>`

this is the error code H2 prints when it crashes : 

```
hydrogen: /home/thijs2/Music/Hydrogen_Code/hydrogen_april2018/src/core/include/hydrogen/basics/playlist.h:49: static H2Core::Playlist* H2Core::Playlist::get_instance(): Assertion `__instance' failed.
Aborted (core dumped)
```

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by francismaria** [comment]
Hey there! 

  I was trying to solve this issue but I haven't encoutered this problem. I changed in hydrogen.default.conf the `<lastPlaylistFilename></lastPlaylistFilename>` to `<lastPlaylistFilename>blabla</lastPlaylistFilename>` as @thijz said and re-built hydrogen however it hasn't crashed. 
  Am I changing this in the write file? 
   
  Cheers,
      
       Francisco

**Comment by mauser** [comment]
Hi! 

The default config file is only taken into consideration if you're installing Hydrogen for the first time or if you re-install hydrogen. In all other cases, Hydrogen takes the config file which is located in /home/Username/.hydrogen.
