### ISSUE TITLE
"Strip volume" midi control strange behaviour.

### ISSUE THREAD

**Issue by aleeusgr** [hydrogen-music/hydrogen#614]
Hydrogen version *          : 0.9.7
Operating system + version  :  Arch  kernel 4.16.7-rt1-1-rt #1 SMP PREEMPT RT
Audio driver + version      :  jackdmp 1.9.12

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Hi.
I have 2 knobs attached to controls - one to "select instrument" , other "strip volume"
I's expect the latter to follow selection  in mixer(the blue light follows strips as I expect on select instrument operation), but instead  of changing volume of selected strip, changes volume of first instrument in the list. 
I'm not sure if I'm not getting the proper order of operation, or if it operates not as intended. Sorry for little info, hit me up - I'll dig what I can

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by thijz** [comment]
hi @aleeusgr 
Actually I have always specified the strip id in the second 'param' column.  I'm not sure what the 'select instrument' action is meant to do 
![image](https://user-images.githubusercontent.com/1384210/40510408-ee5bb4ac-5f9c-11e8-9dfb-c4bd43753eea.png)

**Comment by aleeusgr** [comment]
Oh, Ok. With "select instrument" I rotate a knob and instrument selection cursor moves(kinda quirky, but it works) 
The instrument section in main window follows accordingly, so I can var knobs there with touchscreen. 
So yeah, I thought - move cursor -> apply volume, like that. Good to know
