### ISSUE TITLE
hydrogen fails to build with Qt5 >=  5.11

### ISSUE THREAD

**Issue by david-geiger** [hydrogen-music/hydrogen#615]
Hydrogen version *          : 1.0.0-beta1
Operating system + version  : Linux Mageia Cauldron
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Hi,

Since new Qt5 5.11.0 hydrogen fails to build due to:

> CMake Error at src/gui/CMakeLists.txt:57 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".

Upstream have removed this function in Qt 5.11.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Regards,
David

**Comment by mauser** [comment]
Hi! 

This issue is now resolved in #618. Thanks to @schnitzeltony !
