### ISSUE TITLE
hydrogen beta 64 wont allow pattern access to h2 files transferred on a thumb drive between different pc's 

### ISSUE THREAD

**Issue by creepyD007** [hydrogen-music/hydrogen#617]
Hydrogen version *   1.0.0 beta 1         :
Operating system + version  : win 7
Audio driver + version      : Microsoft hidef... generic

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

hydrogen beta 64 wont allow pattern access to h2 files transferred on a thumb drive between different pc's running win7

**Comment by mauser** [comment]
Hi! 

Could you add more details? What exactly happens with those songs? And could you please provide a h2song file of such a song?

**Comment by creepyD007** [comment]
i am using an hp-g62 and a dell e64atg........ i think the problem may be
related to diffident sound cards.... both running win7 sp1

**Comment by creepyD007** [comment]
next time i am at my studio. i will make a short vid and upload it to
youtube as a  non public vid.... then i will seng u a link

**Comment by theGreatWhiteShark** [comment]
Hey @creepyD007 ,

Is this problem still occurring in the latest release of Hydrogen?

**Comment by theGreatWhiteShark** [comment]
Closed due to inactivity and because I can not reproduce the problem. If the problem still occurs in a recent version of Hydrogen, please reopen the issue and I will take care of it.
