### ISSUE TITLE
Homepage throws 404

### ISSUE THREAD

**Issue by talonx** [hydrogen-music/hydrogen#621]
Hydrogen version *          : NA
Operating system + version  : NA 
Audio driver + version      :  NA

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

< describe your issue or feature request here ** >

http://www.hydrogen-music.org/ shows a "The requested URL / was not found on this server." error

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by trebmuh** [comment]
Duplicate. See https://github.com/hydrogen-music/hydrogen-music/issues/1 .
