### ISSUE TITLE
Generation of the documentation fails

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#630]
Hydrogen version *          :   a89f053d66ed009b3b9b6b8e8f4c1b707c2f0b17
Operating system + version  :  debian-based
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The build of the documentation fails with the following error

`./build.sh d`

> Generating API documentation with Doxygen
> /bin/sh: 1: cd: can't cd to /home/XXX/hydrogen/docs
> CMakeFiles/doc.dir/build.make:57: recipe for target 'CMakeFiles/doc' failed
> make[3]: *** [CMakeFiles/doc] Error 2
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/doc.dir/all' failed
> make[2]: *** [CMakeFiles/doc.dir/all] Error 2
> CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/doc.dir/rule' failed
> make[1]: *** [CMakeFiles/doc.dir/rule] Error 2
> Makefile:184: recipe for target 'doc' failed
> make: *** [doc] Error 2

**Comment by jeremyz** [comment]
closed by #631
