### ISSUE TITLE
Error Starting Audio Driver - Windows 10

### ISSUE THREAD

**Issue by xdakienx** [hydrogen-music/hydrogen#637]
Hydrogen version *          : 0.9.7
Operating system + version  :  Windows 10 64-bit
Audio driver + version      :  Auto

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Apologies if this is the wrong place to post, but I've run out of steam trying to fix this issue. I've googled for a solution, and I've tried to search the issue thread here. This was the closest I could find that was similar to my issue (https://github.com/hydrogen-music/hydrogen/issues/113). I do not have the option to set Tool -> Preferences -> Audio System to ALSA. The only options available to me are Auto, Jack and PortAudio. All 3 of them give me the same pop-up error window. "Error Starting Audio Driver". I can export songs ive made and they play just fine. I can't seem to get them to play in hydrogen itself. I can add new drum sounds but if i hit the play button nothing happens.

The strangest thing is this is a new problem. When I 1st installed Hydrogen there were no issues.

**Comment by mauser** [comment]
Hi! 

"ALSA" is a sound system which is not available for Windows, but that's not a problem. Using PortAudio should be fine.  Have you tried to install the beta version Hydrogen 1.0-beta1?
