### ISSUE TITLE
BEAT cannot be changed after song is saved

### ISSUE THREAD

**Issue by brunoserralheiro** [hydrogen-music/hydrogen#638]
Hydrogen version *          : 0.9.6.1
Operating system + version  :  Linux UBUNTU STUDIO 16.04
Audio driver + version      :  JACK Audio Connection Kit - Qt GUI Interface 
                                            Version: 0.4.2
                                            Build: Apr 7 2016 21:23:34

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I saved a song 193bpm and later tried to lower the beat, and it cannot be done, either by typing another beat on popup nor by clicking on down arrow.

_note: message edited by @trebmuh for a better display_

**Comment by thijz** [comment]
Are you using bpm markers? If so, you need to change th tempo on the marker

**Comment by trebmuh** [comment]
@brunoserralheiro : can you please answer @thijz question?

**Comment by trebmuh** [comment]
@brunoserralheiro : ping?
