### ISSUE TITLE
Holes between instrument layers cause sampler to skip notes

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#639]
After writing the humanizer Hydrogen showed an odd behavior. Occasionally it seemed to just skip notes of specific instruments, e.g. for the Open Hat in the GM kit or for the Kick in Millo_Multilayered2. But all other instruments of the drumkit were not affected. Setting the verbose level to warnings revealed that only notes of very specific velocities in a very narrow range were skipped. 

At first I thought this to be a bug in the pink noise of the tweaked humanizer. But it turned out to occur in both the white noise and the original implementation of the humanizer as well. 

After spending some hours delving into the code base I found the sampler itself to be the cause of the problem. For some instruments the individual layers are not perfectly aligned. Let's take the *Open Hat* of the default GMKit for example. 

> (I) Sampler::__render_note nLayer: 0. Note velocity: 0.796811. Layer velocity_start: 0. Layer velocity_end: 0.202899
> (I) Sampler::__render_note nLayer: 1. Note velocity: 0.796811. Layer velocity_start: 0.202899. Layer velocity_end: 0.394928
> (I) Sampler::__render_note nLayer: 2. Note velocity: 0.796811. Layer velocity_start: 0.398551. Layer velocity_end: 0.601449
> (I) Sampler::__render_note nLayer: 3. Note velocity: 0.796811. Layer velocity_start: 0.605072. Layer velocity_end: 0.793478
> (I) Sampler::__render_note nLayer: 4. Note velocity: 0.796811. Layer velocity_start: 0.797101. Layer velocity_end: 1
> (W) Sampler::__render_note NULL sample for instrument Hat Open. Note velocity: 0.796811.

There are tiny holes between the end of one layer and the start of the next. Whenever the velocity of a note falls into it, it will be skipped by the sampler. The latter just checks whether the note is between the start and the end of a layer.

The problem was just more pronounced since the pink noise is able to create smaller and more subtle fluctuations, even with a large scaling. But you can also reproduce it by setting Open Hat beats to a velocity of 0.8 in the former implementation and setting the humanizer of the velocity to a small, non-zero value.

**Comment by thijz** [comment]
wow ... nice catch !

**Comment by jeremyz** [comment]
fixed by the author of the issue, thanks a lot
