### ISSUE TITLE
various drumkit issues

### ISSUE THREAD

**Issue by spkstrqwen** [hydrogen-music/hydrogen#642]
Hydrogen version *          : Hydrogen 1.0.0 beta1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- Issues loading drumkits from the Hydrogen Website
- No problem loading drumkits from Belofilms but partway through installation, it will cancel, saying that there is a connection error when there is no network issues. This has worked in the past as I was able to successfully install 3/7 kits but does not work now.

**Comment by mauser** [comment]
Hi!

i've put the drumkits which are not located at SourceForge now to a new server, so the downloads work again. You have to update the drumkit list before to get the fresh URLs for the drumkits.

**Comment by spkstrqwen** [comment]
Amazing! Thank you so much for your swift resolution.

**Comment by spkstrqwen** [comment]
I've tried updating the list of drumkits but nothing has happened. Are they located on a different URL server? Would you have a link I can use?

Thank you for your efforts once again.

**Comment by trebmuh** [comment]
@mauser is there a new address for those drumkits?

**Comment by mauser** [comment]
Hi! 

No, the address of the drumkit list itself stayed the same (http://www.hydrogen-music.org/feeds/drumkit_list.php). I've just adopted the URLs in the list itself (located [here](https://github.com/hydrogen-music/hydrogen-music/blob/master/feeds/drumkit_list.php) ). You can't change the entries in the list locally.

Which error are you getting while downloading the kits?
