### ISSUE TITLE
'14 ways to contribute' page missing

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#644]
the '14 ways to contribute' page is missing from the website 
(see http://hydrogen-music.org/contribution)

**Comment by mauser** [comment]
Hi!

Indeed! It seems that this got lost during the transition to github pages. Thanks for noticing! 

Btw, i will close this issue here, we got a separate tracker over for the website issue. New issue is here: https://github.com/hydrogen-music/hydrogen-music/issues/2

**Comment by thijz** [comment]
ok, got it
