### ISSUE TITLE
h2song file uses absolute path names for drumkits from the soundlibrary

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#645]
Hydrogen version *          :  fbe7a78fd829d6e4e0b3d30b03037224ac2e680a
Operating system + version  :  Linux

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When saving a song created with a drumkit from the sound library (either from the system or user path),
Hydrogen uses an absolute filename for all samples. 

This makes it impossible to exchange the song with an instance of Hydrogen which runs on different PC with a different filesystem layout. 

Example from a song:
```
<layer>
      <filename>/home/sebastian/.hydrogen/data/drumkits/GMkit/kick_Dry_b.flac</filename>
      ...
</layer>
```

How to reproduce: 
- Open a new song 
- Save it
- Inspect the filename of a layer

**Comment by elpescado** [comment]
There's workaround though - after loading song you have to reload drumkit from library.

**Comment by thijz** [comment]
@elpescado : that's assuming that you are using an unmodified drumkit.  If you create a song and drag instruments from different kits in the song and you dont save the modified drumkit as a new drumkit (like i do all the time) you're in trouble  :-)

**Comment by elpescado** [comment]
@thijz you're right

**Comment by jeremyz** [comment]
my bad, sorry !!!
