### ISSUE TITLE
Updating the sound library list : wrong default adress !

### ISSUE THREAD

**Issue by phlinux** [hydrogen-music/hydrogen#648]
The default address for updating the sound library list is
http://www.hydrogen-music.org/feeds/drumkit_list.php
but with this one the sound library list is not updated !

By cons with
http://hydrogen-music.org/feeds/drumkit_list.php
the sound library list is well updated.

You have just to remove "www."
Thanks.

**Comment by mauser** [comment]
Hi! 

This should be not a problem if you have a version of Hydrogen which is able to handle HTTP redirects correctly for the drumkit list (see #634). But i will also consider changing the default, which is a little bit more then just removing the "www" from the default file.

**Comment by mauser** [comment]
The address without the "www" is now present in the default configuration file, which is used if Hydrogen is newly installed.
