### ISSUE TITLE
Segmentation fault when changing drumkits while playing

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#649]
Hydrogen version *          :  1.0.0-beta1 (commit edc8584)
Operating system + version  :  Linux / Devuan ASCII
Audio driver + version      :  Jack2 1.9.12 (commit 67e4b43) (compiled without D-Bus)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Every time I load a different system drumkit while the audio engine is playing the application does crash with a segmentation fault. It doesn't matter whether Jack-transport mode and Jack-Time-Master is on or whether I switch to the GMRockKit or TR808EmulationKit. The error is also persistent under removing and reinstalling all shared data (including the drumkits). When the audio engine is stopped, everything is working properly. With some user drumkits I experience the same problems but, oddly, not with all of them.

Unfortunately, I don't have any luck debugging this issue. I'm still not familiar how to properly do this in Qt and setting log messages gets me nowhere. 

The error is the following:

```
(I) ::int H2Core::audioEngine_start(bool, unsigned int) [audioEngine_start]
(E) Sampler::__render_note Note pos in the future?? Current frames: 0, note frame pos: 10849655
(I) LCDCombo::LCDCombo INIT
(I) InstrumentRack::InstrumentRack INIT
(I) InstrumentEditorPanel::InstrumentEditorPanel INIT
(I) LCDCombo::LCDCombo INIT
(I) Drumkit::load Load drumkit /usr/local/share/hydrogen/data/drumkits/GMRockKit
(I) XMLDoc::read XML document /usr/local/share/hydrogen/data/drumkits/GMRockKit/drumkit.xml is valid (/usr/local/share/hydrogen/data/xsd/drumkit.xsd)
(D) XMLNode::read_string Using default value  for image
(D) XMLNode::read_string Using default value undefined license for imageLicense
(I) Drumkit::load Load drumkit /usr/local/share/hydrogen/data/drumkits/TR808EmulationKit
(I) XMLDoc::read XML document /usr/local/share/hydrogen/data/drumkits/TR808EmulationKit/drumkit.xml is valid (/usr/local/share/hydrogen/data/xsd/drumkit.xsd)
(D) XMLNode::read_string Using default value  for image
(D) XMLNode::read_string Using default value undefined license for imageLicense
(I) LCDCombo::LCDCombo INIT
(I) LCDCombo::LCDCombo INIT
(I) PianoRollEditor::PianoRollEditor INIT
(I) LCDCombo::LCDCombo INIT
(I) PlaylistDialog::PlaylistDialog INIT
Segmentation fault
```

_message edited by trebmuh for a better display_

**Comment by theGreatWhiteShark** [comment]
Also, when no notes specified in the current pattern, switching between the drumkit works fine. The more notes present, the more likely for Hydrogen will throw a segmentation fault. On a regular sized pattern it does always happen.

**Comment by mauser** [comment]
Hi! 

Good observation (again :smiley: ) ! I can reproduce this problem here with some drumkits. Will have a deeper look in the next days. At least it crashes always in the same location in the sampler :)

**Comment by trebmuh** [comment]
Just for what it worth, I've played a bit around that (changing drumkit while playing a demo song) with a fresh build from git https://github.com/hydrogen-music/hydrogen/commit/a1b11e66c2c6d0d35ba02e22f68742be3f958cf4, and I'm unable to reproduce the problem.

**Comment by theGreatWhiteShark** [comment]
In order to properly reproduce the issue, I build Hydrogen at the corresponding commit inside a Docker image. It is build against Jack1 since I was unable get Jack2 running inside a Docker container but the bug does still appear.

You can run the image using 

``` bash
sudo docker run -p 5900 --rm --privileged=true --device=/dev/snd:/dev/snd thegreatwhiteshark/hydrogen:edc8584.0 x11vnc -forever -usepw -create
```

It will start up a x11vnc server you can connect to using a local client. The build is located in */root/hydrogen/build*. See https://hub.docker.com/r/thegreatwhiteshark/hydrogen/ for further details.

Steps to reproduce:
- Start Hydrogen
- In the current pattern fill 3-4 instruments using *Fill notes... > Fill all notes*
- Start the audio engine
- Switch between the system drumkits using *Sound library > System drumkits > (right klick) > Load*

**Comment by theGreatWhiteShark** [comment]
The problem seems to be fixed now. Thanks a lot!

**Comment by mauser** [comment]
Hi! 

Thanks for testing again! I've added some smaller fixes in the last days, and it seems that they have helped :) Btw. thanks for providing the docker image! I haven't used docker for debugging yet, but it sounds like a good idea to provide a reproducable environment.
