### ISSUE TITLE
Offer appimage or flatpak?

### ISSUE THREAD

**Issue by 38github** [hydrogen-music/hydrogen#650]
Are you thinking about offering any these to make it easy for us to both run the stable and to easily try out alphas/betas/rc's? It would probably make a lot non technical users able to try out and report bugs before stable releases. Regards.

**Comment by elpescado** [comment]
That's cool idea. I remember that 3rd party software distribution was always pain on Linux.

It would be great if we could automate creation of those packages on Travis.

**Comment by hfiguiere** [comment]
I have submitted a flatpak to flathub. See flathub/flathub#819 It is currently in review, but when it passes Hydrogen will be available on Flathub.

**Comment by trebmuh** [comment]
Nice @hfiguiere , let us now when done.

**Comment by hfiguiere** [comment]
The build is up on Flathub. If you have feedback, feel free to file an issue over there.

**Comment by trebmuh** [comment]
Thanks for keeping us in the loop @hfiguiere and good job!
I'm closing this issue now it's resolved.
