### ISSUE TITLE
Segmentation fault on accessing Instrument -> Layers for newly created drumkit

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#651]
Hydrogen version * : 1.0.0-beta1 (commit edc8584)
Operating system + version : Linux / Devuan ASCII
Audio driver + version : Jack2 1.9.12 (commit 67e4b43) (compiled without D-Bus)

----

I just tried to create a new drumkit from scratch in order to debug another issue but it is just not working.
Firstly, I create a new drumkit using the menu _Drumkits -> New_ (for either an existing or a blank new song). When I try to access the _Instrument -> Layers_ panel, Hydrogen crashes with a segmentation fault and without any debug messages.

Can you reproduce this or is there something buggy within my system/setup?

**Comment by theGreatWhiteShark** [comment]
This only happens with a fresh instance of the Hydrogen application. After hitting the _Layers_ button once, the error does not occur anymore.

In addition, the _InstrumentEditor::buttonClicked_ function is not entered before the segmentation fault occurs.

**Comment by mauser** [comment]
I can't reproduce the exact problem, but i can see that a lot of stuff goes wrong with the layer panel and its initialization/updating. While fixing a bug there last week, i saw that the whole widget behaves not properly when not instruments are being loading.

**Comment by theGreatWhiteShark** [comment]
Hey, 
Thanks a lot! I'll try later today or tomorrow. 

For the time being I created a Docker image containing the build of the version above (against Jack1). Details about the usage are described in here https://hub.docker.com/r/thegreatwhiteshark/hydrogen/ and you can use it to reproduce the bug.

Steps to reproduce:
- Start up Hydrogen
- Klick *Drumkits > New*
- Klick *Instruments > Layer* (without klicking anywhere else beforehand)

P.S. I created another Docker image https://hub.docker.com/r/thegreatwhiteshark/hydrogen-dependencies/ containing all the required packages to compile Hydrogen from source and the x11vnc server in order to interact with it. It may be useful for other debugging/reproducibility issues.

**Comment by theGreatWhiteShark** [comment]
HI @mauser,

The issue was resolved with your latest commit. Thanks again!
