### ISSUE TITLE
Pattern drag'n'drop -> crash

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#652]
Hydrogen version          : git https://github.com/hydrogen-music/hydrogen/commit/4f2ba17d18580b3c6caa2e663be054d5f4090817
Operating system + version  : debian stretch
Compiled with Qt5 : 5.7.1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Drag'n'dropping a hydrogen pattern on the GUI makes it crashes.

Starting hydrogen from a CLI gives:
```
ASSERT failure in QList<T>::at: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 537
Abandon
```

See: http://download.tuxfamily.org/librazik/volatile/bug652-hydrogen.mp4

**Comment by sub26nico** [comment]
Same here with same hydrogen version, same OS and Qt5 in version 5.7.1.

**Comment by trebmuh** [comment]
My bad, my QT version is 5.7.1 as well. I'm editing my first post right after this one.

**Comment by mauser** [comment]
Hi,

there was a bug in the error handling of the support for dragging a pattern from the soundlibrary. As a new feature, i've implemented the support for dropping h2pattern files from external filebrowsers. 

Could someone re-test the issue with a current git version of hydrogen?

**Comment by trebmuh** [comment]
Retested from a fresh build and it doesn't crash anymore.
Thanks @mauser !
