### ISSUE TITLE
Pattern properties do not enable author name

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#653]
Hydrogen version          : git https://github.com/hydrogen-music/hydrogen/commit/4f2ba17d18580b3c6caa2e663be054d5f4090817
Operating system + version  : debian stretch
Qt5 : 5.4.1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Scenario**

I'm making a new pattern. Then I want to add the info that are present in the xml file:
1. drumkit name
2. author
3. license
4. name
5. info
6. category

The issue is that I can only fill 3 of those from the _click on the pattern name -> properties_ window:

4. name
5. info
6. category

See here:
![hydro-pattern-properties](https://user-images.githubusercontent.com/8705846/44993954-cf270500-af9c-11e8-956d-608a0f710283.png)

**What would I expect?**

I'd like to also be able to fill up the 3 other information from this window.

**Comment by mauser** [comment]
Hi! 

The drumkit name was never meant to be editable by the user, this is sth. Hydrogen will set when saving the pattern. 

Author and License are currently more or less unused in the Hydrogen application itself. The data in the XML is taken from the song information, so it is the Author and the License of the song the pattern belongs to when being saved. 
I guess the main idea is here that this information was mostly interesting for the online soundlibrary feature. 

I would say that it makes sense to edit and display Author and License, but not to edit the drumkitname.

**Comment by trebmuh** [comment]
> I would say that it makes sense to edit and display Author and License

Yes.

> but not to edit the drumkitname

I can live without it :)

**Comment by Nikita2552** [comment]
Helllo, this task is available now? @mauser , I want the first contribute for this project.

**Comment by theGreatWhiteShark** [comment]
Hey @Nikita2552 ,

Sorry for the late reply. Of course, go for it :)

**Comment by theGreatWhiteShark** [comment]
Turns out these properties have been introduced just recently https://github.com/hydrogen-music/hydrogen/commit/5d52bfc76017a7d9a7100ec2c4aa3943623c5adc.

**Comment by theGreatWhiteShark** [comment]
Implemented in #2014
