### ISSUE TITLE
Sample layer display uses hard to read colors

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#656]
Hydrogen version *          : 1.0.0-beta1
Operating system + version  :  Ubuntu
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

As it can be seen on the following screenshot, Hydrogen uses a hard to read font color / background color combination on the 'layer' tab:

![grafik](https://user-images.githubusercontent.com/202461/45266224-f1ff6080-b457-11e8-957c-b3d986924ba4.png)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by trebmuh** [comment]
I do agree.

**Comment by theGreatWhiteShark** [comment]
Closed with #1488. See #1491
