### ISSUE TITLE
Instruments will be deleted even if in use

### ISSUE THREAD

**Issue by achimwagenknecht** [hydrogen-music/hydrogen#669]
Hydrogen version       : 0.9.7
Operating system + version  : Ubuntu 18.04
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
When using "Instruments / Delete all instruments", all instruments are deleted, even if they are in use already. The software should check and ask the user if they really want to delete instruments that are in use.

**Comment by trebmuh** [comment]
Hi @achimwagenknecht can you try from a more recent Hydrogen?

I've tried from a fresh mgit head master home build (https://github.com/hydrogen-music/hydrogen/commit/bbeaed1a5d46414360cbce74e81fbcc0a05e26f6) and I've got a pop up window asking me to confirm:

![popup](https://user-images.githubusercontent.com/8705846/55124001-fb56ce80-5104-11e9-90ef-8a8fd8385727.png)


I'm then under the impression that everything is good from an user point of view.

**Comment by mauser** [comment]
Closed due to lack of feedback.
