### ISSUE TITLE
song editor : when adding a tag you must click the 'ok' button to save

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#67]
when you add a new tag to a song you must click the OK button of the tag window to save the tag
if you add a new tag and hit enter, the tag window will close, but the text you added is not saved
it would be nice if hitting enter has the same effect as clicking the OK button (seems only logical to me)

**Comment by jeremyz** [comment]
it is working as expected now, confirm and close please

**Comment by thijz** [comment]
Hi @jeremyz 
Thanks for your work !

Yesterday i had a quick test and noticed a different behavior between when you initially add text to an empty field, and editing existing text:
The behavior was as expected for text you enter in an empty field, but when i edited existing text and hit return the tag window immediately closed but my changes were not saved.

However ...
I just tried to reproduce it ... and now it works perfectly .. ??
I did do a git pull, but i doubt if anything related to this ticket changed in the last day or so ?

**Comment by jeremyz** [comment]
Hello @thijz !
I was bored with life lately ;)))
I can assure you that none of the patches I've pushed are related to this !
(well 28e21725d08be64aef is about drag & drop though)
I've once again just tested that behavior and it seems to be ok.

**Comment by trebmuh** [comment]
Closing now since it looks to be OK.
Feel free to reopen if needed.
