### ISSUE TITLE
Alternate Mapping of Midi Notes to Instruments / Notes

### ISSUE THREAD

**Issue by movitto** [hydrogen-music/hydrogen#671]
Hydrogen version *          : 0.9.7
Operating system + version  : Fedora 28
Audio driver + version      :  PulseAudio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
First off, many thx to the devs for this great software. Playing around with the UI and exploring the code locally I notice there are a few ways which midi events are mapped to Hydrogen actions:

- mapping of midi notes to actions configured in the preferences
- single-instrument toggling (hydrogen plays the selected instrumenet w/ various pitches)
- auto-assigning drumkit instruments to midi notes

From my understanding the last occurs here, where the selected instrument # = note number - 36:

https://github.com/hydrogen-music/hydrogen/blob/master/src/core/src/IO/midi_input.cpp#L271

---

This may work great for a simple drumpad but for controllers like the novation launchpad (consisting of an 8x8 row of buttons each corresponding to a midi note), this auto-assignment results in many inputs not being usable as they are mapped to instruments that do not exist. Would it be possible / acceptable to extend the codebase so as to allow the user to assign midi-notes to instruments / notes in a custom manner?

**Comment by movitto** [comment]
Following up on this, from my investigation this could happen in a couple of different ways:

- extend the 'midi actions' to specify a 'trigger_instrument' action, so that the user can map custom instrument invocations to specific midi events:

https://github.com/hydrogen-music/hydrogen/blob/master/src/core/src/midi_action.cpp#L89

This would have the benefit of fitting into the current model of mapping custom midi events to actions though due to the nature of the related preferences section, specifying multiple parameters (the instrument to trigger, the note to trigger, other instrument properties) would be tricky.

- add an additional/alternate 'midi assignment' configuration mechanism which can be used to override the default midi note / instrument assignment and specify the instrument, note, and params to trigger. This would be launched in the same logic sequence as the default assignment, only if there is no fixed mapping for the midi event.

**Comment by elpescado** [comment]
Hi,

There are two modes when it comes to handling incoming MIDI messages, controlled by "Use output note as input note" checkbox in MIDI preferences.

If this option is enabled, instruments respond to MIDI notes that are assigned in instrument properties panel:
![screenshot](https://user-images.githubusercontent.com/1619113/46920861-b0347d80-cff4-11e8-9692-07ad052b7cdd.png)

When that option is not enabled, Hydrogen uses consecutive note numbers for instrument, starting from 36.

I think enabling "Use output note as input note" solves your problem.

**Comment by movitto** [comment]
@elpescado cool, yes this did work. I had to use a development build of hydrogen as the one vendored w/ Fedora is a bit old, but once I set that option and assigned the instruments to corresponding notes, I was able to map them.

That being said this option name is a little confusing, have the devs considered renaming it. Perhaps "Trigger instrument with assigned notes" or perhaps invert the context and rename the option to "Used fixed midi note / instrument mappings" (in the later case it would make sense to hide the "channel" and "note" controls as well)

Thx for the help! And if anyone is wondering, once midi mappings are configured, one can save the instrument rack via the "Drumkits" menu so as to quickly load the assignment in the future!

**Comment by elpescado** [comment]
Yes, that option is #&#xfeff;1 on my list of most confusing names in Hydrogen;)

The reasoning behind it is probably that this property was originally meant to control *output* note (i.e. MIDI message sent by Hydrogen). Because of that, showing channel and note controls still makes sense even if "Use output note as input note" is disabled.
