### ISSUE TITLE
Zero Layers will save when creating instrument load out

### ISSUE THREAD

**Issue by colinchildsmixing** [hydrogen-music/hydrogen#674]
Created my own drum kit with several samples and made several layers. It saved in one project only, but when opening or starting new projects, none of the layers are saved in the user instrument that I created.

**Comment by theGreatWhiteShark** [comment]
This sounds  a lot like the problem reported in here https://github.com/hydrogen-music/hydrogen/issues/622

Do you use the most recent version of Hydrogen?

**Comment by colinchildsmixing** [comment]
> This sounds a lot like the problem reported in here #622
> 
> Do you use the most recent version of Hydrogen?

Okay cool, I checked out #622 
Looks complicated to fix. 
Yes, I used the most recent version. However the drumkit had saved in the original project that I created it in. So my own solution for now is to just use that original project, create a new song, then save as for a new project and it seems to work. Its slightly annoying but I suppose it beats paying hundreds for a program like superior drummer. Thanks for dropping that link, I'll have to go more into depth with it for a permanent solution.

**Comment by theGreatWhiteShark** [comment]
Just to be sure: You downloaded Hydrogen at the latest commit 538eaeb  and compile and installed it from source?

What operation system are you using? And can you give some step-by-step guide to reproduce the issue?

**Comment by jeremyz** [comment]
Hi,
there's maybe just a little something wrong in the drumkit.xml file of your home made drumkit.
maybe if you post it here we can find out what and fix your file or better improve the loading/saving code path.

**Comment by trebmuh** [comment]
@colinchildsmixing we need your feedback to get the ball rolling here :sunglasses:
