### ISSUE TITLE
not loading songfile on double-click

### ISSUE THREAD

**Issue by sixrabbits** [hydrogen-music/hydrogen#686]
Hydrogen version *  1.0.0 beta1        :
Operating system + version  : Windows 7 Home Premium SP1
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

With Hydrogen not running, a double-click on a  songfile.h2song icon opens Hydrogen, but does not load the songfile contents. Instead, an untitled song is loaded.  (In Preferences, I have cleared the Reopen Last Used Song checkbox.)
Note that multiple instances of Hydrogen will run simultaneously.  I don't know if that's a good thing or not  Maybe add an "Allow multiple instances to run" checkbox in the preferences?

**Comment by trebmuh** [comment]
I can reproduce that on linux from a fresh build from git head master (https://github.com/hydrogen-music/hydrogen/commit/bbeaed1a5d46414360cbce74e81fbcc0a05e26f6).

If I'm right-clicking on a .h2song file and ask to open it with Hydrogen, Hydrogen is launched, but it's opening with the last song I worked with before closing it.

Note that this is happening whether or not the _Preferences -> General -> Reopen last used song_ option is ticked.

**Comment by cme** [comment]
#859 should solve this.

**Comment by trebmuh** [comment]
I can confirm that now, if I'm right-clicking on a .h2song file and ask to open it with Hydrogen, Hydrogen is launched and it opens the correct h2song.

@cme @mauser : since #859 has been merged into master, I'm closing here now. Feel free to reopen if needed.
