### ISSUE TITLE
Title bar doesn't update on 'Save As'

### ISSUE THREAD

**Issue by sixrabbits** [hydrogen-music/hydrogen#687]
Hydrogen version *          :1.0.0 beta1
Operating system + version  : Windows 7 Home Premium SP1
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Project > Save As: "NewSong" doesn't update the file name in the title bar. Instead, the name in the title bar is is inherited from the OldSong's song name in the Song Properties window.  This made me believe that NewSong wasn't saved.  This seems like bad manners for the title bar behavior.

IMHO, the current file name should should always appear in the title bar. 

I suppose it's a feature for the filename and the song title to be independently maintained?

**Comment by pvint** [comment]
Cannot reproduce on latest GIT (in Linux, but it's unlikely to be an OD-specific issue I would think)

 I think I recall this coming up in the past, and although I couldn't find it quickly I believe this was already addressed.

**Comment by mauser** [comment]
Hi! 

The behavior can also be reproduced with the current git version of Hydrogen and Linux. 

1) Load a song and set a name via the song properties (say "MySong")
2) Use "Save as.." to save the song under a different name ("tmp.h2song").  

After Step 2, the title bar still reads "MySong". Why is that? 

When using "Save as...", you're just changing the filename of the Song. The song properies won't be touched and the Song properties (including the name set in the properties) won't be touched. The song name in the song properties and the file name are independent from each other, so in my opinion the current behavior is explainable, alhough i can understand the confusion. 

If no Song name is set and no default song "Untitled song" is loaded, Hydrogen will use the file name for the title bar information. 

Would it help if we use somelink like "Songname (Filename.h2song)" in the title bar? I can imagine that this could be too long for large filenames/songnames..
