### ISSUE TITLE
playlist : some playlist enhancements

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#69]
it would be nice to be able to :
- delete a song from a playtlist by pressing Delete, or by selecting Delete from a menu that pops up when you right-click a song in the playlist
- selects multiple songs in a playlist and delete all of them at once

**Comment by mauser** [comment]
Hi,

the first point is now available in the master branch, all actions of the main menu now have keyboard shortcuts. Can we close this issue or is the second part really important for you?

**Comment by thijz** [comment]
just retested but hitting Del doesnt seem to work  ...

**Comment by thijz** [comment]
-correction-
hitting DEL _does_ work and that's enough for now
closing ticket
