### ISSUE TITLE
need to start/stop before hearing sound 

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#70]
on 1 song that i have created i always need to start/stop/start before i can hear the sound of the samples
in att you can find the song + a short screencast that demonstrates this bug

seems like some other users are also experiencing this type of behavior : see http://hydrogen.popez.org/hcms/node/2003#comment-57784

this bug is 100% reproducible

comment by Wolke:

instrument stick first note on tick 3 has a negative lead-lag value. if you set this note lead-lag to zero or an positive value the error is gone.
imo, we have an problem with negative lead-lag settings!

create this bug:)
open new song
place an note on position 3 (res = 64 than the second position) "other positions will work as expected"
edit lead lag in upper direction(negative value). important the slider must become real read color, otherwise no effect.
save song and reopen the song.

no sond!!

**Comment by thijz** [comment]
i need to retest this one

**Comment by mauser** [comment]
@thijz : You need to retest this one :)

**Comment by georgkrause** [comment]
i have the same problem. i am using luppp and sync h2 to luppp. because luppp does not support many sync types i need to stop hydrogen and luppp, set hydrogen to jack transport but without jack master and push play in luppp. now both are in sync but h2 is muted...

**Comment by georgkrause** [comment]
checked the latest master, still the same problem. :( so i cant sync luppp and hydrogen at the moment.

**Comment by georgkrause** [comment]
when i activate jack sync and jack master both programs are in sync and h2 makes sound.

**Comment by thijz** [comment]
i really think i need to retest this one ...

**Comment by georgkrause** [comment]
well i also can do some intensive testing when someone tell me what is needed

**Comment by thijz** [comment]
just retested with code from this week and i cant reproduce it any more
since this is a really old ticket i'll close it now
@georgkrause : do you still see this with the current h2 code ?  if yes, we can reopen this ticket
