### ISSUE TITLE
Hydrogen Audio not working on Win 10 Pro 

### ISSUE THREAD

**Issue by oelvir** [hydrogen-music/hydrogen#700]
Hydrogen version *          :1.0.0-beta1
Operating system + version  : Windows 10 Pro - 10.0.17134 Build 17134
Audio driver + version      : M-Audio Delta AP 192
Driver version: 5.10.0.5078

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I'm able to install it but the minute I run Hydrogen It shows me the thank you dialog box then when I click OK I see this dialog box: Error starting audio driver.
I went to the Preferences option and I was able to set my midi devices fine and I can see the Midi-In 
Monitor light but no sound The Issue is in the Audio System section  under Device I'm not able to pick my Audio device because it shows nothing to pick and in the Audio Output details section I can pick Auto or PortAudio but none of them work I get the same error, aslo I get the same error when I click on the Restart output.

I,ve tried the Hygrogen 0.9.7- win32 stable version and the 1.0.0-beta1-win64 version they bought do the same error.

hope this help....

**Comment by mauser** [comment]
Hi! 

Do you have multiple soundcards connected to your PC? If yes, could you try to launch Hydrogen when only one soundcard is connected?

**Comment by mauser** [comment]
Closed due to lack of feedback.
