### ISSUE TITLE
[FEATURE REQUEST] pattern to scroll-show

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#701]
Hydrogen version *          : all
Operating system + version  : all
Audio driver + version      : all

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

A user suggested on linuxmao (the francophone linux-audio community) that it could be great to see the different patterns to scroll and to be showed when playing a song. Currently, the pattern showed is the one selected on the patterns-list in the song part of the window.

_origin: http://linuxmao.org/forumthread91600_

**Comment by sub26nico** [comment]
I add my voice here, it could really be a great workflow improvement.

**Comment by thijz** [comment]
that is assuming that you have selected only 1 pattern at the same time in your song editor
what if you have multiple patterns playing at the same time ?  what pattern should then be displayed ?

**Comment by oddtime** [comment]
thijz is right. Maybe priority could be given to the first appearing pattern in patternSequence group.

**Comment by trebmuh** [comment]
I propose and suggest on a first idea that H2 should show the first pattern in the column which would probably cover for 90% of the scenarii.

**Comment by cme** [comment]
This has been added in #1437 now on master.

When enabled (it's an option on the first sheet of the Preferences dialog). The rule used is that if the currently selected pattern is no longer playing, then the pattern which is the first currently-playing pattern visible in the viewport of the Song Editor will be selected.

**Comment by trebmuh** [comment]
Nice! Can't wait to test it!
