### ISSUE TITLE
Muting an instrument does not mute midi events

### ISSUE THREAD

**Issue by julienmoumne** [hydrogen-music/hydrogen#704]
Hydrogen version *          : 0.9.7
Operating system + version  : Ubuntu 18 LTS
Audio driver + version      : pulseaudio 11.1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

This is related to https://github.com/hydrogen-music/hydrogen/issues/266 but not exactly.

Muting an instrument using the `M` button mutes the audio but not the MIDI events.

I am referring to this `M` button : 
![image](https://user-images.githubusercontent.com/723165/55069869-48935b80-5085-11e9-922a-ab0c12b2a657.png)

Midi events are still sent to the `Hydrogen` MIDI output.

I am referring to this MIDI output : 
![image](https://user-images.githubusercontent.com/723165/55069827-2ef21400-5085-11e9-93e6-31c0eaf8e634.png)

Is this expected? If yes, is there a known workaround so that MIDI events are not sent for a muted instrument?

**Comment by trebmuh** [comment]
Thanks for the very well detailed report.
I hope a developer will have some time to take care of that.
I've just triaged this bug as a MIDI related one to help with the process.

Happy drumming!

**Comment by julienmoumne** [comment]
Would you be able to give me some pointers in the code so I could give it a try?

**Comment by julienmoumne** [comment]
I've successfully patched the code but I would need help in making my change fit the bigger picture and apply proper cpp coding style.

**Comment by mauser** [comment]
Hi,

the patch is now available in the master branch.
