### ISSUE TITLE
Got a segfault when open preferences

### ISSUE THREAD

**Issue by Olli** [hydrogen-music/hydrogen#705]
Hydrogen version *          : bbeaed1a5d46414360cbce74e81fbcc0a05e26f6
Operating system + version  :  Debian SID
Audio driver + version      :  Pulseaudio 12.2-4

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I start up Hydrogen and try to open the preferences and hydrogen segfaults instantly.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by Olli** [comment]
Ok some addition: this happens when i build Hydrogen with "cd build && cmake ../ && make" ... with "./build.sh m" it works.

**Comment by theGreatWhiteShark** [comment]
This is quite strange. Did you run `sudo make install` in the build directory in both cases?

**Comment by Olli** [comment]
I did not "make install" and use hydrogen in the source dir because there is an other version of hydrogen installed coming from the Debian repo (yes I did rename the ~/.hydrogen dir ) .

**Comment by theGreatWhiteShark** [comment]
Well, I'm not an expert in C++ yet to pinpoint the exact cause but during development I encountered the same problem multiple times. My guess is that Hydrogen is relying on its shared data, especially the headers, you install during `sudo make install`. When you instead compile a version of the program different from the one installed on your system you get these data all mixed up. 

I would suggest you to use `sudo make install` on every new version of Hydrogen you compile from source. Don't worry, it will be installed in */usr/local* and does not overwrite the package you have installed using your package manager.

**Comment by Olli** [comment]
Ok. But the shared libs are linked against the binary ... it should not matter where the binary is executed. 
Now it runs. I close the PR. I'll try to add debugging symbols to the next build so if it fails I'm able to give more deep insights if it segfaults :)
Thx for response.
