### ISSUE TITLE
H2 'no pattern found' when Jack transport is enabled and not in 'loop mode'

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#707]
Hydrogen version *          : git rev-parse HEAD : bbeaed1a5d46414360cbce74e81fbcc0a05e26f6 (code from March 30)
Operating system + version  : ubuntu 18.05
Audio driver + version      : jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

steps to reproduce : 
- start H2 from terminal
- create a new song
- enable 'loop mode'
- enable 'jack transport'  (enable/disable jack master does not matter)
- no error in the terminal > all OK

now disable 'loop mode' and you will see the terminal flooded with error messages like these : 

```
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 1312. No pattern found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 1312. No pattern found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 1313. No pattern found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 1313. No pattern found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 1313. No pattern found
(E) ::int H2Core::findPatternInTick(int, bool, int*) [findPatternInTick] tick = 1314. No pattern found

```

**Comment by thijz** [comment]
forgot to mention that i have had several crashes while seeing these error messages
note that i'm not sure if these errors are the actual cause of the crashes ...
sometimes H2 can keep running while it is outputting these error messages without any issues ...

**Comment by trebmuh** [comment]
I can confirmed that in a slightly different process:

- start H2 from terminal
- create a new song
- enable 'jack transport' (enable/disable jack master does not matter)
- no error in the terminal > all OK
- **disable** 'loop mode'
- errors in the terminal

HTH

**Comment by theGreatWhiteShark** [comment]
When using the JACK transport mode Hydrogen is relying on the JACK transport information, in particular of the provided frame number, to determine its playback position. The JACK server itself does not support looping but just keeps incrementing time and it's up to the clients to handle the looping itself. In the `findPatternInTick` this is done (with **loop mode enabled**) by calculating the modulo of the current tick number calculated using the frame number from the JACK transport information and the total tick number of the song. In other words, each time the end of the song is reached we kinda reset the tick number internally. When **loop mode** gets **disabled** the reported tick is well behind the last tick of the song and `findPatternInTick` is reporting an error. 

I just can reproduce that the error message is printed once and this is expect. But the playback should stop and the transport should be relocated to the beginning of the song. This is not happening in your case? Can you report on the version number of jackd and whether you use DBUS or not?

That being said the fact that the `findPatternInTick` function throws an error each time the end of a song is reached is annoying and certainly a bug.

**Comment by thijz** [comment]
hi @theGreatWhiteShark 
if i hit stop the playback head moved to the beginning of the song (as expected) but as soon as i hit stop the error messages appear.
While the song is playing there are no error messages.

I'm using jackdbus
```
/usr/bin/jackd -V
jackdmp version 1.9.12 tmpdir /dev/shm protocol 8
```

can this error lead to H2 crashing ?  is there a potential problem when the offset between the jack transport counter and the internal H2 counter?  some overflow maybe ?
Or is this just an annoying error message that i can safely ignore ?

**Comment by theGreatWhiteShark** [comment]
Well, I don't really get the full picture yet. If you hit stop, the JACK server should stop as well (with or without H2 being the timebase master). But from the error messages you posted earlier it seems the JACK transport is still running. This would definitely be a bug.

I don't think this would lead to crashes of H2. AFAIK we use the same variable types as the JACK API and should be fine as long as the transport information is still valid. When starting the playback again the H2 Jack client will relocate the transport anyway. So, it should be fine. Nevertheless, I'm quite puzzled.

**Comment by theGreatWhiteShark** [comment]
I got these messages a lot when working on an older version of Hydrogen (Dec. 2018) but after rebasing currrent master they are gone. @mauser This issue got fixed somewhere along the way.

**Comment by trebmuh** [comment]
I can confirm that this bug isn't there anymore after testing with a beta2.
I'm closing this issue then. @thijz if you still see this error with a newer version, feel free to reopen this thread.
