### ISSUE TITLE
Crashed on changing drum kit

### ISSUE THREAD

**Issue by baderbuddy** [hydrogen-music/hydrogen#709]
Hydrogen version           : 1.0.0-beta1
Operating system + version  : Windows 10
Audio driver + version      : Looks like it says it's using a PortAudio Driver

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I had a drum beat going with the default drumkit, then I tried to switch to the 808 drumkit and it crashed. I reopened the program and had a simple pattern going on the 808 kit and I was able to switch to the other kit, but I added a few extra steps and switched back to the 808 it crashed again.

**Comment by trebmuh** [comment]
Can you launch Hydrogen from the command line (terminal prompt) and see if it says something?

**Comment by ajawamnet** [comment]
Beta 1.0.0 crashes for me too when playing a song and changing drumkits - Window 7

**Comment by theGreatWhiteShark** [comment]
This is a known issue, which was already fixed (see #649).

@baderbuddy and @ajawamnet could you compile and install the most recent version of Hydrogen and check whether it works properly on windows too?
