### ISSUE TITLE
When you have more than 127 instruments the instrument midi note is 'stuck'

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#710]
Hydrogen version *          : git bbeaed1a5d46414360cbce74e81fbcc0a05e26f6
Operating system + version  : ubuntu 18.04
Audio driver + version      : jackdmp

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
For each instrument you add, the midi note value is automatically incremented.
For your 128th instrument the note value is set to 128, for instrument 129 > 129, etc

If you go to the instrument properties of one of these instruments you will see that the midi note is higher than 127, and the value cannot be modified.
In the terminal H2 outputs this error message (depending what instrument you are trying this on the value of '130' will be different of course) : 
`(E) Instrument::set_midi_out_note midi out note 130 out of bounds`

**Comment by mauser** [comment]
Hi,

just committed a small fix. Newly added instruments only get an incremented midi_out_note number if the midi out value is smaller then the maximum midi note value (127 in the default case).

**Comment by trebmuh** [comment]
@thijz is that all good for you now?

**Comment by thijz** [comment]
seems to work as expected
not sure what will happen if you have a drumkit that already has a note value that is higher than 127 (saved in a previous version of H2 for example) but then again i guess this is a corner case

thanks for the fix guys !!
