### ISSUE TITLE
HiRes Display Scaling Issue

### ISSUE THREAD

**Issue by erniejg** [hydrogen-music/hydrogen#711]
Hydrogen version *          :1.0.0-BETA-1
Operating system + version  : WIN-10
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
The application display does not scale properly on a Surface Book Pro 3000 x 2000 screen resolution. All of the on-screen widgets are far too small to be useful.
Ideally, the application would auto-zoom to display as if it was a 1920 screen.

**Comment by theGreatWhiteShark** [comment]
This is related to #683. Could you try to compile and run the code from pull request #688? Maybe this is will already solve your problems.

Unfortunately, my device is no more than 1366x768 so I can not test it myself.

**Comment by mauser** [comment]
Hi,

you could try if the recently released 1.0-beta2 solves your problem.

**Comment by steevithak** [comment]
I tried out Hydrogen on Fedora 32 today and ran into this issue. I have a 4k monitor and Hydrogen is tiny, like maybe 4 x 5 inches on my 27 inch monitor. The latest version of Hydrogen available in the Fedora repo is hydrogen-0.9.7-12.fc32_x86_64. It sounds like this may be fixed when version 1 is released - any guess at when that might be or when a Fedora RPM might be available for the current Beta? In the meantime is there any work around for 0.9.7 that would allow me to make the window and UI a bit larger?

**Comment by theGreatWhiteShark** [comment]
In the upcoming release of Hydrogen there is both a reworked UI that scales way better in terms of graphics as well as an option in the Preferences to scale the whole application to better match different display sizes.
