### ISSUE TITLE
Instrument listing not showed correct

### ISSUE THREAD

**Issue by Olli** [hydrogen-music/hydrogen#712]
Hydrogen version *          : 1.0.0-beta1 b861deaa3b52e148dfdcaf64b6402724c1fe0982
Operating system + version  :  Debian Linux Sid
Audio driver + version      :  Pulseaudio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The instruments of are displayed in this fashion. 
![hydrogen-error](https://user-images.githubusercontent.com/1754/55485094-3f703480-5619-11e9-9b90-4c0dcfab3c6a.png)

I installed hydrogen from the source into /usr/local/bin with build.sh  .
I can reproduce the bug every time I build it. 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by trebmuh** [comment]
Is it the same with any drumkit ?

**Comment by Olli** [comment]
I've only downloaded the GMRock, TR808Emu and Yamaha Vintage as well as EasternHop-1 for testing. Its the same.

**Comment by trebmuh** [comment]
OK, thanks. Let's see if the programming guys can do something.
For info, I can't reproduce here on a Debian Stretch, git-c17fbf0, package build with pbuilder.

**Comment by Olli** [comment]
Ok I'd try something. I'd remove ~/.hydrogen . Now it seems to work as expected. I'd better first think for such options before opening a ticket. ;-)
There also now more console messages.
