### ISSUE TITLE
Scroll madness when song exceeds window width

### ISSUE THREAD

**Issue by ajawamnet** [hydrogen-music/hydrogen#716]
Hydrogen version *   1.0.0 beta       :
Operating system + version  : windows 7 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If the song exceeds the Song Editor window width, it scrolls quickly and will sometimes loop back to the beginning - but not show it. 

See a vid here of it occurring:
http://www.ajawamnet.com/hydrogen1p0p0scrollingmadness.mp4
It seems to me that the ruler at the top should stay locked to the patterns... 

WAM
http://www.ajawamnet.com/
http://www.ajawamnet.com/ajawamnet/marketturd.htm

< describe your issue or feature request here ** >

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by mauser** [comment]
Hi! 

Thanks a lot for reporting that bug and for taking the time to create a video!! 

I think that i've already fixed that bug some time ago and that the bugfix will be part of the next beta version of Hydrogen. It had been tracked here as Issue #515.

**Comment by ajawamnet** [comment]
No problem. I figured you'd seen it before.
Awesome program!1  Really like it a lot.

I use Reaper for most stuff and the loops I do in Hydrogen are great for 
use in that.

But I do a lot of old style analog type remixing.

One song I recently did you might recall from years ago; it's onthe 
marketturd link below:
http://www.ajawamnet.com/ajawamnet/remixoflz.html
If you get a chance take a listen... and if you can, let me know when 
the update to Hydrogen is available.


-- 
WAM
http://www.ajawamnet.com
http://www.ajawamnet.com/ajawamnet/marketturd.htm
------------

More information on my lab and shop:
http://www.ajawamnet.com
http://www.ajawamnet.com/ajawam3/swarf/swarf.htm
------------------------
"Success is going from failure to failure without a loss of enthusiasm."
~~ Sir Winston Leonard Spencer-Churchill (1874-1965)

"I've failed at so many things so many times I make Abraham Lincoln look like Bill Gates"
~~ Wayne Mitzen (1959-  )

"What makes an expert isn't so much what they know,
It's that they've done similar things so many times wrong
They know what not to do"
~~ Wayne Mitzen (1959-  )

"You just keep pushing. You just keep pushing. I made every mistake that could be made. But I just kept pushing."
~~ Rene Descartes 1596-1650

"I hate the way people just go from ignorance to despair so quickly; it's the lazy man's option"
~~Professor Tim Flannery (1956-  )

"When you do things right, people won't be sure you've done anything at all."
~~ God, in Futurama episode "Godfellas"

"Two things are infinite: the universe and human stupidity;
and I'm not even sure about the universe."
~~ Albert Einstein (1879-1955)

"Some scientists claim that hydrogen, because it is so plentiful, is the basic building block of the universe.
I dispute that. I say there is more stupidity than hydrogen, and that is the basic building block of the universe."
~~ Frank Zappa (1940-1993)
