### ISSUE TITLE
[Feature request] Ability to lock the pattern editor

### ISSUE THREAD

**Issue by ajawamnet** [hydrogen-music/hydrogen#717]
Hydrogen version *    any      :
Operating system + version  : any
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Be nice if the pattern editor could be locked to whatever pattern is currently playing in the Song Editor with the ability to have any edits on the fly give a _# suffix and add that pattern to patterns listed under the Song Editor... That'd be cool....

**Comment by cme** [comment]
The main point of this is covered by #1437 . The "record new pattern" type functionality suggested probably warrants further discussion if it's still desirable? If not I'd like to close this. Cheers :)

**Comment by trebmuh** [comment]
@ajawamnet : waht do you think about cme's proposition? Do we close this thread?

**Comment by theGreatWhiteShark** [comment]
Closed with #1563
