### ISSUE TITLE
H2 gives error when sending midi for non-existing intrument

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#718]
Hydrogen version *          : 1.0.0-'24f984a'
Operating system + version  : ubuntu 18.04
Audio driver + version      : jackdmp

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

when controlling H2 with a midi controller that has the knobs mapped to all instruments, H2 will throw this error message : 
`(E) InstrumentList::get idx 21 out of [0;17]`

while this is probably to be expected (i'm trying to set the volume for instrument 21, and i only have 18 instruments in my song) but i was wondering if this can do any 'harm'

trying to chase down the cause of #714 and just want to make sure i log every detail

**Comment by mauser** [comment]
Hi,

no, it is very unlikely that this leads to problems, since the further processing of the note will be stopped once it is clear that there is no valid instrument.

Nontheless, i've changed the current behavior a little bit to get rid of those error messages. Now hydrogen is first checking if the midi note is in a valid range (the range of the current instruments) and emits a Warning (instead of an error) if there is no valid instrument. 

Current output:
```
(I) AlsaMidiDriver::handleMidiMessage [start of handleMidiMessage]
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] channel: 0
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] val1: 77
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] val2: 127
(I) AlsaMidiDriver::handleMidiMessage This is a NOTE ON message.
(W) AlsaMidiDriver::handleNoteOnMessage Can't find corresponding Instrument for note 77
```

**Comment by thijz** [comment]
is it possible that this fix was only applied to the ALSA midi code ?
i'm using Jackmidi and still see the same error message

**Comment by trebmuh** [comment]
@mauser : ping

**Comment by mauser** [comment]
Hi! 

No, this is not driver specific and on my system, the error no error messages are displayed, only the abovementioned warning. @trebmuh , can you reproduce the bug?

**Comment by trebmuh** [comment]
It seems that the ping should have be to @thijz .

**Comment by thijz** [comment]
just checked again with today's code but i still see the error (E) messages ...
(using jack midi)

`(E) InstrumentList::get idx 3 out of [0;1]`

**Comment by mauser** [comment]
@thijz :Could you give instructions how that behavior can be reproduced? If possible with -VDebug output?

**Comment by thijz** [comment]
sure,
it's really easy to reproduce :
- open H2 and clear out all intstruments
- connect a midi device (or virtual midi device) to the midi in of H2
- goto  Options - Preferences - Midi system
- add a CC event linked to a STRIP_VOLUME_ABSOLUTE action with value 1 (or any other value since there are no instruments in the kit anyway)
- link a midi fader to the event
- slide the event and you will see the error output :

```
(I) AlsaMidiDriver::handleMidiMessage [end of handleMidiMessage]
(I) AlsaMidiDriver::handleMidiMessage [start of handleMidiMessage]
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] channel: 0
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] val1: 1
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] val2: 51
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] CONTROL_CHANGE Parameter: 1, Value: 51
(E) InstrumentList::get idx 1 out of [0;1]
(I) AlsaMidiDriver::handleMidiMessage [end of handleMidiMessage]
(I) AlsaMidiDriver::handleMidiMessage [start of handleMidiMessage]
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] channel: 0
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] val1: 1
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] val2: 53
(I) AlsaMidiDriver::handleMidiMessage [handleMidiMessage] CONTROL_CHANGE Parameter: 1, Value: 53
(E) InstrumentList::get idx 1 out of [0;1]
...
```

**Comment by mauser** [comment]
Ah, ok. This problem is different to the issue which i've fixed already. In my case, i tackled the input validation of midi note message. The midi CC processing is implemented differently, but that's not a big problem. I've started to fix that problem.

**Comment by mauser** [comment]
@thijz : Could you re-test the issue? I hope that i've adressed all midi actions now.

**Comment by thijz** [comment]
no more Error messages when changing the volume if an 'empty' instrument
:-)
