### ISSUE TITLE
Segmentation fault when another Hydrogen instance is already running

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#723]
It's not the first time that I compiled various branches, moved the ~/.hydrogen and /usr/local/share/hydrogen folder in order to find a working version of H2. In the end there was another instance already running on a different workspace from an earlier session.

Instead of reporting a segmentation fault, H2 should tell the user that there is already a H2 instance running and it is not allowed to run a second one.

I'll try to fix it myself.

**Comment by theGreatWhiteShark** [comment]
Well, actually there is no general problem prohibiting the use of multiple H2 instances. The segmentation fault is caused by **liblo** when calling 

``` cpp
m_pServerThread = new lo::ServerThread( port );
```

in _osc_server.cpp_. Since there is already another H2 instance registered with the same port, the corresponding call of the second instance results in a crash of liblo. Changing the port number manually will make two instances play together just fine. (Unless one of them is the JACK timebase master. Then the flawed JACK driver is messing things up. But with #678 this will work as well.)

I'll search for a way to check which ports of the OSC server are already occupied. In the end every other application registering itself to port 9000 of the OSC server will cause the startup of H2 to result in a segmentation fault.

**Comment by theGreatWhiteShark** [comment]
You can easily reproduce this issue by running

```
oscdump -L 9000
```

in one terminal and H2 in another.

**Comment by mauser** [comment]
Hi! 

this issue should be fixed now in the master branch.
