### ISSUE TITLE
H2 does not update Tags when skipping to next song in playlist

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#725]
Hydrogen version *          : 51cddb057bd59b5dbe5cbb809b8edd0a59241d9f
Operating system + version  : ubuntu 18.04
Audio driver + version      : jackdmp

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
when you have multiple songs that all have TAGs in the timeline and you load these songs manually the tags are updated correctly > everything OK

However, if you create a playlist containing these songs and you skip to the next/previous song (using F5/F6) the tags are not updated
If you hit the 'BMP' button (left of the timeline) the tags are updated

seems like there is a difference in UI refresh between loading songs manually or via playlist

example : before hitting the 'BMP' button : 
![image](https://user-images.githubusercontent.com/1384210/56216888-8cfd9000-6062-11e9-8651-03b37da6cd1f.png)

after hitting the BMP button : 
![image](https://user-images.githubusercontent.com/1384210/56216926-9c7cd900-6062-11e9-94cd-ade7fdd93a85.png)

**Comment by mauser** [comment]
@thijz : 

Please have a look at the current master branch, i hope that the problem is fixed now. The playlist class re-implemented the song loading, which did not include the proper UI refreshing.

**Comment by trebmuh** [comment]
@thijz ping?

**Comment by thijz** [comment]
that fixed it :-)
thanks @mauser !
