### ISSUE TITLE
playlist not saved 

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#728]
Hydrogen version *          : c756049551652b27d001bb01783ee8d6714a0313
Operating system + version  : ubuntu 18.04
Audio driver + version      : jackdmp

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
playlist are not properly saved

to reproduce :
- create a new playlist
- add a couple of songs
- save playlist
- close H2
- open playlist
- change the order of the songs, save playlist : changes not saved

- now do 'save playlist as' , select same file, now the changes are saved
once you did this, a regular 'save' works

related to relative/absolute path changes ?

**Comment by thijz** [comment]
some more info on this issue :
below you can see the debug output of saving a new playlist (the first line)
and after that (without closing the playlist editor window) i just opened that playlist (Playlist > Open playlist) and this is when you get the warning and the 'playlist has no name' error

```
(I) Playlist::save_file Saving palylist to /home/thijs2/.hydrogen/data/playlists/test_untitled.h2playlist
[New Thread 0x7fff914c5700 (LWP 3523)]
Gtk-Message: 21:24:12.714: GtkDialog mapped without a transient parent. This is discouraged.
[Thread 0x7fff914c5700 (LWP 3523) exited]
(W) XMLDoc::read XML document /home/thijs2/.hydrogen/data/playlists/test_untitled.h2playlist is not valid (/home/thijs2/Music/Hydrogen_Code/gui_lock/data/xsd/playlist.xsd), loading may fail
(W) Legacy::load_playlist this code should not be used anymore, it belongs to 0.9.6
(D) XMLNode::read_child_node XML node playlist->Name should exists.
(D) XMLNode::read_string Using default value  for Name
(E) Legacy::load_playlist Playlist has no name, abort
(E) PlaylistDialog::loadList Error loading the playlist
```

**Comment by theGreatWhiteShark** [comment]
Hi @thijz.

Stupid question, but how urgent are those bugs related to the playlist? There are already a number of different topic/issues in my H2 todo list.

**Comment by thijz** [comment]
this is low priority for me : i can just edit the file manually
might be a bigger issue for people that are not comfortable with manually editing XML files
definitely not a showstopper

**Comment by mauser** [comment]
@theGreatWhiteShark: I'll care for this issue..

**Comment by mauser** [comment]
Hmmmm..... The save functionality of the playlist seems to be flawed. I'm opening a playlist from `~/.hydrogen/data/playlists`, but when saving the playlist, the modified list gets saved to current working directory (the directory from which the Hydrogen binary has been started). So all changes will be lost, at least it seems so for the user.

**Comment by mauser** [comment]
Please try again.. no idea how this has ever worked before :)

**Comment by trebmuh** [comment]
@thijz ping here too :smile:

**Comment by thijz** [comment]
also fixed :-)
thnx @mauser !
