### ISSUE TITLE
Retreiving old sounds

### ISSUE THREAD

**Issue by esbatl** [hydrogen-music/hydrogen#738]
Hydrogen version *  : 1.0.0-beta1
Operating system + version : Windows 10 Home

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I uninstalled 0.9.7 bc the last instrument wasn't exporting when I exported stems instead of a single file, and installed the new beta. The new sounds on this version aren't all upgrades to my ears and I'm wondering if the old sounds are available anywhere for download.

**Comment by esbatl** [comment]
Like, I basically just want the old kit back. pls help.

**Comment by mauser** [comment]
Hi! 

The GMKit samples have been removed from Hydrogen because of an unclear licensing. Due to this fact, we don't provide this samples anymore.
