### ISSUE TITLE
[Feature request] Rewire support

### ISSUE THREAD

**Issue by alkurop** [hydrogen-music/hydrogen#739]
Hydrogen version *       0.9.7   :
Operating system + version  : Mac OS Mojave
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I'm recording music with Ableton Live and using Hydrogen as a drum machine.
I'm looking for a way to sync Hydrogen with Ableton, and connect Hydrogen's audio out with the DAW.

Rewire protocol seems like a good option.
Is there already and other option for sync, what are your thoughts?

If this is worth doing, I would love to take part in implementation.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by theGreatWhiteShark** [comment]
The problem I see with ReWire is their non-free license

> Who can become a developer?
> 
> Anyone can register as a developer as long as they are also associated with a company. This means each developer will sign up for a user account and then ask to be included in a previously registered company, or choose to register a new one.
> 
> Due to the legal aspects of this agreement, only companies can qualify as developers for Rack Extensions, ReWire, REX2, and Remote.
> 
> There are no costs involved. Propellerhead Software will administer the authorization, copyrights, logos, and trademarks. We’ll also provide technical support, free of charge.
[https://www.propellerheads.com/developer/rewire.php]

For connecting Ableton and Hydrogen you can also use the Jack sound server
https://forum.ableton.com/viewtopic.php?t=212349

**Comment by alkurop** [comment]
Thank you for the reply.
Yes, it would be good to use something existing. 
Jack server is a good option.
I'm able to run Jack on OSX.
But Hydrogen does not see Jack server running in the audio or midi system options.
Only core audio is available.
Should I create an other issue for this, or maybe try an other version of Hydrogen?

**Comment by theGreatWhiteShark** [comment]
> Should I create an other issue for this, or maybe try an other version of Hydrogen?

Yes, please (both). 

I have not looked into the Mac builds but it my lucky guess is that H2 was not compiled against Jack in the Mac version. Could you compile and install the most recent version of H2 (Github master)? You can find some instructions in our wiki https://github.com/hydrogen-music/hydrogen/wiki/Building-Hydrogen-from-source-(MAC-OSX)

**Comment by alkurop** [comment]
I've compiled a new version with macports.
Nice and shining 1.0.0-beta1.
But it still won't see Jack server. While ableton can see and use it.
So obviously it's Hydrogen problem - it might be looking for jack in the wrong directory

**Comment by alkurop** [comment]
Update: after some research I added `+jack` option to the macports build
and it's working
I can finally connect Ableton with Hydrogen.
I'm so happy and excited!!!

**Comment by theGreatWhiteShark** [comment]
That's great!

By the way, since none of the developers seem to use Mac, are the instructions in the INSTALL.md and in the wiki page I provided of any help? I just skipped through the wiki page and it still talks about Qt4, which is definitely out of date.

If you find something to be off, would you consider fixing it to help other Mac users struggling to compile the latest version of H2? That would be of great help!

**Comment by alkurop** [comment]
INSTALL.md  is more for developers then from users - compiling manually from the code.
But the wiki page was quite useful with the macports instructions. 
It will make sense to add instruction about the Jack option into the wiki page

**Comment by alkurop** [comment]
https://github.com/hydrogen-music/hydrogen/pull/740

**Comment by theGreatWhiteShark** [comment]
Thanks a lot!

**Comment by alkurop** [comment]
Mate, this is the best drum machine ever.
I've been loving it for years and produced some tracks while I was on ubuntu.
this is dope
