### ISSUE TITLE
manual not available in 0.9.5 and 0.9.6

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#74]
```
  on 2011-10-17 16:00 * By AutoStatic
```

This is Ubuntu and maybe Debian specific and can be traced down to the Rules file provided by the Debian Multimedia maintainers git repository of Hydrogen. It's about this section:
 # Put aside upstream-shipped autogenerated files during build
 upstreamtmpfiles = $(wildcard data/doc/_.html data/doc/_.docbook)
 upstreamtmpfiles_ = $(patsubst %.upstream,%,$(wildcard data/doc/_.html.upstream data/doc/_.docbook.upstream))
 pre-build:: debian/stamp-upstreamtmpstuff
 debian/stamp-upstreamtmpstuff: debian/stamp-copyright-check
    for file in $(upstreamtmpfiles); do \
        [ ! -e $$file ] || [ -e $$file.upstream ] || mv $$file $$file.upstream; \
    done
    touch $@
 clean::
    for file in $(upstreamtmpfiles_); do \
        [ ! -e $$file.upstream ] || mv -f $$file.upstream $$file; \
    done
    rm -f debian/stamp-upstreamtmpstuff

 common-build-indep:: debian/docs.stamp
 debian/docs.stamp:
    $(MAKE) -C data/doc
    touch $@
 clean::
    rm -f debian/docs.stamp

Something goes wrong there, apparently the included .docbook and .html files get renamed properly (as they should according to the readme that comes with the documentation) but don't get regenerated.

Best,

Jeremy

---

```
  on 2011-10-18 12:50 * By AutoStatic
```

Found the reason why $(MAKE) -C data/doc doesn't seem to work. The manual.docbook file doesn't match with the different po files:

make -C data/doc
make: Entering directory `/home/jjongep1/PPA/Hydrogen/hydrogen.test/data/doc'
cp -f manual.docbook manual_en.docbook
xmllint --noout --valid manual_en.docbook
touch manual_en.docbook_validated
LL=$(echo -n manual_en.docbook | sed 's/.*_\(..\)\.docbook/\1/') ; \
    xmlto html-nochunks --stringparam section.autolabel=1 --stringparam toc.max.depth=2 --stringparam xref.with.number.and.title=0 \
        --stringparam l10n.gentext.language=$LL \
        manual_en.docbook
po2xml manual.docbook manual_es.po > manual_es.docbook
line 143: unexpected token: #. Tag: title
line 163: unexpected token: #. Tag: para
can't find
Once you have selected a part of your song you can <emphasis role="bold">delete</emphasis> it by pressing the Delete button. You can <emphasis role="bold">move</emphasis> it by simply dragging your selection to another location, and you can also <emphasis role="bold">copy</emphasis> you selection by Ctrl-dragging it to a new location.
in
Once you have selected a part of your song you can <emphasis role= "bold">delete</emphasis> it by pressing the Delete button. You can <emphasis role="bold">move</emphasis> it by simply dragging your selection to another location, and you can also <emphasis role="bold">copy</emphasis> you selection by Ctrl-dragging it to a new location. </para>
make: *** [manual_es.docbook] Error 1
rm manual_en.docbook_validated
make: Leaving directory`/home/jjongep1/PPA/Hydrogen/hydrogen.test/data/doc'

After having fixed this I ran make clean to start over again. Then I noticed the different .docbook files didn't get removed so apparently the clean rule in the Makefile doesn't work like it should. I added a new variable (ALL_DOCBOOKS) and replaced \* _{en,es,it,fr,nl,ca}.docbook with $(ALL_DOCBOOKS) which seems to work. It's probably got something to do with globbing because running rm -f \* _{en,es,it,fr,nl,ca}.docbook does work.
New issue when running make:

make -C data/doc
make: Entering directory `/home/jjongep1/PPA/Hydrogen/hydrogen.test/data/doc'
cp -f manual.docbook manual_en.docbook
xmllint --noout --valid manual_en.docbook
touch manual_en.docbook_validated
LL=$(echo -n manual_en.docbook | sed 's/.*_\(..\)\.docbook/\1/') ; \
    xmlto html-nochunks --stringparam section.autolabel=1 --stringparam toc.max.depth=2 --stringparam xref.with.number.and.title=0 \
        --stringparam l10n.gentext.language=$LL \
        manual_en.docbook
po2xml manual.docbook manual_es.po > manual_es.docbook
line 143: unexpected token: #. Tag: title
line 163: unexpected token: #. Tag: para
xmllint --noout --valid manual_es.docbook
touch manual_es.docbook_validated
LL=$(echo -n manual_es.docbook | sed 's/.*_\(..\)\.docbook/\1/') ; \
    xmlto html-nochunks --stringparam section.autolabel=1 --stringparam toc.max.depth=2 --stringparam xref.with.number.and.title=0 \
        --stringparam l10n.gentext.language=$LL \
        manual_es.docbook
po2xml manual.docbook manual_fr.po > manual_fr.docbook
exception: expecting '
', found '
make: *** [manual_fr.docbook] Error 1
rm manual_es.docbook_validated manual_en.docbook_validated
make: Leaving directory`/home/jjongep1/PPA/Hydrogen/hydrogen.test/data/doc'

Since I don't get an indication on which line the exception happens I have atm no idea how to proceed.

---

```
  on 2011-10-18 13:19 * By AutoStatic
```

Hmmm, po2xml manual.docbook manual_fr.po > manual_fr.docbook generates an empty docbook file. I can see why, manual.docbook and manual_fr.po do not match completely. Luckily it's just the French po file that might contain errors, the others ones seem ok.

---

```
  on 2011-10-19 13:06 * By thijz
```

Milestone set to 0.9.6

---

```
  on 2011-10-19 16:18 * By AutoStatic
```

My French is good but unfortunately I don't have the time on a short term to check the French po file. Would it be possible to contact the original author (Humbert Olivier)?

---

```
  on 2011-10-21 00:17 * By wolke
```

i don't understand this bug. compiling hydrogen0.9.6svn-head here on my debian unstable system offers a manual & tutorial as expected. did i miss something?

---

```
  on 2011-10-21 12:02 * By AutoStatic
```

Hello Wolke, no not really as a SVN checkout already contains the necessary .html document files. But if I've understood the data/doc/README.DOCUMENTATION.txt file correctly those files should be regenerated after a checkout. This is where it goes wrong, the manual_fr.html doesn't get generated correctly because the docbook and po files do not match.

---

```
on 2011-10-24 12:19 * By thijz
```

mailed Olivier on 21okt, but no answer so far

---

```
  on 2011-11-11 04:09 * By Nerdtek
```

The manual_fr.html is invalid it contains english instead of the translated text. I've done a cursory scan of the manual_fr.po file and can't find the offending tidbit as of yet. I'll do a little more detailed scan and see what I can find.

Slainte
Daniel

---

```
  on 2011-11-11 04:14 * By Nerdtek
```

the catalan .po file seems to be outdated as well. I couldn't get that to build either with the latest trunk.

**Comment by trebmuh** [comment]
I didn't see this issue before and have just had a read at it. No completely 100% sure to understand what this is about. I'll be trying to have a deeper reading asap. It might be related (or not) to https://github.com/hydrogen-music/hydrogen/issues/74

**Comment by trebmuh** [comment]
So, today, I did the following: rebuilding (debian way, ie: pbuilder) the Hydrogen package with a debian patch which:
* remove the 2 french items in data/doc/manual.html
* remove the french-related 4 lines in data/doc/Makefile
* remove data/doc/tutorial_fr.po
* remove data/doc/manual_fr.po
That way, there is no more reference of french-related stuff when building.

Then, I rebuilt the package and install it. I launched Hydrogen, and when I'm going to _menu -> Info -> User manual_, still nothing happens which leads me to think that this is not specifically related to one (or several) mistake in one of the *_fr.po as suggested above.

Then I had a look at the debian BTS (bugs tracker system) (which I/we should have done before) and found this : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=629107 

So I re-re-re-build the package (canceling the changes I made previously) and I looked into /usr/share/hydrogen/data/doc/ to see that the situation evolved since the bug on the BTS since I can see:
```
img			 manual_fr.po		    TODO
img_tutorial		 manual.html.upstream	    tutorial.docbook.upstream
Makefile		 manual_it.po		    tutorial_fr.po
manual_ca.po		 manual_nl.po		    tutorial_it.po
manual.docbook.upstream  manual.pot		    tutorial.pot
manual_en.html.upstream  MidiInstrumentMapping.ods
manual_es.po		 README.DOCUMENTATION.txt
```
 Anyway, There are only 2 html files with an "upstream" extension: manual.html.upstream and manual_en.html.upstream . I renamed them respectively to: manual.html and manual_en.html, launched Hydrogen and ... tadam !

![capture1-hydrogen-manual](https://cloud.githubusercontent.com/assets/8705846/17536586/4797c9fc-5e96-11e6-91fb-ad40223b4fcf.png)

Note that, if I click on "English Manual", I'm getting the english manual. If I click on something else, I get nothing which sounds to be logical considering that there is no manual_fr.html , manual_es.html or ...

To me, at this point, I'll invite the debian multimedia packager to come and to have a look here since, I've got no idea at all about how the debian/rules is supposed to work and why does it fail.

**Comment by trebmuh** [comment]
No news (yet) from the debian multimedia packagers team. @blablack : I think I can remember you're using an ubuntu or debian related distro, aren't you? If so, could you please give a look to the debian/rules: https://anonscm.debian.org/cgit/pkg-multimedia/hydrogen.git/tree/debian/rules (which is basically the makefile used by the build) and tell me if you get a clue about what is going on there?

**Comment by trebmuh** [comment]
There is some update about this. See : https://bugs.debian.org/629107

**Comment by trebmuh** [comment]
There is some update about this. See : https://bugs.debian.org/629107

@mauser : I'd like to check with you if we are still supposed to see this screen : https://cloud.githubusercontent.com/assets/8705846/17536586/4797c9fc-5e96-11e6-91fb-ad40223b4fcf.png

**Comment by mauser** [comment]
Hi,

the window is certainly no candidate for the red dot design award ;-) But it is "still supposed to be there" from a functional view, since it lets you choose from different help files. Sometimes you might be more interested in reading the english manual iso. of your local translation (maybe because of different translation states).

**Comment by trebmuh** [comment]
ahaha :)

Thanks for confirming. I just wanted this confirmation since the work on the debian package is giving the manual EN page but nothing else (even when clicking on "documentation index"). Anyway, that's already a great step which will allow to work on the EN manual efficiently!

**Comment by mauser** [comment]
Hi @trebmuh ,

Sorry, there was a misunderstanding.. i thought you are still gettting the depicted dialog and you're wondering why this is the case. After looking at the code i saw that the dialog is *not* showing up with the current version. 

This is a bug and my fault. I've checked in a faulty version of manual.html two ago. This leads to the manual being display where the index should be. I'm going to fix that now..

**Comment by trebmuh** [comment]
@mauser : awesome. I'll be trying to build it after you fix it, and then report a fix to the Debian packaging team. Thank you.

**Comment by mauser** [comment]
The problem should be fixed now. I've pushed the solution also to the 0.9.7 branch. I've also changed the backgroundcolor of that index file while i was at it. Still not a beauty, but better readable..

![screenshot at 2016-11-14 22 02 01](https://cloud.githubusercontent.com/assets/202461/20282667/088e90f8-aab6-11e6-9f39-555b0d2d1c97.png)

**Comment by mauser** [comment]
Btw. can we close that issue now or is there still a problem left?

**Comment by trebmuh** [comment]
Hi @mauser ,
I've been building hydrogen from : https://github.com/hydrogen-music/hydrogen/commit/b19ba20489588e4b40031235ecd3157610760a85 with the debian tools. Thanks to your commit, I can see the "menu" as shown in your message above. That said, there is still an issue (which come from the debian packaging script I 99% guess) so, I'm going to talk with the debian packaging people.

After making sure that everything is sorted out, I'll let you know when we can close this thread.

One last question: you said that you committed the fix to the 0.9.7 branch. Am I right then to understand that there will be a 0.9.7.1 version later?

**Comment by mauser** [comment]
Yes, there will be a 0.9.7.1 for sure. The question is when.. the documentation fix would not justify this effort in my opinion. But i'm sure that there will be other bugfixes in the next time which are worth to be backported..

**Comment by trebmuh** [comment]
OK great, I'd advocate for the 0.9.7.1 to happen before freeze date for the next Debian stable (Stretch). The (current & informal) timeframe is : https://release.debian.org/ which means that, it should be OK if 0.9.7.1 is ready by mid-January. If you can make it, that's great. If not, I'll cry but understand that it's taking time to do so. No worries.
Hope that helps.

**Comment by mauser** [comment]
@trebmuh , any news on this issue? 

About the release date for 0.9.7.1: early january sounds good to me.

**Comment by trebmuh** [comment]
@mauser : no news from my side. I'm still to check how the files are generated from the .po translation since I suspect that those file are not build from the debian packaging. I'll keep you updated here. If I'm taking too much time, please feel free to ping me.

**Comment by trebmuh** [comment]
Fresh build from git master https://github.com/hydrogen-music/hydrogen/commit/5556c8dbc2a2c58f1441281739eab444273861d0

This issue seems resolved to me since I can see and have access to the manuals and the tutorials in different languages.

I'm closing here then. Feel free to reopen if you'll still have the issue.
