### ISSUE TITLE
Was working, saved a song in the works, crashed and won't restart.

### ISSUE THREAD

**Issue by NightfallFX** [hydrogen-music/hydrogen#749]
Hydrogen version *          : 0.9.7
Operating system + version  :  Dell b.17763.615 - x64 Win 10-H v.1809
Audio driver + version      :  10.0.17763.1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I was using the program for some months now. Had made several songs. While working on one, I tried to save my current work and the program crashed. Now it refuses to restart. I reinstalled the program. I renamed my song files to see if that was the issue. Yes and No, Yes the program starts, but now the frames of the program are all wonky. I tried to load the song I was working on(spent over a month working on), the program crashes again, refuses to start again. Using Win10. In the image you can see the menu's and layout isn't quite right.

Been great to work with so far...
Thanks!

-Byron

![Screenshot_1](https://user-images.githubusercontent.com/53500356/62386606-60dd2080-b526-11e9-9b8f-fd59e5ef6df0.jpg)

**Comment by theGreatWhiteShark** [comment]
Could you run Hydrogen from the command line with the `verbose` option set to `Debug`?

I'm no Windows user but the command should look something like this

`start /b "" "c:\Program Files\Hydrogen\hydrogen.exe" --verbose "DEBUG"`

Afterwards, could you try opening the song, which does not work anymore, and copy/paste the output in here?

**Comment by NightfallFX** [comment]
All it does is crash. Take notice to the text bars not lighting correctly
either.
https://drive.google.com/file/d/13Ww72xEPMo2lrNlZ0Z-pclmNzVO4gWvF/view?usp=drivesdk

**Comment by mikotoiii** [comment]
Based on your picture, you're running the older 0.73 version of Hydrogen.
Try to install the 1.0 version and see if that helps.

https://sourceforge.net/projects/hydrogen/files/Hydrogen/1.0.0%20Binaries/

If that doesn't help, we may need to delete some local files/folders to
clean up older config files, so if it doesn't help reply back and we'll see
what we can do.

**Comment by NightfallFX** [comment]
I've updated it to the 1.0 beta. The screen issues are resolved at least.
The program still crashes opening any song I made, not just the one.
I noticed that the program wants to save files to both the User folder and
in Program Files. Ex. C/Users/XXXXX/.hydrogen and C/Program Files/Hydrogen.
When I load the drum kits, the sounds are missing. I had to move files
around to new folders, but old drum kits won't load as the .kit files. The
1.0 program seems to save .xml files and each drum sound in its own folder
with no .kit files around. 1.0 simply won't work with the former .kit file
formats it seems.

Now I've got files all over the place trying to figure out the combination
of which belonged where so the song files can get the sounds from their
previous recorded paths. Seems impossible.

**Comment by theGreatWhiteShark** [comment]
Sounds like a mess. Unfortunately there is no developer on the project right now who is able to provide some sort of Windows support.

Can you run the command I wrote earlier via the command line/shell/terminal/konsole? Using it you basically tell Hydrogen to write out all errors, warnings, and hints defined in the source code so it's easier to figure out what is going wrong. When just adding the additional argument to the start up script/icon, Windows will probably close the associated shell and throws away all those messages the moment Hydrogen does crash.

**Comment by NightfallFX** [comment]
I changed the directories of auto save and last locations to the new
directory.
I found a song I started that did load, comparing the script for one that
does not and I removed the following lines from the song file that did not
work, as they are not in the one that does work... Not sure if that was an
issue or not...
 <playbackTrackFilename></playbackTrackFilename>
 <playbackTrackEnabled>false</playbackTrackEnabled>
 <playbackTrackVolume>0</playbackTrackVolume>

I changed the path lines in the song files, instruments, drums, sounds to
point to the new file locations.

GKkit in the old version was renamed GMRockKit in 1.0 beta or GMkit is
missing in 1.0... changed the path.

EVERYTHING WORKS!
All I had to do was change all the file paths in several scripts because
for whatever reason, the last time I saved the song, all of my sound files
became corrupt, I copied in the back-up sounds I had.
See now, a little video programming I did for 10 years over 20 years ago,
paid off. =D

Thanks for your help!! Nice program if I can learn it all, but for now
things mostly work that I know of.

Closing thread after reply.

**Comment by NightfallFX** [comment]
Basically the moral of this story is, don't update the program to 1.0 and
then save your song to overwrite one from older versions. The 1.0 saves the
drum kits to an .xml file rather than the .kit files they used to be. Also
included with the kit folder as where it was separate before.

This causes the files to be overwritten with confused file paths and wrong
file types.

**Comment by theGreatWhiteShark** [comment]
Nice to hear that everything is working on your side again!

Yeah, the seems there has been a rather rough change in code base with respect to the song and drumkit files some years back. Occasionally such problem regarding backward compatibility are popping up.
