### ISSUE TITLE
Hydrogen 0.9.7 Can work on MACOS El Capitan?

### ISSUE THREAD

**Issue by ricfreit** [hydrogen-music/hydrogen#750]
Hydrogen version *          :0.97
Operating system + version  : MACOS 10.11 EL Capitan
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I can't install the version 0.97 on MACOS El Capitan. I am using the 0.96 beta but this version are close or not open frequently.

**Comment by theGreatWhiteShark** [comment]
Did you already took a look at [this](https://github.com/hydrogen-music/hydrogen/wiki/Building-Hydrogen-from-Source-(macOS)) wiki page?

At which point of the installation your problem does occur?

**Comment by ricfreit** [comment]
> Did you already took a look at [this](https://github.com/hydrogen-music/hydrogen/wiki/Building-Hydrogen-from-Source-(macOS)) wiki page?
> 
> At which point of the installation your problem does occur?

HI GreatWhiteSark, when I try to install I can see in the Icon a image looks like a stop signal.  After I copy it to MAC I recevie a message informing that this version need a 10.12 MACOS. My MACOS is 10.11. 
![Captura de Tela 2019-08-06 às 09 40 11](https://user-images.githubusercontent.com/53156016/62541099-76f12680-b82f-11e9-82dd-0b4f1b6a2767.png)
![Captura de Tela 2019-08-06 às 09 40 11](https://user-images.githubusercontent.com/53156016/62541123-83757f00-b82f-11e9-88fa-b19f37258b0e.png)
You can see a image of the screen after try to execute the program.

**Comment by theGreatWhiteShark** [comment]
Okay, so I'm no expert Mac user but *how* do you install Hydrogen? I only was aware of doing it via Homebrew or MacPorts and none of them is graphical.

**Comment by mauser** [comment]
Closed, due to lack of feedback.
