### ISSUE TITLE
compilation issue on master : ui_about_dialog.h: No such file

### ISSUE THREAD

**Issue by WilliamTambellini** [hydrogen-music/hydrogen#753]
Hydrogen version *          :  master
$ git rev-parse HEAD
6eb975e8f574c5ce96636bf86805c9a78f696826
Operating system + version  : CentOS 7
Audio driver + version      : ?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Main librarires
* libQt                        : 5.9.2
* libsndfile                   : + used  ( /usr/lib64/libsndfile.so )
*                                libsndfile version must be greater than 1.0.17 to support FLAC and OGG sound file formats
* libtar                       : - not found and not desired
* libarchive                   : + used  ( /usr/lib64/libarchive.so )
* ladspa                       : + used  ( 6 plugins found )
...
make
...
Scanning dependencies of target hydrogen_automoc
[ 61%] Automoc for target hydrogen
Generating moc_AboutDialog.cpp
...
[ 61%] Built target hydrogen_automoc
Scanning dependencies of target hydrogen
[ 61%] Building CXX object src/gui/CMakeFiles/hydrogen.dir/src/AboutDialog.cpp.o
In file included from hydrogen/src/gui/src/AboutDialog.cpp:24:0:
hydrogen/src/gui/src/AboutDialog.h:32:29: fatal error: ui_about_dialog.h: No such file or directory
 #include "ui_about_dialog.h"
                             ^compilation terminated.
make[2]: *** [src/gui/CMakeFiles/hydrogen.dir/src/AboutDialog.cpp.o] Error 1
make[1]: *** [src/gui/CMakeFiles/hydrogen.dir/all] Error 2

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by theGreatWhiteShark** [comment]
Thats odd. This file should have been auto-generated by Qt5 from *about_dialog.ui*. 

Could you provide the `./configure` log (and the remaining `make` log in case anything else went wrong or warnings did pop up)?

**Comment by mauser** [comment]
Closed due to lack of feedback. @WilliamTambellini : Just answer here to re-open the issue again.
