### ISSUE TITLE
[Feat Req] More 'pattern Size' options in pattern editor panel (16ths-meters)

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#755]
This is a simple problem: how to set values like 'five sixteenths' for a pattern size?
I didn't find any open issue on it (nor I know any way of doing it, without writing directly in song file)

I have just modified file src/gui/src/PatternEditor/PatternEditorPanel.cpp and built H2 again.
I have no experience in c++/Qt but it seems to work: now the new pattern size menu shows entries from 1 to 64 (instead of 1-32) and they are considered to be 16ths instead of 8ths.
Pros: can set 16ths-meter sizes!
        minimal code modification
Con: meters more difficult for the user to understand

What do you think about it? Would you suggest different ways?

**Comment by theGreatWhiteShark** [comment]
Could you share the code by e.g. making a pull request?
https://github.com/hydrogen-music/hydrogen/wiki/How-to-contribute-code-using-Github

**Comment by oddtime** [comment]
It is really an elementary alternative to the code. If you wish I can see how to do the the pull req....
this will take a while

If I am not wrong these were the mods:
in file `src/gui/src/PatternEditor/PatternEditorPanel.cpp`
in line 618 "8" comes "16"
in line 802 "8" comes "16" (from eighths to sixteenths)
in line 115 "32" comes "64"
in line 863 "32" comes "64" (items of pattern size menu)

**Comment by oddtime** [comment]
@theGreatWhiteShark are these changements enough to justify a pull req?

**Comment by oddtime** [comment]
The previous changes were applied to v1.0.0.beta1 but are inconsistent with the newest repository.

Just made pull request #756 to show the code.

**Comment by theGreatWhiteShark** [comment]
> are these changements enough to justify a pull req?

Well, I'm not part of Hydrogen developer team and not authorized to merge pull request myself, but, sure. As long as there is a problem present in the current implementation, it's worth to point it out and to provide a solution/alternative. Even if it is just a single line of code.

**Comment by oddtime** [comment]
Ok!
Question, I am working on tuplets as well. Should I clone H2 repo for each thread? Or same clone can be used for different pull requests?

**Comment by theGreatWhiteShark** [comment]
With `git` it's best to keep those threads inside individual branches.

This tutorial describes some best practices to be used in bigger projects (like this one) https://nvie.com/posts/a-successful-git-branching-model/

**Comment by oddtime** [comment]
Pull request #999 closes this issue
