### ISSUE TITLE
UI appearance on high resolution Screens

### ISSUE THREAD

**Issue by philloflynn** [hydrogen-music/hydrogen#757]
Hydrogen version *          :
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The UI needs the facility to resize on high resolution screens like a surface pro 6 screen

**Comment by trebmuh** [comment]
@philloflynn you didn't mention on which operating system (linux ? mac ? win ? other ?).

Plus, it might be a duplicate of #264 .

**Comment by philloflynn** [comment]
Yes. it is the same issue. I tried to find a duplicate bug report. BTW I'm using windows 10

**Comment by trebmuh** [comment]
Please, report on the #264 thread issue then. Don't forget to add the OS and the Hydrogen version used.

**Comment by philloflynn** [comment]
Is there any point? Genuine question. It seems you have to redo the ui for scaling which doesn't seem to be on the agenda

**Comment by trebmuh** [comment]
Chances are devs are working on the most commented/desired issues.

**Comment by philloflynn** [comment]
Ok. I'll Comment on the other thread. Thank you kindly!!
