### ISSUE TITLE
Sample playback and preview for multi layered instruments is broken

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#764]
Hydrogen version *          : 3652dbf9ecea3aba2b2cd47a068eb47b95381953
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When previewing sounds from a multi-layered kit (like _Tom 10" flam_ from the Flac_GSCW-1 kit) , the sound of the instrument seems to be messed up. The sample starts with the original sample (as one would expect), but after that ends, a different sample will be played. 

This is also shown in the sample wave display: 

![grafik](https://user-images.githubusercontent.com/202461/64374423-20d8f400-d024-11e9-9219-9e05d74726f6.png)

When opening the sample editor, the correctly processed sample can be heard when using the "play original sample" functionality.

**Comment by oddtime** [comment]
Confirm. I am experiencing similar problem while playing the instruments via the computer keyboard. Also, is it normal that once one instrument is selected, each key (Z,S,X,D,C,V...) plays the same instrument but transposed?

**Comment by mauser** [comment]
This has been introduced with ee2f8ef78fd0b57790d770e63dcf28c41d23dad4. @theGreatWhiteShark : I'm going to revert that commit, since you mentioned in the other issue that you're afk for the rest of the week. I suppose it is better to go with a potential memory leak then with a broken playback for all multitrack kits. It seems that random data spills into the samples, so harsh pop noises may appear.

**Comment by theGreatWhiteShark** [comment]
That's super strange. It was not ee2f8ef introducing the memory leak after all. Some code in the update of the drumkit properties was responsible for it.

The section causing trouble here was actually a fix of the copy constructor of the `InstrumentLayer`. So, a copy constructor making a deep copy instead just linking some components causes bugs. This sounds quite bad. I'll try to figure out what's going wrong here.

**Comment by theGreatWhiteShark** [comment]
Okay, I can reproduce the issue but it seems to only occur when invoking `Hydrogen::loadDrumkit()` by loading a different drumkit. Does this match your observations?

**Comment by theGreatWhiteShark** [comment]
The problem was actually the copy constructor of `Sample`. Only the first 25% of the audio data got copied.

**Comment by mauser** [comment]
> Okay, I can reproduce the issue but it seems to only occur when invoking `Hydrogen::loadDrumkit()` by loading a different drumkit. Does this match your observations?

Yes, that was the case!
