### ISSUE TITLE
Hydrogen crashes if an invalid sample is added as an instrument layer

### ISSUE THREAD

**Issue by mauser** [hydrogen-music/hydrogen#766]
Hydrogen version *          : a6fbb8b709e345e46600f0cb3f5c0568cb7d76b0

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Start Hydrogen and select a random instrument. Switch to the Instrument Tab (Layer) and click "Load layer". 

Now create a file "test.flac" which has no valid flac data, e.g. by copying some executable to "test.flac". 

After the test data is constructed, add that file as a new layer -> Hydrogen crashes.

**Comment by jeremyz** [comment]
it is now impossible to load a wrong sample file.
