### ISSUE TITLE
Incorrect licensing for the appdata.xml file

### ISSUE THREAD

**Issue by hfiguiere** [hydrogen-music/hydrogen#774]
Hydrogen version *          : 1.0.0-beta1
Operating system + version  : Linux
Audio driver + version      : n/a

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

In the appdata file `linux/org.hydrogenmusic.Hydrogen.appdata.xml`, the metadata license (the actual appdata license) is set to GPL-2.0+ `<metadata_license>. Flathub validation fail on this.

The appstream documentation also doesn't list it as valid:

https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

Furthermore, flathub only accept CC0.

What should happen is that the project commit to change the license of the metadata to one accepted (CC0 seems the only option) and change the license in the file. (I can't since I don't have the right the relicense - but if there is an agreement, I'm willing to submit a PR).

This does NOT impact the licensing of Hydrogen.

As a contributor to this file, this is my blanket permission to got ahead on the relicensing of the appdata file.

Thanks

**Comment by mauser** [comment]
@blablack : Aurelien, since you seem to be the original author of the file, would you be ok with such a relicensing?

**Comment by trebmuh** [comment]
If that helps, as [I participated in that file](https://github.com/hydrogen-music/hydrogen/commit/83e1b695867d41cbf5319cdbc053553c74f2f3ad), I'm fine with the re-licensing of this very file.
@blablack and you?

**Comment by hfiguiere** [comment]
Just to clarify, my contribution to #775 is in `CC0-1.0`. This is an implicit agreement into relicensing for this issue to be solved. 

Note that this issue is important as it prevent from including Hydrogen into appstream "catalogs" that get used by app repositories like Flathub.

**Comment by hfiguiere** [comment]
the latest is always at https://flathub.org/apps/org.hydrogenmusic.Hydrogen

**Comment by hfiguiere** [comment]
When I submitted the flatpak I commented on this issue https://github.com/hydrogen-music/hydrogen/issues/650

**Comment by theGreatWhiteShark** [comment]
> When I submitted the flatpak I commented on this issue https://github.com/hydrogen-music/hydrogen/issues/650

Ah. Okay, this was prior to my involvement. I'll take a look at flatpak.

> the latest Flatpak is always at https://flathub.org/apps/org.hydrogenmusic.Hydrogen

... then why do we state in all places that Linux users either have to use the version found in their repo or compile the application themselves? Well, better late than never.

Thanks a lot for pointing me at this by the way!

**Comment by hfiguiere** [comment]
> ... then why do we state in all places that Linux users either have to use the version found in their repo or compile the application themselves? Well, better late than never.

I don't know. I didn't close the issue.

**Comment by hfiguiere** [comment]
If anyone of you want write access to the repository for flathub, let me know.

**Comment by theGreatWhiteShark** [comment]
> If anyone of you want write access to the repository for flathub, let me know.

I'm thinking about creating a [single-file bundle](https://docs.flatpak.org/en/latest/single-file-bundles.html) in our build pipeline and distributing them along with our release artifacts. This way Linux folks could have more easy access to are rolling releases in e.g. branch `releases/1.2`. Is this plausible and something a flatpak user would expect?

But for this to happen we need a manifest file in control of the hydrogen development team. Sharing access with non-members gives me a bad feeling. I by no means want suggest either you or the flathub team is not trust worthy. It just doesn't feel right. How about a fork and we push changes upstream?

I just read the basic tutorial of flatpak and did not delved into it's build process. But from the mere looks at the manifest file it seems it could use updates. E.g. the vamp SDK is not used anymore. I'll have a look.

> I don't know. I didn't close the issue.

There was probably just a misunderstanding.

**Comment by theGreatWhiteShark** [comment]
Hey @hfiguiere ,

you are the main force behind https://github.com/flathub/org.hydrogenmusic.Hydrogen, right? The repo is not licensed yet and as such we can not add it to our repo or use it in our build pipeline.

**Comment by theGreatWhiteShark** [comment]
@hfiguiere I created a new meta data file which should comply with the license expected by Flathub.
