### ISSUE TITLE
Headphone Events Cause Failures

### ISSUE THREAD

**Issue by dcloutman** [hydrogen-music/hydrogen#778]
Hydrogen version *          : 0.9.7
Operating system + version  : Windows 10 Enterprise
Audio driver + version      : "NoMachine Microphone Adapter" (HP laptop. EliteBook 755 G5)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
There appears to be a problem in how events related to the plugging in and unplugging of wired 3.5mm jack headphones are handled. The desired behavior should be that when headphones are plugged in, sound should come out of the headphone and when they are unplugged sound should come out of the speaker. Non-conforming behaviors are as follows:

1. When application is started with headphones unplugged, application plays over speakers. When headphones are plugged in, application continues to play over speakers while other applications play over headphones.

2. When headphones are plugged in when application is started, application plays through headphones. Removing headphones causes playback to freeze. UI events register visually, but no sounds are produced.

Restarting the application remedies the above problems. It seems the output device must remain constant for the application to function correctly.

**Comment by thijz** [comment]
What audio server are you using ?
Isnt this something that is handled by the OS / audio server ?  (been ages since i used windows so i dont really know)
Do other applications handle the switchover correctly ?

**Comment by elpescado** [comment]
Could you check e.g. if the same problem appear in Audacity (they use PortAudio like Hydrogen)?

**Comment by dcloutman** [comment]
I'm running Audacity at the same time. Works as expected. This seems to be A Hydrogen specific problem. All other apps that are running play on the right device. I write code!https://davidcloutman.comSent from my phone. On Nov 1, 2019 10:14 AM, elpescado <notifications@github.com> wrote:Could you check e.g. if the same problem appear in Audacity (they use PortAudio like Hydrogen)?

**Comment by theGreatWhiteShark** [comment]
Could you start Hydrogen with the command line argument `-VDebug` and report back the debugging logs?

**Comment by theGreatWhiteShark** [comment]
Hey @dcloutman ,

This issue is quite old by now. Could you check whether this bug still applies to the newest 1.1.1 release of Hydrogen? Otherwise, I will close this issue in two weeks. (but feel free to reopen it)

**Comment by cme** [comment]
PortAudio doesn't seem to provide any facilities for detecting changes like headphone insertion. I notice you say the device is "NoMachine Microphone Adapter" which is... certainly odd for an output device, as it's an NX interface and also an input. I'd guess that perhaps PortAudio has managed to allow Hydrogen to select this as an output device, and it's misbehaving. Until 1.1, Hydrogen would only ever use the default PortAudio stream. With 1.1 onwards the HostAPI and output device can be selected, so selecting a local audio device should be possible.
