### ISSUE TITLE
Weird volume drop and increase on sample

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#783]
Hydrogen version * : 0d3bb86
Operating system + version : ubuntu 16.04
Audio driver + version : jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

On one of my songs i have a long sample (about 10sec) loaded that plays just fine in previous versions of H2
When i load the song in this version of H2 i get a very strange slow volume decrease followed by a slow steady increase (until the sound is completely distorted)

This is what the sample editor looks like : 

![image](https://user-images.githubusercontent.com/1384210/68246455-1aadc680-0019-11ea-9c60-6dd0ca9d5d3f.png)

As you can see the original sample (top window) looks ok, but in the bottom window the sample starts normal then the amplitude slowly drops to 0 and then increases until it clips completely

If i hit 'play original sample' i can see the playhead (top window) move, but there is no audio
hitting 'play' works, but i get the distorted audio

i have tried changing the volume envelope but hit bug #782

**Comment by theGreatWhiteShark** [comment]
That's super strange.

Can you share the sample and a step-by-step guide of the changes you applied to it?

**Comment by thijz** [comment]
I can share the sample tonight (nothing special about it really)
IIRC all i did was set the 'sample length to beat' to 16

if i open the song in an 'old' version of H2 (will be more specific about the version when i'm at my music laptop) it works just fine
if i open that same song in this version of H2 i get this weird effect
looks like the sample editor is misinterpreting the configured sample editor settings somehow

**Comment by thijz** [comment]
retested on 338cd7d1c171f8c749ef57021850744435abdaa0 and i dont see it any more ...
uploading sample anyway becausi i think it is probably related to #782

[moog2.wav.zip](https://github.com/hydrogen-music/hydrogen/files/4314799/moog2.wav.zip)

**Comment by thijz** [comment]
will close now since i cant reproduce this specific issue
