### ISSUE TITLE
uneven tempo and glitches on ubuntu 18.02

### ISSUE THREAD

**Issue by mrmagcore** [hydrogen-music/hydrogen#785]
Hydrogen version 0.9.7-6   :
Operating system + version Ubuntu 18.02.04  : 
Audio driver + version     built in audio : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

simple one-beat drum track on a fresh install, no load on processer, plenty of memory and disk space.  Hydrogen glitches and plays at random speeds, and is totally useless.  No extra plugins installed.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by theGreatWhiteShark** [comment]
Glitches are usually caused by settings of the audio driver too high for the hardware to handle.

What audio driver/ version do you use? And if JACK, can you report the options you start `jackd` with (or the options you chose in `QJackCtl`)?

**Comment by mrmagcore** [comment]
Hi, Thanks for writing.
I didn't set anything about the audio driver.  This happens immediately after install on a xps 13 with no special audio software that I'm aware of.  Where can I discover what audio driver I am using?

**Comment by mrmagcore** [comment]
Here is what my audio preferences panel looks like
![hydrogen_audio_system](https://user-images.githubusercontent.com/858728/68545772-005f4a00-0385-11ea-944a-497cd30505a2.png)

**Comment by theGreatWhiteShark** [comment]
Hmmm. When it comes to diagnosis the "auto" driver is not helpful at all.

In general I would recommend to use the JACK audio server  [1] if you intend to do some music and audio processing in Linux. For the most accessible introduction I would recommend to start it using QJackCtl [2].

On the other hand there are some Linux distributions tailored for handling audio, e.g. [3]. 

[1] https://jackaudio.org/
[2] https://qjackctl.sourceforge.io/
[3] https://ubuntustudio.org/

**Comment by mrmagcore** [comment]
Now it says "there was an error restarting the audio driver" when I try jack, and alsa and pulseaudio also produce no sound.  Other sound producing software has no problem.

**Comment by theGreatWhiteShark** [comment]
Can you post the command you used to start the `jackd` server with (including the command line options)?

In addition, can you start Hydrogen on the command line using `hydrogen -VDebug` and attach the output?

**Comment by mrmagcore** [comment]
I don't know how to start the jackd server.  I don't know anything about it, I just see it listed as one of the audio drivers in hydrogen.  I can also try alsa, pulse audio and port audio.  None of them work.

Attached is the log from hydrogen -VDebug
[hydrogen_debug.txt](https://github.com/hydrogen-music/hydrogen/files/3899262/hydrogen_debug.txt)

**Comment by theGreatWhiteShark** [comment]
Seems as Hydrogen is using PulseAudio as audio driver which works just fine.

But the drumsets installed on you system are pretty old and H2 can not load it anymore. After getting a fresh version of them everything should work fine.

**Comment by mrmagcore** [comment]
I have uninstalled and re-installed hydrogen many times. Wouldn't that include whatever drumsets come with it?  This is all a fresh install, I started the whole process of trying to learn how to use hydrogen a few weeks ago, so I wouldn't have any old drum files lying around.  Any drums referenced by hydrogen would have been installed within the last few weeks.  
Are drumsets somehow installed via a different package?  I don't know anything about drumsets or how to install them.

**Comment by trebmuh** [comment]
> Are drumsets somehow installed via a different package?

Yes: [see here](https://packages.ubuntu.com/search?keywords=hydrogen-drumkits).

**Comment by elpescado** [comment]
I've looked at attached log file, and noticed some things:

```
::H2Core::AudioOutput* H2Core::createDriver(const QString&) Driver: 'PulseAudio'
```
That means that PulseAudio driver is used, which is OK as PulseAudio is default sound system in most Linux distros.

```
[32m(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 0, new size = 419[0m
[32m(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 419, new size = 186[0m
[32m(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 186, new size = 233[0m
[32m(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 233, new size = 186[0m
[32m(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 186, new size = 233[0m
```
That is strange, and in my opinion may lead to glitches. I suspect that PulseAudio requests varying buffer sizes and Hydrogen is not prepared to handle those requests. Alternatively, there might be some configuration issues in PulseAudio. I suppose it might be related to timer-based scheduling in PulseAudio - as a workaround you might want to try disabling it, but I'm not that familiar with Linux audio systems:
https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Disabling_timer-based_scheduling_(0/4)

I have just checked on my Mac - Hydrogen uses fixed size buffer and there are no glitches.

**Comment by mrmagcore** [comment]
I used a different drum set, and now it makes sound!  Cool.
However, that is a mystery, since I did not install anything but hydrogen.  If some drumsets came with the package, then that's all I got.
All I did was download hydrogen and try to make a sound, any sound.  I didn't add drumsets or remove them.  I used the drum set that I was presented with when hydrogen started up. Why would hydrogen come with a drumset that doesn't work?

**Comment by thijz** [comment]
IMHO this is not related to the drumkit but to the audio driver/OS
Could it be that CPU frequency scaling is messing things up ?
@mrmagcore : are you running this on a laptop ?  if yes, can you see if you get different results with your power plugged in vs running on battery power ?
This _could_ indicate cpu freq scaling kicking in when on battery (or kicking in faster/harder)

**Comment by mrmagcore** [comment]
No difference between power / battery.  It is repeatable by switching back to the default drumkit that came with the download.  Using a different drumkit (which also came with the base install) allows it to work.

**Comment by theGreatWhiteShark** [comment]
This one seems to be fixed and seems to be caused by packaging error. In addition, there were a couple of improvements done for the PulseAudio driver and the support of variable buffer sizes. If it shows up again in Hydrogen versions >=1.2, just reopen or add a comment and I will have a look
