### ISSUE TITLE
Make auto audio driver display the selected driver

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#786]
When using the `auto` selection in Preferences > Audio system the auto driver will select a proper driver based on the operation system and some heuristics (order to try the different ones).

But, unfortunately, it does not communicate its decision and the user is unable to view the selected driver in the Preferences dialog.

**Comment by trebmuh** [comment]
Agreed.
Could be great to see something like "Auto (whatever_audio_driver_choosen)".

**Comment by thijz** [comment]
there have been many questions asked about this 'auto' option.  would indeed be good to show the driver that was auto-selected

**Comment by mauser** [comment]
Closed: the related pull request has already been merged.
