### ISSUE TITLE
Menu entries nearly invisible

### ISSUE THREAD

**Issue by francwalter** [hydrogen-music/hydrogen#789]
Hydrogen version *          : 0.97
Operating system + version  : Windows 8.1 - 64
Audio driver + version      :  RealTek High Definition Audio 6.3.9600.16384

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hello
With version 0.97 either the 32-Bit or the 64 Bit Beta I have weird white menu color, so it is nearly invisible on the white-grey background of the window.
In the settings it is worse, here it is not visible at all because the background is nearly white as well.

Here some screenshots:
![grafik](https://user-images.githubusercontent.com/927269/70716287-5872ce80-1cec-11ea-8b1d-f897cfe376b6.png)

![grafik](https://user-images.githubusercontent.com/927269/70716268-4ee96680-1cec-11ea-8789-8500af87bbe0.png)

I installed the 1.0.0. Beta 1 but here I have no sound at all. The menu colors are good here, but without sound output it is useless.

Is this system related?
Thanks.
frank

**Comment by mikotoiii** [comment]
If you change your audio driver from Auto to portaudio, it should work. Hydrogen comes with portaudio integrated into it for Windows. The white font could be caused by the system font if your normal system font is set to white.

**Comment by francwalter** [comment]
I tried both, Auto and Portaudio, but none works.

![grafik](https://user-images.githubusercontent.com/927269/70745666-91c73080-1d24-11ea-8738-7d96e3a40647.png)

The white font is not by my system, but from Hydrogen. The Background is to bright though.
In v1.0.0-Beta the background is dark, in 0.9.7 it is white grey. Both fonts are white in the menu bar.
I have no other application on my windows with white fonts in the menu, anyway.

**Comment by theGreatWhiteShark** [comment]
> I installed the 1.0.0. Beta 1 but here I have no sound at all.

You could try to download a fresh version of the drumkits. The bundled ones are sometimes to old to be supported by the 1.0.0 Beta 1 release or newer ones.

**Comment by francwalter** [comment]
Where do I get a "fresh version" of the drumkits?
Thanks.

**Comment by theGreatWhiteShark** [comment]
In the main menu you click on Drumkits > Online Import. Then you select a drumkit and click 'Download and install'

**Comment by elpescado** [comment]
Hi,

Re: original problem - invisible menus. Hydrogen allows user to set GUI theme. The problem is that Hydrogen recently switched from Qt4 to Qt5, and those libraries provide different themes. Long story short, correct settings should be:

* "Fusion" for Hydrogen 1.0.0 beta and newer (Qt5)
* "Plastique" for Hydrogen 0.9.7 and older (Qt4)

Switching between two installations of Hydrogen make it "remember" wrong theme to use.

Theme can be changed in Preferences window, Appearance tab in Style option list.

**Comment by francwalter** [comment]
Yeah! That it!
I nearly didnt see what I did, but I found it neverless, I put Plastique as Style:
![grafik](https://user-images.githubusercontent.com/927269/73187684-111c9200-4122-11ea-8036-1ce79585f795.png)
Thank!!!

**Comment by francwalter** [comment]
And also it works with drumkits, in the 1.0.1beta, I think now, I just had to choose it, as all are working.
But I wasnt able to download online, the list is empty. Never mind. Works all now :)
