### ISSUE TITLE
Runtime issue preventing Hydrogen fromstarting in Windows 7

### ISSUE THREAD

**Issue by YungPhil** [hydrogen-music/hydrogen#791]
Hydrogen version *Beta 1 64 bit:
Operating system + version  : Windows 7 64 bit
Audio driver + version      : Port Midi

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hi -  I have been using Hydrogen Beta 1 64 bit version successfully on my Laptop on Windows 7 until today. I tried starting it up this afternoon and Hydrogen will not run reporting a Runtime error. I tried reinstalling Hydrogen but no success. Also tried uninstalling and loading the last stable version 0.9.7 but again it would not load. I have downloaded Windows updates within the past week. I have also done the same on  my 32 bit PC and Hydrogen still runs OK on that computer. Any thoughts anyone?

**Comment by theGreatWhiteShark** [comment]
Can you start the application in with the `--verbose=Debug` command line option and report the log messages?

Under Windows you might use something like `start /b "" "c:\Program Files\Hydrogen\hydrogen.exe" --verbose "DEBUG"`

**Comment by YungPhil** [comment]
Hi and thanks for responding - I think I have sorted the problem by taking out a few progs from the startup menu - I had 
Hydrogen running fine yesterday but will get back to you if the error happens again.
Regards Phil
     On Saturday, 28 December 2019, 00:02:04 GMT, theGreatWhiteShark <notifications@github.com> wrote:  
 
 
Can you start the application in with the --verbose=Debug command line option and report the log messages?

Under Windows you might use something like start /b "" "c:\Program Files\Hydrogen\hydrogen.exe" --verbose "DEBUG"
