### ISSUE TITLE
connect hydrogen on windows via midi to controller

### ISSUE THREAD

**Issue by hobertuefer** [hydrogen-music/hydrogen#795]
Hydrogen version *          :9.7
Operating system + version  : windows 10
Audio driver + version      : port audio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
can you help me with connecting my midi controller to hydrogen to controlle my playlist
how to set up via port audio or jack
thx

**Comment by mauser** [comment]
Hi! 

First of all, you should try the most recent version of Hydrogen: Hydrogen 1.0-beta2.  I've made some fixed to the portmidi implementation in the last time. If you want to only receive midi, select portmidi as a midi driver and select your midi input device.

**Comment by hobertuefer** [comment]
Dear Sebastian

Many thx – Great - I’ll check asap and feed back

Krgds

Heinz

 

Von: Sebastian Moors <notifications@github.com> 
Gesendet: Montag, 20. April 2020 18:05
An: hydrogen-music/hydrogen <hydrogen@noreply.github.com>
Cc: hobertuefer <hobertuefer@bluewin.ch>; Author <author@noreply.github.com>
Betreff: Re: [hydrogen-music/hydrogen] connect hydrogen on windows via midi to controller (#795)

 

Hi!

First of all, you should try the most recent version of Hydrogen: Hydrogen 1.0-beta2. I've made some fixed to the portmidi implementation in the last time. If you want to only receive midi, select portmidi as a midi driver and select your midi input device.

**Comment by hobertuefer** [comment]
Dear Sebastian

 

Midi Commands Seem to work – but other features seem to have bugs, such as the “open file”, that opens an unusual window with the message – “it is not possible to change the pattern size when playing”

 

It is still more reliable by using ubuntu next to windows - 

 

P.S. how we are using hydrogen live

 <https://www.youtube.com/watch?v=wBaKlX1YVFE> https://www.youtube.com/watch?v=wBaKlX1YVFE

 

Very best rgds

 

Heinz

 

 

 

Von: Sebastian Moors <notifications@github.com> 
Gesendet: Montag, 20. April 2020 18:05
An: hydrogen-music/hydrogen <hydrogen@noreply.github.com>
Cc: hobertuefer <hobertuefer@bluewin.ch>; Author <author@noreply.github.com>
Betreff: Re: [hydrogen-music/hydrogen] connect hydrogen on windows via midi to controller (#795)

 

Hi!

First of all, you should try the most recent version of Hydrogen: Hydrogen 1.0-beta2. I've made some fixed to the portmidi implementation in the last time. If you want to only receive midi, select portmidi as a midi driver and select your midi input device.

**Comment by mauser** [comment]
Hello Heinz! 

the problem which you are describing has been fixed already, but i suppose that i made that fix after beta2 has been released (see #708). This bug happened also to our Ubuntu users, but is is not present in 0.9.7.  The problem will be fixed in the next version for Windows.

And thanks for the link, it's always nice to see how people use Hydrogen :smiley: 

I will close this issue now, since the original problem seems to be solved.

**Comment by nunosga** [comment]
Me too ma trying to use a midi onctroller to "play" hydrogen. So far no luck.
I've installed the latest H2 and drivers for my keyboard.
