### ISSUE TITLE
Rubberband setup Hydrogen Beta 1 version Windows 7

### ISSUE THREAD

**Issue by YungPhil** [hydrogen-music/hydrogen#797]
Hydrogen version *          :1.0.0 Beta 1
Operating system + version  : Windows 7
Audio driver + version      : PortMidi Port Audio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hi
I have been trying to use Rubberband CLI in Sample editor but the functions don't  work. I believe I need to download a Rubberband Utility package and enter the address in Options Preferences General. That much I understand.

Could you possibly help by either telling me which package I need to download or where I can find it.

I have found this one
rubberband-1.8.2-gpl-executable-windows

It is the only version with Windows mentioned but no mention of CLI.

Also I see there is a 2020 64 bit version of Hydrogen 1.0.0 on Filehorse. Is this an official release?

Thanks in anticipation

Phil

**Comment by trebmuh** [comment]
> Also I see there is a 2020 64 bit version of Hydrogen 1.0.0 on Filehorse. Is this an official release?

Not at all. 1.0.0 isn't released yet.

**Comment by mauser** [comment]
> Could you possibly help by either telling me which package I need to download or where I can find it.

Hi! 

You already found the correct package. "CLI" stands for "command line interface". Just create a new folder (like `C:\rubberband`) and put the content of "rubberband-1.8.2-gpl-executable-windows" in that folder. Now go to the Preferences Dialog, put the path `C:\rubberband` in the place which you already found and restart Hydrogen.

**Comment by YungPhil** [comment]
Thank you and very helpful. I think I have it working now. 
Kind regards
Phil
PS Great program - having fun making samples to use in it - I should know better at 70. 
     On Saturday, 4 April 2020, 23:38:27 BST, Sebastian Moors <notifications@github.com> wrote:  
 
 



Could you possibly help by either telling me which package I need to download or where I can find it.


Hi!

You already found the correct package. "CLI" stands for "command line interface". Just create a new folder (like C:\rubberband) and put the content of "rubberband-1.8.2-gpl-executable-windows" in that folder. Now go to the Preferences Dialog, put the path C:\rubberband in the place which you already found and restart Hydrogen.

**Comment by YungPhil** [comment]
Just one  more query on this one - still having problems - I am trying to use Rubberband on the 64 bit version 1.0.1 of Hydrogen on a 64 bit Windows 7 laptop.  I presume I need a 64 bit version of Rubberband-cli  - does that exist?
