### ISSUE TITLE
NSM implementation not according to NSM API 

### ISSUE THREAD

**Issue by grammoboy2** [hydrogen-music/hydrogen#798]
Hydrogen version *          : 1.0 git today
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Let's start positive. Great that there is non-session-manager (nsm) support, but frankly you made a mess of it. :) And that shouldn't have happened if you just read the API.

http://non.tuxfamily.org/nsm/API.html#n:1.1.1.4.

> 1.1.1. File Menu

> 1.1.1.2. Open
> 
> This option MUST be disabled.
>

>  
> > The application may, however, elect to implement an option called 'Import into Session', creates a copy of a file/project which is then saved at the session path provided by NSM. 
> 
> When I open a hsong file. It's not copied to the NSM Session folder. It doesn't get's saved by nsm. 
> 
> > 1.1.1.3. Save
> > 
> > This option should behave as normal, saving the current file/project as established by the NSM open message.
> > 
> > UNDER NO CIRCUMSTANCES should this option present the user with a choice of where to save the file. 
> 1.1.1.4. Save As
> 
> This option MUST be disabled.
> 
> The application may, however, elect to implement an option called 'Export from Session', which creates a copy of the current file/project which is then saved in a user-specified location outside of the session path provided by NSM. 

I do have the option to save a file where ever I want. This is not according to the nsm API.

> 1.1.2. Data Storage
> 1.1.2.1. Internal Files
> 
> All project specific data created by a client MUST be stored in the per-client storage area provided by NSM. This includes all recorded audio and MIDI files, snapshots, etc. Only global configuration items, exports, and renders of the project may be stored elsewhere (wherever the user specifies).
> 1.1.2.2. External Files
> 
> Files required by the project but external to it (typically read-only data such as audio samples) SHOULD be referenced by creating a symbolic link within the assigned session area, and then referring to the symlink. This allows sessions to be archived and transported simply (e.g. with "tar -h") by tools that have no knowledge of the project formats of the various clients in the session. The symlinks thus created should, at the very least, be named after the files they refer to (some unique component may be required to prevent collisions) 

See: https://github.com/hydrogen-music/hydrogen/issues/590

See also: https://github.com/hydrogen-music/hydrogen/pull/792

There're probably more issues. I'd suggest to read the nsm API.

If I can help with something, testing for instance, let me know. 

Good luck, nsm is a great feature! 

--

**Comment by theGreatWhiteShark** [comment]
In the current beta version Hydrogen only supports saving a song via the NSM protocol.

This feature was probably added as a stub to improve on later on and the corresponding code is the one from the code example shipped with the NSM API. An attempt to make Hydrogen compliant with the NSM protocol can be found - as you already mentioned - in #792 . Feel free to try it and to provide your feedback

**Comment by grammoboy2** [comment]
On 20-02-2020 09:03, theGreatWhiteShark wrote:
>
> In the current beta version Hydrogen only supports saving a song via 
> the NSM protocol.
>
> This feature was probably added as a stub to improve on later on and 
> the corresponding code is the one from the code example shipped with 
> the NSM API. An attempt to make Hydrogen compliant with the NSM 
> protocol can be found - as you already mentioned - in #792 
> <https://github.com/hydrogen-music/hydrogen/pull/792> . Feel free to 
> try it and to provide your feedback
>
>
Thanks for your work on this! Really appreciated. Will test it for sure.
