### ISSUE TITLE
add JACK MIDI support for more accurate timing. 

### ISSUE THREAD

**Issue by grammoboy2** [hydrogen-music/hydrogen#799]
Please add Jack Midi support for better timing, as timing accuracy is pretty important for a drum machine right? Let's agree that this is probably the most important feature. I would advise the development team to see timing accuracy with and without JACK Transport as a very high priority for the next release. Hydrogen did have timing issues in the past, would be great if that it really will be a issue of the past! 

JACK midi is more accurate then ALSA midi: 

> _From non-sequencer manual: "3.1.1. About Jack MIDI Connections 
> 
> Since Jack MIDI is new and not all programs support it, many find  themselves confused. This section attempts to explain Jack MIDI ports. The ALSA sequencer interface has long been the standard MIDI routing  subsystem on Linux. But many (all) of the programs we use for synthesis  these days use Jack for their audio IO. It makes more sense for those  MIDI related programs utilizing the Jack Transport for synchronization  to also use Jack ports for MIDI delivery. Therefore, ALSA MIDI is  quickly becoming obsolete. Jack MIDI ports are not related to ALSA MIDI ports in any way. Jack  MIDI ports are just like Jack audio ports, except that the data being  transmitted in each buffer are raw, timestamped MIDI events instead of  floating point audio samples. Jack MIDI is sample-accurate. This means  that a MIDI Note On event can occur concurrently with a sound, and the  two will never drift apart as often happens to some extent with ALSA. In essence, Jack MIDI is a way of expressing a direct temporal correlation between audio and MIDI data.  http://non-sequencer.tuxfamily.org/MANUAL.html_

--

**Comment by jrigg** [comment]
I've been using Hydrogen for quite a few years and for as long as I can remember it has had JACK MIDI support. Are you saying it has been removed?

**Comment by elpescado** [comment]
There has been Jack MIDI [driver](https://github.com/hydrogen-music/hydrogen/blob/master/src/core/include/hydrogen/IO/JackMidiDriver.h) in Hydrogen for [a while](https://github.com/hydrogen-music/hydrogen/commit/f39d3649e179fb8a9649138b7cdf785c3cf9dae1).

**Comment by mauser** [comment]
Closed: Hydrogen has already jack-midi support. @grammoboy2 : Just re-open this issue if there are open questions.
