### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by grammoboy2** [hydrogen-music/hydrogen#806]
What are the future plans for Hydrogen? I'm thrilled about the new NSM developments for instance. Will they be merged in master when ready? https://github.com/hydrogen-music/hydrogen/pull/792

Is there a new release scheduled?

**Comment by mauser** [comment]
Hi! 

Sorry for late reply! I also saw your personal mail, but had not the time for a proper reply yet. 

Some weeks ago,  we had a discussion on our mailing list about that topic. Currently nobody has time to do a lot of work on Hydrogen, so there are no current plans for large new features. The focus will be more about making the current code stable and finish the features which have been started. At least in my opinion, there is a lack of development resources to review and integrate all those new pull requests.
