### ISSUE TITLE
h2 website not displaying all txt on page

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#807]
Hydrogen version *          : na
Operating system + version  : na
Audio driver + version      : na

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

on the h2 site there is at least 1 page where only a fraction of the text that is in the site repo is actually displayed

it concerns this page : http://hydrogen-music.org/contribution
on the site you only see the intro, but noting about the different ways that you can contribute.
however, if you have a look in the site repo you can see that all the text is actually there.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

*  H2 version : see 'Info - About', or in case you build Hydrogen from source use 'git rev-parse HEAD'
** if you are reporting a bug, please describe how the bug can be reproduced

**Comment by trebmuh** [comment]
@thijz please, use https://github.com/hydrogen-music/hydrogen-music if/when that's about the website.

**Comment by thijz** [comment]
a-ha !!
i knew i already created a ticket for this but was unable to find it!
guess what : found it !  :-)
