### ISSUE TITLE
hydrogen as jack transport master does weird things

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#81]
just today i bumped upon this strange issue :

ok, so i'm experimenting with arpage (a jack-synced midi arpeggiator : https://sourceforge.net/projects/arpage/) 
the idea is to use hydrogen as transport master and sync arpage to jack (so arpage is in sync with hydrogen)
that way i can play arpeggiated (does that word exist??) synth in sync with the drum loop

i never was able to get arpage to work at all
until now : since arpage syncs to jack transport it requires jack transport to be running.  that makes sense
however, just starting the transport (via QjackCtl) was not enough.  i also had to start up Qtractor to get arpage working.
ardour as jack master also worked just fine
after some more experimenting and some tips from Jeremy (autostatic) i was also able to get it running using jack_transport

however, when using H2 as jack transport master the arpeggiator did not follow the tempo defined in hydrogen
the tempo of the arpeggiator does change when i change the tempo in H2 so there is definitely a relationship between the H2 tempo and the tempo used by arpage, but it is really freaky

i will try to add a screencapture (in this capture i am constantly pressing a key on my midi keyboard so the notes going on/off are all triggered by arpage)
in this capture there are some things to note : 
1) arpage is not triggered _at all_ when there is only 1 pattern in the song, i need to have at least 2 patterns in the song to trigger arpage
2) when i change the tempo in H2 you can hear that the tempo of arpage also changes, but it is not what you would expect
3) when i close H2 and use the jack_transport utility as master and start transport, arpage reacts as expected.  if i change the tempo value you can hear that this works as it should (this is also the way it works with qtractor and ardour as master)

seems like the jack transport in H2 does something different than the 3 other apps ...

**Comment by theGreatWhiteShark** [comment]
Hey @thijz,

Does this issue still occur? If so, could you retest it with #678 ?

**Comment by theGreatWhiteShark** [comment]
Unfortunately [arpage](https://github.com/arpage/arpage) seems to be no longer maintained and doesn't compile at my end. Is there another application I could reproduce this issue with?

**Comment by mauser** [comment]
I've closed this issue now due to inactivity. If this problem can be reproduced, just re-open the ticket.
