### ISSUE TITLE
sample editor : end marker jumps to start marker position

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#811]
Hydrogen version *          : 7283fcabce84e5575104746135fc6d7cede29e51
Operating system + version  : ubuntu studio 16
Audio driver + version      : jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

to reproduce : 

- open sample editor
- grab the start marker
- End-marker jumps to the Start-marker position

This causes previous edits to be lost : 

- tweak the end-marker position of a sample
- save your edit
- open the same sample again in the editor
- grab the start-marker
- your end-marker jumps to the start and your previous work is lost

**Comment by theGreatWhiteShark** [comment]
Already fixed in f650820219e255ca48136688f8c9a6e9eecffd50
