### ISSUE TITLE
Feature Request: Export song to mp3

### ISSUE THREAD

**Issue by francwalter** [hydrogen-music/hydrogen#812]
Hydrogen version *          : 1.0.0-beta1
Operating system + version  : Windows 8.1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I was experimenting with Hydrogen and creating some songs. Then I wanted to export them, but there is only wav, ogg and some other less known formats.
I would like to have mp3 as export format too. I know that there are free libraries, e.g. used in Audacity.
Is it possible to integrate mp3 as export format for songs?
Thanks.
frank

**Comment by elpescado** [comment]
Hi,

The original reason is that MP3 used to be covered by patents, so using it needed proper licensing, which in turn made open source projects steer clear of it. AFAIK, that no longer applies, but I'm not 100% sure.

The technical reason is that Hydrogen uses `libsndfile` library to read and write audio files, and that library [doesn't support MP3](http://www.mega-nerd.com/libsndfile/FAQ.html#Q020):

> Q20 : Why doesn't libsndfile support MP3?
> 
> In the past, MP3 was not supported because the technology behind MP3 was patented. Those patents have now expired and there is an [open ticket](https://github.com/erikd/libsndfile/issues/258) to implement MP3 support.

It would be possible to use e.g [lame](https://lame.sourceforge.io) directly to encode MP3 audio, bypassing sndfile, but that would involve much more work.

**Comment by francwalter** [comment]
Thank your answer i understand fully now.
I can convert to mp3 separately with several applications, so that is the way.
