### ISSUE TITLE
Immediate crash on startup: free(): invalid pointer (Ubuntu studio)

### ISSUE THREAD

**Issue by skramm** [hydrogen-music/hydrogen#813]
Hydrogen version *          : 0.9.7
Operating system + version  :  Ubuntu studio 18
Audio driver + version      :  ???

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I am suddenly experiencing a direct crash on startup. Although H2 **did** work previously, just one morning, it stopped (see below).

Steps to reproduce:
1. boot machine
2. open terminal:
```
$ hydrogen

Hydrogen 0.9.7 [Sep 19 2017]  [http://www.hydrogen-music.org]
Copyright 2002-2008 Alessandro Cominu
Copyright 2008-2016 The hydrogen development team

Hydrogen comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions. See the file COPYING for details

free(): invalid pointer
Aborted (core dumped)
```
Thiis is without starting qjackctl or anything else.
Same behavior if I start it from the GUI of course. (except I don't get the above log).

- Hydrogen version is the one shipped with OS.
- OS and other software is up to date (update/upgrade done)
- I understand this could be related to some other piece of software (audio driver ?).
- I tried to start it with jack (`hydrogen -d jack`): same result
- I erased `/home/sk/.hydrogen/hydrogen.conf` ,it got regenerated after startup attempt (see attached).
[hydrogen.conf.txt](https://github.com/hydrogen-music/hydrogen/files/4363472/hydrogen.conf.txt)

Could it be related to this: ?
https://github.com/csound/csladspa/issues/1

In case it is, I'm not sure how that helps solving my issue.

Additional info:
```
$ uname -a
Linux sk-ustudio 4.15.0-91-lowlatency #92-Ubuntu SMP PREEMPT Fri Feb 28 12:15:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

$ldd /usr/bin/hydrogen>ldd.txt
```
[ldd.txt](https://github.com/hydrogen-music/hydrogen/files/4363411/ldd.txt)

Anything else I can do to help fix that ?

And thanks for that great piece of software.

**Comment by trebmuh** [comment]
@skramm have you tried to remove the csladspa package?

**Comment by mauser** [comment]
Hi,

you could also try to rename the .hydrogen folder temporarily. This makes sure that Hydrogen does not try to load Drumkits, Songs and Patterns which might be stored in that folder.

**Comment by skramm** [comment]
Thanks for suggestions.
@mauser  just tried. Same result, the file gets regenerated with an "auto" audio_engine/audio_driver

**Comment by skramm** [comment]
@trebmuh Yep! that was it!
Did  `sudo apt remove csladspa` and H2 started.

Problem solved... for me. But for others:
- how is that package related to H2 ? Is it installed alongside H2? If yes, how can H2 work with it?
If it is not needed, why is it there ? (I don't think I installed it myself...).


This is pretty much unclear to me: how can a library make a program crash... if that app doesn't require that library ?



The

**Comment by trebmuh** [comment]
In my humble opinion, this is not the place to discuss it. The debian bug tracker would be a much better place.

Have fun with Hydrogen!

**Comment by skramm** [comment]
@trebmuh Sure, makes sense... but that issue will probably hit other users.
Are you suggesting I post an issue somewhere ? But why Debian ? This is not a Debian issue... (?)

**Comment by trebmuh** [comment]
Rise up an issue against the cladspa package on the Debian BTS.

**Comment by skramm** [comment]
https://bugs.launchpad.net/ubuntu/+source/csound/+bug/1868432
