### ISSUE TITLE
Hydrogen disappeared from the debian-testing "bullseye" repository

### ISSUE THREAD

**Issue by nathanaelmeister** [hydrogen-music/hydrogen#814]
Operating system + version  :  Debian GNU/Linux bullseye/sid
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Hydrogen disappeared from the debian-testing "bullseye" repository,
anyone knows why that happened?

    hydrogen-drumkits/testing,now 2017.09.19~dfsg-1
    hydrogen-drumkits-effects/testing,now 2017.09.19~dfsg-1

are still available.

**Comment by mauser** [comment]
Hi,

i can only guess that this is related to the dependency to QT4, but i can't say for sure. Since we're not involved in the packaging for debian, you have to ask them directly.

**Comment by mauser** [comment]
See also #794

**Comment by trebmuh** [comment]
> i can only guess that this is related to the dependency to QT4, but i can't say for sure. 

It is. See: https://tracker.debian.org/news/1105589/removed-097-6-from-unstable/

**Comment by nathanaelmeister** [comment]
is there a way to get `hydrogen` running on **debian/bullseye/sid** until it is ported to QT5?

**Comment by trebmuh** [comment]
You can compile it yourself since Hydrogen has Qt5 support since 1.0.0-beta1 .

Another interesting link for this thread: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954823

**Comment by elpescado** [comment]
> is there a way to get `hydrogen` running on **debian/bullseye/sid** until it is ported to QT5?

I think Ubuntu Studio packages qt5-based 1.0.0-beta1, so using their packages might work. Hydrogen 1.0.0-beta1 is also available as [flatpak](https://flathub.org/apps/details/org.hydrogenmusic.Hydrogen). Manual compilation is the best (proper?) way, however.

**Comment by mauser** [comment]
Hi,

i'm closing this issue since we can't anything specific about it (aside from releasing 1.0, which we would also do without this issue).
