### ISSUE TITLE
Travis CI failed to upload artefacts for 1.0.0-beta2

### ISSUE THREAD

**Issue by elpescado** [hydrogen-music/hydrogen#817]
As I see, 1.0.0-beta2 has just been released! 🎉 Unfortunately there are no macOS packages (they should be built automatically)

I've seen that [macOS Travis CI pipeline](https://travis-ci.org/github/hydrogen-music/hydrogen/jobs/665586513#L4213) has failed while uploading macOS packages to GitHub release:

> /Users/travis/.rvm/gems/ruby-2.6.3/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)

I've linked Travis CI docs in my old Pull Request #557 

I think some credentials have to be set up, and re-running that pipeline should work. If not, let me know, I'll try to build those packages manually.

**Comment by mauser** [comment]
Hi! 

Yes, i saw that last night, but it was too late for me to fix it :) I will care for that later today.. It seems also that the upgraded their deployment tooling to dpl v2, at least there are some advices/warnings about the .travis.yml in the current builds.

Thanks for the help! I hope that we don't need to build the packages manually anymore..

**Comment by mauser** [comment]
After some fiddling around with travis.yml, the dmg has now been added successfully to the release. Could you try if the dmg works for you?

**Comment by elpescado** [comment]
I've tried it on my MacBook running High Sierra (10.13) and on my work MacBook running Mojave (10.14) and it works fine. Thanks!

**Comment by mauser** [comment]
Ok, perfect!
