### ISSUE TITLE
[beta2] translations broken

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#819]
It seems that the translation system is broken. I've tried to make a LibraZiK package for beta2, but when launching Hydrogen, it's always in English.

Note: I'm using a French locale.

Launching it with `hydrogen -VDebug` from the CLI, I've got those which looks interesting:

```
...
...
(I) Filesystem::info Internationalization dir   : /usr/share/hydrogen/data/i18n/
...
...
(I) ::int main(int, char**) Using QT version 5.11.3
(I) ::int main(int, char**) Using data path: /usr/share/hydrogen/data/
(I) ::int main(int, char**) Warning: no locale found: /usr/share/hydrogen/data/i18n/hydrogen.fr_FR
(I) ::int main(int, char**) Warning: error loading locale: /usr/share/hydrogen/data/i18n//hydrogen.fr_FR.qm
...
...
```

Note that:

```
$ ls -la /usr/share/hydrogen/data/i18n/hydrogen_fr*
-rw-r--r-- 1 root root 109417 mars  25 16:01 /usr/share/hydrogen/data/i18n/hydrogen_fr.qm
```

It looks to me that hydrogen is looking for a `hydrogen.fr_FR.qm` while there is only a `hydrogen_fr.qm` one.

**Comment by trebmuh** [comment]
Note that if I rename  `/usr/share/hydrogen/data/i18n/hydrogen_fr.qm` for  `/usr/share/hydrogen/data/i18n/hydrogen.fr_FR.qm` as expected by Hydrogen, I've got my Hydrogen in French. Renaming it for `/usr/share/hydrogen/data/i18n/hydrogen.fr.qm` looks to be working as well.

**Comment by mauser** [comment]
Hi! 

i've made a recent change 70e828afed2f737d4cb2fa193612bad712c95fdf to the CMakeLists file in the i18n dir. This has been more of a temporary nature for the windows build. Can you try if it works with an earlier commit?

**Comment by trebmuh** [comment]
Hi @mauser , I've applied [jpcima's patch](https://github.com/hydrogen-music/hydrogen/pull/820) and it seems to work here. Do you still need me to try a commit before 70e828a?

**Comment by mauser** [comment]
Hi,

the patch is applied, so i'm closing this issue. @trebmuh : Just re-open it if the problem persists.

**Comment by trebmuh** [comment]
OK, I'll wait for beta3 to recheck this.
