### ISSUE TITLE
[beta2] Mac installer is missing translations

### ISSUE THREAD

**Issue by elpescado** [hydrogen-music/hydrogen#821]
Hydrogen version *          : 1.0.0-beta2
Operating system + version  : macOS 10.13
Audio driver + version      : n/a

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Mac package is missing compiled translation files so Hydrogen is not localised (UI is in English regardless of system language settings).

![Zrzut ekranu 2020-03-25 o 22 19 23](https://user-images.githubusercontent.com/1619113/77586639-d5663480-6ee6-11ea-8fb6-2e498b3e93b3.png)

**Comment by trebmuh** [comment]
@elpescado probably due to https://github.com/hydrogen-music/hydrogen/issues/819

**Comment by elpescado** [comment]
I think that's unrelated.

As you can see in attached screenshot, there are source translation files (*.ts, files used and edited by translators) included in package, but there are no compiled translations (*.qm, those are actually used by application). Some time ago we removed compiled translations from git repository (which was a good thing) and compile them as part of build process. Somehow yet they didn't make their way to package file. (As a side issue, *.ts files are totally unnecessary in binary package and could be skipped).

I'll investigate it, but I cannot assign myself to this issue.

**Comment by trebmuh** [comment]
assigned!

**Comment by mauser** [comment]
When building with Linux, my build/data/i18n directory holds the following files:

```
drwxr-xr-x 3 sebastian sebastian 4,0K Mär 26 21:27 CMakeFiles
-rw-r--r-- 1 sebastian sebastian 2,5K Mär 26 21:27 cmake_install.cmake
-rw-r--r-- 1 sebastian sebastian  56K Mär 26 21:27 hydrogen_ca.qm
-rw-r--r-- 1 sebastian sebastian  53K Mär 26 21:27 hydrogen_cs.qm
-rw-r--r-- 1 sebastian sebastian 105K Mär 26 21:27 hydrogen_de.qm
-rw-r--r-- 1 sebastian sebastian 110K Mär 26 21:27 hydrogen_el.qm
-rw-r--r-- 1 sebastian sebastian 104K Mär 26 21:27 hydrogen_es.qm
-rw-r--r-- 1 sebastian sebastian 107K Mär 26 21:27 hydrogen_fr.qm
-rw-r--r-- 1 sebastian sebastian  85K Mär 26 21:27 hydrogen_gl.qm
-rw-r--r-- 1 sebastian sebastian  58K Mär 26 21:27 hydrogen_hr.qm
-rw-r--r-- 1 sebastian sebastian  14K Mär 26 21:27 hydrogen_hu_HU.qm
-rw-r--r-- 1 sebastian sebastian  77K Mär 26 21:27 hydrogen_it.qm
-rw-r--r-- 1 sebastian sebastian  65K Mär 26 21:27 hydrogen_ja.qm
-rw-r--r-- 1 sebastian sebastian  42K Mär 26 21:27 hydrogen_nl.qm
-rw-r--r-- 1 sebastian sebastian  38K Mär 26 21:27 hydrogen_pl.qm
-rw-r--r-- 1 sebastian sebastian 105K Mär 26 21:27 hydrogen_pt_BR.qm
-rw-r--r-- 1 sebastian sebastian  74K Mär 26 21:27 hydrogen_ru.qm
-rw-r--r-- 1 sebastian sebastian 102K Mär 26 21:27 hydrogen_sr.qm
-rw-r--r-- 1 sebastian sebastian  18K Mär 26 21:27 hydrogen_sv.qm
-rw-r--r-- 1 sebastian sebastian 104K Mär 26 21:27 hydrogen_uk.qm
-rw-r--r-- 1 sebastian sebastian 7,4K Mär 26 21:27 Makefile

```

So i got now *.ts files, just the *.qm files as expected. 

Could you try to run the build process locally on your mac and investigate what happens in data/i18n/CMakeLists.txt?

**Comment by mauser** [comment]
Another thing: i suppose it would make sense to re-tag beta2 if this can be fixed, especially because the linux translations was also buggy.

**Comment by elpescado** [comment]
They are being [built](https://travis-ci.org/github/hydrogen-music/hydrogen/jobs/668440998#L3930):
```
3930 [  5%] Generating hydrogen_hu_HU.qm
3931 Updating '/Users/travis/build/hydrogen-music/hydrogen/build/data/i18n/hydrogen_hu_HU.qm'...
3932     Generated 159 translation(s) (1 finished and 158 unfinished)
3933     Ignored 687 untranslated source text(s)
3934 [  6%] Generating hydrogen_it.qm
3935 Updating '/Users/travis/build/hydrogen-music/hydrogen/build/data/i18n/hydrogen_it.qm'...
3936     Generated 727 translation(s) (702 finished and 25 unfinished)
3937     Ignored 119 untranslated source text(s)
```

But they are not being copied to .dmg image, because that image is built by custom script, not by CMake/CPack.I have to update that script.

**Comment by mauser** [comment]
Hi,

i'm closing this issue since the corresponding pull request has already been merged. The result will be available in beta3.
