### ISSUE TITLE
[beta2] Hydrogen on Retina Macs is pixelated

### ISSUE THREAD

**Issue by elpescado** [hydrogen-music/hydrogen#822]
Hydrogen version *          : 1.0.0-beta2
Operating system + version  : macOS 10.14
Audio driver + version      : n/a

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hydrogen on HighDPI (Retina) screen on Mac looks pixelated. Compare Hydrogen window to Finder window below it:

<img width="1023" alt="Screenshot 2020-03-25 at 22 42 27" src="https://user-images.githubusercontent.com/1619113/77588413-1c095e00-6eea-11ea-83dd-6a6d01fb4a62.png">

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by elpescado** [comment]
I'd like to investigate this issue and assign myself to this issue but I can't do that:(

**Comment by trebmuh** [comment]
done
