### ISSUE TITLE
[beta2] LADSPA is missing ?

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#824]
Hi all.
Build from cfb496c (which is beta2 + a few commits), Hydrogen tells me that "LADSPA effects are not available in this version of Hydrogen" when I'm clicking on a "BYP" or a "EDIT" button on the Mixer view.
Note that I had the "ladspa-sdk" package while building. Debian Buster here.
Anyone to confirm/infirm that the same happen to him/her?

**Comment by elpescado** [comment]
Could you post output from CMake? There should be something like this:

```
Main librarires
* libQt                        : 5.5.1
* libsndfile                   : + used  ( /usr/lib/x86_64-linux-gnu/libsndfile.so )
*                                libsndfile version must be greater than 1.0.17 to support FLAC and OGG sound file formats
* libtar                       : - not found and not desired
* libarchive                   : + used  ( /usr/lib/x86_64-linux-gnu/libarchive.so )
* ladspa                       : + used  ( 5 plugins found )

```
<img width="839" alt="Screenshot 2020-03-31 at 09 59 32" src="https://user-images.githubusercontent.com/1619113/78001715-66e60400-7336-11ea-8216-e8c6edcfdaeb.png">

**Comment by trebmuh** [comment]
I've got this:

```
Warning: You do not have a LADSPA_PATH environment variable set. Defaulting to DEFAULT_LADSPA_PATH.
-- Could NOT find LADSPA (missing: LADSPA_LIBRARIES) 
```

and (later) that:

```
Main librarires
* libQt                     : 5.11.3
* libsndfile                : + used  ( /usr/lib/x86_64-linux-gnu/libsndfile.so )
*                                libsndfile version must be greater than 1.0.17 to support FLAC and OGG sound file formats
* libtar                    : ? available but not desired  ( /usr/lib/libtar.so )
* libarchive                : + used  ( /usr/lib/x86_64-linux-gnu/libarchive.so )
* ladspa                    : -- not found but desired ...
```

This is very strange...

**Comment by mauser** [comment]
Hi,

i've stumbled upon a very similar situation when building Hydrogen with MXE for windows. In my MXE environment only ladspa.h was present, no builtin plugins or such. In that case,  `LADSPA_INCLUDE_DIR` is defined by `FIND_HELPER`, but `LADSPA_LIBRARIES` not. I did a small hack and adjusted the code in such a way that for ladspa, only the include dirs are considered. 

I will see if i can reproduce the problem here with a linux build.

**Comment by mauser** [comment]
In my case, `LADSPA_PATH=/usr/lib/ladspa ./build.sh m` did the trick. Hydrogen is now able to find at least one plugin and will therefore be compiled with ladspa support. Looks fishy to me.

**Comment by trebmuh** [comment]
This is very strange, even fishy as you wrote. From memories, it wasn't the case "before" (whatever this "before" means). Let me know if/how I can help with that.

**Comment by mauser** [comment]
Could you pull from master and try again?

**Comment by trebmuh** [comment]
Hey @mauser, I've rebuild from GIT master 4c08d41 and I4ve got this now:

```
-- Found ALSA: /usr/lib/x86_64-linux-gnu/libasound.so  
-- Checking for module 'LADSPA'
Warning: You do not have a LADSPA_PATH environment variable set. Defaulting to DEFAULT_LADSPA_PATH.
-- Found LADSPA: /usr/include  
```


```
Main librarires
* libQt                        : 5.11.3
* libsndfile                   : + used  ( /usr/lib/x86_64-linux-gnu/libsndfile.so )
*                                libsndfile version must be greater than 1.0.17 to support FLAC and OGG sound file formats
* libtar                       : ? available but not desired  ( /usr/lib/libtar.so )
* libarchive                   : + used  ( /usr/lib/x86_64-linux-gnu/libarchive.so )
* ladspa                       : + used  (  )
```

and after launching the Mixer, I can select among the LADSPA available on my system.

Thanks Sebastian! Closing the issue now then.
