### ISSUE TITLE
[beta2] No Jack support ?

### ISSUE THREAD

**Issue by gnzgg** [hydrogen-music/hydrogen#825]
Hydrogen version *          :  1.0.0-beta2
Operating system + version  : Debian 10 (Buster)
Audio driver + version      :  Jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hi, I can't find a way to connect the newest (beta) version to Jack, despite being able to do so with previous releases

I have tried using Cadence & QjackCtl. One workaround has been to use the Alsa--Jack bridge, but it's obviously not ideal. Is jack supported in the current build ? I'm kind of a newbie here, so maybe it's just me :)

```
(E) ::void H2Core::audioEngine_startAudioDrivers() Error starting audio driver                        
(E) ::void H2Core::audioEngine_startAudioDrivers() Using the NULL output audio driver                 
(E) ::void H2Core::audioEngine_startAudioDrivers() m_pMainBuffer_L == NULL                            
(E) ::void H2Core::audioEngine_startAudioDrivers() m_pMainBuffer_R == NULL                            
(E) ::void H2Core::audioEngine_setupLadspaFX(unsigned int) nBufferSize=0                              
(E) NullDriver::setBpm not implemented yet     
```

Also I have a bunch of questions about certain features (midi mapping, routing and such) but I don't know if this is the right place, if not, is there a forum or a place i might be able to ask other users ? 
 
Anyway, keep up the good work !

**Comment by mauser** [comment]
Hi! 

Yes, jack is still supported, there has been no change. Are you shure that you have selected jack as an audio driver in the Preferences Dialog? 

Currently there is forum available. You could ask here or on our [mailing list](https://sourceforge.net/projects/hydrogen/lists/hydrogen-devel).

**Comment by gnzgg** [comment]
I can only find the Alsa and Pulseaudio options in the preferences, regardless of wether there is a jack server currently running

I have also tried ./hydrogen -d jack but I don't know how to initialize jack from command line so I don't know if that's a good way to do it

My install of the beta is currently in my home folder's opt and I still have hydrogen installed from repo (0.9.7), maybe that would cause the issue ? 
I'll try rebuilding from scratch and will edit the results in here

**Comment by mauser** [comment]
This means that Hydrogen was compiled without jack support. This means that when compiling, cmake was not able to find the jack header files and libraries. For Debian, this will be `libjack-dev`.

**Comment by gnzgg** [comment]
libjack-dev was missing indeed, problem solved, thanks a lot !
