### ISSUE TITLE
GUI refresh issue in Instruments Layer window

### ISSUE THREAD

**Issue by thijz** [hydrogen-music/hydrogen#830]
Hydrogen version *          : 1368d91
Operating system + version  : ubuntu studio 18.04
Audio driver + version      : jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

1) create a new song (default kit is now loaded)
2) add a new instrument (Instruments - Add instrument)
3) select one of the existing instruments and you see the waveform in the instruments layers window :
![image](https://user-images.githubusercontent.com/1384210/78298347-703bc000-7532-11ea-9131-02fe5b3d5e31.png)
4) now select the new instrument (that has no sample loaded yet) and the previous waveform is not cleared :
![image](https://user-images.githubusercontent.com/1384210/78298423-906b7f00-7532-11ea-8ad1-8cd5b0354290.png)
This is quite confusing :-)

**Comment by cme** [comment]
Yea, I noticed this a while ago and forgot about it. The fix (#908) is hilariously trivial :)

**Comment by cme** [comment]
Fixed in master.
