### ISSUE TITLE
Thanks and Some Comments Regarding BPM, Autoscroll etc.

### ISSUE THREAD

**Issue by AkKrock** [hydrogen-music/hydrogen#838]
Great software, nice libraries exist. Thank you for effort everyone!

I could not find any info about Export-Interpolation setings. What are the meanings?

Also is there a bpm-listener kind of application where you can calculate BPM with mouse or key click? Could be useful.

One last comment is when making a long song, autoscroll have some bugs (goes to end automatically, top bar is stands but patterns flow.).

**Comment by trebmuh** [comment]
@AkKrock thanks for your thanks.

Please open one issue per issue. Having different problem in the same thread isn't a good organizational method.

Can you please do that?
By advance, thanks you.

**Comment by mauser** [comment]
> I could not find any info about Export-Interpolation setings. What are the meanings?

The methods are described (for example) [here](http://paulbourke.net/miscellaneous/interpolation/). You for a general introduction, have a look [here](https://en.wikipedia.org/wiki/Sample-rate_conversion).

> Also is there a bpm-listener kind of application where you can calculate BPM with mouse or key click? Could be useful.

Yes, there is the "beat counter" functionality. If you just hit the "," key four times, Hydrogen calculates the tempo from your keystrokes. You can configure this thing by hitting the "BC" button which is located to the left of the tempo display. For example you can adjust the number of hits which are used to calculate the tempo, as well as making Hydrogen starting playback after that number of hits.

>One last comment is when making a long song, autoscroll have some bugs (goes to end automatically, top bar is stands but patterns flow.).

Which version of Hydrogen are you using?

**Comment by trebmuh** [comment]
@AkKrock ping?

**Comment by AkKrock** [comment]
Amazing, thank you for detailed explanation.
For version, I used 1 and today I installed 1.0.1, will send you some details if I face a problem again.
Best Regards...
