### ISSUE TITLE
‘Set automatic velocity’ for layers works in reverse.

### ISSUE THREAD

**Issue by Bella-Roma** [hydrogen-music/hydrogen#841]
Hydrogen version *          : Hydrogen 0.9.7 & Hydrogen 1.0.0-Beta2
Operating system + version  : Linux Mint 19.3 MATE
Audio driver + version      : Behringer UMC202HD USB Audio Interface

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_I did not find another issue mentioning this, so hopefully it’s not a duplicate issue. The problem exists in both Hydrogen 0.9.7 and 1.0.0-Beta2. Unless I've totally missed something, I'm pretty sure this is a bug._

When working with multiple layers in a single instrument, choosing ‘**Set automatic velocity**’ in the load layer import window works in reverse of the intended way.

Typical ways of adding instruments layers would be loading layers from the top down, where layer 1 = lowest velocity range. 

In the image below, note that the 16th layer contains the 16th snare wav file (which is intended to be the loudest snare hit), but is auto-mapped to the lowest velocity range.

![hydro-problem](https://user-images.githubusercontent.com/60560450/79392831-e1af4180-7f28-11ea-85fc-70c1dad5c5c3.png)

The issue with setting automatic velocity happens whether using ctrl-click to select multiple layers to batch import into the instrument layers window, or when adding each layer individually.

Ideally, batch import of sound files into layers would be the preferred way, but this is unusable when selecting ‘set automatic velocity’ because of the reverse-order velocity mapping that occurs.

My solution, which works, but is not ideal, is loading files into each layer in reverse order. So, if you have 16 layers, layer 1 in the instrument layer window would actually be the 16th wav file, instead of the 1st, and likewise, layer 16 would be the 1st wav file.

In this 2nd image, which shows my ‘fix’ for this issue, notice that the 16th layer contains the 1st snare file (which is intended to be the softest snare hit). While the files are actually loaded in reverse, using ‘Set automatic velocity’  maps the velocity ranges correctly.

![hydro-solution](https://user-images.githubusercontent.com/60560450/79392879-f5f33e80-7f28-11ea-90f1-e459c671a51d.png)

Unfortunately, by using this method, you cannot batch import the files, since Hydrogen will load them the conventional way, where layer 1 = sound file 1, and so on. Since you cannot reverse sort the layers, you have to add each layer individually, backwards, where sound file 1 is loaded into the 16th layer first, and so on. Then when importing the final layer, choose ‘Set Automatic Velocity’.

**Comment by Naddiseo** [comment]
I think this bug is caused by the following in [InstrumentEditor.cpp](https://github.com/hydrogen-music/hydrogen/blob/8b200a460d026fb3f4b2fe651bb6962b460d3d9c/src/gui/src/InstrumentEditor/InstrumentEditor.cpp#L1003-L1012):
```c++
// around line 1003
	for ( int i = 0; i < InstrumentComponent::getMaxLayers() ; i++ ) {
		if ( layerInUse[i] == i ){
			nLayers--;
			auto pLayer = pCompo->get_layer( i );
			if ( pLayer ) {
				pLayer->set_start_velocity( nLayers * velocityrange);
				pLayer->set_end_velocity( nLayers * velocityrange + velocityrange );
			}
		}
	}
```

because the `i` and `nLayer` variables go in opposite directions, I think it reverses the layers causing this bug. I think it can be solved by either making `i` decrement from `getMaxLayers()` to `0`, or, by introducing a separate variable that increments from `0` to `nLayers`.

I tried doing this myself, but I couldn't build the project on my system to test it.

This was my solution if someone wants to test/try it:
```cpp
	for ( int i = 0, j = 0; i < InstrumentComponent::getMaxLayers(), j < nLayers ; i++ ) {
		if ( layerInUse[i] == i ){
			//nLayers--;
			j++;
			auto pLayer = pCompo->get_layer( i );
			if ( pLayer ) {
				pLayer->set_start_velocity( j * velocityrange);
				pLayer->set_end_velocity( j * velocityrange + velocityrange );
			}
		}
	}
```
