### ISSUE TITLE
Playback track: include wav files

### ISSUE THREAD

**Issue by sciurius** [hydrogen-music/hydrogen#842]
Hydrogen version *          :1.0.0-beta2
Operating system + version  : Fedora 31
Audio driver + version      : Pulse

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When selecting a playback track, the file selection dialog only shows .flac files. Since .wav files play equally well, the file selection dialog should include these are well.
Also, it is conventional to always include an "all files" option.

**Comment by mauser** [comment]
Hi,

this is already fixed in the master branch. We're now using the AudioFileBrowser Dialog for the playback track. This is the same dialog which can be used to pick samples for the layers of instruments, so it supports all file formats which can be usually used with Hydrogen.
