### ISSUE TITLE
[ feature request ] right click drag and delete

### ISSUE THREAD

**Issue by muziker** [hydrogen-music/hydrogen#848]
When recording into hydrogen using midi input, there are instances when the midi note is not aligned to the beat tempo, but dragging or deleting these notes can be difficult. If there was a box select tool to select multiple notes, they can be deleted easily or shifted. Also if right click to auto delete would help in the workflow

**Comment by cme** [comment]
A box selection tool / mode like in the Song Editor is something that I've often thought would be incredibly handy. If lockdown continues much longer I might have to implement one...

**Comment by cme** [comment]
Yeah, lockdown continued much longer 😆 

A wee work-in-progress demo:
[https://youtu.be/pvOC2J97Isw](url)

**Comment by cme** [comment]
Initial implementation of this is in #919 if anyone wants to give it a try.

**Comment by cme** [comment]
#919 is merged to master. Closing.
