### ISSUE TITLE
Instrument list: reverse velocity when clicking on instrument

### ISSUE THREAD

**Issue by elpescado** [hydrogen-music/hydrogen#851]
Hydrogen version *          : 1.0.0-beta2
Operating system + version  : n/a
Audio driver + version      : n/a

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Some time ago, I've made PR #360 that implemented sample playback witch variable velocity when clicking on instrument name. However I think I made one mistake - playback velocity is rising from left to right. As instrument names are left-aligned, clicking on instrument name produces faint pianissimo brush, whereas clicking on empty space on the right side produces loud blast. That should be reverse - most times users click on left side, where labels are placed, and expect somewhat louder sample playback.

I've just realised that it's last moment to change this. What do you think?

Currently:
![Zrzut ekranu 2020-04-26 o 20 23 02](https://user-images.githubusercontent.com/1619113/80316130-540f0400-87fc-11ea-887d-46d169e7cce8.png)

**Comment by trebmuh** [comment]
I find it good like it is.

**Comment by elpescado** [comment]
Like it's currently implemented?

**Comment by mauser** [comment]
It was quite natural to me that the left part is the most quiet part of the sample, so i never saw that as a problem. Of course it is not easy to understand the preview function at all, but i suppose that this wouldn't be better if it would be reversed. 

I suppose i often click on the right part of the label because it is nearer to the pattern editor, but i guess everyone has a different prefence there :)

**Comment by trebmuh** [comment]
@elpescado yes, the way it is now is fine for me.

**Comment by theGreatWhiteShark** [comment]
I also like the current implementation. Usually I click on the instrument name and am happy about the almost silent switch. Having a preview is nice but most of the time I just want to adjust the velocity of the particular notes while playing. Having a sample played on every switch would interfere with "proof-listening" the current patterns.

Maybe having a classic 🔉 symbol left of the mute button would advertise the feature properly. But on the other hand it would also litter the widget. Maybe just showing it while hovering?

**Comment by theGreatWhiteShark** [comment]
> yes, the way it is now is fine for me.

I think we all agree in here and it is by now a well-established feature
