### ISSUE TITLE
clipping on exportation

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#852]
Hydrogen version *          : 1.0.0 beta2
Operating system + version  : debian buster
Audio driver + version      : jack

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hi there.
I'm working on a song at the moment and when I'm exporting it as WAV, I've got an issue where is is clipping/saturating/... .
Then, I went to check around to see if my levels where OK and I'm wondering what is this: 
![hydrogen-red-master](https://user-images.githubusercontent.com/8705846/80390163-5c267c80-88ac-11ea-8ed8-fc6c9162b107.png)

I mean, what is this red _7035_ on the master level fader? When playing, it doesn't change at all, and stay at this _7035_ number even if the _2 columns lights_ of this track doesn't peak during the song.

Any idea what's going on there?

**Comment by mauser** [comment]
Hi,

can you reproduce the behavior?

**Comment by trebmuh** [comment]
Hi @mauser 

I've been experimenting on this on the last days and I'm not sure if the "clipping issue" is related to the "7035" issue.

I still need to perform tests on the "clipping" issue to narrow it and to try to make it understandable.

About the "7035" display, what I can tell is that when I'm opening Hydrogen, sometime the mixer shows this "7035" and sometimes not... and I can't find a reproducible way to activate it too... I'm very puzzled how to go further here about this 7035 thing.

I'll try more things and report here as soon as I can.

**Comment by trebmuh** [comment]
Probably closed with #880 .  I'll reopen if needed.
