### ISSUE TITLE
Handling of BPM marker

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#854]
Hydrogen version *          : master
Operating system + version  :  all
Audio driver + version      : all

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I noticed some odd behavior of the Timeline lately

1. When positioning playback before the first marker the BPM used when last changing the song will be used (whatever these were). This is already addressed in #416 and #433 
2. When deactivating the Timeline transport stays in the current BPM and does not fall back into the tempo set for the Song before introducing the BPM markers
3. Likewise, when removing all BPM markers the former tempo can not be recovered either.
~4. Sometimes there are glitches making Hydrogen changing the tempo back and forth. (e.g 255 -> 100 -> 255 ->100)~ -> moved to #864 
4. (formerly 5.) The buttons to increase and decrease BPM are still active but the new values will be overwritten in a second. I would, instead, disable them and add a tool tip how to activate them again.
~6. Changing tempo is handled by the GUI instead of the core (except for the Jack Audio driver - since at least 2008)~ -> moved to #865 

Do you also think 2. and 3. are unexpected behavior or is it just personal taste?

----

I do not really like the solution in #433 with a fixed marker at the beginning of the Timeline. Mainly because one can not remove it.

How about we keep track of the original tempo instead? In the core there are to variables, which do both keep track of the tempo and are always set to the same values: `pAudioDriver->m_transport.m_fBPM` and `pSong->__bpm`. How about we make the latter not dependent on the current transport position and use it to keep track of 1. ( and 2. , 3.)?

We could use the LCDSmallGreyFontSet to display both speeds as soon as the Timeline is activate 

![background_BPM_2](https://user-images.githubusercontent.com/14164547/80642023-0dbcdd80-8a66-11ea-9116-52a883a2bc16.png)

---

4. is a nasty one.

The `getTimelineBpm()` function does look up the current tempo on the Timeline based on the current `m_nSongPos` (the current pattern number). (Since the latter is not properly updated when moving the transport via mouse press we see things like #103). Then the tick size is rescaled in `audioEngine_process_checkBPMChange()` and the next `m_nSongPos` is determined in the end of the process cycle by among others a lookahead, which, again, is tempo-dependent. If the change in speed is to large, the pattern number (`m_nSongPos`) after the tempo change _smaller_ than beforehand. 

Not quite sure how to fix this yet. But I try to think about something.

**Comment by mauser** [comment]
Hi! 

First of all, could create separate ticket for (4) and also maybe (6) ? This is new to me, and it seems to be different from all other parts of this ticket.

>



> How about we keep track of the original tempo instead? In the core there are to variables, which do both keep track of the tempo and are always set to the same values: pAudioDriver->m_transport.m_fBPM and pSong->__bpm.How about we make the latter not dependent on the current transport position and use it to keep track of 1. ( and 2. , 3.)?

That sounds alright to me! I would also prefer it to the solution of the aforementioned pull request.

I'm unsure about the tempo display. Personally, i would think that this information is not needed if the timeline is activated. Displaying it would be maybe more confusing then helpful (for my use of Hydrogen, other people might other opinions on this).

**Comment by mauser** [comment]
One addition:  You mentioned on the mailing list, that this issue would be candidate for 1.0. Would it be ok for if we postpone it to 1.1, to allow a faster release of 1.0?

**Comment by theGreatWhiteShark** [comment]
> One addition: You mentioned on the mailing list, that this issue would be candidate for 1.0. Would it be ok for you if we postpone it to 1.1, to allow a faster release of 1.0?

Sure

> I'm unsure about the tempo display. Personally, i would think that this information is not needed if the timeline is activated. Displaying it would be maybe more confusing then helpful (for my use of Hydrogen, other people might other opinions on this).

Your right. Less is more and the manual will explain the details.

Okay. I will take care of 1,2,3 and 5

**Comment by theGreatWhiteShark** [comment]
Implemented in #1418
