### ISSUE TITLE
beta issues

### ISSUE THREAD

**Issue by felixdrum** [hydrogen-music/hydrogen#856]
Hydrogen version *          : beta version
Operating system + version  : windows 10 home
Audio driver + version      : realtek hight definition audio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
I downloaded the beta version of the hydrogen drum machine and I don't hear any drums sound

**Comment by mauser** [comment]
Hi!

do you more then one sound card (including USB headsets and similiar devices) attached to your PC? Have you tried to use a different drumkit (There should be two drumkits already shipped with Hydrogen).

**Comment by felixdrum** [comment]
hi.

at the moment I am using the sounds I found into hydrogen, but my friend
sent me some wav drums sounds so I wanted put them into hydrogen...this is
the problem because I can't do this.
I don't use others devices or usb pendrive.

massimo felice

Il mer 6 mag 2020, 21:28 Sebastian Moors <notifications@github.com> ha
scritto:

**Comment by theGreatWhiteShark** [comment]
Hey @felixdrum ,

Does this problem still occur in recent versions of Hydrogen?

**Comment by theGreatWhiteShark** [comment]
Closed due to inactivity. If the problem still occurs in a recent version of Hydrogen, please reopen the issue and I will take care of it.
