### ISSUE TITLE
Song Editor "Draw mode" does not "draw"

### ISSUE THREAD

**Issue by cme** [hydrogen-music/hydrogen#866]
Hydrogen version *          : master
Operating system + version  : All
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The Song Editor's "Draw" mode behaviour requires a distinct click for each set/clear of a pattern cell. The natural user expectation for a "Draw" mode, by parallel with drawing tools, would probably be that holding a button while moving should set/clear or alter the cells moved over.

A proposal for 'draw' mode behaviour:

  - pressing the mouse over a set cell, should set that *and any cells subsequently moved over until release*.
  - pressing the mouse over a clear cell should clear that cell *and any cells moved over until release*.

Similarly, to make 'select' mode mode useful as a general purpose editing mode, I'd propose that the behaviour in 'select' mode should be modified such that:

  - Clicking and releasing the mouse on a cell (without dragging) should toggle the cell as in 'draw' mode, cancelling any selection
  - Dragging the mouse continues to function as currently, starting a selection or moving/copying a selection

**Comment by trebmuh** [comment]
> The natural user expectation for a "Draw" mode, by parallel with drawing tools, would probably be that holding a button while moving should set/clear or alter the cells moved over.

Agreed.

> A proposal for 'draw' mode behaviour:
> * pressing the mouse over a set cell, should set that and any cells subsequently moved over until release.
> * pressing the mouse over a clear cell should clear that cell and any cells moved over until release.

Agreed.

> Similarly, to make 'select' mode mode useful as a general purpose editing mode, I'd propose that the behaviour in 'select' mode should be modified such that:
> * Clicking and releasing the mouse on a cell (without dragging) should toggle the cell as in 'draw' mode, cancelling any selection
> * Dragging the mouse continues to function as currently, starting a selection or moving/copying a selection

Agreed + another user expectation: clicking on a cell is selecting this cell, holding Ctrl + clicking another cell should add this other cell to the selection. I'm finding myself trying that regularly since years... :smile:

**Comment by cme** [comment]
> > * Dragging the mouse continues to function as currently, starting a selection or moving/copying a selection
> 
> Agreed + another user expectation: clicking on a cell is selecting this cell, holding Ctrl + clicking another cell should add this other cell to the selection. I'm finding myself trying that regularly since years... 😄

Agreed, that's almost certainly a reasonable user expectation. 

I'll probably go ahead and implement this in the next couple of days, probably on top of https://github.com/hydrogen-music/hydrogen/pull/847 because it involves a little refactoring that's already on that branch.

**Comment by trebmuh** [comment]
Let me know when done. I want to try that.

**Comment by cme** [comment]
> Let me know when done. I want to try that.

I've added this to:
  https://github.com/cme/hydrogen/commits/cursor_key_editing/

Ctrl+click (Cmd+click on macOS) for modifying selection is a bit of a pain as drags are started immediately so this could be separated a bit more cleanly.

Also, starting a move and returning to the original location is currently interpreted as a click, which is a pain, I'll fix that. Apart from that, behaviour-wise, it feels pretty good to me so far. I'd be grateful for any feedback! :)

**Comment by trebmuh** [comment]
@cme : where is your branch then I can build and test?

**Comment by cme** [comment]
@trebmuh : As linked above, https://github.com/cme/hydrogen/ on the branch "cursor_key_editing"
Also referenced from the pull request https://github.com/hydrogen-music/hydrogen/pull/847

**Comment by cme** [comment]
Updated to split out drag detection from the press/move/release logic, so now clicking should feel cleaner and doesn't start a momentary transient move/selection on clicking in Select mode.

**Comment by cme** [comment]
#847 incorporates this behaviour and has been merged to master.
