### ISSUE TITLE
Pattern window scrolling unexpectedly when clicking on patterns in middle of area

### ISSUE THREAD

**Issue by Biscuit-Trolley** [hydrogen-music/hydrogen#874]
Hydrogen version *          : 1.0.0-beta2
Operating system + version  : Ubuntu Studio 20.04
Audio driver + version      :  Jack 1.9.12 (Not sure if this is what's being asked for here, but it's a GUI thing so shouldn't be relevant...?)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
When I select a pattern, the vertical scroll immediately repositions the scrollbar such that the pattern I've selected is at the top of the area. E.g. with the default 10 patterns, if I am editing Pattern 1, and click on Pattern 4, it will immediately scroll down to put Pattern 4 at the top (if it can scroll down that far, otherwise it will just scroll down to the bottom of the range). It often does this so quickly that I have not yet let go of the mouse button, causing the pattern I've clicked on to be repositioned. The same thing happens if I have a Pattern further down selected and click on one nearer the top, but scrolling upwards instead.

This was not happening before I upgraded to 20.04, although I can't remember which version I was running before on 19.10.
Let me know if there's anything useful I've neglected to mention.

Thanks!

**Comment by cme** [comment]
This behaviour was part of the fix for issue #584. This scrolls a newly selected (or inserted) pattern directly to the top of the window. It would be better to use ScrollArea::ensureVisible as this would avoid scrolling when the newly selected pattern is already in view.

**Comment by cme** [comment]
Submitted pull request #875 to fix this.

**Comment by mauser** [comment]
Hi! 

This issue is now solved in the master branch. Thanks a lot, @cme!

**Comment by cme** [comment]
> This issue is now solved in the master branch. Thanks a lot, @cme!

Nae bother :)

**Comment by Biscuit-Trolley** [comment]
Hey folks, new to both Linux and Github, so apologies for my ignorance. Can I implement this solution on my system, and if so, how do I do so?

**Comment by trebmuh** [comment]
Just wait for the next beta3 version.

**Comment by Biscuit-Trolley** [comment]
Right, thanks!
