### ISSUE TITLE
Unintuitive behavior of audio driver restart via Preferences > Audio System 

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#883]
Right now all changes applied in the Options > Preferences windows will be saved in the `Preferences` singleton the moment the user hits the 'OK' button.

As a consequence all changes applied to the audio driver settings will _not_ be considered when pressing the 'Restart output' button until the whole dialog gets closed and opened again.

I don't know much about Qt but there is most probably a way to make the 'Restart output' button evaluating the provided forms.

Drawback (also in the current implementation): it's easily possible to have a set of parameter not reflecting the one used to start the driver. Maybe there could a 'Restart output and close' button instead, which won't close the dialog if the restart of the audio driver fails.

**Comment by cme** [comment]
The layout is also confusing, with the drop-down on the left and the 'Restart' button to its left. Is there a *current* use-case for the "Restart..." independently of applying new settings?

The "OK" button currently asks the user to restart if necessary. The behaviour you suggest for "Restart output and close" is pretty close to what the "OK" button already does if there has been a setting change that needs a restart, and the not-closing-the-dialog behaviour is close to a regular "Apply" button.

Would it perhaps be fairly close to user expectation to:
  - Get rid of the 'Restart' button
  - Add an 'Apply' button which behaves the same as the OK button but doesn't close the dialog. 

So the user's tweak-test-retweak cycle would look like:
  - set audio settings
  - hit 'apply'
  - hit "OK" to restart
  - Go back to fix settings if that fails

There are perhaps a few more steps in that than necessary, but they're at least fairly intuitive and well-guided and well-established in other GUIs. It also makes it clear when settings are saved.

If allowing the user to restart the sound system without making any settings changes, perhaps a button at the bottom with behaviour closer to "cancel and restart" might be appropriate? Or a "Force restart" checkbox.

The GUI code looks straightforward enough to refactor.

**Comment by cme** [comment]
(Also, this has annoyed me very recently. And I guess I'm volunteering to take it on... :D )

**Comment by theGreatWhiteShark** [comment]
> Is there a current use-case for the "Restart..." independently of applying new settings?

Jupp. With the JACK server Hydrogen does exclusively use the sample rate and buffer size provided by the server. If you want to tweak these settings, you have to do it in the server and restart the driver in H2 later on.

> if there has been a setting change that needs a restart

This is another thing that needs to be revisited. I totally forgot about this option because there is no dialog prompting when changing the sample rate of the Pulseaudio driver (certainly a thing that requires restart).

While we are at it; an open question: do we need a "Restore Defaults" button? from a Linux perspective I would be -1 since there is still the system wide config file. But maybe things are different with macOS/Windows and their users.

**Comment by cme** [comment]
> > Is there a current use-case for the "Restart..." independently of applying new settings?
> Jupp. With the JACK server Hydrogen does exclusively use the sample rate and buffer size provided by the server. If you want to tweak these settings, you have to do it in the server and restart the driver in H2 later on.

Ah, I see. It feels like the Preferences dialog is not the right place for that, then? It's not a preference, as such, and indeed doesn't need any changes. So perhaps belongs elsewhere, maybe as a menu action? 

> > if there has been a setting change that needs a restart
> 
> This is another thing that needs to be revisited. I totally forgot about this option because there is no dialog prompting when changing the sample rate of the Pulseaudio driver (certainly a thing that requires restart).

Yeah, that's due to what looks like a spurious change, pull request #882 fixes it.

**Comment by cme** [comment]
@theGreatWhiteShark first pass at improved behaviour: #893 applies any new settings changes before restarting the driver.

**Comment by theGreatWhiteShark** [comment]
> Would it be possible to restart the audio driver automatically (possibly with an interruption and some minimal user intervention or acknowledgement) when the server restarts? It's already detected by the driver and raises an error, perhaps it should handle this differently by presenting a dialog with option to restart?

Hmm. In principle we could wrap the `jack_client_open` API call in a for loop + try-catch try to restart the Jack driver every X seconds as soon as the connection to the Jack server is lost and the Jack is selected via the Preference.

I'm not quite sure if this is something wanted/expected by the users. Most Jack applications are plain stupid and usually restarting the server requires (at least in my case) to close and reopen all associated applications. Plus, I don't think tweaking Jack settings is something that is done frequently. But on the other hand some applications might freeze frequently and the user might be annoyed by having to start the audio driver over and over again. No idea if there is an actual need

**Comment by theGreatWhiteShark** [comment]
I'm not sure about a general `Apply` button. One of the most reasonable use cases for it would be to tweak the appearance but for font and color a restart of the application is required. (I'm amazed how little of the font does get actually changed. AFAICS just the one in the splash window and the names of the patterns in the song editor). I think #893 does already does the job.

**Comment by cme** [comment]
Closed with #893 !
