### ISSUE TITLE
Pulseaudio oddities

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#884]
Hydrogen version *          : d29d9e0b9e81c5bca5e04100e5e86c227ad58b06
Operating system + version  :  Ubuntu 20.04
Audio driver + version      :  Pulseaudio 13.99.1

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I just tried the Pulseaudio driver and found it is not working properly on my machine.

1. When using it in combination with the JACK server (via `module-jack-sink`), it only produces the expected output when both sample rate and buffer size match the ones of the JACK server. If this is a general thing, why not provide and fix these values for the users (apart from the additional complexity)?

2. When using it standalone, it floods the log with messages like 

```
[...]
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 760, new size = 756
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 756, new size = 268
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 268, new size = 487
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 487, new size = 537
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 537, new size = 218
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 218, new size = 269
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 269, new size = 486
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 486, new size = 538
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 538, new size = 217
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 217, new size = 761
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 761, new size = 755
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 755, new size = 269
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 269, new size = 486
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 486, new size = 538
(I) ::int H2Core::audioEngine_process(uint32_t, void*) Buffer size changed. Old size = 538, new size = 218
[...]
```
and the audio never sounds (regardless of buffer size and sample rate) as it should.

Is this just my machine or can you reproduce this issue?

**Comment by cme** [comment]
I think issue 2) is just the sort of behaviour that should be expected from PulseAudio, and we should adjust the logging appropriately.

I note that the return value from `pa_stream_connect_playback` is never checked in PulseAudioDriver.cpp, and it's documented as being able to return non-zero for error, so I guess that may be silently happening in issue 1), though it's not clear to me at the moment what the right thing to do would be (just report? Can PulseAudio provide info on the requirements for a stream that *can* be connected to the device?)

**Comment by theGreatWhiteShark** [comment]
> I note that the return value from pa_stream_connect_playback is never checked in PulseAudioDriver.cpp, and it's documented as being able to return non-zero for error, so I guess that may be silently happening in issue 1), though it's not clear to me at the moment what the right thing to do would be (just report? Can PulseAudio provide info on the requirements for a stream that can be connected to the device?)

Puh. I dont' know. Since nearly all Linux audio folks try to avoid PulseAudio and use JACK instead, I did the same and used a combination of both at most. But as it is the default audio driver for many Linux systems and the goto when doing network audio, like bluetooth, I think we should put it on the long list for things to fix/check before 1.2.

**Comment by cme** [comment]
Looks like there is an interface to get default stream format, so probably the right thing to do is to attempt to set the stream from the Hydrogen user preferences, and if that fails, query the PulseAudio default and set Hydrogen's parameters to that.

**Comment by theGreatWhiteShark** [comment]
> When using it in combination with the JACK server (via module-jack-sink), it only produces the expected output when both sample rate and buffer size match the ones of the JACK server. If this is a general thing, why not provide and fix these values for the users (apart from the additional complexity)?

I just reviewed the code and checked using PulseAudio without JACK and everything works as expected. This is most likely just an actefact due to my setup and nothing related to Hydrogen itself.
