### ISSUE TITLE
Edit server list dialog does not have button to close the dialog

### ISSUE THREAD

**Issue by Porrumentzio** [hydrogen-music/hydrogen#886]
Hydrogen version *          : 1.0.0-beta2
Operating system + version  : 5.4.40-1-Manjaro MATE 20.0.1, Arch based 
Audio driver + version      : snd_hda_intel

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Edit server list** dialog, `Drumkits > Online import > Edit server list`, does **not** have button to close the dialog, neither way to go back and use Hydrogen. The only way is to close the dialog/window with the system's window manager.

Please add button to close the dialog.

![irudia](https://user-images.githubusercontent.com/61913683/83123106-daa55280-a0d4-11ea-8857-549321813e48.png)

**Comment by mauser** [comment]
Hi,

this issue is now fixed, there is now a "close" button at the bottom of the dialog.
