### ISSUE TITLE
Make zoom buttons more evident and visibles putting them alongside grid and those other controls

### ISSUE THREAD

**Issue by Porrumentzio** [hydrogen-music/hydrogen#888]
Hydrogen version * : 1.0.0-beta2
Operating system + version : 5.4.40-1-Manjaro MATE 20.0.1, Arch based
Audio driver + version : snd_hda_intel

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The zoom buttons, on the right down side of the grid-area, are not too evident and visible. Even less on HiDPI displays.

Putting them alongside Grid and Hear-Quantize-Input controls could make them easier to see. Just to the right side of them:
![irudia](https://user-images.githubusercontent.com/61913683/83126791-9ec0bc00-a0d9-11ea-9629-cbf44ea4d4a4.png)

**Comment by theGreatWhiteShark** [comment]
> The zoom buttons, on the right down side of the grid-area, are not too evident and visible

A new version of the buttons - which have been slightly enlarged - will be available in version 1.2 of Hydrogen.

But in general I do not like the idea. There is not really a standard and whether or not to expect those buttons at the bottom right and when starting with a new and fresh application your suggestion might be a better choice. However, there are lots of established users who will scratch their head in finding those buttons are first. Plus, there is no nice equivalent for the song editor.

I will close this one for now but please feel free to reopen it. The matter is of course up for discussion.

> Even less on HiDPI displays.

There has been a lot done in terms of scaling. This should also make these buttons more pronounced.
