### ISSUE TITLE
Can't launch last version on ubuntu 18.04

### ISSUE THREAD

**Issue by moonshaadow** [hydrogen-music/hydrogen#894]
Hydrogen version *          : git: aee720e7a3a7e74a5e0e7de0b0831de38322ed22
Operating system + version  : ubuntu studio 18.04
Audio driver + version      : JACK2

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

```
hydrogen: error while loading shared libraries: libhydrogen-core-1.0.0.so: cannot open shared object file: No such file or directory

```

Successfully built from git, following install.md, no dependencies missing, successfully installed.

**Comment by cme** [comment]
Have you tried adding the installation path to `LD_LIBRARY_PATH` as suggested in install.md? 

> ### Running Hydrogen
> 
> After installation, Hydrogen's binaries can be found in CMAKE_INSTALL_PREFIX/bin.
> If this path is not in your PATH environment variable, consider adding it to it
> 
> If Hydrogen doesn't start, it might be because it's shared library is not found.
> You can verify this with the above command :
> ```ldd CMAKE_INSTALL_PREFIX/bin/hydrogen | grep 'not found'```
> 
> To fix this, you can use LD_PRELOAD or LD_LIBRARY_PATH environment variables,
> or configure ldconfig (man ldconfig).
> 
> Another option is to set -DCMAKE_INSTALL_PREFIX=/usr, recompile and reinstall Hydrogen.
> But be aware that you will certainly overwrite Hydrogen files that you might have
> installed with your distribution's package manager.

Alternatively using the `build.sh` helper is useful:

> `./build.sh m && ./hydrogen`

**Comment by moonshaadow** [comment]
Hi.
After restarting the system, all is fine and Hydrogen starts as it should.
