### ISSUE TITLE
Build-fix for Qt 5.15

### ISSUE THREAD

**Issue by adriaandegroot** [hydrogen-music/hydrogen#895]
This patch applies to -beta1, but the important bit -- explicit cast to `QScreen*` because Qt 5.15 introduces an ambiguous constructor for QSplashScreen -- is the same in master.

```
+--- src/gui/src/SplashScreen.cpp.orig  2020-06-03 21:33:30 UTC
++++ src/gui/src/SplashScreen.cpp
+@@ -32,7 +32,7 @@
+ const char* SplashScreen::__class_name = "SplashScreen";
+ 
+ SplashScreen::SplashScreen()
+- : QSplashScreen( NULL )
++ : QSplashScreen( (QScreen*)nullptr )
+  , Object( __class_name )
+ {
+       //INFOLOG( "SplashScreen" );
```

(Applied in FreeBSD packaging of hydrogen)

**Comment by adriaandegroot** [comment]
(sorry .. this **doesn't** compile against Qt 5.14 .. the cast needs to be to `QWidget*`, rather than `QScreen*`. The docs don't really point out which pointer-taking constructor has been deprecated)

**Comment by plater** [comment]
Can confirm that this fixes master as well, QSplashScreen( NULL ) changes to QSplashScreen( nullptr )

**Comment by jeremyz** [comment]
thanks !!
