### ISSUE TITLE
Error building DEB package

### ISSUE THREAD

**Issue by antonio-petricca** [hydrogen-music/hydrogen#913]
Hydrogen version *          : 4b8d6b279411bc33c3fcc0350cb1f3bf7a239802
Operating system + version  : Linux Mint 19,3 (Ubuntu 18.04)
Audio driver + version      : N/A

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I am tryng to build the DEB package, but I get the following error:

```
dpkg-deb: building package 'hydrogen' in '../hydrogen_1.0.0_amd64.deb'.
dpkg-deb: building package 'hydrogen-dbgsym' in 'debian/.debhelper/scratch-space/build-hydrogen/hydrogen-dbgsym_1.0.0_amd64.deb'.
	Renaming hydrogen-dbgsym_1.0.0_amd64.deb to hydrogen-dbgsym_1.0.0_amd64.ddeb
 dpkg-genbuildinfo
 dpkg-genchanges  >../hydrogen_1.0.0_amd64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build linux
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
 signfile hydrogen_1.0.0.dsc
gpg: skipped "Alessandro Cominu <comix@users.sf.net>": No secret key
gpg: dpkg-sign.q8N3B8Y6/hydrogen_1.0.0.dsc: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .dsc file
```

**Comment by mauser** [comment]
Hi! 

you can use `dpkg-buildpackage -rfakeroot -b -uc -us` to create an unsigned package.

**Comment by antonio-petricca** [comment]
Thank you, it works, but with a little change:

`dpkg-buildpackage -rfakeroot -b -uc -us -d`
