### ISSUE TITLE
Hydrogen 1.0.0 is built with debug on

### ISSUE THREAD

**Issue by elpescado** [hydrogen-music/hydrogen#915]
Hydrogen version *          : 1.0.0
Operating system + version  : macOS / maybe others?
Audio driver + version      : n/a

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hydrogen 1.0.0 is built with debug on, so that "Development version" popup is shown upon startup and "Debug" menu is present. Tested on macOS `Hydrogen.dmg` build, not sure whether it affects other platforms.

<img width="589" alt="Screenshot 2020-08-05 at 09 55 22" src="https://user-images.githubusercontent.com/1619113/89386993-293d2180-d702-11ea-946c-e3f434bb5eaf.png">

**Comment by dvzrv** [comment]
I have built 1.0.0 as a package for Arch Linux and experience the same although I have built with `CMAKE_BUILD_TYPE=None` and `WANT_DEBUG=OFF`.
This should definitely not be in debug

**Comment by dvzrv** [comment]
The build log also clearly stated: `* debug capabilities           : FALSE` and the option `QT_NO_DEBUG` is present.

**Comment by mauser** [comment]
Hi,

the popup is not directly related to a build in Debug mode. Have a look at 4b8d6b279411bc33c3fcc0350cb1f3bf7a239802, in this commit i've deactivated the debug mode. The problem with the Mac OS X binaries is that those are directly attached from Travis to the Release. At the time when i've build 4b8d6b279411bc33c3fcc0350cb1f3bf7a239802 with travis, there already have been dmg images for the release. It seems that travis does not overwrite them.  @dvzrv : Can you check which version you have build? 

Regarding the debug menu: This is also not related to the debug mode, but to the log level of Hydrogen. It seems that this only goes away if you use Log level "none", which is *not* the default.

**Comment by dvzrv** [comment]
@mauser  I built 1.0.0 from the tarball.

**Comment by mauser** [comment]
@dvzrv : Ah, ok. The tarball is also automatically generated by GitHub, so it might be the same issue as with the MacOS X binaries. I will see if i can re-generate those artifacts later.

**Comment by dvzrv** [comment]
@mauser  the source tarball is automatically generated on tag. I used [this one](https://github.com/hydrogen-music/hydrogen/archive/1.0.0.tar.gz). The binaries are built by CI I assume. Whatever you do, please do not retag and by that change the source tarball! :)

Do I get this right that I have to patch whatever is set in https://github.com/hydrogen-music/hydrogen/commit/4b8d6b279411bc33c3fcc0350cb1f3bf7a239802 manually on every package build?

**Comment by mauser** [comment]
There is now a 1.0.1 release which fixes this problem, so no patches will be needed. The "debug" menu will be still there, but that does not mean that the binaries will be build in debug mode.
