### ISSUE TITLE
HiDPI issues on multiple monitors with mixed DPI

### ISSUE THREAD

**Issue by elpescado** [hydrogen-music/hydrogen#916]
Hydrogen version *          : 1.0.0
Operating system + version  : macOS 10.14.6
Audio driver + version      : n/a

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I've noticed some UI glitches related to HiDPI scaling:

Timeline:
![Screenshot 2020-08-05 at 10 01 16](https://user-images.githubusercontent.com/1619113/89387578-fc3d3e80-d702-11ea-8029-c349d777dfb4.png)

Pattern list:
<img width="1262" alt="Screenshot 2020-08-05 at 10 01 29" src="https://user-images.githubusercontent.com/1619113/89387592-0101f280-d703-11ea-983d-57fce3b5c5da.png">

I'm using MacBook Pro with retina screen (set to "looks like like 1280x800") and standard DPI external monitor (1920x1200). Those glitches sometimes appear when window is opened, sometimes they appear when window is moved between screens, sometimes they disappear then, and usually user interaction (eg. selecting a pattern on pattern list) makes problem go away.

I do acknowledge that my setup might be a bit unusual. I'll try to look into this issue.

**Comment by theGreatWhiteShark** [comment]
Hey @elpescado ,

 Could you check whether this bug still occurs in the refreshed UI (on master)?

**Comment by cme** [comment]
This still seems to be an issue. With Hydrogen on my external (low DPI) monitor the timeline is double sized. Dragging it to my laptop monitor (hidpi) the timeline is correct but the pattern list half-size.

**Comment by cme** [comment]
I have fixes for these issues, I'l take a look for any other similar ones.
