### ISSUE TITLE
jack-session has been marked as deprecated

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#918]
See: https://jackaudio.org/news/2020/07/16/jack-session-has-been-marked-as-deprecated.html

Not being a coder, I don't know what that implies for Hydrogen. NSM support is already there. Maybe Hydrogen should drop jack-session support?

**Comment by mauser** [comment]
Ah, that "New Session Management" discussion :) Yes, i suppose we can drop support for jack-session then.

**Comment by theGreatWhiteShark** [comment]
I would suggest to just remove the support during compilation by disabling the `H2CORE_HAVE_JACKSESSION` flag. If no one complains, we can drop the code in a couple of releases.

> NSM support is already there

Well, it's still too rough around the edges to really use Hydrogen with NSM. The new fork (so glad this did happen!) does probably uses `JACKPatch` as well. This will prevent all wiring of the per-instrument JACK ports of H2 to persist between sessions. In addition H2 is not fully compliant with the API yet. But most of those things are already done in  #792 and I will soon start with the finishing touches ;)

**Comment by trebmuh** [comment]
Sounds clever.
