### ISSUE TITLE
localised tutorials and manuals

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#923]
Hydrogen version *          : 1.0.0
Operating system + version  : LibraZiK-3
Audio driver + version      : all

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

While working on the 1.0.0 packaging for LibraZiK-3, I had to add a line for the embedded manuals and tutorials to be compiled.
Something like that: `cd data/doc && make`
Without doing it, only the English version was available.

It could be great if that was included in the basic build system.

**Comment by theGreatWhiteShark** [comment]
Hey @trebmuh ,

I'm not that familiar with the building process. But the `build.sh` features an option `p[kg]`. Wouldn't this be a more appropriate place for the command to go? On the other hand neither the `INSTALL.md` nor the `DEVELOPERS` file does mention this command.

**Comment by trebmuh** [comment]
I don't know, I'm not using the `build.sh` script.
@mauser any input on this?

**Comment by theGreatWhiteShark** [comment]
This is already present in the toolchain and should work as expected. Unfortunately, since the overhaul of the manual there translations left with a decent coverage.
