### ISSUE TITLE
Issue with Program Change Commands in MIDI configuration

### ISSUE THREAD

**Issue by PietS33** [hydrogen-music/hydrogen#924]
Hydrogen version *          :1.0.0 Aug 3 2020
Operating system + version  : Windows 10
Audio driver + version      : Focusrite Scarlet 4i4 USB, 4.65.5.658, 02.06.2020

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hello,

Thank you very much for this software, its conception meets exactly, what I was always missing
at my (lots of…) previous (soft- and hardware) drum machines!

But while configuring the MIDI controls I found an issue with the Program Change commands:
Hydrogen does not recognize the different Program Change numbers, neither recorded, nor set
manually.
The parameter field seems to accept different values, but returns always to "0", when saved.
And the related action is always executed, no matter which PC-command has been sent.

Furthermore, once entered and saved, I cannot get rid of the ProgramChange-event in the
preferences, I can modify the action, but not delete.

And when I modify the event field, a new line with the same action is created, and the old one
with the PC-Event is persisting.

And emptying the event and/or action fields makes simply nothing.

Seems that all other events are handled as awaited, I hope that this is not only caused by
a stupid mistake from my side, (even if you had maybe less work then ;-)

Parameter set, not yet saved:
![01 param set not saved](https://user-images.githubusercontent.com/46959638/90272416-ae8ca880-de5d-11ea-9ec2-eac551113c40.jpg)

Parameter after saving:
![02 param after saving](https://user-images.githubusercontent.com/46959638/90272550-dd0a8380-de5d-11ea-92e2-502d24a79ab7.jpg)

Event type modified, not yet saved:
![03 event type modified not saved](https://user-images.githubusercontent.com/46959638/90272572-e4319180-de5d-11ea-9099-f5555997f3c0.jpg)

Result after saving:
![04 modification after saving](https://user-images.githubusercontent.com/46959638/90272686-02978d00-de5e-11ea-9914-73d95fd75d96.jpg)

Thx another time for your help,
best regards,

P.

**Comment by mauser** [comment]
Hi Piet! 

confirmed: sth. went wrong with the deletion of rows if "PROGRAM_CHANGE" actions are involved. I've fixed this issue now. 
Btw., if you want to have a fixed version, you could try out an experimental Windows installer for this version(based on Hydrogen 1.1) which can be found [here](https://ci.appveyor.com/project/mauser/hydrogen/builds/34870127/job/uiukxv4g2an3my8p/artifacts). Apart from that, the bugfix will be present in the next patch release of 1.0 (which should be out soon as well..). 

In addition, it would really make sense to have a better way to delete a line in the midi table, for example by having simple delete but for each row :)

About the program change behavior: I guess this is intended. A program change message has just one parameter, so i guess that one parameter is taken as an argument for the corresponding action. So you cannot say "please trigger play if PC 16 is triggered", but you could express "please trigger song 16 of the playlist when PC message is received" (by using action "PLAYLIST_SONG" for example).
