### ISSUE TITLE
Song Editor "Select mode": Ctrl+click behavior

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#925]
Hydrogen version *          : 1.0.0
Operating system + version  : LZK-3 (Debian Buster based)
Audio driver + version      : any

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Following #866.

User expectation: clicking on a cell is selecting this cell, holding Ctrl + clicking another cell should add this other cell to the selection. I'm finding myself trying that regularly since years... :smile:

Pinging Colin: @cme here. I've been side-tracker by other stuff, and I'm a bit lost here. Is the Ctrl+click behaviour supposed to be working in 1.0.0? If so, it doesn't here... :/

**Comment by cme** [comment]
Sorry, no. The main force behind 1.0 in the last few months was stabilisation rather than new features. This will be in 1.1, which hopefully won't take nearly as long as 1.0 did... ;)

**Comment by cme** [comment]
On master
