### ISSUE TITLE
Build fails using libtar

### ISSUE THREAD

**Issue by sambler** [hydrogen-music/hydrogen#928]
Hydrogen version *          : 1.0.0
Operating system + version  : FreeBSD 12
Audio driver + version      : oss

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Setting WANT_LIBARCHIVE=off to build using libtar fails.

I am using libtar v1.2.11 and clang v9.0.1

The error is 
```
/tmp/workdir/hydrogen-1.0.0/src/gui/src/SoundLibrary/SoundLibraryExportDialog.cpp:216:5: 
error: use of undeclared identifier 'TmpFileCreated'
        if(TmpFileCreated)
           ^
1 error generated.

```

I am unable to find a definition or use for `TmpFileCreated` anywhere other than that one line in [`SoundLibraryExportDialog.cpp` line 216](https://github.com/hydrogen-music/hydrogen/blob/master/src/gui/src/SoundLibrary/SoundLibraryExportDialog.cpp#L216).

It would appear that the definition was removed in db36fb93b0e4

**Comment by mauser** [comment]
Oops, my fault :) Should be fixed now in the master branch as well as the 1.0.0 branch.

**Comment by elpescado** [comment]
Maybe we should add this configuration to CI?

**Comment by sambler** [comment]
Fix looks good to me.

My question would be, do you really need to support two archive libraries? libarchive is preferred, why not make it the only compression option?

If you keep two options, I would add it to CI.

**Comment by elpescado** [comment]
libtar removal [was discussed before](https://github.com/hydrogen-music/hydrogen/pull/502#issuecomment-301678997).

**Comment by mauser** [comment]
Hi, 

about CI: This is the first bug concerning compilation libtar that i'm aware of. In my opinion it would be a little bit too much to build a libtar-build with every commit. And if we would handle libtar this way, there would be also build with ladspa on/off, liblo on/off and so on. Maybe we could introduce a special branch which has a special travis configuration with a lot of those cmake switches turned on/off?
