### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by suyashjoshi** [hydrogen-music/hydrogen#934]
Hydrogen version *          : 1.0
Operating system + version  : macOS Catalina version 10.15.6
Audio driver + version      : Not sure

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hi,

I'm taking Electronic Music Class where our instructor wants us to use this software. I'm not sure if I can own the music I create using Hydrogen as it's a GPL v2 licensed tool. Do I need to open source my music too or not if I plan on commercializing it?

Thanks,
Suyash

**Comment by mauser** [comment]
Hello Suyash,

the license relates only to the source code. You can do anything you want with the music which you've created with Hydrogen.
Enjoy using Hydrogen!

**Comment by suyashjoshi** [comment]
Thanks for clarifying and good to know this as at work we are told to stay away from GPL code as far as we can :)
