### ISSUE TITLE
Ladspa on Vers 1.0.1 for Windows both 64 bit and 32 bit

### ISSUE THREAD

**Issue by YungPhil** [hydrogen-music/hydrogen#938]
Hydrogen version *          :1.0.1
Operating system + version  : Windows 7  - 64 bit and 32 bit
Audio driver + version      : Port Audio

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hi -  I was using Vers 1 and Ladspa Plugins worked certainly on the 64 bit version. I seem to remember my 32 bit computer was also OK with them. I upgraded to 1.0.1 yesterday and it appears the FX function is disabled. No FX showing in mixer and when you try to load a Plugin through edit it says Ladspa Plugins are not available with this version. Have you dropped FX from 1.0.1 for Wndows 7? I had experimented with using them on Vers 1.  Regards Phil

**Comment by trebmuh** [comment]
_(quickly to mention that it looks to be OK for the linux version)_

**Comment by mauser** [comment]
Thanks for the report, i will provide updated installers for windows soon.

**Comment by YungPhil** [comment]
Thanks Sebastian - also if you know of any reverb LADSPA 64 bit plugins 
I would be interested to know where to find them.

Kind regards Phil

------ Original Message ------

**Comment by mauser** [comment]
@YungPhil : The binaries of the GitHub release are now updated, you can try again :)

**Comment by mauser** [comment]
About the reverb recommendation: To be honest, i'm using no plugins with Hydrogen on Windows, so can't make any recommendation there. I'm sorry!

**Comment by trebmuh** [comment]
I'm not using Windows but you might be able to find some LADSPA plugins and info about how to install them on the [audacity wiki page about LADSPA plugins](https://manual.audacityteam.org/man/installing_effect_generator_and_analyzer_plug_ins_on_linux.html#ladspa_install).

**Comment by YungPhil** [comment]
Thanks again
Phil

------ Original Message ------

**Comment by YungPhil** [comment]
No problem - will  keep looking but not over concerned because I often 
export into Audacity and add effects there. I keep recommending Hydrogen 
to other users - best drum machine/sequencer I have found.

Kind regards Phil

------ Original Message ------

**Comment by YungPhil** [comment]
Thanks - if I really get stuck I might use the 32 bit version instead.

------ Original Message ------

**Comment by YungPhil** [comment]
Thanks and all working.
one other query in thr Windows version 1.0.1 Main Menu  - Instruments is 
a tab Add Component. I can't find a reference in the manual for this nor 
online. Does it have a function in the Windows version and if so what is 
a 'Component'

Regards Phil

------ Original Message ------

**Comment by trebmuh** [comment]
The manual isn't up-to-date. Please open another issue.
