### ISSUE TITLE
Hang when trying to invoke rubberband cli, if path is set to a directory

### ISSUE THREAD

**Issue by cannam** [hydrogen-music/hydrogen#939]
Tested with current Hydrogen from git (f1abe238eb) on Linux, and the official 1.0.1 on Windows.

Steps to reproduce:

 * Start Hydrogen, go to preferences
 * Edit "Path to the Rubberband command-line utility" so as to contain the path of any directory on the system (e.g. `/tmp` would do) and hit OK
 * Go to sample editor, choose a new length, click Apply Changes

Observed behaviour:

 * Hydrogen hangs completely when the Apply Changes button is pressed

Expected behaviour:

 * The attempt to set this preference to a directory path is refused, and/or
 * The sample editor gracefully handles the invalid path

This came to my attention because a user on Windows, on being asked to enter the Rubber Band CLI path, had (not unreasonably) pasted in the folder path for the Rubber Band installation rather than the executable path. They then thought Rubber Band itself was hanging, and wrote to me for help.

There are two problems in the code that combine to cause this. One is that the prefs code is checking whether the CLI path exists, but not whether it is a file. Here is one possible fix:
```
diff --git a/src/core/src/preferences.cpp b/src/core/src/preferences.cpp
index e9eee665..215dddd3 100644
--- a/src/core/src/preferences.cpp
+++ b/src/core/src/preferences.cpp
@@ -721,7 +721,10 @@ void Preferences::savePreferences()
        LocalFileMng::writeXmlString( rootNode, "quantizeEvents", quantizeEvents ? "true": "false" );
 
        //extern executables
-       if ( QFile( m_rubberBandCLIexecutable ).exists() == false ) {
+        QFileInfo cliFileInfo( m_rubberBandCLIexecutable );
+       if ( !cliFileInfo.exists() ||
+             !cliFileInfo.isFile() ||
+             !cliFileInfo.isExecutable() ) {
                m_rubberBandCLIexecutable = "Path to Rubberband-CLI";
        }
        LocalFileMng::writeXmlString( rootNode, "path_to_rubberband", QString(m_rubberBandCLIexecutable));
```

The other problem is that the code that invokes Rubber Band then enters a loop to check whether the process has finished by repeatedly calling `waitForFinished`. But this just waits for the `finished` signal to be emitted, and if the process never successfully started, it will never emit `finished` either, so the loop never exits. Here's a fix for that:
```
diff --git a/src/core/src/basics/sample.cpp b/src/core/src/basics/sample.cpp
index 3292e3eb..f76fe92a 100644
--- a/src/core/src/basics/sample.cpp
+++ b/src/core/src/basics/sample.cpp
@@ -559,7 +559,8 @@ bool Sample::exec_rubberband_cli( const Rubberband& rb )
 
                pRrubberbandProc->start( program, arguments );
 
-               while( !        pRrubberbandProc->waitForFinished() ) {
+               while (pRrubberbandProc->state() != QProcess::NotRunning &&
+                       ! pRrubberbandProc->waitForFinished() ) {
                        //_ERRORLOG( QString( "prozessing" ));
                }
                if ( QFile( rubberResultPath ).exists() == false ) {
```

The latter change isn't ideal, as it just makes the sample editor do nothing when Apply Changes is invoked if the CLI can't be executed. Showing an error would be preferable! But this is better than hanging the UI entirely.

**Comment by mauser** [comment]
Hi Chris,

thanks a lot for tracing this problem to Hydrogen and even proposing a fix! Especially since the rubberband code in Hydrogen is quite a mess :) I've integrated your proposed changes (in a slightly different way, using our own filesystem methods) and it seems to work as expected to me.
