### ISSUE TITLE
Component tab in Main Menu - Add Instruments 

### ISSUE THREAD

**Issue by YungPhil** [hydrogen-music/hydrogen#940]
Hydrogen version *          :1.0.1
Operating system + version  : Windows 7 64 bit
Audio driver + version      : Port Audio - Port Midi

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hi - in the Main Menu -  Instruments is a tab - Add Component. I can't find a reference in the manuals and none online. Could you please tell me whether this has a function under the Windows version and if so what Components can be added. 

Thanks Phil
![image](https://user-images.githubusercontent.com/59207210/92921809-a60f9980-f42c-11ea-8e4f-180ed6670448.png)

**Comment by mauser** [comment]
Hi Phil! 

A component is a part of Hydrogen's instrument model. Each instrument consists of one or more components, and each component consists of one or more layers. 

To make an example: A snare could have two components. One component includes sounds from the top side of the snare drum, and the other component includes the sounds from the bottom side of the snare drum (where the snare wires are fitted). Each component can consist of several layers (snare drum hits with different velocities). Now you can adjust the volume of the two components to build your ideal drum sound. If you want more of the attack, you can put in more of the "top head" component. If you want more of the snare wires, you put in more of the bottom component.

**Comment by YungPhil** [comment]
Thanks for that Sebastian - I will look at this when trying to make some 
new samples/sounds.
Kind regards Phil
------ Original Message ------
