### ISSUE TITLE
[Audio Export with Timing Humanize] unwanted samples at the very end of .wav

### ISSUE THREAD

**Issue by oddtime** [hydrogen-music/hydrogen#946]
Hydrogen version *         v1.0.0 rc1 :
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
This seems to happen using the humanized timing:
I have put many empty patterns at the end of the pattern sequence.
But at the very end of the exported song .wav file (fractions of seconds) sometimes it appears something like the beginning of a sample.

Maybe it could be one note in the first pattern in the sequence being anticipated because of humanized timing.
Turning off the loop song button doesn't help because iit turns on automatically when exporting.

**Comment by mauser** [comment]
Hi oddtime,

it seems plausible that this has something to do with humanization. Could you share a song with us (maybe with a stock drumkit) with which the behavior is (at least sometimes) reproducible?

**Comment by oddtime** [comment]
here it is
https://we.tl/t-jV956zcE51

**Comment by oddtime** [comment]
Hi Mauser, may be this a solution?

in `src/core/Hydrogen.cpp` line 3110 in` void Hydrogen::startExportSession(`
>	pSong->set_loop_enabled( true );

replaced by

>	pSong->set_loop_enabled( false );

It seems to work, but I don't know if that causes other problems

**Comment by mauser** [comment]
Hi @oddtime ,

yes, this seems to help! I've play around with loop_enabled(false) and stumbled directly into another problem (#1005 ), but this shouldn't be related to this export situation, it also appears in song mode. I will see if deactivating the loop mode has other negative issues..

**Comment by oddtime** [comment]
Hi @mauser 
Can we integrate the change now, since #1005 seems independent?
I can make the pull req if you don't have time

**Comment by theGreatWhiteShark** [comment]
This was introduced in a fix of a problem https://github.com/hydrogen-music/hydrogen/commit/1b285966bb3c87c3d0bb672606ec34a6623965bd (which one is unfortunately not mentioned in the commit message).
