### ISSUE TITLE
Mark L and R on panning editor

### ISSUE THREAD

**Issue by Porrumentzio** [hydrogen-music/hydrogen#948]
Currently it is confusing because there is no way further than trying out to know which side is left and which right.

Indicating it with L and R would solve this problem

**Comment by trebmuh** [comment]
Not sure what window/space you're referring to. The only thing I can think of already displays a L/R:

![hydro-pan](https://user-images.githubusercontent.com/8705846/94698098-4294cf80-0339-11eb-83ad-39e07560511a.png)

**Comment by Porrumentzio** [comment]
On the pattern editor, below the tracks/instruments.
There is a editing space where every note can be edited, changing velocity, probabili

**Comment by Porrumentzio** [comment]
Sorry for closing, it was a mistake.

The space I say is in the bottom side of the pattern editor, where the velocity, probability... of each note can be edited. And also the panoramization

**Comment by oddtime** [comment]
![screenshot-b95f1a3f](https://user-images.githubusercontent.com/54219881/101774470-6ff6ba00-3aee-11eb-8ea3-89b535d63528.jpg)
 A message similar to this (appearing while changing note Pan) could be useful and easy to program

**Comment by oddtime** [comment]
Opened pull request #1015 for the message

**Comment by oddtime** [comment]
added R L in Pull Req. But they scroll

**Comment by theGreatWhiteShark** [comment]
The note property display can use some scale in general. For *velocity* and *probability* having e.g. a 0, 0.5, and 1 wouldn't hurt either. For the *lead and lag* displaying the amount of milliseconds would be nice too.

**Comment by oddtime** [comment]
> For the lead and lag displaying the amount of milliseconds would be nice too.

Is it a fixed time value or depends on bpm?

**Comment by theGreatWhiteShark** [comment]
> Is it a fixed time value or depends on bpm?
From the current InfoMessage on the LCD it seems it has steps of 0.1 ticks so showing the scale in ms could be tricking

It's given in ticks (probably multiplied by some constant) and depends on the bpm. So, you are right. Displaying milliseconds would require to redraw the widget when passing a tempo marker. This does not seem to be a good idea. Maybe using something like "fraction of a quarter" would be more appropriate instead.

**Comment by theGreatWhiteShark** [comment]
Implemented in #1544. It does not added a "L" and "R" indicator as this did prove difficult/not working in this scrollable widget. But on all changes of the panning you get now a status message telling whether the note is panned to the left or right
