### ISSUE TITLE
Make noteKey more visible by adding a white outline

### ISSUE THREAD

**Issue by Porrumentzio** [hydrogen-music/hydrogen#949]
Currently, when editing note keys on its editor, when putting a note on the black keys on the piano roll, they get unseeable:
![irudia](https://user-images.githubusercontent.com/61913683/94694856-91406a80-0335-11eb-8295-2edcf2214084.png)

Adding a white outline or something similar would solve this problem.

**Comment by trebmuh** [comment]
confirmed

**Comment by cme** [comment]
Perhaps this could be best done by lightening the sharp/flat background colour, to match the piano roll editor?

**Comment by mauser** [comment]
Ah, yes. The colors are really unfortunate :(

**Comment by cme** [comment]
Some options:

White circle background:

![image](https://user-images.githubusercontent.com/768466/94999963-ec33c500-05b4-11eb-807d-263c0672619c.png)

Alternating black / white notes for contrast:

![image](https://user-images.githubusercontent.com/768466/95000078-a4616d80-05b5-11eb-94da-65d9c3cdc6a8.png)

Lighter background on the sharps & flats:

![image](https://user-images.githubusercontent.com/768466/95000118-ef7b8080-05b5-11eb-995e-a30f0c47d0ee.png)

**Comment by trebmuh** [comment]
I prefer the "Lighter background on the sharps & flats" (the last one). The 2 others are more "aggressive" to my eyes.

**Comment by Porrumentzio** [comment]
I like the second one but it's too hard in contrast.
So I think third option would be better.

Anyway, I propose three changes:
1. Make the sharp/flat keys end more abruptly, not with current lighter border.
2. Make the notes on sharp/flat keys the same size as others (bigger). I think it has to see with the first proposal.
3. Add key names at the left. If user does not know piano very well, it is easier this way.

**Comment by cme** [comment]
@Porrumentzio Good ideas, I'll try those and see how they look.

**Comment by cme** [comment]
I like this a lot better! It's much cleaner and easier to follow I think.

![image](https://user-images.githubusercontent.com/768466/95002725-24480180-05cf-11eb-8059-a52b7233e3f2.png)

**Comment by trebmuh** [comment]
It is very nice like that.
Can you make the ABCDEFG be translatable then I can make these Do Ré Mi Fa Sol La Si (as an example in French)? Thank you

**Comment by cme** [comment]
> Can you make the ABCDEFG be translatable then I can make these Do Ré Mi Fa Sol La Si (as an example in French)? 

Done. The same thing should probably be done in the piano roll editor I guess?

**Comment by trebmuh** [comment]
> The same thing should probably be done in the piano roll editor I guess?

Yes, it'd be very useful for the non English notation users.

**Comment by Porrumentzio** [comment]
Good for internazionalitation!

I like the new look and I have more proposals:
1. Notes on sharp keys look a bit tinier than others. Could they be exactly same size?
2. I would like to see how it looks having sharp keys darker (almost black) and notes brighter (inverting the colors). I'm not sure about this anyway
3. Although the black outlines on the keys of piano roll make it look old-fashioned, I think they look clearer that way. What do you think?

**Comment by cme** [comment]
> 1. Notes on sharp keys look a bit tinier than others. Could they be exactly same size?

They're technically the same size with this change, pixel-for-pixel, but the grey background of the sharps being closer to the outline colour makes it appear smaller. The same thing would happen unless the outline were a contrasting colour. I might try an explicitly dark pen colour to see if that minimises the effect.

> 2. I would like to see how it looks having sharp keys darker (almost black) and notes brighter (inverting the colors). I'm not sure about this anyway
> 3. Although the black outlines on the keys of piano roll make it look old-fashioned, I think they look clearer that way. What do you think?

I will try those when I can get the time but from the first set I tried, the alternating colours seemed the most jarring of the bunch so I don't hold much hope for it!

**Comment by trebmuh** [comment]
Re: 1, @cme what if you add the same black lines than in :

![image](https://user-images.githubusercontent.com/768466/95013232-debf1f00-0636-11eb-94b1-af53e57fe931.png)

?

**Comment by cme** [comment]
Keeping visual similarity with the piano roll editor is probably a good idea anyway. 

(I'm going to ignore the increasing temptation to refactor them to use the same code though!)

**Comment by cme** [comment]
Black lines, black-edged note:

![image](https://user-images.githubusercontent.com/768466/95653027-51277780-0aed-11eb-8679-71ca6d2b2cd1.png)

I think this addresses all the issues and looks much better and clearer. Any objections? :)

**Comment by trebmuh** [comment]
No objection from me, it looks very good like that.

_PS: don't refrain your temptation too much :wink:_

**Comment by cme** [comment]
Pushed to master. Thanks for the focus group everyone! :)
