### ISSUE TITLE
i18n files installation path regression

### ISSUE THREAD

**Issue by SpotlightKid** [hydrogen-music/hydrogen#953]
Hydrogen version *          : 1.0.0.r90.g051e723e
Operating system + version  : Manjaro Linux (Arch)
Audio driver + version      : n.a.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

This commit seems to contain a regression with regards to the i18n files installation path:

https://github.com/hydrogen-music/hydrogen/commit/a7f44df2e3b56f937c251b7b5764800ce983f4fe#diff-b600d9559dced5a283e137852d242e56L8

The `i18n` folder is incorrectly getting installed in `<prefix>/data/` instead of `<prefix>/share/hydrogen/data/`.

The latest release still installs to the correct installation, though maybe the path set in the `data/i18n/CMakeLists.txt` file should be based on `${H2_DATA_PATH}` not `${H2_SYS_PATH}`? (I'm not sure about the difference.)

**Comment by cme** [comment]
> I've see this behavior while testing #919 (dev-pattern-editor-selection @cme 's branch, commit ID [083e76d](https://github.com/hydrogen-music/hydrogen/commit/083e76d9f6eb448ae58408b17ac1162c806965c4)).

I merged from master to that branch regularly so it will almost certainly get the same issue from that change.

**Comment by trebmuh** [comment]
Sounds right.

**Comment by trebmuh** [comment]
@elpescado could you please have a look to it?

**Comment by mauser** [comment]
> This commit seems to contain a regression with regards to the i18n files installation path:
> 
> [a7f44df#diff-b600d9559dced5a283e137852d242e56L8](https://github.com/hydrogen-music/hydrogen/commit/a7f44df2e3b56f937c251b7b5764800ce983f4fe#diff-b600d9559dced5a283e137852d242e56L8)
> 
> The `i18n` folder is incorrectly getting installed in `<prefix>/data/` instead of `<prefix>/share/hydrogen/data/`.
> 
> The latest release still installs to the correct installation, though maybe the path set in the `data/i18n/CMakeLists.txt` file should be based on `${H2_DATA_PATH}` not `${H2_SYS_PATH}`? (I'm not sure about the difference.)

Hi! 

in my opinion ${H2_SYS_PATH} is the correct path to use for linux/unix systems. I''ve re-introduced it to `data/i18n/CMakeLists.txt` and also added a special handling for our windows binaries. @SpotlightKid : Please check if this works now for you!

**Comment by SpotlightKid** [comment]
Yes, I can conform that the `i18n` folder is now correctly installed in `<prefix>/share/hydrogen/data`.

**Comment by mauser** [comment]
Ok, thanks for the feedback!

**Comment by trebmuh** [comment]
@mauser what about adding this one to [1.0.2](https://github.com/hydrogen-music/hydrogen/milestone/6)?

**Comment by mauser** [comment]
@trebmuh: This problem has been introduced after the 1.0 release, so 1.0.2 should be working.

**Comment by trebmuh** [comment]
I see.
Thanks for answering.
