### ISSUE TITLE
Question: Extend note duration to control external instrument

### ISSUE THREAD

**Issue by enorrmann** [hydrogen-music/hydrogen#954]
I read the manual and I googled a lot but I can't find a way to make a note on for a whole bar for example, I add a note, drag to the right but note duration is always the same.
Also.. is there a slack or another place to post questions like this ?
Thx !

**Comment by enorrmann** [comment]
I think I run into this
https://github.com/hydrogen-music/hydrogen/issues/63

**Comment by enorrmann** [comment]
duplicated 
https://github.com/hydrogen-music/hydrogen/issues/63

**Comment by cme** [comment]
> Also.. is there a slack or another place to post questions like this ?

There is a #hydrogen IRC channel on freenode.net , which coincidentally @trebmuh took control over just a few days ago. It may or may not be useful in the future!
