### ISSUE TITLE
NSM implementation forgets existing song sometimes

### ISSUE THREAD

**Issue by Houston4444** [hydrogen-music/hydrogen#956]
Hydrogen version *          : 1.0.1
Operating system + version  : Debian 10 or any
Audio driver + version      : JACK

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
NSM support often forgets the existing song.
I am not able to give you steps to reproduce to see this happens in 100% cases, but just start hydrogen under an NSM session manager, save it, stop it, restart it, until hydrogen opens an empty song.

It is really dangerous to run Hydrogen under NSM and it's a shame, there was a very good PR #780 working very well for this.
Unfortunately this PR has never been merged and has many conflicts now.
By user experience, I have to remove the Hydrogen's template from RaySession's templates and put again the template based on LASH save, which is paradoxically safer.

**Comment by theGreatWhiteShark** [comment]
Hey @Houston4444 ,

yes, the current NSM implementation is a stub. Basically, just the code from the NSM C++ example.

But the NSM support is scheduled for the next release and I will soon start working on it again/finishing it (#792 which supersedes #780). There is just some fixes regarding the linking of the drum samples into the session folder and some beautification necessary.

**Comment by theGreatWhiteShark** [comment]
Closed with #792
