### ISSUE TITLE
first beat is muted when switching pattern from midi event

### ISSUE THREAD

**Issue by Houston4444** [hydrogen-music/hydrogen#957]
Hydrogen version *          : 1.0.1
Operating system + version  : Librazik3 (debian buster)
Audio driver + version      : JACK

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Hi !

I tried to map patterns to midi notes events (I also tried with CC events). I used SELECT_AND_PLAY_PATTERN key and it works, the current pattern is changed during the transport play. Unfortunately, each time I change pattern from midi, the first beat of the bar following the midi event is muted.
It's quite a shame to not have a midi input mode to change current pattern as "Instrument", and "Drumkit" exists, "Pattern" could also exist, and this way no need for user to assign itself all patterns to midi notes/CC/PC. Maybe a such thing already exist, am I ignoring this ?

Steps to reproduce:
* edit two patterns
* In Preferences dialog, assign a MIDI note event to SELECT_AND_PLAY_PATTERN parameter 0 (first pattern).
* assign a MIDI note event to SELECT_AND_PLAY_PATTERN parameter 1 (second pattern).
* save changes
* try to change patterns with your midi device

**Comment by Houston4444** [comment]
I just saw that SELECT_NEXT_PATTERN works for this without this bug.
I think it could works with the workflow I try to have, I'd like to change pattern from an ardour midi track.

**Comment by mauser** [comment]
Thanks for the report, i'm going to look into the problem. 

About your feature request: Do I understand it correctly, that you would like to have a new input mode "Pattern" (besides Instrument and Drumkit) which allows you to switch patterns by using Midi Note events? So Note 0 will select pattern 0, Note 1 will select pattern 1 and so on? If yes: Just turn this into a new github issue, we could discuss it further over there.

**Comment by Houston4444** [comment]
Thanks. I will do that.

**Comment by theGreatWhiteShark** [comment]
Fixed with #1435. The reason for this to occur was a that the lookahead of the audio engine was not reset.
