### ISSUE TITLE
Unintended change of instruments when processing OSC command

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#959]
Hydrogen version *          : b51508b3d6267df9c36e0e8fe0ae7de58f5fd972
Operating system + version  : 
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

When relocating via 

```
oscsend localhost 9000 /Hydrogen/RELOCATE i 2
```

transport changes as intended but the focus in the pattern editor changes to the last instrument of the drumkit. When relocating via mouse click, however, the focus is persistent.

---

Edit: This behavior occurs with all sorts of OSC commands (not just the ones recently introduced)

**Comment by cme** [comment]
Hmm, is that new with that last commit? If so I'll take a look into it.

Does the actual selected instrument change, or is it just the position of the window?

**Comment by theGreatWhiteShark** [comment]
Nope, it already was there beforehand but went unnoticed.

Something with `CoreActionController::initExternalControlInterfaces`. I will have a look into it later today.

**Comment by cme** [comment]
Yeah, I see setStripVolume changes instrument [here](https://github.com/hydrogen-music/hydrogen/blob/b51508b3d6267df9c36e0e8fe0ae7de58f5fd972/src/core/src/core_action_controller.cpp#L75) for some reason. It probably shouldn't.

**Comment by theGreatWhiteShark** [comment]
The variable itself is quite strange. So, the core does store the particular instrument selected/highlighted in the GUI. But this seems to be necessary due to the MIDI input, which can be configured to play either the entire drumkit or just the selected instrument.
