### ISSUE TITLE
Jack D Hydrogen v 1.0.1 64

### ISSUE THREAD

**Issue by YungPhil** [hydrogen-music/hydrogen#965]
Hydrogen version *          : 1.0.1 64 bit
Operating system + version  : Windows 7 64 bit (Lenovo laptop)
Audio driver + version      : PortAudio Conexant 20672 Smart Audio HD

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Good mornng - I am trying to set Jack d up ( possibly with asio4all but first things first). 

I have Jackd on my system and its shows System inputs and outputs as potential connections. I am clearly getting system sounds routed though Jackd on headphones so in short Jack seems to be working.

According to the Hydrogen manual Hydrogen should pick up Jack and give it as an option in Preferences Audio System menue but it doesn't appear. Equally Hydrogen  is not appearing as a connection option in the Jack patchbay.

Any thoughts on how to get Jack working? Does it have anything to do with running the 64 bit version of Hydrogen?

PS I am using Jack2 64bit for windows - 64-bit installer: JACK 1.9.16 win64.According to the people at Jack they have removed the jackrouter.dll from the 64bits file in their installation. 

 I see that there is a dll in Hydrogen folder  - jack-0 so assume that Hydrogen is not detecting Jack2 but not having any programming knowledge I don't know how to rectify.

**Comment by theGreatWhiteShark** [comment]
Hey @YungPhil,

So, I guess I'm somewhat of the Jack guy here. But I have almost no experiences with Windows at all...

The Jack API itself should be agnostic to your type of operation system as long as it is supported (what according to the webpage should be the case). Could you run Hydrogen with the command line option `-VDebug` and paste the output in here? Maybe the log contains some clues.

**Comment by YungPhil** [comment]
![Hydrogen debug](https://user-images.githubusercontent.com/59207210/97293219-46d2e080-1844-11eb-9157-9f6fc50ded06.png)
Hi thanks for coming back - not sure whether this is what you want - I used the Debug function from the menu in Hydrogen to get this image.

**Comment by mauser** [comment]
Hi! 

It seems that the 1.0.1 version is not compiled with jack support. I will have a look at this.. I remember that there have been problems when building the installer.

**Comment by YungPhil** [comment]
Thanks - I know nothing about programming so completely in the dark - I 
believe Jack now have a version called Jack2 with both 32 and 64 bit 
support. They used to have a file  - jackrouter.dll - in a 64 bit folder 
in the program folder but that has changed and been removed in the  most 
recent version. I did take this up with the Jack people because their 
instructions still refer to this file but apparently that info is out of 
date. They weren't able to help on setting up with Hydrogen though.

Phil
------ Original Message ------

**Comment by theGreatWhiteShark** [comment]
@cme Is this a problem of just a missing line in the `.appveyor.yml` file so we can fix it before 1.1 or is there something more to it?

**Comment by cme** [comment]
The Windows releases are built in @mauser's local MXE environment rather than appveyor; I think the appveyor Window build still has stability issues.

My Windows builds in my MXE environments seem to have Jack support (it's compiled-in anyway, appears in the drop-down menu, and there's a Jack DLL). I've tried installing the Jack build (including QJackCtl) from jackaudio.org on my Windows VM, but that doesn't seem to work at all (even qjackctl can't connect to jackd after starting it) so I can't say if the Hydrogen build would work or not in a working system.

**Comment by theGreatWhiteShark** [comment]
Hmm. Sounds like quite a mess. IIRC the appveyor builds were at some point praised to ease the building and releasing process. But maybe this was just for a limited time.

Let's hope people will report that everything is working in 1.1

**Comment by mauser** [comment]
In general, the appveyor builds are "stable". But (at least last year) there was no jack package for msys2. This was the reason why i kept building the packages with jack support locally. Besides that, there should be no difference between the appveyor packages and my local packages. Appveyor eases (or enables) the build process for Windows, but it does not ease the release process. However it helps a lot with building OS X packages (CI builds and release).

On the other hand, even the locally build MXE packages have a problem with jack, as @cme pointed out. I ran into the same problems and could not get it to work on my machine.I could not find out if this is a jack problem or a problem with our build scripts.

**Comment by cme** [comment]
> On the other hand, even the locally build MXE packages have a problem with jack, as @cme pointed out. I ran into the same problems and could not get it to work on my machine.I could not find out if this is a jack problem or a problem with our build scripts.

It looks like the JACK DLLs aren't found in the 64-bit Windows builds, so it gets disabled in cmake. The 32-bit Windows builds successfully find the DLLs and enable it in the config. I suspect this is because the 64-bit DLLs are named `libjack*64.dll`?

**Comment by mauser** [comment]
@cme:  Sorry, i wasn't precise enough. I was able to build a windows binary with jack support locally with MXE, but i was not able to execute it properly on my Windows 10 system. Everytime i start Hydrogen and try to connect to jackd, Hydrogen freezes.

Btw., i've just started to build the binaries for 1.0.2 and will give them a try on tuesday, will contact you then!

**Comment by cme** [comment]
Hmm. I've just realised two things about the Appveyor Windows builds
  - they seem to be debug builds. Was this because the stability issues were with the Release builds? 
  - until the next release of PortAudio, and it being streamed into MSYS, Appveyor Hydrogen builds will suffer from the same PortAudio + WDM-KS issues that stopped Hydrogen running at all on machines with malformed ( #899 and some others )

**Comment by cme** [comment]
Appveyor builds are good and now include JACK on Windows, hurrah :) Closing!
