### ISSUE TITLE
Latest system updates stopped *.h2song created from previous H versions.

### ISSUE THREAD

**Issue by drbonezy** [hydrogen-music/hydrogen#970]
Hydrogen version *          :1.0.0-rc1
Operating system + version  :Ubuntu 20.04.1 LTS
Audio driver + version      :Realtek ALC268

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Latest updates stopped *.h2song created from previous H versions.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Latest system xubuntu updates on Nov 1 2020 stopped playing any and all *.h2song created from previous H versions.  They will load but not play.  Changing audio driver from Alsa to Jackd doesn't help.  H will allow me to create new patterns and will play the demo _songs.

**Comment by drbonezy** [comment]
Latest system xubuntu updates on Nov 1 2020 stopped playing any and all *.h2song created from previous H versions.  They will load but not play.  Changing audio driver from Alsa to Jackd doesn't help.  H will allow me to create new patterns and will play the demo _songs.

**Comment by trebmuh** [comment]
Try with Hydrogen 1.0.1 please.

**Comment by drbonezy** [comment]
It's all working again. Solved by reloading the drumkit associated with my *.2dsong  files.  Thanks and sorry for not posting msg correctly.

**Comment by trebmuh** [comment]
Good that it is working for you now @drbonezy .
I'm closing here since you resolved it.
Feel free to reopen if needed.

Happy drumming then.
