### ISSUE TITLE
Recording in "Song" mode behaviour is unexpected

### ISSUE THREAD

**Issue by cme** [hydrogen-music/hydrogen#975]
Hydrogen version *          : current master / 1.0 / 1.0.1
Operating system + version  : all
Audio driver + version      :  all

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Using "record" in song mode has some unexpected behaviour. While it's not documented what behaviour the user *should* expect, I think the current behaviour deviates from most reasonable expectations.

The current behaviour is that notes entered while recording in song mode will be inserted into the pattern of the *song pattern list* corresponding to the current index into the *pattern sequence*.

To illustrate:

![image](https://user-images.githubusercontent.com/768466/99000272-e5438f00-2530-11eb-8da4-0a8902811cf6.png)

  * A note played during the first bar, when "Pattern 1" is playing, will be entered into "Pattern 1"

  * A note played in the second bar, while "Pattern 1" is playing for the second time, will be entered in "Pattern 2"

  * A note played in the fourth bar, while "Pattern 2" is playing for the first time, will be entered into "Pattern 4"

I think a reasonable user expectation in this case would be that notes played in the first 4 bars would go into pattern 1, and notes played in the second bar into pattern 2. From the code in `Hydrogen::addRealTimeNote` it looks as if this is the intention, and it's easy to fix.

I'm not sure though if the behaviour is useful in the case where there are multiple patterns active at the same time. It looks like the intention would be to enter the notes in the "first" pattern that's active, in the internal order kept by the Song (which is, I think in all cases, the first one the user enabled) which isn't visible or represented on the Song grid.

This may not be the most useful behaviour. For example, playing over a click track that you then intend to remove later, would potentially record all notes into the click track if that's the first thing that you enabled in a grid time slot.

Reasonable potential alternative behaviours:

  1. Record into the "first" (by order of the song pattern list) currently active pattern

  2. Record into the "last" (by order of the song pattern list) currently active pattern. This seems like a good definition to me, as the "last" patterns are likely to be the ones most currently worked on.

  3. Record into the currently selected pattern. This also seems a useful definition as it means the user will always *see* their newly inserted notes immediately, which makes it discoverable. It would make things like live-looping performance a bit more involved as it would mean having to manually change patterns.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by cme** [comment]
Another potential option:

4. Record into the "last" active pattern by sequence list position. I.e. the most recently "activated" pattern. Add some visual indicated (eg. a "·" in the sequence cell of the "last" active pattern when the "Record" button is pressed down.

This would let the user *see* in advance which pattern would be recorded into, and would let them change it by clicking their intended target pattern in that time period (possibly de-activating it and re-activating it in the process)

**Comment by theGreatWhiteShark** [comment]
Do you think people might want to use different of your alternative behaviors on different occasions (via another option)? Or should there be just one fixed behavior documented in the manual?

I like alternative 1&2 since they are less dynamic and might lead to less unintended results.

**Comment by cme** [comment]
I think I'm leaning pretty strongly to 2. 1 or 2 should cover almost all the use cases I can think of that 4 would cover (with some temporary reordering of patterns). Do you have any feel for what other behaviour (3?) might be useful to switch to?

Also adding (as a note to self if nothing else) that it might be useful to show on the song grid which pattern is being recorded into when in song record mode.

**Comment by theGreatWhiteShark** [comment]
> Do you have any feel for what other behaviour (3?) might be useful to switch to?

Hmm. I think seeing the inserted notes while looping over the pattern is handy. But this is already covered by recording in "Pattern" mode. So, no, not really.
