### ISSUE TITLE
MacOS build on Travis fails because brew doesn't find jack.h

### ISSUE THREAD

**Issue by theGreatWhiteShark** [hydrogen-music/hydrogen#977]
Operating system + version  :  MacOS

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I'm not quite sure since when but the Travis build for macOS does fail with 

```
/Users/travis/build/hydrogen-music/hydrogen/src/core/include/hydrogen/IO/jack_audio_driver.h:35:10: fatal error: 'jack/jack.h' file not found

#include <jack/jack.h>
```

https://travis-ci.org/github/hydrogen-music/hydrogen/jobs/743486988

But the installation of the `jack` package using `brew` seems to work.

Unfortunately, I do not have access to a mac anymore.

**Comment by cme** [comment]
Hmm, it looks like it's just the tests that don't build. They don't seem to have the JACK includes in the CMakeLists.txt, they just need to be added. But I'm curious about how it managed to build before, and indeed how it manages to build in *my* local environment! :D I'll investigate.

This will also have masked that the mac build will probably *also* be broken by switching C++ standard to C++17, which is breaking my build at the moment, because the version of JACK's types.h header file in the Homebrew JACK has the 'register' keyword used as an identifier.

**Comment by cme** [comment]
Commit 4fb4bb53ac8fad731e73269cfe5aa3d28d882f21 broke the tests by adding the JACK includes to hydrogen.h. Works on Linux because /usr/include has everything :)

**Comment by mauser** [comment]
> This will also have masked that the mac build will probably _also_ be broken by switching C++ standard to C++17, which is breaking my build at the moment, because the version of JACK's types.h header file in the Homebrew JACK has the 'register' keyword used as an identifier.

@cme : I've activated C++17 just to check if our environment gives us any trouble. There is currently no code that makes use of it, so we could go back to C++14 if there are libraries which have to be adapted first. Is this a still a problem with the JACK code or does Homebrew have an older version of the header?

**Comment by cme** [comment]
> @cme : I've activated C++17 just to check if our environment gives us any trouble. There is currently no code that makes use of it, so we could go back to C++14 if there are libraries which have to be adapted first. Is this a still a problem with the JACK code or does Homebrew have an older version of the header?

It looks like my local Homebrew is just in an inconsistent state. The Travis builds install a fresh JACK and seem to have no issues, builds are green again.

**Comment by theGreatWhiteShark** [comment]
> Works on Linux because /usr/include has everything

How annoying :/

I have the plan (for a more distant future) to cover all actions required for the CLI and the player with OSC commands and to replace the former with plain and simple OSC command line interfaces talking to a Hydrogen process running without GUI in the background. This way both CLI and player are way more easily to keep up to date and we can disentangle the code base. But this has very low priority for me right now

**Comment by mauser** [comment]
> > @cme : I've activated C++17 just to check if our environment gives us any trouble. There is currently no code that makes use of it, so we could go back to C++14 if there are libraries which have to be adapted first. Is this a still a problem with the JACK code or does Homebrew have an older version of the header?
> 
> It looks like my local Homebrew is just in an inconsistent state. The Travis builds install a fresh JACK and seem to have no issues, builds are green again.

@cme: The same problem appears now at the [Appveyor CI build for OS X](https://ci.appveyor.com/project/mauser/hydrogen/build/job/ke9sd0jiu7qg89km). How have you solved your local problem?

**Comment by cme** [comment]
I commented out the offending unnecessary parameter name in my Homebrew JACK install, for fear of breaking the installation. It's odd though, the version of JACK that Homebrew claims it has, that parameter name is commented out in the upstream version.
