### ISSUE TITLE
Hydrogen not opening in Big Sur

### ISSUE THREAD

**Issue by jonmay6** [hydrogen-music/hydrogen#982]
Hydrogen version *          :1.0.1
Operating system + version  : Mac OS 11.0.1
Audio driver + version      : 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I upgraded to Mac OS 11.0.1 and Hydrogen no longer starts up.  The wheels spins and then nothing.
[hydrogen_2020-11-12-172042_MacBook-Air.txt](https://github.com/hydrogen-music/hydrogen/files/5544547/hydrogen_2020-11-12-172042_MacBook-Air.txt)

**Comment by cme** [comment]
I don't have a machine I can upgrade to Big Sur at the moment to try to reproduce this, but from the stack backtrace there's a possibility that the crash might be caused by an inconsistent h2song file.

Could you try deleting or rename your `hydrogen.conf` and see if the same crash still occurs?

(it's in `Library/Application Support/Hydrogen/hydrogen.conf`)

**Comment by jonmay6** [comment]
I deleted the file but the problem is the same.  I also deleted the entire app with the same result.

**Comment by bhopmann** [comment]
I can confirm this error with Big Sur.

**Comment by cme** [comment]
> I deleted the file but the problem is the same. I also deleted the entire app with the same result.

Thanks for trying. Looks like I have to find a spare HD now!

**Comment by cme** [comment]
Apparently Apple have dropped support for my laptop in Big Sur (ugh) so I won't be able to replicate this directly. Could you get the debug tracing from Hydrogen itself, please?

You can do that with 

``` 
/Applications/Hydrogen.app/Contents/MacOS/hydrogen -V Debug > ~/Desktop/hydrogen-debug.txt
```

from Terminal.

Also, if this doesn't lead to an answer, would you be willing to help out by running an instrumented debug build (or a few) to try and nail down the problem?

Many thanks!

**Comment by mauser** [comment]
We're currently using XCode 9.4.1 in our CI Jobs to build the OS X packages ( `MACOSX_DEPLOYMENT_TARGET="10.12" `). Could it be the case that this version is too old? I'm not too familiar with the XCode, so i don't if this is relevant. Just mentioning it  :)

**Comment by cme** [comment]
> Could it be the case that this version is too old? I'm not too familiar with the XCode, so i don't if this is relevant. Just mentioning it :)

It's *possible* but seems unlikely -- the stack backtrace that @jonmay6 provided shows that it asserts in the SongEditor; I'd expect a toolchain incompatibility to show up earlier in the startup process.

**Comment by theGreatWhiteShark** [comment]
The assertion sounds like #714

**Comment by bhopmann** [comment]
Although I did not start this post, I would like to contribute something to find the error. Attached you'll find the debug tracing.
[hydrogen-debug.txt](https://github.com/hydrogen-music/hydrogen/files/5562418/hydrogen-debug.txt)

**Comment by cme** [comment]
> The assertion sounds like #714

Agreed. I'll spin a fixed dmg and post here, if someone with Big Sur can try to confirm it.

We're using a std::mutex for the audio lock at the moment, but recursive mutexes are also available in the std library, which might make a general improvement to the locking situation easier now.

**Comment by cme** [comment]
Hi, @jonmay6 , @bhopmann would you mind trying out this build:

[Hydrogen-dev-1.0.1-bigsur.dmg](https://drive.google.com/file/d/1lhEii-AKWlMW-sbr4gGBpZFYumQ5QFIT/view?usp=sharing)

It's built from 1.0.1 but with an added fix for the race condition that I *think* the release build is hitting.

Thanks!

**Comment by jonmay6** [comment]
It works!

**Comment by bhopmann** [comment]
Thanks @cme , it works for me too!

**Comment by jacobichr** [comment]
Hi @cme I'm trying to download the dmg file referenced above but get a "google drive file does not exist" error message. The official DMG on hydrogen-music.org still is from Sep and doesn't seem to have this fix?

**Comment by cme** [comment]
Oh. That was in my personal gdrive and I removed it at the weekend.

We should push 1.0.2 out as soon as we can since that fixes this and other issues.

**Comment by cme** [comment]
Hi @jacobichr, @bhopmann , @jonmay6, I've created a release, 1.0.2, that has the fix for this issue. Would you mind trying it out please?

https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.2
