### ISSUE TITLE
Hydrogen not opening in Mac Os 10.12.6

### ISSUE THREAD

**Issue by pippiz** [hydrogen-music/hydrogen#985]
Hydrogen version *    : 1.0.1
Operating system + version  : Mac OS 10.12.6
Audio driver + version      :  

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Hydrogen does not open, dialogue box suggests it maybe incompatible with OS but Hydrogen 1.0.1  should be compatible with Mac OS 10.12.6. (via developer website).  Hydrogen version 9.7 opens (but was crashing when adding instrument layers/ importing sample wavs)

**Comment by mauser** [comment]
Hi! 

in #982, we found out that other OS X users had a similiar problem. @cme has published a version of Hydrogen which fixes a bug in 1.0.1 [Hydrogen-dev-1.0.1-bigsur.dmg](https://drive.google.com/file/d/1lhEii-AKWlMW-sbr4gGBpZFYumQ5QFIT/view?usp=sharing). Maybe you could try out this version? The fix has nothing to do with Big Sur, so maybe it is also your problem.

**Comment by cme** [comment]
There's also a change that [the OS X 10.11 build of the 1.0.1 release](https://sourceforge.net/projects/hydrogen/files/Hydrogen/1.0.0%20Binaries/Hydrogen-legacy-1.0.1.dmg/download) might work.

If neither of those work, could you tell us more about the way in which it fails to open?

 * Is there a Mac OS dialog box displayed?
 * Does the Hydrogen splash screen show at all?
 * Do you get a crash report?

Thanks!

**Comment by theGreatWhiteShark** [comment]
Hey @pippiz ,

This issue is quite old by now. Could you check whether this bug still applies to the newest 1.1.1 release of Hydrogen? Otherwise, I will close this issue in two weeks. (but feel free to reopen it)
