### ISSUE TITLE
1 Some drum voices not sounding    2 saving behaviour

### ISSUE THREAD

**Issue by aomahana** [hydrogen-music/hydrogen#990]
Hydrogen version *   V1.0.1       :
Operating system + version  :  Windows 7 64
Audio driver + version      : 
Port Audio (No other choice)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Recently, when I opened a Hydrogen Song, some of the drum voices did not sound.
I was able to restore them by right clicking on the drum kit in the Sound Library and selecting the Load button.
This hasn't happened before.

Also, just a comment about the auto save behaviour. 
Each time a song or pattern is loaded a copy is made in the folder.
These gradually mount up in number and have to be manually deleted.
I realise this is probably intended as a safe guard, but it would be good if there was a selectable option for this.

And, it is so good to see Hydrogen actively being worked on again.
Not being any kind of a programmer, this much appreciated.

All the best,
aomahana.

**Comment by mauser** [comment]
Hi! 

Can you reproduce the behavior of the first problem somehow? 

About the second one: I saw something similar when looking into issue #941. Issue #941 describes some problems which appear if Hydrogen can't save things to the temporary directory. In that case, the problem was caused by a white space in the windows user name. Normally, those autosave file should also go to the temporary directory (and should be deleted if Hydrogen is closed). Is there by any change any whitespace or other unusual character in your windows user name?

**Comment by aomahana** [comment]
Hi Sebastian,

Thank you for your reply.

With regard to some drum voices not sounding, this has not shown itself 
again so far, since I re-established the link with the files.
And I have no idea why it occurred in the first place.
I wrote the message so that anyone who experienced the same issue would 
have a solution.

With the saving issue .... yes, I may have a space in the user name.
I had thoght that the saving was normal behaviour. I'm glad to hear that 
it isn't.
But since I wrote the original message, I have begun a rebuild of my 
computer with a new mother board, processor, RAM. and power supply.
This will take a while to complete, so when everything is functioning 
again, I will check my user name and if necessary remove any spaces.
I will get back to you then. This might take several weeks as I have 
quite a lot of software to integrate into my new system.


Bye now,
aomahana.



------ Original Message ------

**Comment by aomahana** [comment]
Hi Sebastian,

Thank you for your reply.

With regard to some drum voices not sounding, this has not shown itself again so far, since I re-established the link with the files.
And I have no idea why it occurred in the first place.
I wrote the message so that anyone who experienced the same issue would have a solution.

With the saving issue .... yes, I may have a space in the user name.
I had thought that the saving was normal behaviour. I'm glad to hear that it isn't.
But since I wrote the original message, I have begun a rebuild of my computer with a new mother board, processor, RAM. and power supply.
This will take a while to complete, so when everything is functioning again, I will check my Windows user name and if necessary remove any spaces.
I will get back to you then. This might take several weeks as I have quite a lot of software to integrate into my new system.


Bye now,
aomahana.

**Comment by mauser** [comment]
Alright! You could also try [this](https://ci.appveyor.com/api/buildjobs/h9canbiuepsp9j16/artifacts/build%2FHydrogen-1.1.0-win64.exe) version of Hydrogen then, it should have that user name problem fixed.

**Comment by trebmuh** [comment]
@aomahana any news here?

**Comment by aomahana** [comment]
Hi,

It has taken longer than expected to complete my new computer rebuild as there are so many elements to address.
Although I am getting closer to running and using Hydrogen, I am not there yet.
From the comments above, it appears that the saving issue may be addressed.
So I think we can safely close this issue report.

**Comment by aomahana** [comment]
Closed .... see above.
