### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID for https://hydrogen-music.org/

### ISSUE THREAD

**Issue by sten0** [hydrogen-music/hydrogen#994]
Hi,

I just wanted to report that https://hydrogen-music.org has an SSL cert problem `NET::ERR_CERT_COMMON_NAME_INVALID`.  It would be nice to have this fixed :-)

Thank you,
Nicholas

**Comment by trebmuh** [comment]
Confirmed but that should be reported on the [website repo](https://github.com/hydrogen-music/hydrogen-music). Can you please do so @sten0 ?

**Comment by trebmuh** [comment]
Scratch that, I did it.
Closing it here then.

**Comment by sten0** [comment]
> Confirmed but that should be reported on the [website
> repo](https://github.com/hydrogen-music/hydrogen-music). Can you
> please do so @sten0 ?
>

Sorry for the report to the wrong subproject.

> Scratch that, I did it.
> Closing it here then.
>

Thank you, much appreciated! :-)
