### ISSUE TITLE
Open demo broken

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#996]
Hydrogen version *          : GIT master b17f662
Operating system + version  : LibraZiK-3 (Debian Buster based)
Audio driver + version      : jack (but not relevant for this issue)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Fresh build to check the NSM support (thanks @theGreatWhiteShark & @mauser !).
Trying to load a demo, I've got this popup window:

![errorloadingsong](https://user-images.githubusercontent.com/8705846/100547458-29d86580-3267-11eb-876d-2b93d09a0ee1.png)

and starting fromp the CLI, I've got this error log:

```
(E) CoreActionController::isSongPathValid Error: Unable to handle path [/usr/share/hydrogen/data/demo_songs/GM_kit_Diddley.h2song]. You must have permissions to write the file!
```

Please note that if I' copy/paste the demo in a location where I have written permission (e.g. $HOME), H2 loads it fine.

From a user point of view, it shouldn't be needed to have the write permission to open and play a demo.

_(I'll go testing the NSM support now! :sunglasses: )_

**Comment by theGreatWhiteShark** [comment]
Ah, I see. I unified the code responsible for loading songs and the demo song was probably handled a little different.

But let's talk about the handling of songs located at places with read but not write access in general (this should apply to the demo songs too). It's of course reasonable to allow opening them. But on the other hand, there is some unexpected behavior of Hydrogen in the background since the autosave won't work (and maybe the user is not aware of the read-only access).

I would suggest display a warning stating the song is opened in read-only mode a "save as" is required to enable the autosave. Is this enough or should we append something like "(read-only)" to the song name in the buffer title was well?

**Comment by trebmuh** [comment]
> Ah, I see. I unified the code responsible for loading songs and the demo song was probably handled a little different.

OK.

> But let's talk about the handling of songs located at places with read but not write access in general (this should apply to the demo songs too). It's of course reasonable to allow opening them.

OK

> But on the other hand, there is some unexpected behavior of Hydrogen in the background since the autosave won't work (and maybe the user is not aware of the read-only access).

I see.

> I would suggest display a warning stating the song is opened in read-only mode a "save as" is required to enable the autosave. Is this enough or should we append something like "(read-only)" to the song name in the buffer title was well?

This sounds good.

Another approach could be to open it with disabling the autosave functionality as long as the song remains untouched, and at the very first time the user is modifying anything on the song, then popping up a window saying something around this line:

```
This song is located in a place where you have no writing rights.
Hence, Hydrogen is then unable to save it there.
Would you like to make a copy elsewhere in a place where you have the writing permission?
```

and then, proposing to save in, e.g., Hydrogen user's `~/.local/share/hydrogen/song/` ?

Only sharing ideas here.

**Comment by theGreatWhiteShark** [comment]
For the demo songs it would reasonable to "just have a look". (are there more than 5 buttons which do not alter the song? Anyway.) But for songs in general I would prefer a immediate feedback after opening. At this point it should be the least surprising/confusing. (Probable scenario apart from the demo songs: the song is located at an external storage and is mounted without fuse or pmount).

 > proposing to save in, e.g., Hydrogen user's `~/.local/share/hydrogen/song/`

Have we already decided to move the user's data folder? With latest master mine is still using `$HOME/.hydrogen/`.

**Comment by trebmuh** [comment]
> > proposing to save in, e.g., Hydrogen user's `~/.local/share/hydrogen/song/`
> 
> Have we already decided to move the user's data folder? With latest master mine is still using `$HOME/.hydrogen/`

I didn't looked precisely before writing when I post the last comment, that was only a "sharing ideas" message. So, yes, the actual place is indeed `$HOME/.hydrogen/`.

**Comment by theGreatWhiteShark** [comment]
Ah, okay. Don't worry. I just wondered since I was absent during the discussion of moving the resources.
