### ISSUE TITLE
[i18n] missing strings for translation

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen#997]
Hydrogen version *          : GIT master b17f662
Operating system + version  : LibraZiK-3 (Debian Buster based)
Audio driver + version      : jack (but not relevant for this issue)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I've updated (with the data/i18n/updateTranslations.sh script) the French .po file and rebuild with it locally.
There are some missing translations (see the items where I've put a black-dot-on-a-green-circle next to it) :

![hydrogen-i18n-missing](https://user-images.githubusercontent.com/8705846/100552487-cad71880-3287-11eb-99be-24e2766253f7.png)

Those strings are not available any more in the .ts file while I'm fairly sure they were "before".

**Comment by trebmuh** [comment]
While I'm at it, I'd like to have those translatable too:

![traductions-note-hydrogen](https://user-images.githubusercontent.com/8705846/100554689-9dde3200-3296-11eb-9bcd-b74e916f8e93.png)

If I'm not wrong, 4 means "quarternote", 8 means "eightnote", 16 means "sixteenthnote", 32 means "thirthysecondnote", and 64 means "sixyfourthnote" in Anglo-Saxon notation. In French, it should be:
* 4 -> noire
* 8 -> croche
* 16 -> double-croche
* 32 -> triple-croche
* 64 -> quadruple-croche
and in other languages it'd be probably different too.

Could you please make those translatable?

**Comment by theGreatWhiteShark** [comment]
> There are some missing translation

This seems to affect the German translation too.

**Comment by oddtime** [comment]
Personally, I prefer numbers in the resolution combo and in general, which are less intuitive in italian (semiminima, croma, semicroma, biscroma, semibiscroma)

**Comment by theGreatWhiteShark** [comment]
> Could you please make those translatable?

I do prefer numbers too. For one because it's faster to read and more important because it doesn't require translation in the first place. So, even people unfamiliar with English can make sense of it.

Is there additional information contained in the written words you listed or is a purely aesthetic thing?

**Comment by trebmuh** [comment]
@oddtime: it's not really something as a "preference".
In French, the music theory doesn't is as I described above.

**Comment by oddtime** [comment]
Ok, I don't know about French.
In both English and Italian theory both numbers and names are used.

**Comment by theGreatWhiteShark** [comment]
How about having both the number as a fraction, like 1/4 (but properly rendered), and the name to the right of it?

**Comment by cme** [comment]
> How about having both the number as a fraction, like 1/4 (but properly rendered), and the name to the right of it?

I like this a lot

**Comment by cme** [comment]
Another thought: unicode has codes for quarter note, eighth note, etc. Including those instead of names may be useful?

**Comment by theGreatWhiteShark** [comment]
It seems there is no unicode equivalent for the sixyfourthnote as well as the triplets. But we still could do it with custom SVGs.

@trebmuh what do you make of these suggestions?

**Comment by trebmuh** [comment]
This one slipped out of my monitoring probably because it's been close (hence, I'm reopening it).

@theGreatWhiteShark I think that the best tradeoff is the one you proposed: "_having both the number as a fraction, like 1/4 (but properly rendered), and the name to the right of it_".

Then it will cater for everyone.

**Comment by theGreatWhiteShark** [comment]
> unicode/svg could do as well.

I left it as "1/8" since this is also the way it get's displayed in the corresponding LCDCombo. Is this ok?

**Comment by oddtime** [comment]
I would not to impose a different opinion, but the word "resolution" makes me think that its value is proportional to the density, not inversely proportional.
If we switch to "1/8" fashion "Res" should become "quantum"

**Comment by theGreatWhiteShark** [comment]
> I would not to impose a different opinion, but the word "resolution" makes me think that its value is proportional to the density, not inversely proportional.

Hmm. There are indeed different uses of this term. While for images resolution means the number of pixels per area (?inch?) in e.g. spectroscopy it means the smallest resolvable distance. The latter is also used for frequency resolution in frequency spectra and for temporal resolution in time series. In other words, the intend for the changes could be rephrased in changing the resolution from "4X per Y" - were neither the X or Y is clear - to "having a 1/4 - a quarter as the smallest resolvable note". I think for someone who never used Hydrogen this is more clear. For all who already get used to the current representation this might be confusing at first.

**Comment by oddtime** [comment]
Ok

**Comment by trebmuh** [comment]
Just testing from 0aa7fe6, that's awesome like that. Thanks!
